import {memoryStillAllowed,saveConversationTurn} from './ai-memory-bridge.mjs';
export async function* inferenceText(stream){const reader=stream.getReader(),decoder=new TextDecoder();let pending='';try{while(true){const {value,done}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});if(pending.length>65536)throw Error('invalid_stream');let end;while((end=pending.indexOf('\n'))>=0){const line=pending.slice(0,end).trim();pending=pending.slice(end+1);if(!line.startsWith('data:'))continue;const raw=line.slice(5).trim();if(!raw||raw==='[DONE]')continue;const data=JSON.parse(raw);if(data.error)throw Error('provider_error');const text=data.response??data.choices?.[0]?.delta?.content??'';if(typeof text==='string'&&text)yield text;}}}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}}
export function answerStream(upstream,{headers,requestId,access,meta,request,onComplete}){
 const encoder=new TextEncoder();let cancelled=false;
 const stream=new ReadableStream({async start(controller){const emit=(event,data)=>{if(!cancelled)controller.enqueue(encoder.encode('event: '+event+'\ndata: '+JSON.stringify(data)+'\n\n'))};let answer='',pending='',last=0;
 try{if(!await memoryStillAllowed(access))throw Error('privacy_changed');emit('meta',meta);
 for await(const text of inferenceText(upstream)){if(cancelled||request.signal.aborted)throw Error('cancelled');answer+=text;pending+=text;if(answer.length>5000)throw Error('answer_too_long');if(!last||Date.now()-last>=200){if(!await memoryStillAllowed(access))throw Error('privacy_changed');emit('delta',{text:pending});pending='';last=Date.now();}}
 if(!answer.trim())throw Error('empty_answer');if(!await memoryStillAllowed(access))throw Error('privacy_changed');if(pending)emit('delta',{text:pending});await saveConversationTurn(access,'assistant',answer);if(!await memoryStillAllowed(access))throw Error('privacy_changed');const completed={ok:true,requestId,mode:'grounded',...meta,answer:answer.replace(/\[\s*\]/g,'').trim(),keyPoints:[],nextSteps:[],followUps:[],delivery:'streamed'};await onComplete?.(completed);emit('done',completed);
 }catch(error){emit('error',{ok:false,error:error.message==='privacy_changed'?'privacy_changed':'answer_interrupted',message:error.message==='privacy_changed'?'Your privacy settings changed. Please ask again.':'The answer was interrupted. Your question is still here; please try again.'});}finally{if(!cancelled)controller.close();}},cancel(){cancelled=true;upstream.cancel().catch(()=>{})}});
 return new Response(stream,{headers:{...headers,'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-store, private','X-Accel-Buffering':'no','X-Content-Type-Options':'nosniff'}});
}
