// Approved My Timber master: isolated to the dashboard; public shell stays unchanged.
export const homeStyles=String.raw`
html body.sst-member-experience[data-member-page="dashboard"]{font-family:sans-serif!important}
html body.sst-member-experience[data-member-page="dashboard"]:has(#panel-today.active){background:#050505!important;color:#e7e3da!important}
html body.sst-member-experience[data-member-page="dashboard"] main{max-width:1100px!important;padding:20px 28px 70px!important;font-family:sans-serif!important}
html body.sst-member-experience[data-member-page="dashboard"] :is(main,dialog,[role=dialog],.sst-member-tabs) :is(h1,h2,h3,h4,p,span,small,strong,button,a,input,select,textarea,summary,label){font-family:sans-serif!important}
html body.sst-member-experience[data-member-page="dashboard"] .sst-member-tabs{background:#050505!important;border-bottom:1px solid #414638!important}
html body.sst-member-experience[data-member-page="dashboard"] .sst-member-tabs :is(a,summary){color:#e7e3da!important}
html body.sst-member-experience[data-member-page="dashboard"] .sst-member-tabs a[aria-current=page]{background:#e7e3da!important;color:#050505!important}
html body.sst-member-experience[data-member-page="dashboard"] #panel-today>.preview-note{display:none!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayTitle{color:#e7e3da!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home{color:#e7e3da!important;font:16px/1.6 sans-serif!important;min-width:0}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home :is(section,article,div,h2,h3,h4,p,li,small,span,strong,b,label,summary,a){color:#e7e3da!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home :is(h2,h3){text-transform:none!important;font-weight:500!important;letter-spacing:-.025em!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home p{line-height:1.6!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home :is(button,.mt-now-action){border:1px solid #707762!important;border-radius:9px!important;background:transparent!important;color:#e7e3da!important;min-height:46px!important;padding:12px 18px!important;font-size:15px!important;font-weight:600!important;box-shadow:none!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home button:hover{background:#70776230!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home :is(.mt-card,.mt-saved,.mt-error){background:#11150f!important;color:#e7e3da!important;border:1px solid #707762!important;border-radius:12px!important;padding:22px!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home :is(.mtm-kicker,.mtm-section-head>.mtm-kicker){font-size:13px!important;line-height:1.4!important;font-weight:700!important;letter-spacing:.13em!important;margin:0!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-muted{color:#b7b9ad!important;font-size:14px!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-hero{position:relative;min-height:220px;display:flex;align-items:center;overflow:hidden}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-hero>div{position:relative;z-index:1;max-width:78%}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-hero h2{font-size:clamp(36px,5vw,60px)!important;font-weight:600!important;line-height:1.08!important;margin:16px 0!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-hero p:last-child{font-size:20px!important;color:#b7b9ad!important;margin:0 0 24px!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-hero img{position:absolute;right:-40px;top:-65px;width:530px;height:350px;object-fit:cover;opacity:.8;mask-image:linear-gradient(90deg,transparent,#000 35%)}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-care{padding:30px 34px;border-radius:17px;background:#e7e3da!important;color:#050505!important;margin:0 0 22px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-care :is(h2,p,span,a,button,strong,small){color:#050505!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-care h2{font-size:clamp(30px,4vw,43px)!important;line-height:1.15!important;margin:23px 0 10px!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-feelings{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:24px 0 14px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-feelings>*{display:flex;align-items:center;justify-content:center;gap:12px;min-height:58px;border:1px solid #414638!important;border-radius:9px;padding:14px 8px!important;font-weight:600!important;text-align:center;text-decoration:none}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-feelings span{font-size:25px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-latest{font-size:14px!important;color:#414638!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-care-links{display:grid;grid-template-columns:1fr 1fr;gap:20px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-care-links a{border-top:1px solid #b2b4a7;padding:14px 0 0;min-height:44px;font-size:14px;text-decoration:none}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-section-head{display:flex;justify-content:space-between;align-items:center;gap:12px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-section-head>a{font-size:14px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-pill{border:1px solid #929782;border-radius:30px;padding:5px 10px;font-size:13px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-dashboard{display:grid;grid-template-columns:1.2fr 1fr;gap:20px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-panel{padding:26px;border:1px solid #414638;border-radius:15px;background:linear-gradient(135deg,#11150f,#080a07)}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-next{display:block!important;padding:22px 0!important;margin:0!important;background:none!important;border:0!important;min-height:0!important;box-shadow:none!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-next :is(h3,p,small){color:#e7e3da!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-next small{font-size:12px!important;letter-spacing:.1em!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-next h3{font-size:27px!important;margin:10px 0!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-next .mt-now-action{display:inline-flex!important;width:auto!important;min-width:0!important;background:#e7e3da!important;color:#050505!important;text-decoration:none!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-plan{display:block!important;padding:0!important;margin:0!important;overflow:visible!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-step{display:block!important;background:none!important;padding:20px 0!important;min-height:0!important;border:0!important;border-top:1px solid #414638!important;border-radius:0!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-step :is(h3,p,small,li,strong){color:#e7e3da!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-step h3{font-size:23px!important;margin:10px 0!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-step small{font-size:12px!important;letter-spacing:.1em}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-step a{display:inline-block;border-bottom:1px solid #707762;padding:6px 0;font-size:15px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-day-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-day-actions button{flex:1}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-details{margin-top:16px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-details summary{padding:10px 0;min-height:44px;cursor:pointer}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-days{display:flex;justify-content:space-between;gap:6px;margin:23px 0}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-days span{display:grid;gap:8px;text-align:center;font-size:13px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-days b{width:32px;height:32px;border:1px solid #707762;border-radius:50%;display:grid;place-items:center;font-size:18px;font-weight:400}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-days .is-logged{background:#e7e3da!important;color:#050505!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home hr{border:0;border-top:1px solid #414638;margin:23px 0}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mt-connected-life{display:block!important;background:transparent!important;border:0!important;padding:0!important;color:#e7e3da!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-score{font-size:43px!important;margin:14px 0 8px!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-score span{font-size:18px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mt-connected-life>h3:not(.mtm-score){font-size:23px!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-utility :is(strong,span){display:block}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-utility span{font-size:14px!important;color:#b7b9ad!important;margin-top:6px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-daily{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:22px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mt-fluid-line{background:none!important;color:#e7e3da!important;display:flex;justify-content:space-between;align-items:center;gap:16px;border:0!important;padding:0!important;margin:0!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mt-fluid-line strong{font-size:26px!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mt-daily-reminder{background:none!important;color:#e7e3da!important;border:0!important;border-left:1px solid #414638!important;border-radius:0!important;padding:0 0 0 24px!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mt-daily-reminder :is(summary,p,label,span){color:#e7e3da!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mt-daily-reminder summary{min-height:44px;cursor:pointer;font-size:18px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-records{margin-top:22px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-record-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-record-grid>a{padding:18px;border:1px solid #414638;border-radius:9px;text-decoration:none}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-record-grid strong{display:block;font-size:18px;font-weight:500}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-record-grid span{display:block;font-size:14px;margin-top:6px;color:#b7b9ad!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-ask{margin-top:22px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-ask h2{font-size:31px!important;margin:14px 0!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-ask form{display:grid;gap:10px}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home textarea{width:100%!important;font:16px/1.6 sans-serif!important;background:#e7e3da!important;color:#050505!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-ask button{justify-self:end;background:#e7e3da!important;color:#050505!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mt-today-footer{margin:18px 0!important;padding:12px 0!important;color:#b7b9ad!important}
html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-announcement{border-left:3px solid #707762;padding:12px 16px}
html body.sst-member-experience[data-member-page="dashboard"] #sstFiveLoops{border-radius:15px!important;border-color:#414638!important;background:linear-gradient(135deg,#11150f,#080a07)!important;padding:26px!important}
html body.sst-member-experience[data-member-page="dashboard"] #sstFiveLoops :is(h2,h3,p,span,small,a){color:#e7e3da!important}
html body.sst-member-experience[data-member-page="dashboard"] #sstFiveLoops .sst-five-head h2{font-size:28px!important;font-weight:500!important}
html body.sst-member-experience[data-member-page="dashboard"] #sstFiveLoops .sst-five-grid article{border-color:#414638!important;border-radius:10px!important;background:#080a07!important}
html body.sst-member-experience[data-member-page="dashboard"] #sstFiveLoops .sst-five-grid :is(button,a.sst-loop-button){border-radius:9px!important;background:#e7e3da!important;color:#050505!important;font-size:15px!important}
html body.sst-member-experience[data-member-page="dashboard"] #sstFiveLoops .sst-five-grid article[data-loop="human"]{order:-2}
html body.sst-member-experience[data-member-page="dashboard"] #sstFiveLoops .sst-five-grid article[data-loop="comingoff"]{order:-1;grid-column:auto!important}
html body.sst-member-experience[data-member-page="dashboard"] #sstFiveLoops .sst-five-grid article[data-loop="fridge"]{grid-column:1/-1}
html body.sst-member-experience[data-member-page="dashboard"] #sstTodayContext{border-radius:15px!important}
@media(max-width:650px){
 html body.sst-member-experience[data-member-page="dashboard"] .member-nav-tools{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px!important;width:100%;text-align:center}
 html body.sst-member-experience[data-member-page="dashboard"] main{padding:12px 16px 60px!important}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-hero{min-height:185px}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-hero h2{font-size:38px!important}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-hero img{width:340px;height:225px;right:-115px;top:-13px;opacity:.65}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-care{padding:22px 19px}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-care h2{font-size:32px!important}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-care .mtm-section-head{align-items:flex-start;flex-direction:column}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-feelings{gap:8px}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-feelings>*{flex-direction:column;gap:7px;padding:12px 4px!important;font-size:14px!important}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-care-links{grid-template-columns:1fr;gap:10px}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-dashboard{grid-template-columns:1fr;gap:18px}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-panel{padding:22px 20px}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-daily{grid-template-columns:1fr}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mt-daily-reminder{border-left:0!important;border-top:1px solid #414638!important;padding:20px 0 0!important}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-record-grid{grid-template-columns:1fr}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-day-actions{flex-direction:column}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-days{gap:4px}
 html body.sst-member-experience[data-member-page="dashboard"] #todayActions.mtm-home .mtm-days b{width:29px;height:29px}
}
`;
