import {draftQuestionnaire,clinicalAnswers,needsUrgentHelp} from './patient-questionnaire-v2.js';
import {normaliseAnswers} from './patient-intake-v2.js';
// Read-only server. Synthetic demo state stays in this browser tab's memory.
const originalFetch=window.fetch.bind(window),params=new URLSearchParams(location.search);params.set('demo','1');history.replaceState(null,'',location.pathname+'?'+params);
let state={ok:true,order:{number:'SHIFT-DEMO-001',medicine:'Mounjaro',strength:'2.5 mg',payment:'paid',clinicalStatus:'assessment_pending'},version:0,status:'draft',answers:{firstName:'Alex',lastName:'Example',email:'alex@example.test',phone:'07700900000',dateOfBirth:'1982-06-15',country:'GB',weightUnit:'kg',heightUnit:'cm',previousTreatment:'new'},evidence:[],questionnaire:draftQuestionnaire};
if(params.get('variant')==='12'){state.order.medicine='Wegovy injection';state.order.strength='0.25 mg'}
window.fetch=async(input,init={})=>{const url=new URL(String(input),location.origin);if(!url.pathname.startsWith('/v1/'))return originalFetch(input,init);const json=(b,s=200)=>Promise.resolve(Response.json(b,{status:s}));const method=init.method||'GET';
 if(url.pathname==='/v1/catalogue/medicines')return json({intakeFlow:'shift_v2',products:[{name:'Mounjaro',variants:[{id:11,strengthLabel:'2.5 mg',pricePence:16900,status:'available'}]},{name:'Wegovy injection',variants:[{id:12,strengthLabel:'0.25 mg',pricePence:9900,status:'available'}]}]});
 if(url.pathname==='/v1/commerce/medicine-checkout')return json({checkoutUrl:`/patient-intake?order=SHIFT-DEMO-001&demo=1&variant=${Number(JSON.parse(init.body).variantId)}`});
 if(url.pathname.endsWith('/lookup'))return json({results:url.searchParams.get('kind')==='gp'?[{id:'DEMO-GP',label:'Example GP Practice · SK10 1AA (sample)',practice:'Example GP Practice',line1:'2 Sample Street',town:'Macclesfield',postcode:'SK10 1AA'}]:[{id:'DEMO-ADDRESS',label:'1 Sample Street, Macclesfield, SK10 1AA (sample)',line1:'1 Sample Street',town:'Macclesfield',postcode:'SK10 1AA'}],message:'Sample result for preview only. Live directory connection is not configured.'});
 if(url.pathname==='/v1/patient-intake'&&method==='GET')return json(state);
 if(url.pathname==='/v1/patient-intake'&&method==='POST'){const b=JSON.parse(init.body);state.answers=normaliseAnswers(b.answers);state.answers.clinical=clinicalAnswers(b.answers.clinical,draftQuestionnaire);state.version++;return json({ok:true,version:state.version})}
 if(url.pathname.endsWith('/evidence')){const slot=init.body.get('slot'),file=init.body.get('file');if(file.size>8*1024*1024)return json({error:'Upload must be under 8 MB.'},400);state.evidence=state.evidence.filter(x=>x.slot!==slot);state.evidence.push({id:crypto.randomUUID(),slot,mime_type:file.type,byte_size:file.size});return json({ok:true,evidence:state.evidence})}
 if(url.pathname.endsWith('/submit')){try{normaliseAnswers(state.answers,true);clinicalAnswers(state.answers.clinical,draftQuestionnaire,true);if(needsUrgentHelp(state.answers.clinical))throw Error('Please get urgent support now. If you cannot keep yourself safe, call 999 or go to A&E.');for(const slot of ['photoId','bodyFront','bodySide',...(state.answers.previousTreatment==='new'?[]:['previousEvidence'])])if(!state.evidence.some(x=>x.slot===slot))throw Error(`Upload ${slot} before submitting.`)}catch(e){return json({error:e.message},400)}state.status='queued';return json({ok:true,status:'queued',message:'PREVIEW: the assessment is saved in this tab only. No information has been sent to a pharmacy. Reloading clears this demonstration.'},202)}
 if(url.pathname.endsWith('/retry'))return json({ok:true,status:'queued',message:'PREVIEW: pharmacy transfer is deliberately disconnected. Your demonstration stays in this tab.'},202);
 if(url.pathname.endsWith('/refund'))return json({ok:true,status:'refunded',message:'PREVIEW: simulated refund outcome. No payment or refund was made.'});
 return json({error:'This action is not part of the synthetic preview.'},404);
};
