import core from './worker.js';
import v3 from './shift-ai-v3.js';
import {selectShoulderGear,shoulderInstruction} from './shoulder-v2.js';
import {buildProactiveInsights,listProactiveInsights} from './proactive-insights.js';
import {evaluateShiftReply,SYNTHETIC_SCENARIOS} from './academy-v2.js';

export default{async fetch(request,env,ctx){const u=new URL(request.url),p=u.pathname.replace(/\/+$/,'')||'/';if(request.method==='POST'&&p==='/v1/shift-ai/shoulder'){const a=await auth(request,env,ctx);if(a.response)return a.response;const b=await readJson(request),gear=selectShoulderGear(b.message);return cors(json({ok:true,...gear,instruction:shoulderInstruction(gear)}),request,env)}if(request.method==='GET'&&p==='/v1/shift-ai/proactive-insights'){const a=await auth(request,env,ctx);if(a.response)return a.response;const uid=Number(a.user.id);await buildProactiveInsights(env,uid);return cors(json({ok:true,insights:await listProactiveInsights(env.DB,uid)}),request,env)}if(request.method==='POST'&&p==='/v1/shift-ai/academy/evaluate'){const a=await auth(request,env,ctx);if(a.response)return a.response;const b=await readJson(request),gear=selectShoulderGear(b.prompt||'');return cors(json({ok:true,gear:gear.gear,evaluation:evaluateShiftReply({prompt:b.prompt,reply:b.reply,gear:gear.gear})}),request,env)}if(request.method==='GET'&&p==='/v1/shift-ai/academy/scenarios'){const a=await auth(request,env,ctx);if(a.response)return a.response;return cors(json({ok:true,scenarios:SYNTHETIC_SCENARIOS}),request,env)}if(request.method==='POST'&&p==='/v1/shift-ai/chat'){const cloned=request.clone();let b={};try{b=await cloned.json()}catch{}const gear=selectShoulderGear(b.message||'');const res=await v3.fetch(request,env,ctx);if(!res.ok)return res;try{const data=await res.clone().json();if(data&&data.ok){data.shoulderGear=gear.gear;data.shoulderInitiative=gear.initiative;return cors(json(data,res.status),request,env)}}catch{}return res}return v3.fetch(request,env,ctx)}};
async function auth(request,env,ctx){const probe=new Request(new URL('/v1/me',request.url),{method:'GET',headers:request.headers}),r=await core.fetch(probe,env,ctx);if(!r.ok)return{response:r};return{user:(await r.json()).user}}
async function readJson(r){try{return await r.json()}catch{return{}}}function json(d,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}function cors(r,request,env){const h=new Headers(r.headers),o=request.headers.get('Origin'),allowed=new Set(['https://shiftsometimber.co.uk','https://www.shiftsometimber.co.uk','https://shiftsometimber.com','https://www.shiftsometimber.com','https://hq.shiftsometimber.co.uk',...String(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean)]);if(o&&allowed.has(o))h.set('Access-Control-Allow-Origin',o);h.set('Access-Control-Allow-Credentials','true');h.set('Vary','Origin');return new Response(r.body,{status:r.status,headers:h})}
