import {authenticateMember} from './member-state-fast-v1.js';

export const TAP_ROOMS=Object.freeze([
  {slug:'sport-banter',name:'Sport & Banter',purpose:'Fixtures, results, tables, news, rumours + conversation. Live data where practical.'},
  {slug:'treatment-experiences',name:'Treatment Experiences',purpose:'Honest talk about treatment, side effects, progress and reality.'},
  {slug:'food-everyday',name:'Food & Everyday',purpose:'Food, eating out, family meals, travel food and low-motivation days.'},
  {slug:'confidence-setbacks',name:'Confidence & Setbacks',purpose:'Rough weeks, confidence and setbacks. This is not a mental-health service.'},
  {slug:'travel-breaks',name:'Travel & Breaks',purpose:'Sports breaks, family trips and singles travel. Practical help only.'},
  {slug:'general-life',name:'General Life',purpose:'Work, money, clothes, relationships, family and everything else.'}
]);
export const REPORT_CATEGORIES=Object.freeze({
  unsafe_treatment_advice:{label:'Unsafe treatment advice / dose instruction',priority:'P1'},
  medication_sales:{label:'Selling or promoting medication / unlicensed products',priority:'P1'},
  harassment:{label:'Harassment or abuse',priority:'P2'},
  spam:{label:'Spam or commercial promotion',priority:'P2'},
  crisis:{label:'Crisis / self-harm language',priority:'P0'},
  other:{label:'Other',priority:'P2'}
});
const DOSE_PATTERNS=[/\b(skip|miss|double|halve|increase|decrease|raise|lower|change|stop|start)\b.{0,35}\b(dose|dosage|mg|regimen|injection|tablet)s?\b/i,/\b(you|he|she|they)\s+(should|need to|must|ought to|could just)\b.{0,45}\b(take|inject|stop|start|skip|miss|double|halve|increase|decrease|come off|go up|go down|move up|drop down)\b/i,/\b(take|inject|go up to|go down to|move up to|drop down to|switch to)\b.{0,20}\b(half|\d+(?:\.\d+)?\s*mg)\b/i,/\bjust\s+(skip|miss|double|halve|stop|start|increase|decrease|come off|go up|go down|move up|drop down)\b/i];
const SALES_PATTERNS=[/\b(buy|sell|supplier|source|telegram|whatsapp|dm me)\b.{0,45}\b(mounjaro|wegovy|ozempic|semaglutide|tirzepatide|reta|retatrutide|peptide|pen|vial|medication)\b/i,/\b(unlicensed|research[- ]?grade|no prescription)\b/i];
const CRISIS_PATTERNS=[/\b(kill myself|end my life|suicid(?:e|al)|self[- ]?harm(?:ing|ed)?|not worth living|better off dead)\b/i];
const SCHEMA=[
`CREATE TABLE IF NOT EXISTS tap_room_profiles (user_id INTEGER PRIMARY KEY,display_name TEXT NOT NULL,bio TEXT,joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,treatment_rules_ack_at TEXT,privacy_prompt_seen_at TEXT,status TEXT NOT NULL DEFAULT 'active',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS tap_room_posts (id INTEGER PRIMARY KEY AUTOINCREMENT,room_slug TEXT NOT NULL,user_id INTEGER,parent_id INTEGER,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'visible',is_founder_prompt INTEGER NOT NULL DEFAULT 0,risk_flags_json TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,deleted_at TEXT,deleted_by INTEGER)`,
`CREATE TABLE IF NOT EXISTS tap_room_blocks (blocker_user_id INTEGER NOT NULL,blocked_user_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(blocker_user_id,blocked_user_id))`,
`CREATE TABLE IF NOT EXISTS tap_room_reports (id INTEGER PRIMARY KEY AUTOINCREMENT,reporter_user_id INTEGER NOT NULL,post_id INTEGER NOT NULL,category TEXT NOT NULL,detail TEXT,priority TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,reviewed_at TEXT,reviewed_by TEXT,outcome TEXT)`,
`CREATE TABLE IF NOT EXISTS tap_room_moderation_audit (id INTEGER PRIMARY KEY AUTOINCREMENT,actor TEXT NOT NULL,action TEXT NOT NULL,reason TEXT NOT NULL,content_id INTEGER,affected_user_id INTEGER,metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS tap_room_restrictions (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,restriction_type TEXT NOT NULL,starts_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,ends_at TEXT,reason TEXT NOT NULL,created_by TEXT NOT NULL,revoked_at TEXT)`,
`CREATE TABLE IF NOT EXISTS tap_room_events (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,event_name TEXT NOT NULL,room_slug TEXT,post_id INTEGER,metadata_json TEXT NOT NULL DEFAULT '{}',occurred_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS tap_room_erasure_requests (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'received',requested_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,due_at TEXT NOT NULL,completed_at TEXT)`];
SCHEMA.push(`CREATE TABLE IF NOT EXISTS tap_room_appeals (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,restriction_id INTEGER,reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',requested_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,reviewed_at TEXT,reviewed_by TEXT,decision TEXT)`,`CREATE TABLE IF NOT EXISTS tap_room_hosts (user_id INTEGER PRIMARY KEY,invited_by TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'invited',invited_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,accepted_at TEXT)`);
let schemaReady;
const now=()=>new Date().toISOString();
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, private','X-Content-Type-Options':'nosniff','X-Robots-Tag':'noindex, nofollow, noarchive, nosnippet',...extra}});
const clean=(v,max=4000)=>String(v??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').trim().slice(0,max);
const room=(slug)=>TAP_ROOMS.find(x=>x.slug===slug);
async function ensureSchema(env){if(!schemaReady)schemaReady=env.DB.batch(SCHEMA.map(sql=>env.DB.prepare(sql))).catch(e=>{schemaReady=null;throw e});await schemaReady}
export function detectTapRoomRisk(text){const flags=[];if(DOSE_PATTERNS.some(r=>r.test(text)))flags.push('unsafe_treatment_advice');if(SALES_PATTERNS.some(r=>r.test(text)))flags.push('medication_sales');if(CRISIS_PATTERNS.some(r=>r.test(text)))flags.push('crisis');return flags}
async function verified(request,env){const auth=await authenticateMember(request,env);if(auth.response)return auth;const row=await env.DB.prepare(`SELECT a.email_verified,p.user_id profile_id,p.display_name,p.bio,p.joined_at,p.treatment_rules_ack_at,p.privacy_prompt_seen_at,p.status FROM user_auth a LEFT JOIN tap_room_profiles p ON p.user_id=a.user_id WHERE a.user_id=?`).bind(auth.userId).first();const linked=await env.DB.prepare('SELECT user_id FROM member_state WHERE user_id=?').bind(auth.userId).first();if(!Number(row?.email_verified)||!linked)return{response:json({ok:false,error:'verified_member_required'},403)};if(row?.status==='suspended')return{response:json({ok:false,error:'tap_room_access_suspended'},403)};if(!row?.profile_id){const name=clean(auth.user.first_name||'Member',30);await env.DB.prepare('INSERT INTO tap_room_profiles(user_id,display_name,joined_at,updated_at) VALUES(?,?,?,?)').bind(auth.userId,name,now(),now()).run();row.display_name=name;row.joined_at=now()}return{...auth,profile:row}}
async function restriction(env,userId){return env.DB.prepare(`SELECT * FROM tap_room_restrictions WHERE user_id=? AND revoked_at IS NULL AND (ends_at IS NULL OR ends_at>?) ORDER BY id DESC LIMIT 1`).bind(userId,now()).first()}
async function event(env,userId,eventName,slug=null,postId=null,meta={}){await env.DB.prepare('INSERT INTO tap_room_events(user_id,event_name,room_slug,post_id,metadata_json,occurred_at) VALUES(?,?,?,?,?,?)').bind(userId,eventName,slug,postId,JSON.stringify(meta),now()).run()}
async function autoReport(env,userId,postId,flags){for(const category of flags){const rule=REPORT_CATEGORIES[category];await env.DB.prepare('INSERT INTO tap_room_reports(reporter_user_id,post_id,category,detail,priority,status,created_at) VALUES(?,?,?,?,?,?,?)').bind(userId,postId,category,'Automatic safety flag',rule.priority,'open',now()).run()}if(flags.includes('crisis'))await notifyP0(env,{userId,postId})}
async function notifyP0(env,payload){const destination=clean(env.TAP_ROOM_P0_EMAIL,200),owner=clean(env.TAP_ROOM_MODERATION_OWNER,100),backup=clean(env.TAP_ROOM_MODERATION_BACKUP,100),incident={type:'tap_room_p0',at:now(),owner,backup,...payload};if(!destination||!owner||!backup){console.error('tap_room_p0_notification_unconfigured',JSON.stringify(incident));return false}let delivered=false;if(env.EMAIL){try{await env.EMAIL.send({from:{email:String(env.AUTH_EMAIL_FROM||'welcome@shiftsometimber.co.uk'),name:'Shift Some Timber'},to:destination,subject:'URGENT: Tap Room safeguarding alert',text:`Immediate human review required.\n\nOwner: ${owner}\nOut-of-hours backup: ${backup}\nTime: ${incident.at}\nPost ID: ${payload.postId||'unknown'}\nReport ID: ${payload.reportId||'automatic flag'}\n\nOpen the Tap Room moderation queue now. Do not reply to this email with member information.`});delivered=true}catch(e){console.error('tap_room_p0_email_failed',e?.message)}}if(env.TAP_ROOM_P0_WEBHOOK){try{const r=await fetch(env.TAP_ROOM_P0_WEBHOOK,{method:'POST',headers:{'Content-Type':'application/json',...(env.TAP_ROOM_P0_SECRET?{'Authorization':`Bearer ${env.TAP_ROOM_P0_SECRET}`}:{})},body:JSON.stringify(incident)});delivered=delivered||r.ok}catch(e){console.error('tap_room_p0_webhook_failed',e?.message)}}if(!delivered)console.error('tap_room_p0_delivery_failed',JSON.stringify(incident));return delivered}
async function listPosts(env,userId,slug){const rows=(await env.DB.prepare(`SELECT p.id,p.room_slug,p.parent_id,p.body,p.created_at,p.updated_at,p.user_id,p.is_founder_prompt,pr.display_name,pr.bio,(SELECT COUNT(*) FROM tap_room_posts r WHERE r.parent_id=p.id AND r.status='visible') reply_count,COALESCE((SELECT MAX(r.created_at) FROM tap_room_posts r WHERE r.parent_id=p.id AND r.status='visible'),p.created_at) last_activity_at FROM tap_room_posts p LEFT JOIN tap_room_profiles pr ON pr.user_id=p.user_id WHERE p.room_slug=? AND p.status='visible' AND p.parent_id IS NULL AND (p.user_id IS NULL OR p.user_id NOT IN (SELECT blocked_user_id FROM tap_room_blocks WHERE blocker_user_id=?)) ORDER BY last_activity_at DESC,p.created_at DESC LIMIT 100`).bind(slug,userId).all()).results||[];return rows}
function moderator(request,env){const token=String(request.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');return token&&env.TAP_ROOM_MODERATOR_KEY&&token===env.TAP_ROOM_MODERATOR_KEY}
export async function tapRoomRoutes(request,env,ctx){
 const u=new URL(request.url),path=u.pathname.replace(/\/+$/,'')||'/';if(!path.startsWith('/v1/tap-room'))return null;await ensureSchema(env);
 if(path.startsWith('/v1/tap-room/moderation/'))return moderationRoute(request,env,path);
 const auth=await verified(request,env);if(auth.response)return auth.response;
 if(request.method==='GET'&&path==='/v1/tap-room'){await event(env,auth.userId,'tap_room_viewed');return json({ok:true,demo:String(env.TAP_ROOM_DEMO||'false')==='true',member:{displayName:auth.profile.display_name,bio:auth.profile.bio,joinedAt:auth.profile.joined_at,treatmentRulesAcknowledged:!!auth.profile.treatment_rules_ack_at,privacyPromptSeen:!!auth.profile.privacy_prompt_seen_at},rooms:TAP_ROOMS,reportCategories:REPORT_CATEGORIES,directMessages:false})}
 if(path==='/v1/tap-room/profile'&&request.method==='GET')return json({ok:true,profile:{displayName:auth.profile.display_name,bio:auth.profile.bio,joinedAt:auth.profile.joined_at}});
 if(path==='/v1/tap-room/profile'&&request.method==='PATCH'){const b=await request.json().catch(()=>({})),display=clean(b.displayName,40),bio=clean(b.bio,160);if(display.length<2)return json({ok:false,error:'display_name_required'},400);await env.DB.prepare('UPDATE tap_room_profiles SET display_name=?,bio=?,updated_at=? WHERE user_id=?').bind(display,bio||null,now(),auth.userId).run();return json({ok:true,profile:{displayName:display,bio}})}
 if(path==='/v1/tap-room/acknowledgements/treatment-experiences'&&request.method==='POST'){await env.DB.prepare('UPDATE tap_room_profiles SET treatment_rules_ack_at=?,updated_at=? WHERE user_id=?').bind(now(),now(),auth.userId).run();return json({ok:true})}
 if(path==='/v1/tap-room/acknowledgements/privacy'&&request.method==='POST'){await env.DB.prepare('UPDATE tap_room_profiles SET privacy_prompt_seen_at=?,updated_at=? WHERE user_id=?').bind(now(),now(),auth.userId).run();return json({ok:true})}
 let m=path.match(/^\/v1\/tap-room\/rooms\/([a-z-]+)\/posts$/);if(m&&room(m[1])){
   const slug=m[1];if(request.method==='GET'){await event(env,auth.userId,'room_viewed',slug);return json({ok:true,room:room(slug),posts:await listPosts(env,auth.userId,slug),notice:slug==='treatment-experiences'?'Share your own experience. Do not tell anyone to change a dose or treatment, diagnose them, or sell medication.':null})}
   if(request.method==='POST'){const active=await restriction(env,auth.userId);if(active)return json({ok:false,error:'posting_restricted',until:active.ends_at},403);if(slug==='treatment-experiences'&&!auth.profile.treatment_rules_ack_at)return json({ok:false,error:'treatment_rules_acknowledgement_required'},428);const b=await request.json().catch(()=>({})),body=clean(b.body,4000);if(body.length<2)return json({ok:false,error:'post_body_required'},400);const flags=detectTapRoomRisk(body),created=now(),status=flags.length?'held':'visible';const r=await env.DB.prepare('INSERT INTO tap_room_posts(room_slug,user_id,parent_id,body,status,risk_flags_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(slug,auth.userId,null,body,status,JSON.stringify(flags),created,created).run(),id=Number(r.meta?.last_row_id||0);if(flags.length)await autoReport(env,auth.userId,id,flags);await event(env,auth.userId,'post_created',slug,id,{riskFlags:flags});return json({ok:true,id,status,flagged:flags.length>0,reviewMessage:flags.length?'This has not been published. A human moderator will review it.':null,crisisSupport:flags.includes('crisis')?'If you may be in immediate danger, call 999. You can also call Samaritans on 116 123.':null},201)}
 }
 m=path.match(/^\/v1\/tap-room\/posts\/(\d+)\/replies$/);if(m&&request.method==='GET'){const rows=(await env.DB.prepare(`SELECT p.id,p.body,p.created_at,p.user_id,pr.display_name FROM tap_room_posts p LEFT JOIN tap_room_profiles pr ON pr.user_id=p.user_id WHERE p.parent_id=? AND p.status='visible' AND (p.user_id IS NULL OR p.user_id NOT IN (SELECT blocked_user_id FROM tap_room_blocks WHERE blocker_user_id=?)) ORDER BY p.created_at`).bind(Number(m[1]),auth.userId).all()).results||[];return json({ok:true,replies:rows})}
 if(m&&request.method==='POST'){const parent=await env.DB.prepare(`SELECT id,room_slug FROM tap_room_posts WHERE id=? AND status='visible'`).bind(Number(m[1])).first();if(!parent)return json({ok:false,error:'post_not_found'},404);const b=await request.json().catch(()=>({})),body=clean(b.body,4000);if(body.length<2)return json({ok:false,error:'reply_body_required'},400);const flags=detectTapRoomRisk(body),created=now(),status=flags.length?'held':'visible',r=await env.DB.prepare('INSERT INTO tap_room_posts(room_slug,user_id,parent_id,body,status,risk_flags_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(parent.room_slug,auth.userId,parent.id,body,status,JSON.stringify(flags),created,created).run(),id=Number(r.meta?.last_row_id||0);if(flags.length)await autoReport(env,auth.userId,id,flags);await event(env,auth.userId,'reply_created',parent.room_slug,id,{parentId:parent.id,riskFlags:flags});return json({ok:true,id,status,flagged:flags.length>0,reviewMessage:flags.length?'This has not been published. A human moderator will review it.':null},201)}
 m=path.match(/^\/v1\/tap-room\/posts\/(\d+)$/);if(m&&request.method==='DELETE'){const post=await env.DB.prepare('SELECT id,user_id FROM tap_room_posts WHERE id=?').bind(Number(m[1])).first();if(!post||Number(post.user_id)!==auth.userId)return json({ok:false,error:'post_not_found'},404);await env.DB.prepare(`UPDATE tap_room_posts SET status='deleted_by_member',deleted_at=?,deleted_by=?,updated_at=? WHERE id=?`).bind(now(),auth.userId,now(),post.id).run();await event(env,auth.userId,'post_deleted',null,post.id);return json({ok:true,recoverableForInvestigation:true})}
 m=path.match(/^\/v1\/tap-room\/posts\/(\d+)\/report$/);if(m&&request.method==='POST'){const b=await request.json().catch(()=>({})),category=clean(b.category,50),rule=REPORT_CATEGORIES[category];if(!rule)return json({ok:false,error:'invalid_report_category'},400);const detail=clean(b.detail,800);if(category==='other'&&!detail)return json({ok:false,error:'report_detail_required'},400);const r=await env.DB.prepare('INSERT INTO tap_room_reports(reporter_user_id,post_id,category,detail,priority,status,created_at) VALUES(?,?,?,?,?,?,?)').bind(auth.userId,Number(m[1]),category,detail||null,rule.priority,'open',now()).run();if(rule.priority==='P0')await notifyP0(env,{reportId:Number(r.meta?.last_row_id||0),postId:Number(m[1])});return json({ok:true,priority:rule.priority,holdingMessage:rule.priority==='P0'?'Thanks for flagging this. It has been sent for urgent human review. If somebody is in immediate danger, call 999.':null},201)}
 m=path.match(/^\/v1\/tap-room\/members\/(\d+)\/block$/);if(m&&request.method==='POST'){const target=Number(m[1]);if(target===auth.userId)return json({ok:false,error:'cannot_block_self'},400);await env.DB.prepare('INSERT OR IGNORE INTO tap_room_blocks(blocker_user_id,blocked_user_id,created_at) VALUES(?,?,?)').bind(auth.userId,target,now()).run();return json({ok:true})}if(m&&request.method==='DELETE'){await env.DB.prepare('DELETE FROM tap_room_blocks WHERE blocker_user_id=? AND blocked_user_id=?').bind(auth.userId,Number(m[1])).run();return json({ok:true})}
 if(path==='/v1/tap-room/privacy/erasure'&&request.method==='POST'){const due=new Date(Date.now()+30*86400000).toISOString();await env.DB.prepare('INSERT INTO tap_room_erasure_requests(user_id,status,requested_at,due_at) VALUES(?,?,?,?)').bind(auth.userId,'received',now(),due).run();await event(env,auth.userId,'erasure_requested',null,null,{due});return json({ok:true,dueAt:due},202)}
 if(path==='/v1/tap-room/appeals'&&request.method==='POST'){const b=await request.json().catch(()=>({})),reason=clean(b.reason,1000),restrictionId=Number(b.restrictionId||0)||null;if(!reason)return json({ok:false,error:'appeal_reason_required'},400);const prior=await env.DB.prepare(`SELECT id FROM tap_room_appeals WHERE user_id=? AND status='open'`).bind(auth.userId).first();if(prior)return json({ok:false,error:'appeal_already_open'},409);await env.DB.prepare('INSERT INTO tap_room_appeals(user_id,restriction_id,reason,status,requested_at) VALUES(?,?,?,?,?)').bind(auth.userId,restrictionId,reason,'open',now()).run();return json({ok:true,message:'Your appeal will receive one human review. The Phase 1 decision is final.'},201)}
 return json({ok:false,error:'not_found'},404);
}
async function moderationRoute(request,env,path){
 if(!moderator(request,env))return json({ok:false,error:'moderator_auth_required'},401);const actor=clean(request.headers.get('X-Shift-Moderator')||env.TAP_ROOM_MODERATION_OWNER,100);if(!actor)return json({ok:false,error:'named_moderator_required'},428);
 if(request.method==='GET'&&path==='/v1/tap-room/moderation/queue'){const [reports,appeals,erasures]=await Promise.all([env.DB.prepare(`SELECT r.*,p.body,p.user_id affected_user_id FROM tap_room_reports r JOIN tap_room_posts p ON p.id=r.post_id WHERE r.status='open' ORDER BY CASE r.priority WHEN 'P0' THEN 0 WHEN 'P1' THEN 1 ELSE 2 END,r.created_at`).all(),env.DB.prepare(`SELECT * FROM tap_room_appeals WHERE status='open' ORDER BY requested_at`).all(),env.DB.prepare(`SELECT * FROM tap_room_erasure_requests WHERE status='received' ORDER BY due_at`).all()]);return json({ok:true,owner:env.TAP_ROOM_MODERATION_OWNER||null,reports:reports.results||[],appeals:appeals.results||[],erasures:erasures.results||[]})}
 if(request.method==='GET'&&path==='/v1/tap-room/moderation/metrics'){const since=new Date(Date.now()-30*86400000).toISOString();const q=async sql=>(await env.DB.prepare(sql).bind(since).first())||{};const [views,contributors,replies,reports,crossRoom]=await Promise.all([q(`SELECT COUNT(DISTINCT user_id) n FROM tap_room_events WHERE event_name='tap_room_viewed' AND occurred_at>=?`),q(`SELECT COUNT(DISTINCT user_id) n FROM tap_room_posts WHERE created_at>=? AND status='visible'`),q(`SELECT COUNT(*) n FROM tap_room_posts WHERE parent_id IS NOT NULL AND created_at>=? AND status='visible'`),q(`SELECT COUNT(*) n FROM tap_room_reports WHERE created_at>=?`),q(`SELECT COUNT(*) n FROM (SELECT user_id FROM tap_room_posts WHERE created_at>=? AND status='visible' GROUP BY user_id HAVING COUNT(DISTINCT room_slug)>1)`)]);return json({ok:true,windowDays:30,uniqueVisitors:Number(views.n||0),activeContributors:Number(contributors.n||0),replies:Number(replies.n||0),reports:Number(reports.n||0),crossRoomContributors:Number(crossRoom.n||0),rawEventsCaptured:true})}
 const appeal=path.match(/^\/v1\/tap-room\/moderation\/appeals\/(\d+)$/);if(appeal&&request.method==='PATCH'){const b=await request.json().catch(()=>({})),decision=clean(b.decision,500);if(!decision)return json({ok:false,error:'decision_required'},400);await env.DB.prepare(`UPDATE tap_room_appeals SET status='reviewed',reviewed_at=?,reviewed_by=?,decision=? WHERE id=? AND status='open'`).bind(now(),actor,decision,Number(appeal[1])).run();return json({ok:true,finalForPhase1:true})}
 const erase=path.match(/^\/v1\/tap-room\/moderation\/erasures\/(\d+)\/complete$/);if(erase&&request.method==='POST'){const item=await env.DB.prepare(`SELECT * FROM tap_room_erasure_requests WHERE id=? AND status='received'`).bind(Number(erase[1])).first();if(!item)return json({ok:false,error:'erasure_not_found'},404);await env.DB.batch([env.DB.prepare(`UPDATE tap_room_posts SET body='[removed at member request]',user_id=NULL,status='removed_by_erasure',updated_at=? WHERE user_id=?`).bind(now(),item.user_id),env.DB.prepare('DELETE FROM tap_room_blocks WHERE blocker_user_id=? OR blocked_user_id=?').bind(item.user_id,item.user_id),env.DB.prepare('DELETE FROM tap_room_profiles WHERE user_id=?').bind(item.user_id),env.DB.prepare(`UPDATE tap_room_erasure_requests SET status='completed',completed_at=? WHERE id=?`).bind(now(),item.id),env.DB.prepare('INSERT INTO tap_room_moderation_audit(actor,action,reason,affected_user_id,metadata_json,created_at) VALUES(?,?,?,?,?,?)').bind(actor,'complete_erasure','Member request',item.user_id,'{}',now())]);return json({ok:true,completedAt:now()})}
 const m=path.match(/^\/v1\/tap-room\/moderation\/posts\/(\d+)\/action$/);if(m&&request.method==='POST'){const b=await request.json().catch(()=>({})),action=clean(b.action,40),reason=clean(b.reason,500),allowed=['warn','hide','delete','restrict_7','restrict_30','remove','suspend_account'];if(!allowed.includes(action)||!reason)return json({ok:false,error:'invalid_moderator_action'},400);const post=await env.DB.prepare('SELECT id,user_id FROM tap_room_posts WHERE id=?').bind(Number(m[1])).first();if(!post)return json({ok:false,error:'post_not_found'},404);if(action==='hide'||action==='delete')await env.DB.prepare('UPDATE tap_room_posts SET status=?,deleted_at=?,updated_at=? WHERE id=?').bind(action==='hide'?'hidden_by_moderator':'deleted_by_moderator',now(),now(),post.id).run();if(action.startsWith('restrict_')){const days=action==='restrict_7'?7:30;await env.DB.prepare('INSERT INTO tap_room_restrictions(user_id,restriction_type,starts_at,ends_at,reason,created_by) VALUES(?,?,?,?,?,?)').bind(post.user_id,'posting',now(),new Date(Date.now()+days*86400000).toISOString(),reason,actor).run()}if(action==='remove')await env.DB.prepare(`UPDATE tap_room_profiles SET status='removed',updated_at=? WHERE user_id=?`).bind(now(),post.user_id).run();if(action==='suspend_account')await env.DB.prepare(`UPDATE tap_room_profiles SET status='suspended',updated_at=? WHERE user_id=?`).bind(now(),post.user_id).run();await env.DB.batch([env.DB.prepare('INSERT INTO tap_room_moderation_audit(actor,action,reason,content_id,affected_user_id,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(actor,action,reason,post.id,post.user_id,JSON.stringify({retentionMonths:24}),now()),env.DB.prepare(`UPDATE tap_room_reports SET status='reviewed',reviewed_at=?,reviewed_by=?,outcome=? WHERE post_id=? AND status='open'`).bind(now(),actor,action,post.id)]);return json({ok:true,action,actor})}return json({ok:false,error:'not_found'},404)}
