import {analyticsSnapshot} from './product-analytics-v1.js';
import {readRadarFreshness} from './radar-freshness-v2.js';
const safeCount=async(DB,sql,bind=[])=>{try{const r=await DB.prepare(sql).bind(...bind).first();return Number(r?.c||0)}catch{return null}};
const safeFirst=async(DB,sql,bind=[])=>{try{return await DB.prepare(sql).bind(...bind).first()}catch{return null}};
export async function watchtowerSnapshot(env){
 const now=new Date(),warnings=[];const [users,activePlans,ai24,feedback24,radarQueue,lastKnowledge,analytics,radarFreshness]=await Promise.all([safeCount(env.DB,'SELECT COUNT(*) c FROM users'),safeCount(env.DB,"SELECT COUNT(*) c FROM shift_plans WHERE status='active'"),safeCount(env.DB,"SELECT COUNT(*) c FROM shift_ai_conversations WHERE created_at>=datetime('now','-24 hours')"),safeCount(env.DB,"SELECT COUNT(*) c FROM product_feedback WHERE updated_at>=datetime('now','-24 hours')"),safeCount(env.DB,"SELECT COUNT(*) c FROM radar_events WHERE status IN ('detected','verified','needs_more_evidence','ready_for_review','hold','publish_failed')"),safeFirst(env.DB,"SELECT id,label,updated_at FROM shift_knowledge_nodes WHERE status='active' ORDER BY updated_at DESC LIMIT 1"),analyticsSnapshot(env.DB,{hours:24}).catch(()=>({windowHours:24,activeMembers:null,errors:null,events:[],surfaces:[]})),readRadarFreshness(env.DB)]);
 const knowledgeAge=ageHours(lastKnowledge?.updated_at);for(const r of radarFreshness.reasons)warnings.push(alert(`radar_${r.code}`,r.level,radarMessage(r),r));if(analytics.errors!==null&&analytics.errors>=5)warnings.push(alert('member_errors','AMBER',`${analytics.errors} member-facing errors recorded in 24h`,{count:analytics.errors}));if(knowledgeAge!==null&&knowledgeAge>24*14)warnings.push(alert('knowledge_stale','AMBER',`No canonical Knowledge update for ${Math.round(knowledgeAge/24)} days`,{ageHours:knowledgeAge}));
 const status=warnings.some(x=>x.level==='RED')?'RED':warnings.length?'AMBER':'GREEN';return{ok:status!=='RED',status,generatedAt:now.toISOString(),attention:warnings.sort((a,b)=>(a.level==='RED'?-1:1)-(b.level==='RED'?-1:1)),platform:{database:'connected',workersAiBound:!!env.AI,emailBound:!!env.EMAIL},members:{registered:users,activePlans},intelligence:{aiTurns24h:ai24,feedbackSignals24h:feedback24,knowledge:{latest:lastKnowledge,ageHours:knowledgeAge}},radar:{queue:radarQueue,freshness:radarFreshness},product:analytics,alerts:warnings,rule:'GREEN means no currently detected Watchtower condition. It does not by itself mean the full platform is commissioned.'};
}
function radarMessage(r){if(r.code==='publication_failures')return`${r.count} Radar publication job(s) have failed`;return`Radar ${r.code.replace('_',' ')}${r.ageHours==null?' has no recent evidence':` is ${Math.round(r.ageHours)}h old`}`}
function alert(code,level,message,detail={}){return{code,level,message,detail}}
function ageHours(value){if(!value)return null;const t=Date.parse(value);if(!Number.isFinite(t))return null;return Math.max(0,(Date.now()-t)/3600000)}
