name: MyTimber
options:
  deploymentTarget:
    iOS: '16.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    TARGETED_DEVICE_FAMILY: '1,2'
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  MyTimber:
    type: application
    platform: iOS
    sources:
      - Sources
      - Resources
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: uk.co.shiftsometimber.mytimber.dev
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: uk.co.shiftsometimber.mytimber
    info:
      path: GeneratedInfo.plist
      properties:
        CFBundleDisplayName: My Timber
        UILaunchScreen:
          UIColorName: LaunchBackground
        NSCameraUsageDescription: Take a photo you choose to upload to your My Timber account.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
schemes:
  MyTimber:
    build:
      targets:
        MyTimber: all
