import json,pathlib
root=pathlib.Path(__file__).resolve().parents[2]
edits=[]
def change(source,route,old,new,reason,kind='public'):
 p=root/source;s=p.read_text();assert s.count(old)==1,(source,old,s.count(old))
 p.write_text(s.replace(old,new));edits.append(dict(source=source,route=route,old=old,new=new,reason=reason,kind=kind))
p='public-continuity.mjs'
change('preview/voice/about-source.html','/about',"Getting help mattered. So did the food, movement and ordinary decisions around it. I wasn't becoming a different bloke overnight. I was starting to look after the one who was already there.","Getting help mattered. So did the changes to food, movement and the ordinary decisions around them.",'Keep the confirmed actions; remove the polished identity flourish.')
change(p,'/life-back','Try a simple weekly routine: open your goal, look at your latest check-in and choose one manageable action for the week ahead. You can make that choice even when the week has been messy. You do not need to manufacture a win or mark everything higher.',"Once a week, look at your goal and latest check-in. What helped? What got harder? Choose one manageable action for the week ahead. If something felt worse, record that too.",'Replace reassurance with usable review questions.')
change(p,'/life-back','Write a short personal goal in Life Back. Keep it specific enough that you can recognise progress in everyday life.',"Write down what you want to do more easily. Be specific enough that you can tell when something has changed.",'Make goal-setting instruction concrete.')
change(p,'/life-back','Your goal does not have to sound impressive. It has to belong to you.',"Choose something that matters to you, however ordinary it sounds.",'Keep meaning without the formulaic contrast.')
change(p,'/life-back','Add something that went better. It might be joining a walk, finding an easier routine or doing something you had put off. Saved check-ins help you look back.',"Record something that went better: joining a walk, finding an easier routine or doing something you'd put off. You can look back at your saved check-ins.",'Natural phrasing; same examples and feature.')
route='/articles/food-noise-after-stopping-glp1'
change(p,route,'Before your next appointment or message to your prescriber, make a brief note of what has changed. You can use paper or your own notes app; you do not need another score to worry about.',"Before you speak or write to your prescriber, jot down what's changed. Paper or the notes on your phone will do. Use the points below to organise what you want to ask.",'Clarify instruction without editing clinical advice.')
change(p,route,'Choose the part of the day that causes the most friction and make one plan for it: decide what is for dinner before the working day runs away with you, keep a shopping list, or ask someone you trust to help you prepare for an appointment. These are planning suggestions, not a proven treatment for food noise.',"Pick the part of the day that's hardest and make one plan for it. Decide what's for tea before work runs late, keep a shopping list, or ask someone you trust to help you prepare for an appointment. These are planning suggestions, not a proven treatment for food noise.",'Replace abstraction; retain evidence limitation unchanged.')
change(p,'/clinic-gone-quiet','Keep the everyday thing you are trying to get back to, even if the prescription or provider changes.',"Keep a note of what you want to get back to, even if your prescription or provider changes.",'Specify what keeping a reason means.')
change(p,'/provider-switch','This is about continuity of support, not promising a cheaper pen or automatic continuation of a prescription.',"Keep your practical support organised while a new clinician assesses your treatment. Changing provider doesn't guarantee a cheaper medicine or continuation of your prescription.",'Explain the job; retain price and prescribing limits.')
change(p,'/husband-help','It gives him some control without pretending you have the answer.',"Let his answer guide what you do next.",'Respect agency without implying control is granted by a partner.')
change(p,'/shift-health','the guides above explain the topic, the limitations and appropriate help.','the guides above explain the concern, what remains uncertain and where to get help.','Make navigation description understandable.')
change('public-startup-stability.mjs','/programme','Explain your options, build your plan and support you through it.','Explain your options and help you plan food, movement, sleep and check-ins.','Name existing practical support instead of an open-ended promise.')
change('radar-news-pages-v1.js','/medicine-news/*','SHIFT’s interpretation of the findings and what they could mean for members.','What we think this could mean for you, and what remains uncertain.','Plain-language label; do not change reported findings or article data.','news')
change('member-experience/checkin-followup-client.mjs','/member/check-in','Saved to your private check-in history. After trying a food or movement step, you can say whether it helped on that page. One useful thing is enough.','Your next step is saved. If it’s a food or movement step, try it, then return to the Grub or Fit page you used to say whether it helped.','Specify saved item and destination; retain conditional wording.','member')
change('member-experience/checkin-followup-client.mjs','/member/check-in','Optional. Choosing a meal or opening Fit does not mean you ate it or completed a session. Answer after trying the step, or choose “I have not tried it yet”.','This question is optional. Choosing a meal or opening Fit doesn’t mean you ate it or completed a session. Answer after trying the step, or choose “I have not tried it yet”.','A natural contraction; keep completion distinction and exact response label.','member')
change('member-experience/grub-runtime.mjs','/member/grub','Your week is clear. Build a plan or choose a day from any recipe.','No meals planned yet. Build a plan or choose a day from any recipe.','Make empty state explicit.','member')
change('member-experience/grub-runtime.mjs','/member/grub','Your list is clear.','Your shopping list is empty.','Make empty state explicit.','member')
change('member-experience/grub-runtime.mjs','/member/grub','Your account response was incomplete. Reload before making changes.','We couldn’t load all your saved food. Reload before making changes.','Describe user impact; preserve reload-before-write instruction.','member')
change('member-experience/grub-runtime.mjs','/member/grub','Updating a meal rebuilds its ingredients. Items with changed quantities return to needed.','When you change a meal, its ingredients update on your shopping list. If a quantity changes, that item is marked as needed again.','Explain shopping-list behaviour without changing it.','member')
change('member-experience/fit-runtime.mjs','/member/fit','Your plan is ready. Start where you are and swap anything that does not suit.','Your plan is ready. Read through the exercises and swap any that don’t suit you.','Replace slogan with the next action.','member')
change('member-experience/fit-runtime.mjs','/member/fit','Shift could not build the plan just now.','We couldn’t build your plan just now. Please try again.','Calm error and next action.','member')
change('member-experience/fit-runtime.mjs','/member/fit','Prefer not to say cannot be combined with another limitation.','Choose either “Prefer not to say” or the limitations you want to include.','Explain how to resolve the selection error.','member')
change('member-experience/entry.mjs','/member/saved','Recipes and meals you explicitly saved to your account.','Recipes and meals you chose to save to your account.','Remove administrative phrasing.','member')
(root/'preview/voice/edits.json').write_text(json.dumps(edits,ensure_ascii=False,indent=2)+'\n')
print(f'{len(edits)} targeted copy changes')
