import fs from 'node:fs';
import {catalogueRecords,bindCatalogueImages,catalogueSummary,generationJobs} from './catalogue-data.mjs';
export function catalogueAssets(){
  const records=bindCatalogueImages(catalogueRecords(),JSON.parse(fs.readFileSync('preview/fit-grub/catalogue-images.json')));
  const summary=catalogueSummary(records);
  const html=`<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>SHIFT · Full catalogue visual preview</title><link rel="stylesheet" href="/catalogue.css"></head><body><a class="skip" href="#catalogue-main">Skip to content</a><header><a class="brand" href="/catalogue">SHIFT <span>FIT & GRUB</span></a><nav aria-label="Preview"><a href="/member/grub">Grub programme</a><a href="/member/fit">Fit programme</a><a href="/visuals">Original samples</a></nav><p class="preview">PREVIEW ONLY · Catalogue imagery rollout · Live website unchanged</p></header><main id="catalogue-main"><section class="intro"><p class="eyebrow">A little more life. The same SHIFT.</p><h1>Good food.<br>Movement that makes sense.</h1><p>Explore the accepted recipe and movement catalogue in the new look. Open any card for its original instructions.</p><p class="coverage">${summary.recipeImages} of ${summary.recipes} recipes have new preview photos. ${summary.movementImages} of ${summary.movements} movement examples have draft images; technique review remains pending. All ${summary.exerciseVariants.toLocaleString('en-GB')} exercise variants are listed. Variant imagery has not been approved.</p></section><section aria-label="Catalogue filters" class="filters"><div class="tabs"><button type="button" data-kind="food" aria-pressed="true">SHIFT Grub</button><button type="button" data-kind="movement" aria-pressed="false">SHIFT Fit</button></div><label>Find a recipe or movement<input id="search" type="search" placeholder="Try chicken, oats or sit to stand"></label><div class="filter-row"><label id="meal-label">Meal<select id="meal"><option value="">Every meal</option><option>breakfast</option><option>lunch</option><option>dinner</option><option>snack</option></select></label><label>Photography<select id="status"><option value="">All items</option><option value="with">With preview images</option><option value="without">Awaiting images</option></select></label></div><p id="results-count" role="status"></p></section><section id="cards" class="cards" aria-label="Catalogue results"></section><div class="pagination"><button id="previous" type="button">Previous</button><span id="page-number"></span><button id="next" type="button">Next</button></div><p class="footnote">Generated imagery is illustrative; it cannot prove ingredient weights or exercise suitability. Original recipe content and exercise dosage remain unchanged. This is a review preview, not a personalised plan.</p></main><dialog id="detail" aria-labelledby="detail-title"><button id="close-detail" type="button">Close ×</button><div id="detail-content"></div></dialog><script id="catalogue-data" type="application/json">${JSON.stringify(records).replaceAll('<','\\u003c')}</script><script src="/catalogue.js"></script></body></html>`;
  const out={'/catalogue':{type:'text/html',body:html},'/catalogue.js':{type:'text/javascript',body:fs.readFileSync('preview/fit-grub/catalogue-client.js','utf8')},'/catalogue.css':{type:'text/css',body:fs.readFileSync('preview/fit-grub/catalogue.css','utf8')},'/catalogue-summary.json':{type:'application/json',body:JSON.stringify(summary)},'/catalogue-jobs.json':{type:'application/json',body:JSON.stringify(generationJobs(records))}};
  out['/catalogue-phone']={type:'text/html',body:'<!doctype html><html lang="en-GB"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>SHIFT catalogue · phone preview</title><style>body{margin:16px;background:#050505;color:#e7e3da;font:16px Arial}iframe{display:block;width:390px;max-width:100%;height:850px;border:1px solid #707762;margin:auto}a{color:inherit}</style></head><body><p>Phone width · <a href="/catalogue">Open full preview</a></p><iframe title="Catalogue phone preview" src="/catalogue"></iframe></body></html>'};
  // Files are served as separate lazy-loaded static assets, not repeated base64 in every page.
  fs.mkdirSync('preview/fit-grub/public/catalogue-images',{recursive:true});
  for(const r of records.filter(r=>r.image))fs.copyFileSync(`preview/fit-grub/images/${r.image.file}`,`preview/fit-grub/public/catalogue-images/${r.image.file}`);
  return out;
}
