import assert from 'node:assert/strict';
export function applyProgrammeVisuals(source,kind,records){
 const replace=(from,to)=>{assert.equal(source.split(from).length-1,1,`Preview visual hook changed: ${from.slice(0,60)}`);source=source.replace(from,to);};
 const data=JSON.stringify(records.filter(x=>x.kind===(kind==='grub'?'food':'movement'))).replaceAll('<','\\u003c');
 if(kind==='grub'){
  replace('function recipeDetails(meal)',`const previewFoodRecords=${data};
function previewFoodImage(id){const m=previewFoodRecords.find(x=>x.id===id);return m?'<figure class="sv-food" data-visual-id="'+esc(m.id)+'"><img width="1448" height="1086" src="'+m.image+'" alt="'+esc(m.alt)+'"><figcaption>Recipe-specific illustration · portions illustrative</figcaption></figure>':''}
function recipeDetails(meal)`);
  replace('<small>${esc(meal.type)}</small><b>${esc(meal.name)}</b>','${previewFoodImage(meal.id)}<small>${esc(meal.type)}</small><b>${esc(meal.name)}</b>');
  replace("return{key:di+'-'+mi,day:day.day","return{id:meal.id,key:di+'-'+mi,day:day.day");
  replace('<div style="display:block;padding:16px"><label><input type="checkbox" data-prep-check>','<div style="display:block;padding:16px">${previewFoodImage(x.id)}<label><input type="checkbox" data-prep-check>');
  replace('${plan.catalogue?.published_total_available||798} reviewed recipes available','3 draft recipe samples · image review');
  replace('Your Grub week','Your sample Grub plan');
 }else{
  replace('function markup()',`const previewMovementRecords=${data};
function previewMovementLibrary(){return '<section class="sv-library" aria-labelledby="svGuideTitle"><p class="sf-kicker">MOVEMENT GUIDES · APPROVED VISUALS</p><h2 id="svGuideTitle">See how it moves.</h2><p>Explore these movement guides, or <a href="/fit-v3">browse all 300 movement images</a>. Your session is built separately from your saved profile.</p><div class="sv-guide-grid">'+previewMovementRecords.map(m=>'<details class="sv-guide" data-visual-id="'+esc(m.id)+'"><summary><img width="'+m.width+'" height="'+m.height+'" src="'+m.image+'" alt="'+esc(m.title)+' — three-stage sequence"><span><b>'+esc(m.title)+'</b><em>Open the movement guide ↓</em></span></summary><div class="sv-guide-body"><div class="sv-stages">'+m.phases.map((p,i)=>'<figure><div class="sv-pose" style="aspect-ratio:'+m.width+'/'+(m.height*3)+'"><img src="'+m.image+'" style="left:-'+(i*100)+'%" alt="'+esc(p.alt)+'"></div><figcaption><b>'+esc(p.title)+'</b><span>'+esc(p.caption)+'</span></figcaption></figure>').join('')+'</div><h3>Movement instructions</h3><ul>'+m.source.instructions.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul><h3>Form & safety</h3><ul>'+[...m.source.form_cues,...m.source.safety_cues].map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul><h3>Make it easier</h3><p>'+esc(m.source.regression.instruction)+'</p><p class="sv-caption">AI-generated illustration, visually approved by Matt. This guide does not select an exercise for you or log a session.</p></div></details>').join('')+'</div></section>'}
function markup()`);
  replace('<details class="sf-card sf-profile" id="sfProfile">','${previewMovementLibrary()}<details class="sf-card sf-profile" id="sfProfile">');
 }
 return source;
}
export const programmeVisualCSS=`
.preview-bar nav{flex-wrap:wrap}.sg-primary,.sf-primary{font-size:20px}.sg-card,.sf-card{border-radius:14px}.sg-launch,.sf-launch{text-align:left}.sg-launch .sf-centre,.sf-launch .sf-centre{justify-content:flex-start}.sg-hero,.sf-hero{padding-bottom:24px}.sg-meal{padding:0 0 18px;background:transparent;overflow:hidden;border-bottom:1px solid #707762}.sg-meal>b{font-size:25px;line-height:1.15;margin-top:5px}.sg-meal .sg-recipe,.sg-meal .sg-meal-actions{margin-top:15px}.sv-food{margin:0 0 16px;max-width:640px}.sv-food img{display:block;width:100%;height:auto;border-radius:12px}.sv-food figcaption,.sv-caption{font-size:12px;line-height:1.5;margin-top:8px;color:#e7e3da}.sg-utility .sv-food{max-width:500px;margin-bottom:22px}.sg-day>div{grid-template-columns:minmax(0,1fr)}.sg-day>summary{flex-wrap:wrap}.sg-next{gap:10px}.sv-library{margin:32px 0 20px;border-top:1px solid #707762;padding-top:30px}.sv-library>h2{font-size:clamp(30px,4vw,46px);margin:5px 0 16px;line-height:1.1}.sv-library>p{max-width:760px}.sv-guide-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.sv-guide{min-width:0;border:1px solid #707762;border-radius:14px;overflow:hidden;align-self:start}.sv-guide>summary{list-style:none;cursor:pointer}.sv-guide>summary::-webkit-details-marker{display:none}.sv-guide>summary>img{width:100%;height:auto;display:block}.sv-guide>summary>span{display:grid;gap:8px;padding:20px}.sv-guide>summary b{font-size:24px}.sv-guide>summary em{font-size:14px;font-style:normal;text-decoration:underline}.sv-guide[open]{grid-column:1/-1}.sv-guide[open]>summary>img{display:none}.sv-guide-body{padding:0 20px 24px}.sv-stages{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.sv-stages figure{min-width:0;margin:0}.sv-pose{position:relative;overflow:hidden;background:#e7e3da;border-radius:10px}.sv-pose img{position:absolute;width:300%;max-width:none;height:100%;top:0}.sv-stages figcaption{display:grid;gap:5px;margin:12px 0;line-height:1.4}.sv-stages figcaption b{font-size:19px}.sv-guide-body li{margin:12px 0}.sv-guide-body ul{padding-left:22px}.sv-guide summary:focus-visible{outline:3px solid #e7e3da;outline-offset:-4px}@media(max-width:700px){.sv-guide-grid,.sv-stages{grid-template-columns:1fr}.sv-guide[open]{grid-column:auto}.sv-stages figure{max-width:410px;width:100%;margin:auto}.sv-guide-body{padding:0 16px 20px}.sg-card,.sf-card{padding:20px}.sg-meal>b{font-size:23px}.sg-utility{padding:14px}.sg-utility .sg-day>div{padding:0!important}.sg-utility .sv-food{margin-top:16px}.sg-recipe-grid{grid-template-columns:1fr}.preview-bar nav{gap:10px 20px}}@media print{.sv-food{max-width:240px}.sv-food figcaption{color:#050505}}
`;
