import {refinementStyles,refinementClient} from './refinement.mjs';
import {tabStyles,tabClient} from './tabs.mjs';
import {screenStyles,screenClient} from './screens.mjs';
// Preview-only presentation. No data endpoints, copied member state or native bridge.
export const appStyles=String.raw`
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]){background:#050505!important;font-family:Arial,Helvetica,sans-serif!important;padding-bottom:90px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) main{max-width:780px!important;background:#050505!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]):not([data-member-page="dashboard"]):not([data-member-page="life-back"]){background:#e7e3da!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]):not([data-member-page="dashboard"]):not([data-member-page="life-back"]) main{background:#e7e3da!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout])[data-member-page="life-back"]{color:#e7e3da!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) :is(main,main p,main h1,main h2,main h3){font-family:Arial,Helvetica,sans-serif!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) :is(main,#todayActions.mtm-home) [data-member-hero="v1"]{min-height:0!important;padding:24px 0!important;background:#050505!important;margin-bottom:18px!important;border-radius:0!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) :is(main,#todayActions.mtm-home) [data-member-hero="v1"]:after{display:none!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) :is(main,#todayActions.mtm-home) [data-member-hero="v1"]>div{max-width:100%!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) :is(main,#todayActions.mtm-home) [data-member-hero="v1"] :is(h1,h2){font-size:32px!important;line-height:1.12!important;font-weight:800!important;letter-spacing:-.035em!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) nav.sst-member-tabs{display:none!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout])[data-app-more="open"] nav.sst-member-tabs{display:flex!important;flex-wrap:wrap!important;position:relative!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.mtm-home .mtm-dashboard{grid-template-columns:1fr!important;gap:16px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.mtm-home .mtm-panel{padding:20px!important;border-color:#707762!important;border-radius:16px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.mtm-home .mtm-next{background:#e7e3da!important;color:#050505!important;padding:24px!important;border-radius:16px!important;margin:0 0 16px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.mtm-home .mtm-next :is(h3,p,small,strong,span,a){color:#050505!important;-webkit-text-fill-color:#050505!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.mtm-home .mtm-next .mt-now-action{display:flex!important;justify-content:center;width:100%!important;background:#050505!important;color:#e7e3da!important;-webkit-text-fill-color:#e7e3da!important;min-height:50px!important;margin-top:18px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #dailyCheckinFollowup{padding:20px!important;border-radius:16px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.mtm-home .mtm-feelings{grid-template-columns:1fr!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) :is(button,a,summary):focus-visible{outline:3px solid #707762!important;outline-offset:3px!important}
#appPreviewBar{padding:10px 16px;background:#e7e3da;color:#050505;font:13px/1.5 Arial,sans-serif}#appPreviewBar a{color:#050505;text-decoration:underline}
#appBottomNav{position:fixed;z-index:45;bottom:0;left:0;right:0;display:grid;grid-template-columns:repeat(4,1fr);gap:6px;padding:10px 12px max(10px,env(safe-area-inset-bottom));background:#050505;border-top:1px solid #707762;color:#e7e3da;font:700 13px/1.3 Arial,sans-serif}
#appBottomNav :is(a,button){display:flex;align-items:center;justify-content:center;min-height:48px;border:0;border-radius:9px;text-decoration:none;background:transparent;color:#e7e3da;font:inherit;cursor:pointer}
#appBottomNav [aria-current="page"]{background:#e7e3da;color:#050505}
@media(min-width:800px){#appBottomNav{max-width:780px;margin:auto;border:1px solid #707762;border-radius:14px 14px 0 0}}

/* Today v2: compact app composition, retaining the original live controls. */
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout])[data-member-page="dashboard"] main{max-width:980px!important;padding:0 20px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2{display:flex!important;flex-direction:column;gap:16px;color:#e7e3da!important;padding:0!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-hero{padding:20px 0 6px!important;min-height:0!important;margin:0!important;background:none!important;border:0!important;display:block!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-hero img{display:none!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-hero h2{font-size:36px!important;letter-spacing:-1.4px!important;margin:8px 0!important;line-height:1.08!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-hero p{font-size:15px!important;margin:0!important;color:#c5c8bc!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-kicker{font-size:11px!important;letter-spacing:1.6px!important;color:#bac4a7!important;font-weight:700!important}
.app-today-shortcuts{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #46503d;border-radius:14px;padding:6px;background:#11160f;gap:5px}
.app-today-shortcuts a{display:grid;justify-items:center;gap:7px;color:#d8dbce!important;text-decoration:none;padding:10px 4px;font-size:12px!important;border-radius:9px;min-height:62px}.app-today-shortcuts a:first-child{background:#303a27;color:#e7e3da!important}
.app-line-icon{width:25px;height:25px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round;color:#b4c39a;flex-shrink:0}
.app-today-grid{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(0,1fr);gap:16px;align-items:stretch}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-panel{margin:0!important;padding:20px!important;min-width:0;border:1px solid #46503d!important;background:linear-gradient(145deg,#141c11,#0a0e09)!important;border-radius:16px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-section-head{margin:0 0 12px!important;gap:10px!important;align-items:center!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-section-head h2{margin:0!important;font-size:11px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-section-head :is(a,span){font-size:12px!important;color:#c5c8bc!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-plan{display:grid!important;grid-template-columns:1fr!important;gap:0!important;margin:0!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-step{position:relative;display:grid!important;grid-template-columns:42px 1fr;column-gap:12px;padding:14px 0!important;border:0!important;border-bottom:1px solid #303b29!important;border-radius:0!important;background:none!important;min-height:0!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-step>.app-line-icon{grid-column:1;grid-row:1/6;align-self:center;width:36px;height:36px;padding:5px;box-sizing:border-box}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-step>:not(.app-line-icon){grid-column:2;margin:0!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-step small{font-size:10px!important;color:#bac4a7!important;letter-spacing:1px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-step h3{font-size:17px!important;line-height:1.25!important;margin:4px 0!important;color:#e7e3da!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-step p{font-size:12px!important;line-height:1.4!important;color:#c5c8bc!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-step a{font-size:12px!important;min-height:32px;display:flex;align-items:center;color:#dbe3ce!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-next{margin:16px 0 0!important;padding:16px!important;border:0!important;border-radius:10px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-next h3{font-size:19px!important;margin:5px 0!important;line-height:1.2!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-next p{font-size:13px!important;line-height:1.4!important;margin:5px 0!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-next .mt-now-action{margin-top:10px!important;min-height:44px!important;font-size:14px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-change-step{display:block;font-size:12px!important;margin:10px 0 0!important;text-align:center}
.app-life-card{display:flex;flex-direction:column;align-items:center;text-align:center;justify-content:center;gap:12px}
.app-life-ring{width:158px;height:158px;border-radius:50%;background:conic-gradient(#9da98a calc(var(--app-score,0)*1%),#293321 0);padding:8px;box-sizing:border-box;display:grid;place-items:center}
.app-life-ring>div{width:100%;height:100%;border-radius:50%;background:#10160e;display:flex;flex-direction:column;align-items:center;justify-content:center}
.app-life-ring strong{font-size:48px!important;line-height:1!important;letter-spacing:-2px;color:#e7e3da!important}.app-life-ring span{font-size:12px;color:#c5c8bc;margin-top:6px}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .app-life-card h3{font-size:18px!important;line-height:1.3!important;margin:0!important;color:#e7e3da!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .app-life-card p{font-size:12px!important;margin:0!important;line-height:1.45!important;color:#c5c8bc!important}
.app-life-card>a{border:1px solid #707762;border-radius:8px;padding:12px;display:block;width:100%;box-sizing:border-box;color:#e7e3da!important;text-decoration:none;font-size:13px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-days{display:grid!important;grid-template-columns:repeat(7,1fr)!important;gap:8px!important;margin:14px 0!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-days span{display:grid!important;justify-items:center;gap:6px!important;font-size:11px!important;color:#c5c8bc!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-days b{width:30px!important;height:30px!important;border:2px solid #46503d!important;border-radius:50%;display:grid;place-items:center;background:transparent!important;color:#bac4a7!important;font-size:17px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-days b.is-logged{background:#b4c39a!important;color:#050505!important;border-color:#b4c39a!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-week>p{font-size:13px!important;margin:0!important;color:#c5c8bc!important}
.app-secondary-controls{border-top:1px solid #303b29;padding-top:12px;margin-top:12px}.app-secondary-controls>summary{font-size:12px;color:#d8dbce;min-height:32px;cursor:pointer}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-record-grid{display:grid!important;grid-template-columns:1fr 1fr!important;gap:10px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-record-grid a{padding:12px!important;border:1px solid #46503d!important;border-radius:9px!important;min-height:60px!important;background:#10160e!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-record-grid strong{font-size:14px!important;color:#e7e3da!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-record-grid span{font-size:11px!important;color:#c5c8bc!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-ask h2{font-size:24px!important;margin:8px 0!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-ask>p{font-size:13px!important;margin:5px 0!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 #mtmAskForm{display:grid!important;grid-template-columns:1fr auto!important;gap:8px!important;margin-top:14px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 #mtmAskForm label{grid-column:1/-1;font-size:12px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 #mtmQuestion{min-height:48px!important;height:48px!important;background:#20291b!important;border:1px solid #707762!important;color:#e7e3da!important;border-radius:8px!important;margin:0!important;padding:12px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 #mtmAskForm button{min-height:48px!important;background:#e7e3da!important;color:#050505!important;border-radius:8px!important;margin:0!important;padding:12px!important;font-size:12px!important}
@media(max-width:600px){.app-today-grid{grid-template-columns:1fr}.app-life-card{display:grid!important;grid-template-columns:100px 1fr;column-gap:18px;text-align:left;justify-items:start}.app-life-ring{width:100px;height:100px;grid-column:1;grid-row:1/6}.app-life-ring strong{font-size:32px!important}.app-life-card>.mtm-kicker,.app-life-card>h3,.app-life-card>p,.app-life-card>a{grid-column:2}.app-life-card>a{padding:9px;text-align:center}.app-life-card>.app-life-ring{grid-column:1}.app-today-shortcuts a{font-size:11px!important}html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout])[data-member-page="dashboard"] main{padding:0 14px!important}html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-panel{padding:16px!important}}


.app-review-account{font:12px/1.4 Arial,Helvetica,sans-serif;background:#e7e3da;color:#050505;padding:4px 16px}.app-review-account summary{cursor:pointer;min-height:24px}.app-review-account aside{overflow-wrap:anywhere}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .app-life-card{display:flex!important;align-items:center!important;text-align:center!important;justify-content:center!important;gap:14px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-step a{background:transparent!important;border:0!important;padding:6px 0!important;text-decoration:none!important;font-weight:600!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .app-life-card>a{display:block!important;background:transparent!important;color:#e7e3da!important;border:1px solid #707762!important;border-radius:8px!important;padding:12px!important;text-decoration:none!important;width:100%!important}
@media(max-width:600px){html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .app-life-card{display:grid!important;grid-template-columns:100px 1fr!important;text-align:left!important;justify-items:start!important;gap:8px 16px!important}}


html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .mtm-next .mtm-loop-controls button{color:#050505!important;-webkit-text-fill-color:#050505!important;border-color:#707762!important;background:transparent!important;font-size:12px!important;padding:9px!important;min-height:40px!important}
html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) .app-footer-details{max-width:980px;margin:20px auto;padding:16px 20px;color:#e7e3da;border-top:1px solid #46503d;font:13px/1.5 Arial,Helvetica,sans-serif}.app-footer-details>summary{cursor:pointer;min-height:44px}.app-footer-details>summary::marker{color:#b4c39a}
@media(max-width:600px){html body[data-app-layout="preview"]:is(#app-preview-scope,[data-app-layout]) #todayActions.app-today-v2 .app-life-card{height:auto!important;min-height:0!important;align-self:start!important;align-content:start!important;grid-template-rows:repeat(4,auto)!important}.app-life-card>.app-life-ring{grid-row:1/5!important}.app-life-card>*{min-height:0!important}}

@media(max-width:600px){.app-today-grid{display:flex!important;flex-direction:column!important;gap:16px!important;height:auto!important;min-height:0!important}.app-today-grid>.app-life-card{align-self:stretch!important}}
@media print{#appBottomNav,#appPreviewBar{display:none!important}}
`+screenStyles+tabStyles+refinementStyles;
export const appClient=screenClient+String.raw`(()=>{
 function current(){document.querySelectorAll('#appBottomNav a').forEach(a=>{const u=new URL(a.href),match=u.pathname.replace('/staging/member-connected/','/member/')===location.pathname.replace('/staging/member-connected/','/member/')&&(u.hash?u.hash===(location.hash||'#today'):true);if(match){if(a.getAttribute('aria-current')!=='page')a.setAttribute('aria-current','page')}else a.removeAttribute('aria-current')})}
 document.addEventListener('click',e=>{const more=e.target.closest?.('#appMore');if(!more)return;const open=document.body.dataset.appMore!=='open';document.body.dataset.appMore=open?'open':'closed';more.setAttribute('aria-expanded',String(open));if(open){const nav=document.querySelector('.sst-member-tabs');nav?.scrollIntoView({block:'start'});nav?.querySelector('a')?.focus()}},true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.dataset.appMore==='open'){document.body.dataset.appMore='closed';const more=document.getElementById('appMore');more?.setAttribute('aria-expanded','false');more?.focus()}});
 
 const iconPaths={sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5',fit:'M4 8v8m3-11v14m10-14v14m3-11v8M7 12h10',food:'M5 3v7m3-7v7M3 3v6a3 3 0 0 0 6 0M6 12v9M18 3v18m0-18c-5 3-5 10 0 10',life:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z'};
 function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','app-line-icon');svg.setAttribute('aria-hidden','true');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',iconPaths[name]);svg.append(p);return svg}
 function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n}
 function rebuildToday(){
 const root=document.getElementById('todayActions'),hero=root?.querySelector('.mtm-hero'),grid=root?.querySelector('.mtm-dashboard');if(!hero||!grid||root.querySelector('.app-today-grid'))return;
 root.classList.add('app-today-v2');const day=grid.querySelector('.mtm-panel'),week=grid.querySelector('.mtm-week'),plan=root.querySelector('.mtm-plan'),next=root.querySelector('.mtm-next'),life=week?.querySelector('.mt-connected-life');if(!day||!week||!plan||!life)return;
 const shortcuts=el('nav','app-today-shortcuts');shortcuts.setAttribute('aria-label','Today tools');[['Today','sun','/member/dashboard#today'],['Shift Fit','fit','/member/fit'],['Shift Grub','food','/member/grub'],['Life Back','life','/member/life-back']].forEach(([label,key,href])=>{const a=el('a','',label);a.href=href;a.prepend(icon(key));shortcuts.append(a)});hero.after(shortcuts);
 const oldMore=root.querySelector('#more-for-today');plan.querySelectorAll('.mtm-step').forEach((row,i)=>row.prepend(icon(i?'fit':'food')));day.querySelector('.mtm-section-head').after(plan);if(next)plan.after(next);
 const controls=el('details','app-secondary-controls'),summary=el('summary','','Adjust today or see why');controls.append(summary);[...day.children].filter(n=>n!==plan&&n!==next&&!n.classList.contains('mtm-section-head')).forEach(n=>controls.append(n));day.append(controls);if(oldMore){oldMore.id='';controls.id='more-for-today';[...oldMore.children].filter(n=>n.tagName!=='SUMMARY').forEach(n=>controls.append(n));oldMore.remove()}root.querySelector('.mtm-change-step')?.addEventListener('click',()=>{controls.open=true});
 const lifeCard=el('section','mtm-panel app-life-card');lifeCard.append(el('p','mtm-kicker','LIFE BACK'));const score=life.querySelector('.mtm-score'),num=score?.textContent.match(/^(\d+)/),ring=el('div','app-life-ring'),inside=el('div');ring.style.setProperty('--app-score',num?Math.min(100,Number(num[1])):0);inside.append(el('strong','',num?num[1]:'—'),el('span','',num?'out of 100':'Your baseline'));ring.append(inside);ring.setAttribute('aria-label',num?'Life Back score '+num[1]+' out of 100':'No Life Back score recorded');lifeCard.append(ring);score?.remove();while(life.firstChild)lifeCard.append(life.firstChild);life.remove();week.querySelectorAll('hr').forEach(n=>n.remove());week.querySelectorAll(':scope>.mtm-kicker').forEach(n=>n.remove());const utility=week.querySelector('.mtm-utility');if(utility)controls.append(utility);const weekly=week.querySelector('.mt-weekly');if(weekly)controls.append(weekly);
 const newGrid=el('div','app-today-grid');newGrid.append(day,lifeCard);grid.replaceWith(newGrid);shortcuts.after(newGrid);newGrid.after(week);
 const care=root.querySelector('#optional-checkin');if(care)week.after(care);const followup=document.getElementById('dailyCheckinFollowup');if(followup)(care||week).after(followup);const guide=document.getElementById('memberDayGuide');if(guide&&!guide.closest('[data-app-guide]')){const details=el('details','app-secondary-controls');details.dataset.appGuide='true';details.append(el('summary','','Help using My Timber'),guide);root.after(details)}
 }
 document.addEventListener('sst:today-rendered',()=>queueMicrotask(rebuildToday));

 function boot(){current();rebuildToday();if(document.body.dataset.memberPage==='dashboard')document.querySelectorAll('footer').forEach(footer=>{if(footer.closest('main,details'))return;const details=el('details','app-footer-details');details.append(el('summary','','Help & legal'));footer.before(details);details.append(footer)});const account=document.getElementById('connected-account')?.closest('aside');if(account&&!account.closest('details')){const details=el('details','app-review-account');details.append(el('summary','','Fictional review account'));account.before(details);details.append(account)}const bar=document.getElementById('appBottomNav');if(bar)new MutationObserver(current).observe(bar,{subtree:true,attributes:true,attributeFilter:['href']})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();addEventListener('hashchange',current);
})();`+tabClient+refinementClient;
export function appPresentation(html,path,embedded=false){
 path=path.replace('/staging/member-connected/','/member/').replace(/\.html$/,'');
 if(!/^\/member\/(dashboard|grub|fit|life-back|check-in|settings|saved|plans|orders|ask-timber)$/.test(path)||html.includes('data-app-layout="preview"'))return html;
 if(!html.includes('data-member-chrome="v1"'))return html;
 const bar='<aside id="appPreviewBar">APP LAYOUT PREVIEW · fictional accounts only · <a href="?view=web">Compare website view</a> · <a href="/__app-review">Review &amp; health connections</a></aside>';
 const nav='<nav id="appBottomNav" aria-label="App navigation"><a href="/member/dashboard#today">Today</a><a href="/member/dashboard#visualise">Progress</a><a href="/member/life-back">Life Back</a><button id="appMore" type="button" aria-expanded="false">More</button></nav>';
 return html.replace(/<body([^>]*)>/,(_,a)=>'<body'+a+' data-app-layout="preview"'+(embedded?' data-app-panel="1"':'')+'>'+bar).replace('</body>','<style data-app-preview-style>'+appStyles+'</style>'+nav+'<script defer src="/__app-layout.mjs"></script></body>');
}
