const fs=require('fs'),assert=require('assert/strict'),{randomUUID}=require('crypto');
const {chromium,webkit}=require(process.env.APP_TOOLS+'/node_modules/playwright');
const base=process.env.PREVIEW_URL,dir='work/staging/generated/app-layout-evidence';
assert(/^https:\/\/shift-stabilisation-preview\.[a-z0-9-]+\.workers\.dev$/.test(base));
const fixture=JSON.parse(fs.readFileSync('work/staging/generated/probe.json'));
const report={source:process.env.GITHUB_SHA,cases:[],productionWrites:0,limits:['Fictional accounts in isolated preview only.','Browser Chromium/WebKit at 390 and 1440px, not signed native apps or physical phones.','Apple Health and Health Connect are interaction prototypes only; no native bridge or health sync is implemented.']};
async function api(ctx,path,body){const r=await ctx.request.fetch(base+path,{method:body?'POST':'GET',headers:{Origin:base},...(body?{data:body}:{}),timeout:45000});assert(r.ok(),path+' '+r.status());return r.json()}
(async()=>{let index=0;try{for(const [engine,name]of [[chromium,'chromium'],[webkit,'webkit']])for(const width of [390,1440]){
 const browser=await engine.launch(),app=await browser.newContext({viewport:{width,height:900}}),web=await browser.newContext({viewport:{width,height:900}}),p=await app.newPage(),w=await web.newPage();
 const row={engine:name,width,checks:[]};report.cases.push(row);
 try{
 const login={email:'probe'+fixture.browserIds[index++]+'@example.invalid',password:fixture.password};await api(app,'/v1/auth/login',login);await api(web,'/v1/auth/login',login);await api(app,'/v1/consents',{type:'my_shift_health_tracking',version:'2026-08-18-v1',granted:true});
 await p.goto(base+'/member/dashboard?view=app#today',{waitUntil:'domcontentloaded'});await p.locator('.today-week-start[data-week-state="start"]').waitFor({timeout:45000});assert(await p.getByText('Start with one meal. No need to overhaul your week.',{exact:true}).isVisible());await p.locator('.today-week-start>a').click();assert(await p.locator('.today-meal').isVisible());assert.equal((await api(app,'/v1/grub/workspace')).today,null,'Opening a first action does not save a meal');await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:dir+'/'+name+'-'+width+'-first-visit.png'});row.checks.push('Fresh account gets a clear meal-first start and useful recipe access without a mood or goal questionnaire; clicks do not create records');
 let life=await api(app,'/v1/life-back');life=await api(app,'/v1/life-back',{action:'goal',revision:life.progress.revision,goal:'Fictional app layout review',operationId:randomUUID()});life=await api(app,'/v1/life-back',{action:'checkin',goalId:life.progress.goalId,ratings:{energy:40,sleep:60,confidence:60,movement:60,clothes:60,personal:60},win:'',supportNeed:'food',operationId:randomUUID()});
 await p.goto(base+'/member/dashboard?view=app#today',{waitUntil:'domcontentloaded'});await p.locator('#appBottomNav').waitFor();if(await p.locator('.cookie-banner-v3a').count())await p.locator('[data-consent="necessary"]').click();await p.getByText(life.progress.nextShift.title,{exact:true}).filter({visible:true}).first().waitFor({timeout:45000});
 await p.locator('.today-layout').waitFor();assert(await p.locator('.today-meal').isVisible());assert(await p.locator('.today-life').isVisible());assert.equal(await p.locator('.app-today-shortcuts a').count(),4);if(width===390){const gap=await p.evaluate(()=>document.querySelector('.mtm-week').getBoundingClientRect().top-document.querySelector('.today-meal').getBoundingClientRect().bottom);assert(gap>=0&&gap<=24,'Week follows meal without an empty grid track');}
 assert.match(await p.locator('body').evaluate(el=>getComputedStyle(el).fontFamily),/Arial/);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await p.locator('#appMore').click();assert.equal(await p.locator('#appMore').getAttribute('aria-expanded'),'true');assert(await p.locator('.sst-member-tabs').isVisible());await p.keyboard.press('Escape');assert.equal(await p.locator('#appMore').getAttribute('aria-expanded'),'false');
 assert.equal(await p.locator('.mtm-next').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(231, 227, 218)');
 await p.locator('.today-meal[data-meal-state]').waitFor();assert.notEqual(await p.locator('.today-meal').getAttribute('data-meal-state'),'chosen','First-use Today does not invent a chosen meal');
 let food=await api(app,'/v1/grub/workspace');const results=await api(app,'/v1/grub/search',{mode:'discover',query:'Chicken Traybake'});const illustrated=results.top.find(r=>r.image);assert(illustrated,'Governed catalogue has illustrated meal');
 await api(app,'/v1/grub/workspace',{action:'choose-today',recipeId:illustrated.id,revision:food.revision,operationId:randomUUID()});
 await p.reload({waitUntil:'domcontentloaded'});await p.locator('.today-meal[data-meal-state="chosen"]').waitFor({timeout:45000});assert.equal(await p.locator('.today-meal').getAttribute('data-recipe-id'),illustrated.id);assert((await p.locator('.today-meal-meta').textContent()).includes(illustrated.name));await p.waitForFunction(()=>{const i=document.querySelector('.today-meal img');return i?.complete&&i.naturalWidth>0});
 assert.equal(await p.locator('.today-meal').evaluate(el=>getComputedStyle(el).padding),'0px','Food image reaches card edges');assert.equal(await p.locator('.today-meal .today-eyebrow').evaluate(el=>getComputedStyle(el).color),'rgb(86, 96, 68)','Grub label is legible on cream');
 await p.locator('.today-meal-action').click();const mealFrame=p.frameLocator('#appTool-grub iframe');await mealFrame.locator('#grubDiscoverResults h3').filter({hasText:illustrated.name}).waitFor({timeout:45000});assert.equal(new URL(p.url()).pathname,'/member/dashboard');if(await mealFrame.locator('#grubDiscoverResults .app-refine-recipe:not([open])').count())await mealFrame.locator('#grubDiscoverResults .app-refine-recipe>summary').click();await mealFrame.locator('#grubDiscoverResults .grub-recipe-detail summary').click();assert(await mealFrame.locator('#grubDiscoverResults .grub-recipe-detail ol').isVisible());await p.locator('#appTab-today').click();
 row.checks.push('Honest first-use view; selected catalogue meal and exact illustration persist after refresh; meal CTA opens correct recipe and cooking instructions inline');

 await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:dir+'/'+name+'-'+width+'-app-today.png',fullPage:true});
 await p.evaluate(async()=>{document.documentElement.style.scrollBehavior='auto';document.body.style.scrollBehavior='auto';document.activeElement?.blur();scrollTo({top:0,behavior:'instant'});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});await p.screenshot({path:dir+'/'+name+'-'+width+'-today-viewport.png'});
 const mainURL=new URL(p.url()).pathname;let topNavigations=0;const countTop=r=>{if(r.isNavigationRequest()&&r.frame()===p.mainFrame())topNavigations++};p.on('request',countTop);
 await p.locator('#appTab-grub').click();const grubFrame=p.frameLocator('#appTool-grub iframe');await grubFrame.locator('#grubSearch').waitFor({timeout:45000});await grubFrame.locator('#grubSearch').fill('Unfinished meal search');
 assert.equal(new URL(p.url()).pathname,mainURL);assert.equal(await p.locator('#appTab-grub').getAttribute('aria-selected'),'true');assert(await p.locator('.mtm-hero').isVisible());assert(!(await p.locator('.today-layout').isVisible()));
 await p.locator('#appTab-fit').click();const fitFrame=p.frameLocator('#appTool-fit iframe');await fitFrame.locator('#fitPrefs').waitFor({timeout:45000});await fitFrame.locator('#fitPrefs').fill('Fictional unfinished workout note');
 await p.locator('#appTab-life-back').click();const lifeFrame=p.frameLocator('#appTool-life-back iframe');await lifeFrame.locator('#journeyView:not([hidden])').waitFor({timeout:45000});await lifeFrame.locator('.area-card').first().click();assert(await lifeFrame.locator('dialog[open]').isVisible());await lifeFrame.locator('dialog[open] [data-close]').first().click();
 await p.locator('#appTab-grub').click();assert.equal(await grubFrame.locator('#grubSearch').inputValue(),'Unfinished meal search');await p.goBack();assert.equal(await p.locator('#appTab-life-back').getAttribute('aria-selected'),'true');await p.goForward();assert.equal(await p.locator('#appTab-grub').getAttribute('aria-selected'),'true');
 await p.locator('#appTab-fit').click();assert.equal(await fitFrame.locator('#fitPrefs').inputValue(),'Fictional unfinished workout note');assert.equal(topNavigations,0,'Tool tabs never navigate the containing page');p.off('request',countTop);
 await p.locator('#appTab-grub').click();await grubFrame.locator('#grubRecommendation .grub-recipe').waitFor({timeout:45000});assert(!(await p.locator('#dailyCheckinFollowup').isVisible()));assert(!(await grubFrame.locator('#dailyCheckinFollowup').isVisible()));await p.screenshot({path:dir+'/'+name+'-'+width+'-inline-grub.png',fullPage:true});
 const plainResults=await api(app,'/v1/grub/search',{mode:'discover',query:'Pasta'});const plain=plainResults.top.find(r=>!r.image);assert(plain,'Real unillustrated recipe exists');await grubFrame.locator('#grubSearch').fill(plain.name);await grubFrame.locator('#grubSearchGo').click();const chosenButton=grubFrame.locator('#grubDiscoverResults [data-food-today=\"'+plain.id+'\"]');await chosenButton.waitFor({timeout:45000});const chosenId=plain.id;await chosenButton.click();await p.locator('.today-meal[data-recipe-id="'+chosenId+'"]').waitFor({state:'attached',timeout:45000});assert.equal(new URL(p.url()).pathname,mainURL);await p.locator('#appTab-fit').click();assert.equal(await fitFrame.locator('#fitPrefs').inputValue(),'Fictional unfinished workout note');await p.locator('#appTab-today').click();assert(await p.locator('.today-layout').isVisible());assert(!(await p.locator('#appToolPanels').isVisible()));assert.equal(await p.locator('.today-meal img').count(),0,'No unrelated image for unillustrated meal');assert((await p.locator('.today-meal-meta').textContent()).includes(plain.name));assert((await p.locator('.today-meal-visual').boundingBox()).height<=48,'No empty photograph space');await p.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:dir+'/'+name+'-'+width+'-today-no-photo.png'});row.checks.push('Real unillustrated meal chosen inside Grub refreshes Today into compact fallback without losing Fit draft');row.checks.push('Inline tool tabs preserve page, header, food search and workout draft; Back/Forward restores tabs; Life Back dialog opens inside panel');

 await w.goto(base+'/member/dashboard?view=web#today',{waitUntil:'domcontentloaded'});if(await w.locator('.cookie-banner-v3a').count())await w.locator('[data-consent="necessary"]').click();await w.getByText(life.progress.nextShift.title,{exact:true}).filter({visible:true}).first().waitFor({timeout:45000});assert.equal(await w.locator('#appBottomNav').count(),0);

 await w.locator('#appTab-grub').click();const webGrub=w.frameLocator('#appTool-grub iframe');await webGrub.locator('#grubSearch').waitFor({timeout:45000});await webGrub.locator('#grubSearch').fill('Website unfinished search');
 assert.equal(await webGrub.locator('[data-app-layout]').count(),0);assert.equal(await w.locator('[data-app-layout]').count(),0);
 await w.locator('#appTab-fit').click();const webFit=w.frameLocator('#appTool-fit iframe');await webFit.locator('#fitPrefs').waitFor({timeout:45000});await webFit.locator('#fitPrefs').fill('Website workout draft');
 await w.locator('#appTab-life-back').click();const webLife=w.frameLocator('#appTool-life-back iframe');await webLife.locator('#journeyView:not([hidden])').waitFor({timeout:45000});await webLife.locator('.area-card').first().click();assert(await webLife.locator('dialog[open]').isVisible());await webLife.locator('dialog[open] [data-close]').first().click();
 await w.locator('#appTab-grub').click();assert.equal(await webGrub.locator('#grubSearch').inputValue(),'Website unfinished search');await w.goBack();assert.equal(await w.locator('#appTab-life-back').getAttribute('aria-selected'),'true');await w.goForward();assert.equal(await w.locator('#appTab-grub').getAttribute('aria-selected'),'true');
 await w.screenshot({path:dir+'/'+name+'-'+width+'-website-inline.png',fullPage:true});await w.locator('#appTab-today').click();row.checks.push('Website uses same inline tabs, retained drafts, history and dialog; original website styling remains');
 assert.deepEqual((await api(web,'/v1/life-back')).progress,life.progress);row.checks.push('App presentation and existing website render the same saved goal and next step; Arial, no horizontal overflow, More keyboard recovery');
 for(const [ctx,page,view,other,otherPage]of [[app,p,'app',web,w],[web,w,'web',app,p]]){
 const marker='Fictional '+view+' '+randomUUID();await page.goto(base+'/member/check-in?view='+view,{waitUntil:'domcontentloaded'});await page.locator('[data-mood]').first().click();await page.locator('#moodNote').fill(marker);
 const saved=page.waitForResponse(r=>new URL(r.url()).pathname==='/v1/check-ins'&&r.request().method()==='POST',{timeout:45000});await page.locator('#saveMood').click();const response=await saved;assert(response.ok(),'Check-in save failed: '+response.status()+' '+await response.text());
 await otherPage.reload({waitUntil:'domcontentloaded'});assert(JSON.stringify(await api(other,'/v1/check-ins')).includes(marker),'Other session reads the saved check-in');
 row.checks.push(view+' check-in saved using UI and read through other independently signed-in session after refresh');
 }
 const before=(await api(app,'/v1/life-back')).progress;await api(web,'/v1/life-back',{action:'shift-feedback',shiftId:before.nextShift.id,outcome:'not-fit',operationId:randomUUID()});await p.goto(base+'/member/dashboard?view=app#today',{waitUntil:'domcontentloaded'});const changed=(await api(app,'/v1/life-back')).progress;assert.notEqual(changed.nextShift.detail,before.nextShift.detail);await p.getByText(changed.nextShift.title,{exact:true}).filter({visible:true}).first().waitFor({timeout:45000});
 for(const path of ['/member/grub','/member/fit','/member/life-back','/member/settings']){await p.goto(base+path,{waitUntil:'domcontentloaded'});await p.locator('#appBottomNav').waitFor();
 if(path==='/member/grub'){
  await p.locator('#grubRecommendation .grub-recipe').waitFor({timeout:45000});
  await p.locator('#grubRecommendation .app-screen-details').first().waitFor({state:'attached'});
  if(await p.locator('.app-refine-recipe:not([open])').count())await p.locator('.app-refine-recipe>summary').click();
  await p.locator('#grubRecommendation .app-screen-details summary').first().click();
  assert(await p.locator('.grub-pick-why').isVisible());
  if(await p.locator('.app-refine-recipe:not([open])').count())await p.locator('.app-refine-recipe>summary').click();
  await p.locator('#grubRecommendation .app-screen-details summary').first().click();
  await p.locator('#member-food-tab-saved').click();assert(await p.locator('#member-food-panel-saved').isVisible());assert(!(await p.locator('.grub-search').isVisible()),'Discover search is hidden on Saved');
  await p.locator('#member-food-tab-discover').click();row.checks.push('Grub data loaded; meal explanation expands; food tabs switch panels');
 }
 if(path==='/member/fit'){
  if(await p.locator('[data-app-fit-setup]:not([open])').count())await p.locator('[data-app-fit-setup]>summary').click();
  await p.locator('#fitGenerate:not([disabled])').waitFor({timeout:45000});
  await p.locator('#fitGenerate').click();await p.locator('.sf-session').first().waitFor({timeout:45000});
  await p.locator('.sf-exercise').first().waitFor();await p.locator('[data-sf-start]').first().click();assert(await p.locator('.sf-session.active').first().isVisible());row.checks.push('Fit generates a real fictional plan; prominent Start control opens its exercise session');
 }
 if(path==='/member/settings'){await p.locator('.app-account-details>summary').click();await p.locator('#memberDetailsForm').waitFor();assert(await p.locator('#memberDetailsTitle').isVisible());}
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal overflow '+path);
 if(path==='/member/life-back'){
 await p.locator('#journeyView:not([hidden])').waitFor({timeout:45000});
 assert.equal(await p.locator('main').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(5, 5, 5)','Life Back retains dark canvas for its light labels');
 const contrast=await p.locator('#scoreCaption').evaluate(el=>{const rgb=getComputedStyle(el).color.match(/[\d.]+/g).slice(0,3).map(Number);const lum=v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4};const l=.2126*lum(rgb[0])+.7152*lum(rgb[1])+.0722*lum(rgb[2]);return(l+.05)/(lum(5)+.05)});assert(contrast>=4.5,'Life Back caption contrast');
 await p.locator('.area-card').first().click();assert(await p.locator('dialog[open]').isVisible());await p.screenshot({path:dir+'/'+name+'-'+width+'-life-back-dialog.png',fullPage:true});await p.keyboard.press('Escape');
 assert(await p.locator('.timeline-card').evaluateAll(cards=>cards.every(c=>c.scrollWidth<=c.clientWidth+1)),'Timeline values fit inside each card');
 row.checks.push('Life Back dark canvas and caption contrast verified; progress card opens its dialog');
 }
 if(path==='/member/settings')await p.locator('.app-account-details>summary').click();
 await p.evaluate(async()=>{document.documentElement.style.scrollBehavior='auto';document.body.style.scrollBehavior='auto';document.activeElement?.blur();scrollTo({top:0,behavior:'instant'});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});
 await p.screenshot({path:dir+'/'+name+'-'+width+'-'+path.split('/').pop()+'.png',fullPage:true});
 await p.screenshot({path:dir+'/'+name+'-'+width+'-'+path.split('/').pop()+'-viewport.png'});}
 await p.goto(base+'/programme',{waitUntil:'domcontentloaded'});assert.equal(await p.locator('#appBottomNav').count(),0);assert.equal(await p.locator('[data-app-layout]').count(),0);row.checks.push('Layout persists across member routes; public Programme receives no app markup');
 assert.equal(await p.locator('#appPreviewBar').count(),0);
 await api(app,'/v1/auth/logout',{});await api(app,'/v1/auth/login',login);assert.deepEqual((await api(app,'/v1/life-back')).progress,changed);row.checks.push('Feedback adaptation visible in app; progress survives new session; health prototype never claims connection');
 }catch(error){row.error=error.message;await p.screenshot({path:dir+'/'+name+'-'+width+'-failure.png',fullPage:true}).catch(()=>{});await w.screenshot({path:dir+'/'+name+'-'+width+'-web-failure.png',fullPage:true}).catch(()=>{});throw error}finally{await browser.close()}
}}finally{fs.writeFileSync(dir+'/report.json',JSON.stringify(report,null,2))}})().catch(e=>{console.error(e);process.exitCode=1});
