import {chromium,webkit} from 'playwright';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const origin=process.env.PREVIEW_URL;
assert.equal(origin,'https://shift-stabilisation-preview.matobrien.workers.dev');
const fixture=JSON.parse(readFileSync('work/staging/generated/probe.json')),dir='work/staging/generated/review-evidence';mkdirSync(dir,{recursive:true});
const report={source:process.env.PREVIEW_SOURCE_SHA,previewOnly:true,checkedAt:new Date().toISOString(),cases:[],failures:[],gpProvider:null,physicalDeviceTested:false};
const output=()=>writeFileSync(dir+'/member-details-browser.json',JSON.stringify(report,null,2));
async function api(context,path,method='GET',body,status=200){const r=await context.request.fetch(origin+path,{method,headers:{Origin:origin},...(body?{data:body}:{})});assert.equal(r.status(),status,path+' status '+await r.text());return r.json().catch(()=>({}));}
async function open(page,path){await page.goto(origin+path,{waitUntil:'domcontentloaded',timeout:45000});}
async function login(page,id){await open(page,'/staging/sign-in');await page.fill('input[name="email"]','probe'+id+'@example.invalid');await page.fill('input[name="password"]',fixture.password);await page.locator('#stage-auth button[type="submit"]').click();await page.waitForURL(/\/member\/dashboard/,{timeout:45000});}
async function ready(page){await page.locator('#memberDetailsSave').waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('#memberDetailsFields').disabled,null,{timeout:30000});assert.match(await page.locator('#memberDetailsStatus').innerText(),/saved account details/);}
async function paint(page){
 const values=await page.evaluate(()=>{
  const rgb=s=>{const v=s.match(/[\d.]+/g)?.map(Number);return v&&v.length>=3?v:null;};
  const lum=c=>c.slice(0,3).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);
  return ['#memberDetailsTitle','.md-notice a','#memberEmailHelp a','#memberDetailsSave','#memberAddressHelp'].map(selector=>{
   const el=document.querySelector('#memberDetailsPanel '+selector),style=getComputedStyle(el),fg=rgb(style.webkitTextFillColor)||rgb(style.color);let parent=el,bg=null;
   while(parent){const c=rgb(getComputedStyle(parent).backgroundColor);if(c&&(c.length<4||c[3]===1)){bg=c;break;}parent=parent.parentElement;}
   const a=lum(fg),b=lum(bg||[231,227,218]);return {selector,foreground:fg,background:bg,contrast:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),opacity:Number(style.opacity),width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height};
  });
 });
 for(const v of values){assert(v.contrast>=4.5,'Unreadable account control '+JSON.stringify(v));assert.equal(v.opacity,1,'Unproved opacity '+v.selector);assert(v.width>0&&v.height>0,'Hidden control '+v.selector);}
 return values;
}
async function save(page){await page.locator('#memberDetailsSave').click();await page.getByText('Member details saved.',{exact:true}).waitFor({state:'visible',timeout:30000});}
async function geometry(page){const result=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,card:document.querySelector('#memberDetailsPanel')?.getBoundingClientRect().toJSON()}));assert(result.scroll<=result.width+1,'horizontal overflow '+JSON.stringify(result));if(result.card)assert(result.card.x>=0&&result.card.right<=result.width+1,'card bounds');}
const cases=[['chromium-desktop',chromium,{width:1440,height:1000}],['chromium-phone',chromium,{width:390,height:844}],['webkit-desktop',webkit,{width:1440,height:1000}],['webkit-phone',webkit,{width:390,height:844}]];
for(let i=0;i<cases.length;i++){
 const[name,engine,viewport]=cases[i],browser=await engine.launch({headless:true}),context=await browser.newContext({viewport}),page=await context.newPage(),row={name,checks:[],phase:'start',status:'running',browserErrors:[]};report.cases.push(row);output();
 page.on('pageerror',e=>row.browserErrors.push(e.message));
 let externalWrites=[];await context.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(u.origin!==origin&&['POST','PATCH','DELETE','PUT'].includes(r.method())){externalWrites.push(u.host+u.pathname);return route.abort();}return route.continue();});
 try{
  row.phase='ordinary-fictional-login';await login(page,fixture.browserIds[i]);
  row.phase='visible-member-navigation';await page.locator('.member-nav-more summary').click();const link=page.locator('.member-nav-more a').filter({hasText:'Member details'});assert.equal(await link.count(),1);await link.click();await ready(page);await geometry(page);row.paint=await paint(page);row.checks.push('Existing My Timber menu opens Member details inside Settings');row.checks.push('Actual painted support links, lookup/save buttons and headings exceed 4.5:1 contrast');
  const oldState=await api(context,'/v1/member-state'),oldConsents=await api(context,'/v1/consents');
  row.phase='edit-real-account-record';await page.fill('#memberLastName','Preview Reviewer');await page.fill('#memberPhone','07700 900123');await page.fill('#memberDob','1982-01-12');await page.fill('#memberPostcode','sk10 1aa');await page.fill('#memberAddress1','1 Fictional Close');await page.fill('#memberAddress2','Preview only');await page.fill('#memberTown','Macclesfield');await page.fill('#memberCounty','Cheshire');await page.fill('#memberGpPostcode','');
  // Save ordinary contact details through the actual candidate API and actual isolated D1.
  await save(page);let saved=await api(context,'/v1/member/details');assert.equal(saved.details.address1,'1 Fictional Close');assert.equal(saved.details.postcode,'SK10 1AA');assert.equal(saved.details.phone,'07700 900123');assert.equal(saved.details.email,'probe'+fixture.browserIds[i]+'@example.invalid');
  await page.reload({waitUntil:'domcontentloaded'});await ready(page);assert.equal(await page.inputValue('#memberAddress1'),'1 Fictional Close');assert.equal(await page.inputValue('#memberPhone'),'07700 900123');row.checks.push('Address, name, phone and DOB save to isolated D1 and survive reload');
  assert(await page.locator('#memberEmail').getAttribute('readonly')!==null);assert.equal(await page.locator('#memberFindAddress,#memberAddressSelect,#memberAddressQuery').count(),0);assert.match(await page.locator('#memberAddressHelp').innerText(),/Enter your full address/);row.checks.push('Email remains protected; manual address entry has no lookup controls');
  row.phase='failed-save-and-retry';const match=origin+'/v1/member/details';let rejected=false;await page.route(match,route=>{if(route.request().method()==='PATCH'&&!rejected){rejected=true;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'save_failed',message:'Your details were not saved. Please try again.'})});}return route.continue();});await page.fill('#memberAddress1','2 Fictional Lane');await page.locator('#memberDetailsSave').click();await page.getByText('Your details were not saved. Please try again.',{exact:true}).waitFor();assert.equal((await api(context,'/v1/member/details')).details.address1,'1 Fictional Close');assert.equal(await page.inputValue('#memberAddress1'),'2 Fictional Lane');await page.unroute(match);await save(page);row.checks.push('Failed save preserves typed edits and old database record; explicit retry succeeds');
  row.phase='lost-response-idempotent-retry';let lost=false;await page.route(match,async route=>{if(route.request().method()==='PATCH'&&!lost){lost=true;await route.fetch();return route.abort('failed');}return route.continue();});await page.fill('#memberAddress1','3 Fictional Way');await page.locator('#memberDetailsSave').click();await page.getByRole('button',{name:'Retry save',exact:true}).waitFor();const afterLost=await api(context,'/v1/member/details');assert.equal(afterLost.details.address1,'3 Fictional Way');await page.unroute(match);await page.getByRole('button',{name:'Retry save',exact:true}).click();await page.getByText('Member details saved.',{exact:true}).waitFor();const afterRetry=await api(context,'/v1/member/details');assert.equal(afterRetry.revision,afterLost.revision);row.checks.push('Response loss after real write retries the same operation without another revision');
  row.phase='stale-second-window';const base=await api(context,'/v1/member/details'),{email,...changed}=base.details;changed.phone='07700 900555';await api(context,'/v1/member/details','PATCH',{details:changed,revision:base.revision,operationId:randomUUID()});await page.fill('#memberAddress2','Unsaved stale edit');await page.locator('#memberDetailsSave').click();await page.waitForFunction(()=>document.querySelector('#memberDetailsStatus').textContent.includes('another window'));assert.equal((await api(context,'/v1/member/details')).details.address2,'Preview only');assert.equal(await page.inputValue('#memberAddress2'),'Unsaved stale edit');assert(await page.locator('#memberDetailsSave').isDisabled());page.once('dialog',dialog=>dialog.accept());await page.locator('#memberDetailsReload').click();await ready(page);assert.equal(await page.inputValue('#memberPhone'),'07700 900555');row.checks.push('Stale tab conflicts safely, preserves edits and requires explicit reload');
  row.phase='clear-optional-value';await page.fill('#memberAddress2','');await save(page);assert.equal((await api(context,'/v1/member/details')).details.address2,'');row.checks.push('Clearing an optional field really clears the saved value');
  row.phase='gp-directory';if(i===0){await page.fill('#memberGpPractice','Blackdown');await page.waitForTimeout(850);await page.waitForFunction(()=>{const s=document.querySelector('#memberGpHelp').textContent;return !s.includes('Searching')&&!s.startsWith('Type three');},null,{timeout:15000});const gpVisible=await page.locator('#memberGpLookup').isVisible();report.gpProvider={available:gpVisible,message:await page.locator('#memberGpHelp').innerText()};if(gpVisible){await page.selectOption('#memberGpSelect',{index:1});assert((await page.inputValue('#memberGpCode')).length>0);await save(page);const gpSaved=await api(context,'/v1/member/details');report.gpProvider.code=gpSaved.details.gpCode;report.gpProvider.name=gpSaved.details.gpPractice;await page.reload({waitUntil:'domcontentloaded'});await ready(page);assert.equal(await page.inputValue('#memberGpCode'),gpSaved.details.gpCode);row.checks.push('Actual NHS GP suggestion selected, saved and retained after refresh');}else{await page.fill('#memberGpPractice','Fictional Practice');await page.fill('#memberGpPostcode','SK10 1AA');await save(page);row.checks.push('NHS directory unavailable; manual GP save verified, no fabricated suggestions');}}
  row.phase='legacy-state-preservation';assert.deepEqual(await api(context,'/v1/member-state'),oldState);assert.deepEqual(await api(context,'/v1/consents'),oldConsents);row.checks.push('Existing member preferences, Grub/Fit/Journey state and consents remain exactly unchanged');
  row.phase='shared-journeys';for(const path of ['/member/dashboard#today','/member/grub','/member/fit']){await open(page,path);await page.locator('.sst-member-tabs').waitFor({state:'visible'});await geometry(page);}row.checks.push('Existing Today, Grub and Fit open with the shared menu and no horizontal overflow');
  row.phase='fresh-sign-in';await api(context,'/v1/auth/logout','POST',{});await api(context,'/v1/member/details','GET',undefined,401);await login(page,fixture.browserIds[i]);await open(page,'/member/settings#memberDetailsPanel');await ready(page);assert.equal(await page.inputValue('#memberAddress1'),'3 Fictional Way');assert.equal(await page.inputValue('#memberPhone'),'07700 900555');assert.equal(await page.inputValue('#memberAddress2'),'');row.checks.push('Logout denies private details; fresh actual sign-in restores the saved address and phone');
  row.phase='keyboard-and-screenshot';await page.locator('#memberFirstName').focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'memberLastName');await geometry(page);await paint(page);await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0)});await page.screenshot({path:dir+'/'+name+'-member-details.png',fullPage:true});assert.deepEqual(externalWrites,[]);assert.deepEqual(row.browserErrors,[]);row.checks.push('Keyboard focus order, phone/desktop geometry and zero browser errors checked');row.status='pass';row.phase='complete';
 }catch(e){row.status='fail';row.error=String(e.stack||e).replaceAll(fixture.password,'[REDACTED]');report.failures.push({name,phase:row.phase,error:row.error});await page.screenshot({path:dir+'/'+name+'-failure.png',fullPage:true}).catch(()=>{});}
 finally{await context.close();await browser.close();output();}
}
// Exercise the exact button Matt will use, not just the seeded test-account shortcut.
const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage();
try{await open(page,'/__review');await page.getByRole('button',{name:'Start a fictional member preview'}).click();await page.waitForURL('**/member/settings#memberDetailsPanel');await ready(page);const meta=await api(context,'/__preview/meta');assert.equal(meta.source,process.env.PREVIEW_SOURCE_SHA);assert.equal(meta.productionBindings,false);await page.fill('#memberLastName','Preview');await page.fill('#memberAddress1','4 Fictional Road');await page.fill('#memberTown','Macclesfield');await page.fill('#memberPostcode','SK10 1AA');await save(page);report.ownerEntry='pass';report.ownerPaint=await paint(page);await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0)});await page.screenshot({path:dir+'/owner-entry.png',fullPage:true});await api(context,'/v1/profile','PATCH',{firstName:'Fictional automated reviewer'});report.ownerSlotReleased=true;}
catch(e){report.ownerEntry='fail';report.failures.push({phase:'owner-entry',error:String(e.stack||e)});await page.screenshot({path:dir+'/owner-entry-failure.png',fullPage:true}).catch(()=>{});}finally{await context.close();await browser.close();output();}
console.log(JSON.stringify({cases:report.cases.map(({name,status,phase})=>({name,status,phase})),ownerEntry:report.ownerEntry,gpProvider:report.gpProvider,failures:report.failures},null,2));
if(report.failures.length)process.exitCode=1;
