import {treatmentRoutes} from '../../member-experience/treatment-routes.mjs';
import {treatmentHTML,treatmentStyles,treatmentRuntime} from '../../member-experience/treatment-page.mjs';
import {sessionRuntime} from '../../member-experience/session-state.mjs';
import {authenticateMember} from '../../member-state-fast-v1.js';
const headers={'Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"};
const page=html=>new Response(html,{headers:{...headers,'Content-Type':'text/html; charset=utf-8'}});
const intro=`<!doctype html><html lang="en-GB"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Treatment preview</title><style>body{max-width:650px;margin:40px auto;padding:24px;background:#e7e3da;color:#050505;font:17px/1.5 Arial}button{padding:14px 20px;background:#050505;color:#e7e3da;border:0;border-radius:10px;font:inherit}a{color:inherit}</style><h1>My Treatment · working preview</h1><p>Separate fictional accounts and database. Use made-up records only. This preview does not import live prescriptions or medical disclosures and does not send reminders.</p><form action="/__start" method="post"><button>Start a fictional account</button></form><p><a href="/member/treatment">Return to your preview records</a></p><form action="/__logout" method="post"><button>Sign out</button></form></html>`;
export default {async fetch(request,env){const u=new URL(request.url);if(env.SHIFT_ENVIRONMENT!=='treatment-preview-20261008'||!env.EXPIRES_AT||Date.now()>Date.parse(env.EXPIRES_AT))return new Response('Preview unavailable',{status:404,headers});
if(u.pathname==='/'||u.pathname==='/member-login'||u.pathname==='/member/dashboard')return page(intro);
if(u.pathname==='/__start'&&request.method==='POST'){if(request.headers.get('Origin')!==u.origin)return new Response('Use the preview button',{status:403});const count=await env.DB.prepare('SELECT COUNT(*) count FROM users').first();if(count.count>=100)return new Response('Preview account limit reached',{status:429});const token=crypto.randomUUID()+crypto.randomUUID(),hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))).toString('hex');const at=new Date().toISOString(),expiry=new Date(Date.now()+86400000).toISOString();const user=await env.DB.prepare('INSERT INTO users(email) VALUES(?) RETURNING id').bind('fictional-'+crypto.randomUUID()+'@example.invalid').first();await env.DB.batch([env.DB.prepare('INSERT INTO user_sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').bind(crypto.randomUUID(),user.id,hash,expiry),env.DB.prepare('INSERT INTO consents(user_id,consent_type,granted) VALUES(?,?,1)').bind(user.id,'my_shift_health_tracking')]);return new Response(null,{status:303,headers:{...headers,Location:'/member/treatment','Set-Cookie':'sst_session='+token+'; Secure; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400'}});}
if(u.pathname==='/__logout'&&request.method==='POST'){if(request.headers.get('Origin')!==u.origin)return new Response('Forbidden',{status:403});const auth=await authenticateMember(request,env);if(!auth.response)await env.DB.prepare('UPDATE user_sessions SET revoked_at=? WHERE id=?').bind(new Date().toISOString(),auth.user.session_id).run();return new Response(null,{status:303,headers:{...headers,Location:'/','Set-Cookie':'sst_session=; Secure; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'}});}
if(u.pathname==='/v1/me'){const auth=await authenticateMember(request,env);return auth.response||Response.json({user:{id:auth.userId}},{headers});}
const routes={'/member/treatment':[treatmentHTML(),'text/html'],'/assets/member-experience/treatment.mjs':[treatmentRuntime,'text/javascript'],'/assets/member-experience/treatment.css':[treatmentStyles,'text/css'],'/assets/member-experience/session.mjs':[sessionRuntime,'text/javascript']};if(routes[u.pathname])return new Response(routes[u.pathname][0],{headers:{...headers,'Content-Type':routes[u.pathname][1]}});
return await treatmentRoutes(request,env)||new Response('Not found',{status:404,headers});}};
