import test from 'node:test';import assert from 'node:assert/strict';import {fixture,ask,consent} from './helpers/ai-member-fixture.mjs';import {askTimberRoutes} from '../ask-timber-v1.js';import {fastPublicAnswer,savedFactKind} from '../member-experience/ai-fast-answers.mjs';import {inferenceText} from '../member-experience/ai-stream.mjs';
const encode=new TextEncoder();const chunk=text=>encode.encode('data: '+JSON.stringify({response:text})+'\n\n');
test('common checked question skips generation and DB reads but added constraints do not match',async()=>{const message='How can I make protein practical when appetite is low?';const r=await askTimberRoutes(new Request('https://api.shiftsometimber.co.uk/v1/ai/chat',{method:'POST',body:JSON.stringify({message,useJourney:false})}),{SHIFT_AI_PRACTICAL_CONTEXT:'true',DB:{prepare(){throw Error('must not read')}},AI:{run(){throw Error('must not generate')}}});const data=await r.json();assert.equal(data.delivery,'checked_answer');assert(data.answer.split(/\s+/).length>=70);assert.equal(data.sources.length,2);for(const q of ['How can I eat more protein with low appetite and kidney disease?','How can I make protein practical when appetite is low? I am allergic to eggs.'])assert.equal(fastPublicAnswer(q),null)});
test('exact member facts bypass model and remain scoped to signed-in consented member',async t=>{const{env}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';env.SHIFT_AI_CONVERSATION_MEMORY='true';env.AI.run=()=>{throw Error('must not generate')};let data=await(await ask(env,{message:'What is my personal goal?',useJourney:false})).json();assert.equal(data.delivery,'saved_fact');assert.match(data.answer,/Enjoying weekend walks/);assert.equal(savedFactKind('What is my personal goal and should I change dose?'),null);data=await(await ask(env,{message:'What is my personal goal?',useJourney:false},null)).json();assert.doesNotMatch(data.answer,/Enjoying weekend walks/)});
test('stream emits useful text before completion, then persists complete private reply',async t=>{const {env,DB}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';env.SHIFT_AI_CONVERSATION_MEMORY='true';let finish;env.AI.run=async()=>new ReadableStream({start(c){c.enqueue(chunk('First useful sentence. '));finish=()=>{c.enqueue(chunk('A complete answer.'));c.close()}}});const r=await ask(env,{message:'How can I fit a walk around work?',useJourney:false,stream:true});assert.match(r.headers.get('Content-Type'),/event-stream/);const reader=r.body.getReader();let s='';while(!s.includes('First useful sentence'))s+=new TextDecoder().decode((await reader.read()).value);assert(!s.includes('event: done'));finish();while(true){const p=await reader.read();if(p.done)break;s+=new TextDecoder().decode(p.value)}assert(s.includes('event: done'));assert(DB.sqlite.prepare("SELECT body FROM shift_ai_conversations WHERE direction='assistant'").get().body.includes('A complete answer'))});
test('withdrawal during stream stops further private text and never saves a completed reply',async t=>{const{env,DB}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';env.SHIFT_AI_CONVERSATION_MEMORY='true';let finish;env.AI.run=async()=>new ReadableStream({start(c){finish=()=>{consent(DB,1,false);c.enqueue(chunk('PRIVATE_AFTER_WITHDRAWAL'));c.close()}}});const r=await ask(env,{message:'Help me plan my evening with my saved context',useJourney:false,stream:true});finish();const s=await r.text();assert.match(s,/privacy_changed/);assert.doesNotMatch(s,/PRIVATE_AFTER_WITHDRAWAL|event: done/);assert.equal(DB.sqlite.prepare("SELECT COUNT(*) n FROM shift_ai_conversations WHERE direction='assistant'").get().n,0)});
test('provider stream decoder handles boundaries and rejects malformed events',async()=>{const text='data: {"response":"Hello"}\n\ndata: [DONE]\n\n';const stream=new ReadableStream({start(c){for(const char of text)c.enqueue(encode.encode(char));c.close()}});let answer='';for await(const token of inferenceText(stream))answer+=token;assert.equal(answer,'Hello')});

import {publicAnswerCache} from '../member-experience/ai-public-answer-cache.mjs';
import {storePublicPage} from '../member-experience/ai-site-knowledge.mjs';
const cacheFixture=()=>{const data=new Map();return{match:async key=>data.get(key.url)?.clone(),put:async(key,value)=>data.set(key.url,value.clone())}};
test('unchanged public recrawls reuse answers after five minutes, but changed evidence and expiry invalidate them',async()=>{
 let now=0;const entries=new Map(),cache={async match(k){const e=entries.get(k.url);return e&&e.until>now?e.value.clone():undefined},async put(k,v){const ttl=Number(v.headers.get('Cache-Control').match(/max-age=(\d+)/)[1]);entries.set(k.url,{until:now+ttl*1000,value:v.clone()})}};
 const source={title:'Life Back',content:'Choose a personal goal.',citation:'https://shiftsometimber.co.uk/life-back',reviewState:'published_site',authority:75,limitations:'Public information',provenance:[{type:'shift_website',ref:'https://shiftsometimber.co.uk/life-back',checkedAt:'2026-09-27 10:00:00'}]};
 const args={request:new Request('https://example.test'),body:{},message:'What is Life Back?',evidence:[source],model:'current',cache};
 await(await publicAnswerCache(args)).write({ok:true,journeyUsed:false,answer:'Choose a personal goal. [1]'});
 now=6*60*1000;const refreshed={...source,provenance:[{...source.provenance[0],checkedAt:'2026-09-27 10:06:00'}]};
 assert.equal((await(await publicAnswerCache({...args,message:'WHAT  IS LIFE BACK',evidence:[refreshed]})).read()).answer,'Choose a personal goal. [1]');
 for(const change of [{content:'Changed information.'},{title:'Changed title'},{authority:50},{limitations:'New limitation'},{citation:'https://shiftsometimber.co.uk/programme'},{provenance:[{...source.provenance[0],ref:'https://shiftsometimber.co.uk/programme'}]}])assert.equal((await(await publicAnswerCache({...args,evidence:[{...refreshed,...change}]}))?.read())??null,null);
 assert.equal(await(await publicAnswerCache({...args,model:'changed-model'})).read(),null);
 assert.equal(await(await publicAnswerCache({...args,request:new Request('https://example.test',{headers:{'Cache-Control':'no-cache'}})})).read(),null);
 now=24*60*60*1000;assert.equal(await(await publicAnswerCache(args)).read(),null);
});
test('recrawled public answers expose current source receipts and stale evidence cannot use the cache',async t=>{
 const{env,DB,calls}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';env.SHIFT_AI_PUBLIC_CACHE=cacheFixture();
 DB.sqlite.exec("CREATE TABLE ai_knowledge_documents(id INTEGER PRIMARY KEY,title,source_uri,category,trust_tier,status,checksum UNIQUE,updated_at);CREATE TABLE ai_knowledge_chunks(id INTEGER PRIMARY KEY,document_id,chunk_index,content,search_text);");
 const page={url:'https://shiftsometimber.co.uk/life-back',title:'Life Back | Progress Beyond Weight',chunks:['Life Back helps you choose a personal goal and record small wins.']};await storePublicPage(DB,page);
 DB.sqlite.exec("UPDATE ai_knowledge_documents SET updated_at=datetime('now','-1 hour')");
 const payload={message:'What is Life Back?',useJourney:false};const first=await(await ask(env,payload,null)).json();
 await storePublicPage(DB,page);const refreshed=await(await ask(env,{...payload,message:'What is Life Back',stream:true},null)).json();
 assert.equal(refreshed.delivery,'cached_public');assert.equal(calls.length,1);assert.equal(refreshed.answer,first.answer);assert.notEqual(refreshed.sources[0].provenance[0].checkedAt,first.sources[0].provenance[0].checkedAt);
 await storePublicPage(DB,{...page,chunks:['Life Back now describes a different published goal feature.']});const changed=await(await ask(env,payload,null)).json();assert.notEqual(changed.delivery,'cached_public');assert.equal(calls.length,2);
 DB.sqlite.exec("UPDATE ai_knowledge_documents SET updated_at=datetime('now','-3 days')");const stale=await(await ask(env,payload,null)).json();assert.notEqual(stale.delivery,'cached_public');assert(!stale.sources.some(s=>s.url===page.url));
});
test('public answer reuse excludes private inputs and invalidates changed source content',async()=>{const cache=cacheFixture(),evidence=[{title:'Life Back',content:'Choose a personal goal.',citation:'https://shiftsometimber.co.uk/life-back',reviewState:'published_site'}],args={request:new Request('https://example.test'),body:{},message:'What is Life Back?',evidence,model:'test',cache};assert(await publicAnswerCache({...args,request:new Request('https://example.test',{headers:{Cookie:'cookie_consent=necessary'}})}));const first=await publicAnswerCache(args);await first.write({ok:true,journeyUsed:false,answer:'A public answer'});assert.equal((await first.read()).answer,'A public answer');assert.equal(await(await publicAnswerCache({...args,evidence:[{...evidence[0],content:'Changed content'}]})).read(),null);for(const change of [{request:new Request('https://example.test',{headers:{Cookie:'sst_session=private'}})},{body:{history:[{role:'user',content:'private'}]}},{body:{useJourney:true}},{message:'What is my Life Back goal?'},{message:'What is Life Back for John Smith?'},{evidence:[{...evidence[0],reviewState:'withdrawn'}]}])assert.equal(await publicAnswerCache({...args,...change}),null);});
test('dedicated site evidence avoids graph scans; repeated public answer skips generation; withdrawal cannot serve cached answer',async t=>{const{env,DB,calls}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';env.SHIFT_AI_PUBLIC_CACHE=cacheFixture();DB.sqlite.exec("CREATE TABLE ai_knowledge_documents(id INTEGER PRIMARY KEY,title,source_uri,category,trust_tier,status,checksum UNIQUE,updated_at);CREATE TABLE ai_knowledge_chunks(id INTEGER PRIMARY KEY,document_id,chunk_index,content,search_text);");await storePublicPage(DB,{url:'https://shiftsometimber.co.uk/life-back',title:'Life Back | Progress Beyond Weight',chunks:['Life Back helps you choose a personal goal and record small wins.']});const payload={message:'What is Life Back?',useJourney:false};const first=await(await ask(env,payload,null)).json();assert.equal(first.sources.length,1);assert.equal(calls.length,1);assert(!DB.reads.some(sql=>sql.includes('shift_knowledge_nodes')));const second=await(await ask(env,{...payload,stream:true},null)).json();assert.equal(second.delivery,'cached_public');assert.equal(calls.length,1);assert.notEqual(first.requestId,second.requestId);DB.sqlite.exec("UPDATE ai_knowledge_documents SET status='withdrawn'");const after=await(await ask(env,payload,null)).json();assert.notEqual(after.delivery,'cached_public');assert(!after.sources.some(s=>s.url?.endsWith('/life-back')));});

test('streaming and JSON retain the proven model and respect explicit overrides',async t=>{
 const {env}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';const models=[];
 env.AI.run=async(model,input)=>{models.push(model);return input.stream?new ReadableStream({start(c){c.enqueue(chunk('Choose one manageable step that fits your day.'));c.close()}}):{response:{answer:'Choose one manageable step that fits your day.',confidence:'low',keyPoints:[],nextSteps:[],followUps:[],limitations:'General information'}}};
 const payload={message:'How can I fit a walk around work?',useJourney:false};
 for(const [stream,flag,override,expected] of [[true,'true',undefined,'@cf/meta/llama-3.3-70b-instruct-fp8-fast'],[false,'true',undefined,'@cf/meta/llama-3.3-70b-instruct-fp8-fast'],[true,'false',undefined,'@cf/meta/llama-3.3-70b-instruct-fp8-fast'],[true,'true','synthetic-approved-override','synthetic-approved-override']]){env.SHIFT_AI_PRACTICAL_CONTEXT=flag;env.SHIFT_AI_MODEL=override;const r=await ask(env,{...payload,stream});await r.text();assert.equal(models.at(-1),expected)}
});

test('stream format instruction names real evidence markers without manufacturing private citations',async t=>{
 const {env}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';const inputs=[];env.AI.run=async(_,input)=>{inputs.push(input);return new ReadableStream({start(c){c.enqueue(chunk('A focused answer.'));c.close()}})};
 await(await ask(env,{message:'Can I eat chocolate while taking Mounjaro?',useJourney:false,stream:true})).text();assert.match(inputs.at(-1).messages.at(-1).content,/literal numbered markers: \[1\]/);
 await(await ask(env,{message:'Remember that I cannot cook after midnight. Have you saved that for next week?',useJourney:false,stream:true})).text();assert.match(inputs.at(-1).messages.at(-1).content,/No general evidence sources were supplied/);assert.doesNotMatch(inputs.at(-1).messages.at(-1).content,/\[1\]/);
});
