import test from 'node:test';import assert from 'node:assert/strict';import {fixture,ask,consent} from './helpers/ai-member-fixture.mjs';import {askTimberRoutes} from '../ask-timber-v1.js';import {fastPublicAnswer,savedFactKind} from '../member-experience/ai-fast-answers.mjs';import {inferenceText} from '../member-experience/ai-stream.mjs';
const encode=new TextEncoder();const chunk=text=>encode.encode('data: '+JSON.stringify({response:text})+'\n\n');
test('common checked question skips generation and DB reads but added constraints do not match',async()=>{const message='How can I make protein practical when appetite is low?';const r=await askTimberRoutes(new Request('https://api.shiftsometimber.co.uk/v1/ai/chat',{method:'POST',body:JSON.stringify({message,useJourney:false})}),{SHIFT_AI_PRACTICAL_CONTEXT:'true',DB:{prepare(){throw Error('must not read')}},AI:{run(){throw Error('must not generate')}}});const data=await r.json();assert.equal(data.delivery,'checked_answer');assert(data.answer.split(/\s+/).length>=70);assert.equal(data.sources.length,2);for(const q of ['How can I eat more protein with low appetite and kidney disease?','How can I make protein practical when appetite is low? I am allergic to eggs.'])assert.equal(fastPublicAnswer(q),null)});
test('exact member facts bypass model and remain scoped to signed-in consented member',async t=>{const{env}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';env.SHIFT_AI_CONVERSATION_MEMORY='true';env.AI.run=()=>{throw Error('must not generate')};let data=await(await ask(env,{message:'What is my personal goal?',useJourney:false})).json();assert.equal(data.delivery,'saved_fact');assert.match(data.answer,/Enjoying weekend walks/);assert.equal(savedFactKind('What is my personal goal and should I change dose?'),null);data=await(await ask(env,{message:'What is my personal goal?',useJourney:false},null)).json();assert.doesNotMatch(data.answer,/Enjoying weekend walks/)});
test('stream emits useful text before completion, then persists complete private reply',async t=>{const {env,DB}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';env.SHIFT_AI_CONVERSATION_MEMORY='true';let finish;env.AI.run=async()=>new ReadableStream({start(c){c.enqueue(chunk('First useful sentence. '));finish=()=>{c.enqueue(chunk('A complete answer.'));c.close()}}});const r=await ask(env,{message:'How can I fit a walk around work?',useJourney:false,stream:true});assert.match(r.headers.get('Content-Type'),/event-stream/);const reader=r.body.getReader();let s='';while(!s.includes('First useful sentence'))s+=new TextDecoder().decode((await reader.read()).value);assert(!s.includes('event: done'));finish();while(true){const p=await reader.read();if(p.done)break;s+=new TextDecoder().decode(p.value)}assert(s.includes('event: done'));assert(DB.sqlite.prepare("SELECT body FROM shift_ai_conversations WHERE direction='assistant'").get().body.includes('A complete answer'))});
test('withdrawal during stream stops further private text and never saves a completed reply',async t=>{const{env,DB}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';env.SHIFT_AI_CONVERSATION_MEMORY='true';let finish;env.AI.run=async()=>new ReadableStream({start(c){finish=()=>{consent(DB,1,false);c.enqueue(chunk('PRIVATE_AFTER_WITHDRAWAL'));c.close()}}});const r=await ask(env,{message:'Help me plan my evening with my saved context',useJourney:false,stream:true});finish();const s=await r.text();assert.match(s,/privacy_changed/);assert.doesNotMatch(s,/PRIVATE_AFTER_WITHDRAWAL|event: done/);assert.equal(DB.sqlite.prepare("SELECT COUNT(*) n FROM shift_ai_conversations WHERE direction='assistant'").get().n,0)});
test('provider stream decoder handles boundaries and rejects malformed events',async()=>{const text='data: {"response":"Hello"}\n\ndata: [DONE]\n\n';const stream=new ReadableStream({start(c){for(const char of text)c.enqueue(encode.encode(char));c.close()}});let answer='';for await(const token of inferenceText(stream))answer+=token;assert.equal(answer,'Hello')});

import {publicAnswerCache} from '../member-experience/ai-public-answer-cache.mjs';
import {storePublicPage} from '../member-experience/ai-site-knowledge.mjs';
const cacheFixture=()=>{const data=new Map();return{match:async key=>data.get(key.url)?.clone(),put:async(key,value)=>data.set(key.url,value.clone())}};
test('public answer reuse excludes private inputs and invalidates changed source content',async()=>{const cache=cacheFixture(),evidence=[{title:'Life Back',content:'Choose a personal goal.',citation:'https://shiftsometimber.co.uk/life-back',reviewState:'published_site'}],args={request:new Request('https://example.test'),body:{},message:'What is Life Back?',evidence,model:'test',cache};const first=await publicAnswerCache(args);await first.write({ok:true,journeyUsed:false,answer:'A public answer'});assert.equal((await first.read()).answer,'A public answer');assert.equal(await(await publicAnswerCache({...args,evidence:[{...evidence[0],content:'Changed content'}]})).read(),null);for(const change of [{request:new Request('https://example.test',{headers:{Cookie:'sst_session=private'}})},{body:{history:[{role:'user',content:'private'}]}},{body:{useJourney:true}},{message:'What is my Life Back goal?'},{message:'What is Life Back for John Smith?'},{evidence:[{...evidence[0],reviewState:'withdrawn'}]}])assert.equal(await publicAnswerCache({...args,...change}),null);});
test('dedicated site evidence avoids graph scans; repeated public answer skips generation; withdrawal cannot serve cached answer',async t=>{const{env,DB,calls}=fixture(t);env.SHIFT_AI_PRACTICAL_CONTEXT='true';env.SHIFT_AI_PUBLIC_CACHE=cacheFixture();DB.sqlite.exec("CREATE TABLE ai_knowledge_documents(id INTEGER PRIMARY KEY,title,source_uri,category,trust_tier,status,checksum UNIQUE,updated_at);CREATE TABLE ai_knowledge_chunks(id INTEGER PRIMARY KEY,document_id,chunk_index,content,search_text);");await storePublicPage(DB,{url:'https://shiftsometimber.co.uk/life-back',title:'Life Back | Progress Beyond Weight',chunks:['Life Back helps you choose a personal goal and record small wins.']});const payload={message:'What is Life Back?',useJourney:false};const first=await(await ask(env,payload,null)).json();assert.equal(first.sources.length,1);assert.equal(calls.length,1);assert(!DB.reads.some(sql=>sql.includes('shift_knowledge_nodes')));const second=await(await ask(env,{...payload,stream:true},null)).json();assert.equal(second.delivery,'cached_public');assert.equal(calls.length,1);assert.notEqual(first.requestId,second.requestId);DB.sqlite.exec("UPDATE ai_knowledge_documents SET status='withdrawn'");const after=await(await ask(env,payload,null)).json();assert.notEqual(after.delivery,'cached_public');assert(!after.sources.some(s=>s.url?.endsWith('/life-back')));});
