import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {publicKnowledgeUrl,extractPublicPage,storePublicPage,retrievePublishedSite,refreshPublicKnowledge} from '../member-experience/ai-site-knowledge.mjs';
function db(t){const sqlite=new DatabaseSync(':memory:');t.after(()=>sqlite.close());sqlite.exec("CREATE TABLE ai_knowledge_documents(id INTEGER PRIMARY KEY,title,source_uri,category,trust_tier,status,checksum UNIQUE,updated_at);CREATE TABLE ai_knowledge_chunks(id INTEGER PRIMARY KEY,document_id,chunk_index,content,search_text);");const DB={prepare(sql){let args=[];const st={bind(...a){args=a;return st},async all(){return{results:sqlite.prepare(sql).all(...args)}},async run(){return sqlite.prepare(sql).run(...args)}};return st},async batch(ss){sqlite.exec('BEGIN');try{for(const s of ss)await s.run();sqlite.exec('COMMIT')}catch(e){sqlite.exec('ROLLBACK');throw e}}};return{DB,sqlite}}
const url='https://shiftsometimber.co.uk/articles/everyday-protein';
test('only canonical public information URLs are eligible; private and foreign URLs are excluded',()=>{for(const u of ['https://evil.test/articles/x','https://shiftsometimber.co.uk/member/dashboard','https://shiftsometimber.co.uk/articles/x?account=1','http://shiftsometimber.co.uk/articles/x'])assert.equal(publicKnowledgeUrl(u),null);assert.equal(publicKnowledgeUrl(url),url)});
test('extracts main content without scripts, navigation, forms or false clinical approval',()=>{const p=extractPublicPage('<h1>Protein</h1><main><nav>UNWANTED</nav><script>SECRET</script><p>'+('Protein choices for meals. '.repeat(15))+'</p><form>PRIVATE</form></main>',url);assert(p.chunks.length);assert.doesNotMatch(p.chunks.join(''),/UNWANTED|SECRET|PRIVATE/);assert.equal(extractPublicPage('<meta name="robots" content="noindex"><h1>x</h1><main>'+('text '.repeat(50))+'</main>',url),null)});
test('atomic refresh is idempotent; retrieval excludes withdrawn and stale copies',async t=>{const {DB,sqlite}=db(t);const p={url,title:'Practical protein meals',chunks:['Choose protein foods for small meals. Include foods you tolerate.']};await storePublicPage(DB,p);await storePublicPage(DB,p);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM ai_knowledge_documents').get().n,1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM ai_knowledge_chunks').get().n,1);let rows=await retrievePublishedSite(DB,'How can I make protein practical in meals?');assert.equal(rows.length,1);assert.equal(rows[0].reviewState,'published_site');sqlite.exec("UPDATE ai_knowledge_documents SET updated_at='2000-01-01'");assert.deepEqual(await retrievePublishedSite(DB,'protein meals'),[]);await storePublicPage(DB,p);sqlite.exec("UPDATE ai_knowledge_documents SET status='withdrawn'");assert.deepEqual(await retrievePublishedSite(DB,'protein meals'),[])});
test('removed sitemap pages are withdrawn without reading member data',async t=>{const{DB,sqlite}=db(t);await storePublicPage(DB,{url,title:'Protein meals',chunks:['Protein meals.']});const out=await refreshPublicKnowledge({DB},{fetcher:async u=>u.endsWith('sitemap.xml')?new Response('<urlset><loc>https://shiftsometimber.co.uk/articles/another-page</loc></urlset>'):new Response('',{status:404})});assert.equal(out.withdrawn,1);assert.equal(sqlite.prepare('SELECT status FROM ai_knowledge_documents').get().status,'withdrawn')});

test('dedicated page ranks before a hundred broad body matches',async t=>{const{DB}=db(t);for(let i=0;i<110;i++)await storePublicPage(DB,{url:'https://shiftsometimber.co.uk/articles/page-'+i,title:'General wellbeing',chunks:['Getting life back is a common aim.']});await storePublicPage(DB,{url:'https://shiftsometimber.co.uk/life-back',title:'Life Back | Progress Beyond Weight | SHIFT',chunks:['Life Back records the activities you want to return to.']});const rows=await retrievePublishedSite(DB,'What is Life Back?');assert.equal(rows[0].citation,'https://shiftsometimber.co.uk/life-back');});
