import test from 'node:test';import assert from 'node:assert/strict';
import {withAppLayout,livePresentation,appAsset,launchAsset} from '../app-layout-live.mjs';
import {webToolsPresentation} from '../member-inline-tools.mjs';
import {appPresentation,appClient} from '../preview/app-layout/presentation.mjs';
const html='<html><head></head><body data-member-chrome="v1"><main><form id="real"><input name="note"></form></main><script src="/original.js"></script></body></html>';
const source=()=>new Response(html,{headers:{'Content-Type':'text/html','ETag':'original','Vary':'Accept-Encoding','Content-Security-Policy':"default-src 'self'; frame-ancestors 'self'"}});
test('every public/API/error/unsupported response is the original object, even with app cookie',async()=>{for(const path of ['/','/programme','/shop','/member-login','/v1/life-back','/member/unknown']){const r=source();assert.equal(await withAppLayout(new Request('https://shiftsometimber.co.uk'+path+'?view=app',{headers:{Cookie:'shift_app_view=1'}}),r),r)}const r=new Response('no',{status:401});assert.equal(await withAppLayout(new Request('https://shiftsometimber.co.uk/member/dashboard?view=app'),r),r)});
test('app output is exact approved presentation except review toolbar and asset path; original data forms preserved',async()=>{const r=await withAppLayout(new Request('https://shiftsometimber.co.uk/member/dashboard?view=app'),source());const body=await r.text();assert.equal(body,appPresentation(html,'/member/dashboard').replace(/<aside id="appPreviewBar">[\s\S]*?<\/aside>/,'').replace('src="/__app-layout.mjs"','src="'+appAsset+'"'));assert(body.includes('<form id="real">'));assert(!body.includes('fictional accounts only'));assert.equal(r.headers.get('ETag'),null);assert.match(r.headers.get('Set-Cookie'),/Path=\/member; Secure; HttpOnly/);assert.match(r.headers.get('Vary'),/Accept-Encoding, Cookie/);assert.equal(r.headers.get('Content-Security-Policy'),source().headers.get('Content-Security-Policy'))});
test('web view explicitly clears app preference and preserves exact document',async()=>{const r=await withAppLayout(new Request('https://shiftsometimber.co.uk/member/dashboard?view=web',{headers:{Cookie:'shift_app_view=1'}}),source());assert.equal(await r.text(),webToolsPresentation(html,'/member/dashboard'));assert.match(r.headers.get('Set-Cookie'),/Max-Age=0/);assert.equal(r.headers.get('ETag'),null)});
test('normal browser member view only gets standalone launcher; no app styling',async()=>{const r=await withAppLayout(new Request('https://shiftsometimber.co.uk/member/dashboard'),source());assert.equal(await r.text(),webToolsPresentation(html,'/member/dashboard').replace('</body>','<script defer src="'+launchAsset+'"></script></body>'))});
test('asset and cookie route work; embedded styling confined to tool routes',async()=>{let r=await withAppLayout(new Request('https://shiftsometimber.co.uk'+appAsset),new Response('404',{status:404}));assert.equal(await r.text(),appClient);for(const path of ['grub','dashboard']){r=await withAppLayout(new Request('https://shiftsometimber.co.uk/member/'+path+'?app_panel=1',{headers:{Cookie:'shift_app_view=1'}}),source());assert.equal(/<body[^>]*data-app-panel="1"/.test(await r.text()),path==='grub')}});

test('standalone auto-launch is confined to Today; ordinary tool pages retain exact original HTML',async()=>{for(const name of ['life-back','grub','fit','settings']){const r=await withAppLayout(new Request('https://shiftsometimber.co.uk/member/'+name),source());assert.equal(await r.text(),html);assert.equal(r.headers.get('ETag'),'original')}});
