import test from 'node:test';
import assert from 'node:assert/strict';
import {selectDecisionOutcome,validateDecisionContent,resolveGovernedDecisionOutcome} from '../decision-content-v1.js';

const NOW='2026-08-23T12:00:00.000Z';
const DIGEST='a'.repeat(64),REF=`nice-ta-1@1:${DIGEST}`;
const base=()=>({id:7,decision_key:'weight-route',version:2,title:'Find the useful next step',channel:'treatment_pathway',destination:'/treatments/results',status:'approved',effective_at:'2026-08-01T00:00:00.000Z',review_due_at:'2026-10-01T00:00:00.000Z',content:{questions:[{key:'preference',prompt:'Which routine suits you?'}],outcomes:[{key:'tablet',title:'A daily routine may suit',summary:'Read the governed comparison.',when:[{field:'preference',operator:'equals',value:'daily'}],claim_keys:['tablet-routine'],next_action:{type:'education',href:'/treatments/tablets'}},{key:'compare',title:'Compare the routes',summary:'See both governed routes.',default:true,claim_keys:[],next_action:{type:'route_finder',href:'/treatments'}}]},evidence:[{evidence_id:'nice-ta-1',version:1,state:'verified',digest:DIGEST,source:'NICE:TA-1',verified_at:'2026-08-20T00:00:00.000Z',expires_at:'2026-11-20T00:00:00.000Z',owner:'clinical-content'}],review:{status:'approved',content_version:2,evidence_refs:[REF],reviewed_by:'clinical-reviewer',reviewed_at:'2026-08-20T00:00:00.000Z'},provenance:{schema_version:1,source_system:'shift-hq',authored_by:'content-editor',change_reason:'Initial governed route'}});

test('approved, current, evidenced content is publishable',()=>assert.deepEqual(validateDecisionContent(base(),{at:NOW}).errors,[]));
test('stale review fails closed',()=>{const x=base();x.review_due_at='2026-08-22T00:00:00.000Z';assert.equal(validateDecisionContent(x,{at:NOW}).ok,false)});
test('unapproved and evidence-free content fails closed',()=>{const x=base();x.status='draft';x.evidence=[];assert.deepEqual(validateDecisionContent(x,{at:NOW}).errors.sort(),['approval_required','review_evidence_mismatch','verified_evidence_required'])});
test('commercial outcome actions are forbidden',()=>{const x=base();x.content.outcomes[0].next_action={type:'purchase',href:'/checkout'};assert.equal(validateDecisionContent(x,{at:NOW}).errors.includes('safe_next_action_required'),true)});
test('review approval is bound to the exact content and evidence versions',()=>{const x=base();x.review.content_version=1;x.review.evidence_refs=['nice-ta-1@2:'+DIGEST];assert.deepEqual(validateDecisionContent(x,{at:NOW}).errors.filter(x=>x.includes('mismatch')).sort(),['review_evidence_mismatch','review_version_mismatch'])});
test('provenance and immutable evidence identity are mandatory',()=>{const x=base();delete x.provenance;x.evidence[0].digest='not-a-digest';assert.equal(validateDecisionContent(x,{at:NOW}).errors.includes('provenance_required'),true);assert.equal(validateDecisionContent(x,{at:NOW}).errors.includes('verified_evidence_required'),true)});
test('evidence must be explicitly verified, current and not future-dated',()=>{for(const change of [{state:'in_review'},{expires_at:'2026-08-22T00:00:00.000Z'},{verified_at:'2026-08-24T00:00:00.000Z'}]){const x=base();Object.assign(x.evidence[0],change);assert.equal(validateDecisionContent(x,{at:NOW}).errors.includes('verified_evidence_required'),true)}});
test('content author cannot independently approve their own decision',()=>{const x=base();x.review.reviewed_by='content-editor';assert.equal(validateDecisionContent(x,{at:NOW}).errors.includes('independent_review_required'),true)});
test('external and protocol-relative outcome destinations fail closed',()=>{const x=base();x.content.outcomes[0].next_action.href='https://example.com/checkout';assert.equal(validateDecisionContent(x,{at:NOW}).errors.includes('safe_destination_required'),true)});
test('outcome selection uses conditions then safe default',()=>{const x=base();assert.equal(selectDecisionOutcome(x.content,{preference:'daily'}).key,'tablet');assert.equal(selectDecisionOutcome(x.content,{preference:'weekly'}).key,'compare')});

function envFor(rows){const audit=[];return{audit,DB:{batch:async statements=>{for(const statement of statements)if(typeof statement.run==='function')await statement.run()},prepare(sql){return{bind(...args){return{all:async()=>({results:rows}),run:async()=>{audit.push({sql,args});return{success:true}}}},all:async()=>({results:rows})}}}}}
test('resolver emits governed outcome with lineage proof only when every claim resolves',async()=>{const env=envFor([base()]);const result=await resolveGovernedDecisionOutcome(env,{decisionKey:'weight-route',channel:'treatment_pathway',destination:'/treatments/results',answers:{preference:'daily'},correlationId:'corr-1',at:NOW,claimResolver:async()=>({key:'tablet-routine',version:3,wording:'A governed claim.'})});assert.equal(result.outcome.key,'tablet');assert.equal(result.outcome.claims.length,1);assert.equal(env.audit.length,2);assert.match(env.audit[1].sql,/decision_outcome_proof/);assert.deepEqual(JSON.parse(env.audit[1].args[5]),[{key:'tablet-routine',version:3}]);assert.equal(result.governance.evidenceFingerprint,REF)});
test('missing governed claim fails closed without outcome audit',async()=>{const env=envFor([base()]);const result=await resolveGovernedDecisionOutcome(env,{decisionKey:'weight-route',channel:'treatment_pathway',destination:'/treatments/results',answers:{preference:'daily'},correlationId:'corr-2',at:NOW,claimResolver:async()=>null});assert.equal(result,null);assert.equal(env.audit.length,0)});
test('claim lineage mismatch fails closed without outcome audit',async()=>{const env=envFor([base()]);const result=await resolveGovernedDecisionOutcome(env,{decisionKey:'weight-route',channel:'treatment_pathway',destination:'/treatments/results',answers:{preference:'daily'},correlationId:'corr-3',at:NOW,claimResolver:async()=>({key:'different-claim',version:1})});assert.equal(result,null);assert.equal(env.audit.length,0)});
test('invalid newest approved version fails closed instead of silently falling back',async()=>{const newest=base();newest.version=3;newest.review.content_version=3;newest.review_due_at='2026-08-22T00:00:00.000Z';const env=envFor([newest,base()]);const result=await resolveGovernedDecisionOutcome(env,{decisionKey:'weight-route',channel:'treatment_pathway',destination:'/treatments/results',answers:{preference:'daily'},correlationId:'corr-4',at:NOW,claimResolver:async()=>({key:'tablet-routine',version:3})});assert.equal(result,null);assert.equal(env.audit.length,0)});
