import test from 'node:test';
import assert from 'node:assert/strict';
import {ARTICLES,PATHS,UPDATED,STATS,VERSION,rewriteArticle,articleMain,updateArticleSitemap} from '../editorial/five-articles/render.mjs';
import {withEditorialResources} from '../editorial-resources-v1.js';
import {CSV,CHART,DATA} from '../editorial/statistics/assets.js';
import {setSitemapDate} from '../radar-editorial-trust-v1.js';
const origin='https://shiftsometimber.co.uk';
const shell=()=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Old</title><meta content="old" name="description"><meta name='DESCRIPTION' content='duplicate'><meta content="wrong" property="og:title"><link href="/old" rel="canonical"><LINK REL=canonical HREF='/also-old'><script data-old type="application/ld+json">{"@type":"Article","datePublished":"2026-08-03","headline":"Wrong generic headline"}</script><script type='application/ld+json'>{"@type":"FAQPage"}</script><script src="/retained-site-script.js"></script></head><body><header>Retained header</header><main id="main-content"><h1>Old body</h1></main><footer>Retained footer</footer></body></html>`;
const count=(s,re)=>[...s.matchAll(re)].length;
test('only the five owner-approved routes are in scope',()=>{assert.ok(Object.isFrozen(PATHS));assert.deepEqual([...PATHS].sort(),['/comparisons/medications/mounjaro-vs-orlistat','/comparisons/medications/mounjaro-vs-saxenda','/guides/nhs-weight-loss-medication-pathways','/mental-health/mental-health-and-weight',STATS].sort())});
for(const path of PATHS){
 test(path+' one truthful main, H1, canonical, description and article schema',()=>{
  const html=rewriteArticle(shell(),path);assert.equal(count(html,/<main\b/g),1);assert.equal(count(html,/<h1\b/g),1);assert.equal(count(html,/<link rel="canonical"/g),1);assert.ok(html.includes('href="'+origin+path+'"'));assert.equal(count(html,/<meta name="description"/g),1);assert.equal(count(html,/<meta property="og:title"/g),1);
  const schemas=[...html.matchAll(/<script type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g)].map(m=>JSON.parse(m[1]));assert.equal(schemas.length,1);const article=schemas[0]['@graph'].find(x=>x['@type']==='Article');assert.equal(article.headline,ARTICLES[path].title);assert.equal(article.dateModified,UPDATED);assert.equal(article.datePublished,'2026-08-03');assert.equal(article.url,origin+path);assert.equal(article.reviewedBy,undefined);assert.equal(article.aggregateRating,undefined);assert.ok(html.includes('not independent clinical review'));
  for(const retained of ['<header>Retained header</header>','<footer>Retained footer</footer>','<script src="/retained-site-script.js"></script>'])assert.ok(html.includes(retained));assert.doesNotMatch(html,/FAQPage|Wrong generic headline|being built|10\/10|5\/10|3\/10|reviewedBy/);
 });
 test(path+' usable anchors, source-specific citations and change record',()=>{
  const html=articleMain(path),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);for(const m of html.matchAll(/href="#([^"]+)"/g))assert.ok(ids.includes(m[1]),m[1]);assert.ok(ARTICLES[path].sources.length>=4);assert.ok(ARTICLES[path].sections.length>=5);assert.ok(html.includes('What changed on 19 September 2026'));
  for(let n=1;n<=ARTICLES[path].sources.length;n++)assert.ok(html.includes('href="#source-'+n+'"'),'Uncited source '+n);for(const s of ARTICLES[path].sources){const u=new URL(s.url);assert.equal(u.protocol,'https:');assert.ok(!u.hostname.endsWith('nice.org.uk')&&!u.hostname.endsWith('pharmacyregulation.org'),'Pending source permissions remain protected')}
 });
 test(path+' idempotence and no invented first-publication date',()=>{const one=rewriteArticle(shell(),path);assert.equal(rewriteArticle(one,path),one);assert.doesNotMatch(rewriteArticle(shell().replace('"datePublished":"2026-08-03",',''),path),/datePublished|Originally published/)});
}
test('unrelated public, private, commerce and other guide documents are untouched',async()=>{for(const path of ['/','/start-here','/programme','/member/dashboard','/member-login','/treatment-order','/treatment-centre','/articles/stopping-glp1','/mental-health/what-will-gp-ask']){assert.equal(rewriteArticle(shell(),path),shell());const r=new Response(shell(),{headers:{'Content-Type':'text/html'}});assert.equal(await withEditorialResources(r,new Request(origin+path)),r)}});
test('only successful public HTML GETs change; old transport validators are removed',async()=>{
 const path=PATHS[0];for(const [status,type,host,method] of [[404,'text/html',origin,'GET'],[302,'text/html',origin,'GET'],[200,'application/json',origin,'GET'],[200,'text/html','https://api.shiftsometimber.co.uk','GET'],[200,'text/html',origin,'POST']]){const r=new Response(shell(),{status,headers:{'Content-Type':type}});assert.equal(await withEditorialResources(r,new Request(host+path,{method})),r)}
 const head=new Response(null,{headers:{'Content-Type':'text/html'}});assert.equal(await withEditorialResources(head,new Request(origin+path,{method:'HEAD'})),head);
 const r=await withEditorialResources(new Response(shell(),{headers:{'Content-Type':'text/html','etag':'stale','Content-Encoding':'br'}}),new Request(origin+path));assert.equal(r.headers.get('x-shift-article-revision'),VERSION);assert.equal(r.headers.get('etag'),null);assert.equal(r.headers.get('content-encoding'),null);assert.match(r.headers.get('cache-control'),/no-store/);
});
test('incomplete or multiply-main source shape fails closed',()=>{for(const html of ['<html><head></head><body>No main</body></html>',shell().replace('</body>','<main>Another</main></body>')])assert.throws(()=>rewriteArticle(html,PATHS[0]),/one complete main/)});
test('NHS finder retired without deleting general scripts or established section anchors',()=>{
 const path='/guides/nhs-weight-loss-medication-pathways',old=shell().replace('</body>','<script>function runNHSFinder(){return "not a clinical decision"}</script><script>window.keepMe=true;</script></body>'),html=rewriteArticle(old,path);assert.doesNotMatch(html,/function runNHSFinder/);assert.match(html,/window.keepMe=true/);for(const id of ['finder','questions','print','mounjaro','primary','wegovy','saxenda','orlistat','nice','rollout','icb','referral','bloods'])assert.ok(html.includes('id="'+id+'"'),id);
});
test('comparison evidence keeps comparator, duration, unit, stopping and safety limits',()=>{
 const sax=articleMain('/comparisons/medications/mounjaro-vs-saxenda'),orl=articleMain('/comparisons/medications/mounjaro-vs-orlistat');for(const text of ['not a head-to-head comparison','12 weeks at 3.0 mg a day','56 weeks','72 weeks','2,539','3,731'])assert.ok(sax.includes(text),text);for(const text of ['additional kilogram difference versus placebo','3.2 kg','5% of initial body weight'])assert.ok(orl.includes(text),text);for(const text of [sax,orl]){assert.match(text,/severe, persistent abdominal pain/);assert.match(text,/prescrib/i)}
});
test('current versus future NHS cohorts, care settings and UK nations are explicit',()=>{const html=articleMain('/guides/nhs-weight-loss-medication-pathways');for(const text of ['23 June 2026','1 April 2027','not yet the current phase','four of the five','35–39.9','2.5','specialist','cardiovascular','Scotland','Wales','Northern Ireland'])assert.ok(html.includes(text),text);assert.doesNotMatch(html,/<form\b|onclick=|<select\b/)});
test('mental-health help is not weight conditional and includes urgent escalation',()=>{const html=articleMain('/mental-health/mental-health-and-weight');for(const text of ['999','111','116 123','not independent clinical review','Do not abruptly stop','different body weights','not monitored as a crisis service'])assert.ok(html.includes(text),text)});
test('nine source values and existing downloadable bytes are preserved',async()=>{
 const html=articleMain(STATS);assert.equal(DATA.rows.length,9);for(const row of DATA.rows)assert.ok(html.includes('<td>'+row.value));for(const text of ['eight percentage points','not a combined UK estimate','not evidence of treatment results'])assert.ok(html.includes(text));for(const [suffix,body] of [['/data.csv',CSV],['/chart.svg',CHART]]){const r=await withEditorialResources(new Response('404',{status:404}),new Request(origin+STATS+suffix));assert.equal(await r.text(),body)}
});
test('sitemap modifies dates only on the same five locs and cannot redate unrelated standards',()=>{
 const old='<urlset>'+[...PATHS,'/programme','/editorial-standards'].map(p=>'<url><loc>'+origin+p+'</loc><lastmod>2026-09-13</lastmod></url>').join('')+'</urlset>',fixed=updateArticleSitemap(old);assert.equal(count(fixed,/<url>/g),7);assert.equal(count(fixed,/<lastmod>2026-09-19<\/lastmod>/g),5);assert.ok(fixed.includes('/editorial-standards</loc><lastmod>2026-09-13'));assert.equal(updateArticleSitemap(fixed),fixed);assert.equal(setSitemapDate(fixed,STATS,'2026-09-13'),fixed);
});
