import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {verifyLateWatchFactualUpdate,verifyReconciledRelease,LATE_WATCH_BASE as base,LATE_WATCH_APPROVED_MERGE as approvedMerge,LATE_WATCH_SOURCE as source,LATE_WATCH_PATHS as paths,LATE_WATCH_MAINTENANCE as maintenance,RECONCILIATION_MANIFEST,COMPOSITION_TRIGGER_BASE,COMPOSITION_TRIGGER_SOURCE,assertExactCompositionTrigger} from '../release/approved-runtime-composition.mjs';
const restored='scripts/verify-public-continuity-live.mjs';
const receipt=()=>({proof:'EXACT_LATE_WATCH_FACTUAL_UPDATE_V1',base,approvedMerge,source,paths:[...paths],maintenancePaths:[...maintenance],maintenanceSource:'a'.repeat(40),workflowTriggerSource:COMPOSITION_TRIGGER_SOURCE,approvedPR:1267,publicationStatus:'already_merged_owner_authorised_factual_publication',clinicalApproval:null,exactCompleteBodyProofRestored:true,memberTreatmentChanged:false,homepageChanged:false,startHereChanged:false,customerDataChanged:false,genericAdoptionAllowed:false,deploymentAuthorityBroadened:false,rollbackAuthorityBroadened:false,existingGatesWeakened:false});
const options=()=>({head:'b'.repeat(40),ancestor:()=>{},read:()=> 'same',diff:(a,b)=>a===COMPOSITION_TRIGGER_BASE?['.github/workflows/cloudflare-production-promote.yml']:a===base?(b===approvedMerge?[...paths,restored]:[...paths]):a===approvedMerge?[restored]:a===source?[...maintenance]:[RECONCILIATION_MANIFEST]});
test('only the exact merged factual Watch update and original complete-body proof pass',()=>verifyLateWatchFactualUpdate(receipt(),options()));
test('unrelated changes, altered approval and broader deployment authority fail closed',()=>{for(const patch of [{approvedPR:1},{approvedMerge:'f'.repeat(40)},{source:'f'.repeat(40)},{publicationStatus:'draft'},{clinicalApproval:true},{exactCompleteBodyProofRestored:false},...['memberTreatmentChanged','homepageChanged','startHereChanged','customerDataChanged','genericAdoptionAllowed','deploymentAuthorityBroadened','rollbackAuthorityBroadened','existingGatesWeakened'].map(k=>({[k]:true}))])assert.throws(()=>verifyLateWatchFactualUpdate({...receipt(),...patch},options()));for(const boundary of [base,approvedMerge,source,'a'.repeat(40)]){const o=options(),diff=o.diff;o.diff=(a,b)=>a===boundary?[...diff(a,b),'unapproved.js']:diff(a,b);assert.throws(()=>verifyLateWatchFactualUpdate(receipt(),o));}const o=options();o.ancestor=()=>{throw Error('not an ancestor')};assert.throws(()=>verifyLateWatchFactualUpdate(receipt(),o));});
test('restored check and every current or approved source blob remain immutable',()=>{for(const [ref,path] of [['HEAD',restored],[source,restored],...[...paths,...maintenance].map(p=>['HEAD',p]),...paths.map(p=>[source,p])]){const o=options();o.read=(r,p)=>r===ref&&p===path?'drift':'same';assert.throws(()=>verifyLateWatchFactualUpdate(receipt(),o),/source drift|required/);}});
test('real release composition keeps prior ownership and all fresh-reader drift checks',()=>{const c=verifyReconciledRelease();assert.equal(c.lateWatchFactualUpdate.source,source);assert.equal(c.continuityPreservationRepair.source,'7ad0c34d2551a609b959f2b350f1bde1e8313f10');assert.equal(c.myTreatment.source,'8681d219edc06be15c24135741877c47ee36b011');const read=(ref,path)=>execFileSync('git',['show',ref+':'+path],{encoding:'utf8',maxBuffer:4e6});for(const path of [...paths,...maintenance,restored])assert.throws(()=>verifyReconciledRelease((ref,p)=>ref==='HEAD'&&p===path?'drift':read(ref,p)),/source drift/);});


test('release-ledger trigger fix changes no production guard or workflow step',()=>{const read=ref=>execFileSync('git',['show',ref+':.github/workflows/cloudflare-production-promote.yml'],{encoding:'utf8'}),before=read(COMPOSITION_TRIGGER_BASE),after=read(COMPOSITION_TRIGGER_SOURCE);assert.doesNotThrow(()=>assertExactCompositionTrigger(before,after));for(const changed of [after.replace("needs.select-current.outputs.current == 'true'","true"),after.replace('Recover only the evidenced cancelled runtime','Ignore the evidenced cancelled runtime'),after.replace('PROMOTE_CURRENT_MAIN','PROMOTE_ANY_BRANCH'),after+'\n',before])assert.throws(()=>assertExactCompositionTrigger(before,changed));});
