import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {verifyLateWatchFactualUpdate,verifyReconciledRelease,LATE_WATCH_BASE as base,LATE_WATCH_APPROVED_MERGE as approvedMerge,LATE_WATCH_SOURCE as source,LATE_WATCH_PATHS as paths,LATE_WATCH_MAINTENANCE as maintenance,RECONCILIATION_MANIFEST,COMPOSITION_TRIGGER_BASE,COMPOSITION_TRIGGER_SOURCE,assertExactCompositionTrigger} from '../release/approved-runtime-composition.mjs';
const restored='scripts/verify-public-continuity-live.mjs';
const receipt=()=>({proof:'EXACT_LATE_WATCH_FACTUAL_UPDATE_V1',base,approvedMerge,source,paths:[...paths],maintenancePaths:[...maintenance],maintenanceSource:'a'.repeat(40),workflowTriggerSource:COMPOSITION_TRIGGER_SOURCE,approvedPR:1267,publicationStatus:'already_merged_owner_authorised_factual_publication',clinicalApproval:null,exactCompleteBodyProofRestored:true,memberTreatmentChanged:false,homepageChanged:false,startHereChanged:false,customerDataChanged:false,genericAdoptionAllowed:false,deploymentAuthorityBroadened:false,rollbackAuthorityBroadened:false,existingGatesWeakened:false});
const options=()=>({head:'b'.repeat(40),ancestor:()=>{},read:()=> 'same',diff:(a,b)=>a===COMPOSITION_TRIGGER_BASE?['.github/workflows/cloudflare-production-promote.yml']:a===base?(b===approvedMerge?[...paths,restored]:[...paths]):a===approvedMerge?[restored]:a===source?[...maintenance]:[RECONCILIATION_MANIFEST]});
test('only the exact merged factual Watch update and original complete-body proof pass',()=>verifyLateWatchFactualUpdate(receipt(),options()));
test('unrelated changes, altered approval and broader deployment authority fail closed',()=>{for(const patch of [{approvedPR:1},{approvedMerge:'f'.repeat(40)},{source:'f'.repeat(40)},{publicationStatus:'draft'},{clinicalApproval:true},{exactCompleteBodyProofRestored:false},...['memberTreatmentChanged','homepageChanged','startHereChanged','customerDataChanged','genericAdoptionAllowed','deploymentAuthorityBroadened','rollbackAuthorityBroadened','existingGatesWeakened'].map(k=>({[k]:true}))])assert.throws(()=>verifyLateWatchFactualUpdate({...receipt(),...patch},options()));for(const boundary of [base,approvedMerge,source,'a'.repeat(40)]){const o=options(),diff=o.diff;o.diff=(a,b)=>a===boundary?[...diff(a,b),'unapproved.js']:diff(a,b);assert.throws(()=>verifyLateWatchFactualUpdate(receipt(),o));}const o=options();o.ancestor=()=>{throw Error('not an ancestor')};assert.throws(()=>verifyLateWatchFactualUpdate(receipt(),o));});
test('restored check and every current or approved source blob remain immutable',()=>{for(const [ref,path] of [['HEAD',restored],[source,restored],...[...paths,...maintenance].map(p=>['HEAD',p]),...paths.map(p=>[source,p])]){const o=options();o.read=(r,p)=>r===ref&&p===path?'drift':'same';assert.throws(()=>verifyLateWatchFactualUpdate(receipt(),o),/source drift|required/);}});
test('real release composition keeps prior ownership and all fresh-reader drift checks',()=>{const c=verifyReconciledRelease();assert.equal(c.lateWatchFactualUpdate.source,source);assert.equal(c.continuityPreservationRepair.source,'7ad0c34d2551a609b959f2b350f1bde1e8313f10');assert.equal(c.myTreatment.source,'8681d219edc06be15c24135741877c47ee36b011');const read=(ref,path)=>execFileSync('git',['show',ref+':'+path],{encoding:'utf8',maxBuffer:4e6});for(const path of [...paths,...maintenance,restored])assert.throws(()=>verifyReconciledRelease((ref,p)=>ref==='HEAD'&&p===path?'drift':read(ref,p)),/source drift/);});


test('release-ledger trigger fix changes no production guard or workflow step',()=>{const read=ref=>execFileSync('git',['show',ref+':.github/workflows/cloudflare-production-promote.yml'],{encoding:'utf8'}),before=read(COMPOSITION_TRIGGER_BASE),after=read(COMPOSITION_TRIGGER_SOURCE);assert.doesNotThrow(()=>assertExactCompositionTrigger(before,after));for(const changed of [after.replace("needs.select-current.outputs.current == 'true'","true"),after.replace('Recover only the evidenced cancelled runtime','Ignore the evidenced cancelled runtime'),after.replace('PROMOTE_CURRENT_MAIN','PROMOTE_ANY_BRANCH'),after+'\n',before])assert.throws(()=>assertExactCompositionTrigger(before,changed));});

import {verifyTogetherBiomarkerUpdate,assertTogetherBiomarkerProof,TOGETHER_BIOMARKER_BASE as bioBase,TOGETHER_BIOMARKER_SOURCE as bioSource,TOGETHER_BIOMARKER_RUN as bioRun,TOGETHER_BIOMARKER_PATHS as bioPaths,TOGETHER_BIOMARKER_MAINTENANCE as bioMaintenance} from '../release/approved-runtime-composition.mjs';
const bioReceipt=()=>({proof:'EXACT_TOGETHER_BIOMARKER_UPDATE_V1',base:bioBase,source:bioSource,proofRun:bioRun,paths:[...bioPaths],maintenancePaths:[...bioMaintenance],maintenanceSource:'a'.repeat(40),approvedPR:1276,publicationStatus:'owner_authorised_factual_publication',clinicalApproval:null,...Object.fromEntries(['registryFactsChanged','reviewDatesRenewedByHttp','monitorBaselinesChanged','memberTreatmentChanged','homepageChanged','startHereChanged','customerDataChanged','genericAdoptionAllowed','deploymentAuthorityBroadened','rollbackAuthorityBroadened','existingGatesWeakened'].map(k=>[k,false]))});
const bioOptions=()=>({head:'b'.repeat(40),read:()=> 'same',ancestor:()=>{},diff:(a,b)=>a===bioBase?[...bioPaths]:a===bioSource?[...bioMaintenance]:[RECONCILIATION_MANIFEST]});
test('biomarker release requires exact reviewed payload and finite maintenance',()=>verifyTogetherBiomarkerUpdate(bioReceipt(),bioOptions()));
test('biomarker release rejects stale evidence, clinical approval and unrelated changes at every boundary',()=>{
 for(const patch of [{source:'f'.repeat(40)},{base:'f'.repeat(40)},{proofRun:1},{approvedPR:1},{clinicalApproval:true},{publicationStatus:'draft'},{maintenanceSource:'main'},...Object.keys(bioReceipt()).filter(k=>bioReceipt()[k]===false).map(k=>({[k]:true}))])assert.throws(()=>verifyTogetherBiomarkerUpdate({...bioReceipt(),...patch},bioOptions()));
 for(const boundary of [bioBase,bioSource,'a'.repeat(40)]){const o=bioOptions(),diff=o.diff;o.diff=(a,b)=>a===boundary?[...diff(a,b),'worker.js']:diff(a,b);assert.throws(()=>verifyTogetherBiomarkerUpdate(bioReceipt(),o));}
 const o=bioOptions();o.ancestor=()=>{throw Error('unrelated history')};assert.throws(()=>verifyTogetherBiomarkerUpdate(bioReceipt(),o));
});
test('biomarker release detects current payload and maintenance drift including overlapping review workflow',()=>{
 for(const path of new Set([...bioPaths,...bioMaintenance])){const o=bioOptions();o.read=(r,p)=>r==='HEAD'&&p===path?'drift':'same';assert.throws(()=>verifyTogetherBiomarkerUpdate(bioReceipt(),o),/source drift/);}
});
test('biomarker proof requires exact successful PR attempt, source and workflow',()=>{
 const proof={id:bioRun,head_sha:bioSource,path:'.github/workflows/medicines-watch-check.yml',event:'pull_request',head_branch:'review/watch-together-biomarkers-20261009',status:'completed',conclusion:'success'};assertTogetherBiomarkerProof(proof);
 for(const patch of [{id:bioRun+1},{head_sha:'f'.repeat(40)},{path:'.github/workflows/cloudflare-production-promote.yml'},{event:'push'},{head_branch:'main'},{status:'in_progress'},{conclusion:'failure'}])assert.throws(()=>assertTogetherBiomarkerProof({...proof,...patch}));
});
test('real biomarker composition retains previous verified runtime and rejects all fresh-reader drift',()=>{
 const c=verifyReconciledRelease();assert.equal(c.togetherBiomarkerUpdate.source,bioSource);assert.equal(c.lateWatchFactualUpdate.source,source);
 const read=(ref,path)=>execFileSync('git',['show',ref+':'+path],{encoding:'utf8',maxBuffer:4e6});
 for(const path of new Set([...bioPaths,...bioMaintenance]))assert.throws(()=>verifyReconciledRelease((ref,p)=>ref==='HEAD'&&p===path?'drift':read(ref,p)),/source drift/);
});

import {verifyWatchBacklogUpdate,assertWatchBacklogProof,WATCH_BACKLOG_BASE as backlogBase,WATCH_BACKLOG_SOURCE as backlogSource,WATCH_BACKLOG_RUN as backlogRun,WATCH_BACKLOG_PATHS as backlogPaths,WATCH_BACKLOG_MAINTENANCE as backlogMaintenance} from '../release/approved-runtime-composition.mjs';
const backlogReceipt=()=>({proof:'EXACT_WATCH_BACKLOG_UPDATE_V1',base:backlogBase,source:backlogSource,proofRun:backlogRun,paths:[...backlogPaths],maintenancePaths:[...backlogMaintenance],maintenanceSource:'a'.repeat(40),approvedPR:1281,publicationStatus:'owner_authorised_factual_publication',clinicalApproval:null,sourceReviews:35,changedTrialRecords:3,officialAlternativeReplacements:1,...Object.fromEntries(['reviewDatesRenewedByHttp','memberTreatmentChanged','homepageChanged','startHereChanged','customerDataChanged','genericAdoptionAllowed','deploymentAuthorityBroadened','rollbackAuthorityBroadened','existingGatesWeakened'].map(k=>[k,false]))});
const backlogOptions=()=>({head:'b'.repeat(40),read:()=> 'same',ancestor:()=>{},diff:(a,b)=>a===backlogBase?[...backlogPaths]:a===backlogSource?[...backlogMaintenance]:[RECONCILIATION_MANIFEST]});
test('backlog publication binds exact reviewed payload and rejects unrelated changes, drift and clinical signoff',()=>{
 assert.equal(backlogBase,'b31e1c63cede1cde2be975c4b4cc609ef1a11630');assert.equal(backlogSource,'48020574fdda274d04901052942aacbe1502fb31');assert.equal(backlogRun,37995046889);
 verifyWatchBacklogUpdate(backlogReceipt(),backlogOptions());
 for(const patch of [{source:'f'.repeat(40)},{base:'f'.repeat(40)},{proofRun:1},{approvedPR:1},{clinicalApproval:true},{sourceReviews:0},{changedTrialRecords:0},{officialAlternativeReplacements:0},...Object.keys(backlogReceipt()).filter(k=>backlogReceipt()[k]===false).map(k=>({[k]:true}))])assert.throws(()=>verifyWatchBacklogUpdate({...backlogReceipt(),...patch},backlogOptions()));
 for(const boundary of [backlogBase,backlogSource,'a'.repeat(40)]){const o=backlogOptions(),diff=o.diff;o.diff=(a,b)=>a===boundary?[...diff(a,b),'worker.js']:diff(a,b);assert.throws(()=>verifyWatchBacklogUpdate(backlogReceipt(),o));}
 for(const path of [...backlogPaths,...backlogMaintenance]){const o=backlogOptions();o.read=(r,p)=>r==='HEAD'&&p===path?'drift':'same';assert.throws(()=>verifyWatchBacklogUpdate(backlogReceipt(),o),/source drift/);}
 const proof={id:backlogRun,head_sha:backlogSource,path:'.github/workflows/medicines-watch-check.yml',event:'pull_request',head_branch:'review/watch-backlog-20261009',status:'completed',conclusion:'success'};assertWatchBacklogProof(proof);
 for(const patch of [{id:1},{head_sha:'f'.repeat(40)},{conclusion:'failure'},{status:'in_progress'},{event:'push'},{head_branch:'main'}])assert.throws(()=>assertWatchBacklogProof({...proof,...patch}));
});
