import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {verifyMaleObesityPillar,verifyReconciledRelease,MALE_OBESITY_BASE as base,MALE_OBESITY_SOURCE as source,MALE_OBESITY_PATHS as paths,MALE_OBESITY_MAINTENANCE as maintenancePaths,RECONCILIATION_MANIFEST} from '../release/approved-runtime-composition.mjs';
const flags=['homepageChanged','startHereFlowChanged','primaryNavigationChanged','memberDataChanged','checkoutChanged','externalCommunicationsSent','costsCommitted','genericAdoptionAllowed','deploymentAuthorityBroadened','rollbackAuthorityBroadened','existingGatesWeakened'];
const receipt=()=>({proof:'EXACT_MALE_OBESITY_PILLAR_V1',base,source,paths:[...paths],maintenancePaths:[...maintenancePaths],maintenanceSource:'a'.repeat(40),ownerApproval:'Approved, Go; complete authorised informational release',externalReviewerRequired:false,publicationStatus:'approved_for_guarded_release',...Object.fromEntries(flags.map(k=>[k,false]))});
const opts=()=>({head:'b'.repeat(40),read:()=> 'same',content:()=> '{}',ancestor:()=>{},diff:(a,b)=>a===base?[...paths]:a===source?[...maintenancePaths]:[RECONCILIATION_MANIFEST]});
test('male-obesity registration accepts exact approved source and finite maintenance only',()=>verifyMaleObesityPillar(receipt(),opts()));
test('unapproved scope, reviewer gate revival, paths and unrelated changes fail closed',()=>{for(const patch of [{source:'f'.repeat(40)},{base:'f'.repeat(40)},{paths:[...paths,'unapproved.js']},{ownerApproval:'pending'},{externalReviewerRequired:true},{publicationStatus:'draft'},...flags.map(k=>({[k]:true}))])assert.throws(()=>verifyMaleObesityPillar({...receipt(),...patch},opts()));for(const ref of [base,source,'a'.repeat(40)]){const o=opts(),diff=o.diff;o.diff=(a,b)=>a===ref?[...diff(a,b),'unapproved.js']:diff(a,b);assert.throws(()=>verifyMaleObesityPillar(receipt(),o));}});
test('all current payload and maintenance blobs remain immutable',()=>{for(const path of [...paths,...maintenancePaths]){const o=opts();o.read=(ref,p)=>ref==='HEAD'&&p===path?'drift':'same';assert.throws(()=>verifyMaleObesityPillar(receipt(),o),/source drift/);}});
test('real registered composition preserves prior receipts and rejects fresh reader drift',()=>{const c=verifyReconciledRelease();assert.equal(c.maleObesityPillar.source,source);assert.equal(c.togetherBiomarkerUpdate.approvedPR,1276);const read=(ref,path)=>execFileSync('git',['show',ref+':'+path],{encoding:'utf8',maxBuffer:4e6});for(const path of ['obesity-awareness/production.mjs','shift-coach/worker.mjs','release/approved-runtime-composition.mjs'])assert.throws(()=>verifyReconciledRelease((ref,p)=>ref==='HEAD'&&p===path?'drift':read(ref,p)),/source drift/);});

test('receipt registration cannot alter any prior ledger field',()=>{const o=opts();o.content=(ref)=>JSON.stringify({prior:ref===base?'approved':'changed'});assert.throws(()=>verifyMaleObesityPillar(receipt(),o),/Prior release receipts/)});
