import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {createHmac} from 'node:crypto';
import {medicineCommerceRoutes} from '../medicine-commerce-v1.js';
function fixture(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(`CREATE TABLE medicine_products(id INTEGER PRIMARY KEY);CREATE TABLE medicine_variants(id INTEGER PRIMARY KEY);CREATE TABLE medicine_orders(id INTEGER PRIMARY KEY,order_number TEXT,user_id INTEGER,email TEXT,variant_id INTEGER,status TEXT,stripe_payment_intent_id TEXT,updated_at TEXT);CREATE TABLE medicine_inventory(variant_id INTEGER PRIMARY KEY,stock_on_hand INTEGER,reserved INTEGER,updated_at TEXT);INSERT INTO medicine_orders VALUES(1,'TEST-ORDER',1,'synthetic@example.test',1,'checkout_open',NULL,NULL);INSERT INTO medicine_inventory VALUES(1,10,2,NULL);`);
 const state={failAt:null,emails:[],waits:[]};
 const DB={async exec(sql){sqlite.exec(sql)},prepare(sql){const statement={sql,args:[],bind(...args){return {...statement,args}},async run(){return {meta:sqlite.prepare(this.sql).run(...this.args)}},async first(){return sqlite.prepare(this.sql).get(...this.args)||null},async all(){return {results:sqlite.prepare(this.sql).all(...this.args)}}};return statement},async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(let i=0;i<statements.length;i++){if(state.failAt===i&&statements.some(x=>x.sql.startsWith('UPDATE medicine_inventory'))){state.failAt=null;throw Error('transient database failure')}results.push({meta:sqlite.prepare(statements[i].sql).run(...statements[i].args)})}sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
 const env={DB,STRIPE_WEBHOOK_SECRET:'synthetic-secret',EMAIL:{async send(message){state.emails.push(message);return {id:'synthetic-delivery'}}}};
 async function send(id='evt_one',type='checkout.session.completed',paid=true){const event={id,type,data:{object:{metadata:{order_type:'medicine',order_number:'TEST-ORDER'},payment_status:paid?'paid':'unpaid',payment_intent:'pi_synthetic'}}};const payload=JSON.stringify(event),timestamp=Math.floor(Date.now()/1000),signature=createHmac('sha256',env.STRIPE_WEBHOOK_SECRET).update(timestamp+'.'+payload).digest('hex');const response=await medicineCommerceRoutes(new Request('https://example.test/v1/commerce/stripe/webhook',{method:'POST',headers:{'stripe-signature':`t=${timestamp},v1=${signature}`},body:payload}),env,{waitUntil(p){state.waits.push(p)}});await Promise.all(state.waits);return {status:response.status,body:await response.json()}}
 const read=()=>({order:sqlite.prepare('SELECT status,clinical_status FROM medicine_orders').get(),inventory:sqlite.prepare('SELECT stock_on_hand,reserved FROM medicine_inventory').get(),events:sqlite.prepare('SELECT processed_at,processing_error FROM medicine_stripe_events').all()});
 return {sqlite,state,send,read};
}
for(const at of [0,1,2,3])test('retry recovers transaction failure at statement '+at,async()=>{const f=fixture();f.state.failAt=at;await assert.rejects(()=>f.send(),/transient/);assert.equal(f.read().order.status,'checkout_open');assert.equal(f.read().inventory.stock_on_hand,10);assert.equal(f.read().events[0].processed_at,null);await f.send();assert.equal(f.read().order.status,'paid');assert.equal(f.read().inventory.stock_on_hand,9);assert.equal(f.read().inventory.reserved,1);assert.ok(f.read().events[0].processed_at);assert.equal(f.read().events[0].processing_error,null);const count=f.state.emails.length;assert.ok(count>0);assert.equal((await f.send()).body.duplicate,true);assert.equal(f.state.emails.length,count);assert.equal(f.read().inventory.stock_on_hand,9)});
test('distinct success events settle once and preserve clinical progress',async()=>{const f=fixture();await f.send();f.sqlite.exec("UPDATE medicine_orders SET clinical_status='dispatched'");const count=f.state.emails.length;await f.send('evt_two','checkout.session.async_payment_succeeded');assert.equal(f.read().order.clinical_status,'dispatched');assert.equal(f.read().inventory.stock_on_hand,9);assert.equal(f.state.emails.length,count)});
test('late failure cannot downgrade payment or release somebody else’s reservation',async()=>{const f=fixture();await f.send();await f.send('evt_failure','checkout.session.expired',false);assert.equal(f.read().order.status,'paid');assert.equal(f.read().inventory.reserved,1);assert.equal(f.read().inventory.stock_on_hand,9)});
test('failure repeats release once; later confirmed payment does not release another reservation',async()=>{const f=fixture();await f.send('evt_fail','checkout.session.async_payment_failed',false);await f.send('evt_expire','checkout.session.expired',false);assert.equal(f.read().inventory.reserved,1);assert.equal(f.read().inventory.stock_on_hand,10);await f.send();assert.equal(f.read().order.status,'paid');assert.equal(f.read().inventory.stock_on_hand,9);assert.equal(f.read().inventory.reserved,1)});
test('missing order remains retryable',async()=>{const f=fixture();f.sqlite.exec('DELETE FROM medicine_orders');const result=await f.send();assert.equal(result.status,503);assert.equal(f.read().events[0].processed_at,null)});
test('refunded orders cannot be restored to paid',async()=>{const f=fixture();await f.send();f.sqlite.exec("UPDATE medicine_orders SET status='refunded',clinical_status='refunded'");await f.send('evt_later');assert.equal(f.read().order.status,'refunded');assert.equal(f.read().inventory.stock_on_hand,9)});

test('concurrent distinct success deliveries settle the order once',async()=>{const f=fixture();await Promise.all([f.send('evt_a'),f.send('evt_b'),f.send('evt_c')]);assert.equal(f.read().order.status,'paid');assert.equal(f.read().inventory.stock_on_hand,9);assert.equal(f.read().inventory.reserved,1);assert.equal(f.state.emails.filter(x=>x.to==='synthetic@example.test').length,1)});
