import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {saveHealthInterest,OWNED_JOURNEY_SQL,normaliseHealthInterest} from '../member-experience/health-interest-store.mjs';
function fixture(t,{consent=1,prefs={myJourney:{weight:{currentKg:95},setup:{why:'family'}},lifeBack:{progress:{revision:4}},grubV2:{today:'meal'}},row=true}={}){
 const sqlite=new DatabaseSync(':memory:');t.after(()=>sqlite.close());
 sqlite.exec("CREATE TABLE member_state(user_id INTEGER PRIMARY KEY,preferences TEXT NOT NULL DEFAULT '{}',updated_at TEXT);CREATE TABLE consents(id INTEGER PRIMARY KEY,user_id INTEGER,consent_type TEXT,granted INTEGER)");
 sqlite.prepare("INSERT INTO consents(user_id,consent_type,granted) VALUES(1,'my_shift_health_tracking',?)").run(consent);
 if(row)sqlite.prepare('INSERT INTO member_state(user_id,preferences) VALUES(1,?)').run(typeof prefs==='string'?prefs:JSON.stringify(prefs));
 const DB={prepare(sql){let args=[];return {bind(...a){args=a;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}}}};
 return {sqlite,DB,read:()=>JSON.parse(sqlite.prepare('SELECT preferences FROM member_state WHERE user_id=1').get()?.preferences||'{}')};
}
test('real SQLite append preserves every other member field',async t=>{const f=fixture(t);const before=f.read();await saveHealthInterest(f.DB,1,'health-mot');const after=f.read();assert.deepEqual(after.myJourney.weight,before.myJourney.weight);assert.deepEqual(after.lifeBack,before.lifeBack);assert.deepEqual(after.grubV2,before.grubV2);assert.deepEqual(after.myJourney.healthInterests,['health-mot'])});
test('parallel additions both survive; repeat is idempotent',async t=>{const f=fixture(t);await Promise.all([saveHealthInterest(f.DB,1,'health-mot'),saveHealthInterest(f.DB,1,'sleep-apnoea')]);await saveHealthInterest(f.DB,1,'health-mot');assert.deepEqual(new Set(f.read().myJourney.healthInterests),new Set(['health-mot','sleep-apnoea']))});
test('consent off cannot create a member state row',async t=>{const f=fixture(t,{consent:0,row:false});await assert.rejects(saveHealthInterest(f.DB,1,'health-mot'),e=>e.status===409);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM member_state').get().n,0)});
test('withdrawn consent blocks writes even after an earlier affirmative read',async t=>{const f=fixture(t);assert.equal(f.sqlite.prepare('SELECT granted FROM consents ORDER BY id DESC LIMIT 1').get().granted,1);const before=f.read();f.sqlite.exec("INSERT INTO consents(user_id,consent_type,granted) VALUES(1,'my_shift_health_tracking',0)");await assert.rejects(saveHealthInterest(f.DB,1,'health-mot'),e=>e.status===409);assert.deepEqual(f.read(),before)});
test('fresh consenting account is created without fabricated measurements',async t=>{const f=fixture(t,{row:false});await saveHealthInterest(f.DB,1,'health-mot');assert.deepEqual(f.read(),{myJourney:{healthInterests:['health-mot']}})});
test('missing Journey object is safely added; explicit corrupt shapes are not erased',async t=>{const f=fixture(t,{prefs:{grubV2:{today:'x'}}});await saveHealthInterest(f.DB,1,'sleep-apnoea');assert.deepEqual(f.read().grubV2,{today:'x'});for(const value of [{myJourney:null},{myJourney:[]},{myJourney:{healthInterests:'bad'}}]){f.sqlite.prepare('UPDATE member_state SET preferences=? WHERE user_id=1').run(JSON.stringify(value));await assert.rejects(saveHealthInterest(f.DB,1,'health-mot'));assert.deepEqual(f.read(),value)}});
test('stale Journey save cannot replace endpoint-owned priorities',async t=>{const f=fixture(t);const stale=f.read().myJourney;await saveHealthInterest(f.DB,1,'health-mot');await saveHealthInterest(f.DB,1,'sleep-apnoea');const sql=`INSERT INTO member_state(user_id,preferences) VALUES(1,?) ON CONFLICT(user_id) DO UPDATE SET preferences=json_set(member_state.preferences,'$.myJourney',${OWNED_JOURNEY_SQL})`;f.sqlite.prepare(sql).run(JSON.stringify({myJourney:{...stale,weight:{currentKg:94},healthInterests:[]}}));assert.deepEqual(f.read().myJourney.healthInterests,['health-mot','sleep-apnoea']);assert.equal(f.read().myJourney.weight.currentKg,94);assert.equal(f.read().lifeBack.progress.revision,4)});
test('existing erase removes priorities with Journey and does not affect another member',async t=>{const f=fixture(t);await saveHealthInterest(f.DB,1,'health-mot');f.sqlite.exec(`INSERT INTO member_state(user_id,preferences) VALUES(2,'{"myJourney":{"healthInterests":["sleep-apnoea"]}}');UPDATE member_state SET preferences=json_remove(preferences,'$.myJourney','$.lifeBack') WHERE user_id=1`);assert.equal(f.read().myJourney,undefined);assert.deepEqual(JSON.parse(f.sqlite.prepare('SELECT preferences FROM member_state WHERE user_id=2').get().preferences).myJourney.healthInterests,['sleep-apnoea'])});
test('invented priorities and invalid member IDs cannot write',async t=>{const f=fixture(t);for(const value of ['invented','__proto__','constructor',{},null]){await assert.rejects(saveHealthInterest(f.DB,1,value),e=>e.status===400)}await assert.rejects(saveHealthInterest(f.DB,0,'health-mot'),e=>e.status===401);assert.equal(f.read().myJourney.healthInterests,undefined);assert.equal(normaliseHealthInterest(' HEALTH-MOT '),'health-mot')});
test('all ten choices remain bounded under repeated concurrent writes',async t=>{const f=fixture(t);const values=['health-mot','testosterone-energy','blood-pressure-monitor','digital-scales','resistance-bands','shift-measure','erectile-dysfunction','hair-loss','stop-smoking','sleep-apnoea'];await Promise.all([...values,...values].map(v=>saveHealthInterest(f.DB,1,v)));assert.equal(f.read().myJourney.healthInterests.length,10)});
