import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {setup,memberRequest,partnerRequest} from './patient-intake-fixture.mjs';
import {medicineCommerceRoutes} from '../medicine-commerce-v1.js';
import {normaliseAnswers} from '../patient-intake-v2.js';
import {draftQuestionnaire} from '../patient-questionnaire-v2.js';
import {withPatientStartHere} from '../patient-start-here-v2.js';
const realFetch=globalThis.fetch;
const valid={firstName:'Synthetic',lastName:'Patient',email:'patient@example.test',phone:'07700900000',dateOfBirth:'1981-08-03',addressLine1:'1 Test Road',town:'Macclesfield',postcode:'SK10 1AA',country:'GB',weightUnit:'st',weightStone:'14',weightLb:'7',heightUnit:'ft',heightFeet:'5',heightInches:'8',gpPractice:'Synthetic Practice',gpAddress:'2 Test Road',gpPostcode:'SK10 1AA',conditions:'None',medicines:'None',allergies:'None',previousTreatment:'switching',previousMedicine:'Mounjaro',previousDoseMg:'2.5',lastDoseDate:'2026-09-01',treatmentBreaks:'None',sideEffects:'None',gpContactConsent:true,imageConsent:true,dataConsent:true,answersConfirmed:true,clinical:Object.fromEntries(draftQuestionnaire.questions.map(q=>[q.id,{answer:'no',details:''}]))};
async function envSetup(){const DB=await setup(),objects=new Map();const env={DB,MEDICINE_INTAKE_V2_ENABLED:'true',PATIENT_DATA_KEY:'ab'.repeat(32),PATIENT_EVIDENCE:{async put(k,v){objects.set(k,v)},async get(k){return objects.has(k)?{text:async()=>objects.get(k)}:null},async delete(k){objects.delete(k)}},PATIENT_CLINICAL_POLICY_JSON:JSON.stringify({...draftQuestionnaire,status:'approved',approvedBy:'SYNTHETIC TEST FIXTURE ONLY',approvedAt:'2026-09-13'}),STRIPE_MODE:'test',STRIPE_SECRET_KEY:'sk_test_synthetic',STRIPE_WEBHOOK_SECRET:'whsec_synthetic',PUBLIC_SITE_URL:'https://shiftsometimber.co.uk',PHARMACY_INTEGRATION_SECRET:'pharmacy-e2e-secret'};return{env,objects,DB}}
async function call(env,path,method='GET',value){const init={method};if(value instanceof FormData)init.body=value;else if(value!==undefined){init.body=JSON.stringify(value);init.headers={'content-type':'application/json'}}const r=await medicineCommerceRoutes(memberRequest(path,init),env,{});return{status:r.status,body:await r.json()}}
async function pay(env){let sessions=0;globalThis.fetch=async(url,init)=>{assert.equal(String(url),'https://api.stripe.com/v1/checkout/sessions');sessions++;const data=new URLSearchParams(init.body);assert.match(data.get('success_url'),/patient-intake\?session_id/);assert.equal(data.get('cancel_url'),'https://shiftsometimber.co.uk/treatment-checkout?variant=11&checkout=cancelled');return Response.json({id:'cs_test_patient_v2',url:'https://checkout.stripe.test/synthetic'})};const requestId=crypto.randomUUID(),body={variantId:11,assessmentTermsAccepted:true,checkoutRequestId:requestId};const c=await call(env,'/v1/commerce/medicine-checkout','POST',body);assert.equal(c.status,201,JSON.stringify(c));const retry=await call(env,'/v1/commerce/medicine-checkout','POST',body);assert.equal(retry.status,200);assert.equal(retry.body.checkoutUrl,c.body.checkoutUrl);assert.equal(sessions,1);assert.equal((await call(env,`/v1/patient-intake?order=${c.body.orderNumber}`)).status,409);assert.equal((await call(env,`/v1/patient-intake?order=${c.body.orderNumber}`,'POST',{version:0,answers:valid})).status,409);
 const timestamp=Math.floor(Date.now()/1000),event={id:'evt_patient_paid',type:'checkout.session.completed',data:{object:{id:'cs_test_patient_v2',payment_status:'paid',payment_intent:'pi_patient_v2',metadata:{order_type:'medicine',order_number:c.body.orderNumber}}}},payload=JSON.stringify(event),sig=createHmac('sha256',env.STRIPE_WEBHOOK_SECRET).update(`${timestamp}.${payload}`).digest('hex');const r=await medicineCommerceRoutes(new Request('https://api.shiftsometimber.co.uk/v1/commerce/stripe/webhook',{method:'POST',headers:{'stripe-signature':`t=${timestamp},v1=${sig}`},body:payload}),env,{});assert.equal(r.status,200);return c.body.orderNumber}
async function upload(env,order,slot,type='image/jpeg'){const f=new FormData();f.set('slot',slot);f.set('file',new File([type==='application/pdf'?'%PDF-1.4 synthetic':new Uint8Array([255,216,255,217])],'synthetic',{type}));return call(env,`/v1/patient-intake/evidence?order=${order}`,'POST',f)}
test('paid-order intake persists encrypted data, enforces evidence and clinical answers, retries a single pharmacy handoff',async()=>{const{env,DB,objects}=await envSetup();try{const order=await pay(env),url=`/v1/patient-intake?order=${order}`;const read=await call(env,url);assert.equal(read.status,200);assert.equal(read.body.status,'draft');let v=read.body.version;
 const premature=await medicineCommerceRoutes(partnerRequest('/v1/integrations/pharmacy/treatment-status',{orderNumber:order,status:'approved',partnerReference:'not-received'}),env,{});assert.equal(premature.status,409);
 let saved=await call(env,url,'POST',{version:v,answers:valid});assert.equal(saved.status,200);v=saved.body.version;const restored=await call(env,url);assert.equal(restored.body.answers.firstName,'Synthetic');assert.equal(restored.body.answers.heightCm,172.72);assert.equal(restored.body.answers.weightKg,92.08);assert.equal(restored.body.answers.clinical.eatingDisorder.answer,'no');
 const stored=await DB.prepare('SELECT answers_encrypted FROM patient_intakes_v2').first();assert.ok(!stored.answers_encrypted.includes('Synthetic'));assert.ok(!stored.answers_encrypted.includes('Mounjaro'));
 assert.equal((await call(env,url,'POST',{version:0,answers:valid})).status,409);
 assert.equal((await call(env,`/v1/patient-intake/submit?order=${order}`,'POST',{version:v})).status,400);
 for(const slot of ['photoId','bodyFront','bodySide','previousEvidence'])assert.equal((await upload(env,order,slot,slot==='previousEvidence'?'application/pdf':'image/jpeg')).status,200);
 assert.equal(objects.size,4);for(const x of objects.values())assert.ok(x.startsWith('{"v":1'));
 let answer={...valid,clinical:{...valid.clinical,eatingDisorder:{answer:'yes',details:''}}};saved=await call(env,url,'POST',{version:v,answers:answer});v=saved.body.version;let submit=await call(env,`/v1/patient-intake/submit?order=${order}`,'POST',{version:v});assert.equal(submit.status,400);assert.match(submit.body.error,/Add details/);
 answer={...valid,clinical:{...valid.clinical,immediateDanger:{answer:'yes',details:''}}};saved=await call(env,url,'POST',{version:v,answers:answer});v=saved.body.version;submit=await call(env,`/v1/patient-intake/submit?order=${order}`,'POST',{version:v});assert.equal(submit.status,422);assert.match(submit.body.error,/999/);
 saved=await call(env,url,'POST',{version:v,answers:valid});v=saved.body.version;
 submit=await call(env,`/v1/patient-intake/submit?order=${order}`,'POST',{version:v});assert.equal(submit.status,202);assert.equal(submit.body.status,'queued');assert.equal((await call(env,url,'POST',{version:v,answers:valid})).status,409);
 env.PHARMACY_PATIENT_INTAKE_V2_URL='https://pharmacy.example.test/intake/v2';const keys=[];globalThis.fetch=async(url,init)=>{assert.equal(String(url),env.PHARMACY_PATIENT_INTAKE_V2_URL);keys.push(init.headers['idempotency-key']);const body=JSON.parse(init.body);assert.equal(body.assessment.clinical.mentalHealth.answer,'no');assert.equal(body.evidence.length,4);assert.equal(body.orderNumber,order);if(keys.length===1)throw Error('Network timeout');return Response.json({reference:'PHA-V2-TEST'})};
 const timeout=await call(env,`/v1/patient-intake/retry?order=${order}`,'POST');assert.equal(timeout.body.status,'queued');const accepted=await call(env,`/v1/patient-intake/retry?order=${order}`,'POST');assert.equal(accepted.body.status,'submitted');assert.equal(keys[0],keys[1]);await call(env,`/v1/patient-intake/retry?order=${order}`,'POST');assert.equal(keys.length,2);
 globalThis.fetch=async()=>{throw Error('Unexpected outbound')};let r=await medicineCommerceRoutes(partnerRequest('/v1/integrations/pharmacy/treatment-status',{orderNumber:order,status:'approved',partnerReference:'PHA-V2-TEST'}),env,{});assert.equal(r.status,200);r=await medicineCommerceRoutes(partnerRequest('/v1/integrations/pharmacy/treatment-status',{orderNumber:order,status:'dispensing',partnerReference:'PHA-V2-TEST'}),env,{});assert.equal(r.status,409);
 const journey={myJourney:{setup:{startDate:'2026-09-13',targetMode:'loss'},weight:{startKg:92,currentKg:92,targetKg:80},lifeBack:{priorities:['energy']}}};await DB.prepare('UPDATE member_state SET preferences=? WHERE user_id=42').bind(JSON.stringify(journey)).run();for(const status of ['dispensing','dispatched']){r=await medicineCommerceRoutes(partnerRequest('/v1/integrations/pharmacy/treatment-status',{orderNumber:order,status,partnerReference:'PHA-V2-TEST'}),env,{});assert.equal(r.status,200)}
 const tracker=await call(env,'/v1/treatment/orders');assert.equal(tracker.body.orders[0].assessmentUrl,`/patient-intake?order=${order}`);
 }finally{globalThis.fetch=realFetch;DB.close()}});
test('cross-account and cross-origin requests cannot read or mutate an assessment or its evidence',async()=>{const{env,DB}=await envSetup();try{const order=await pay(env);await call(env,`/v1/patient-intake?order=${order}`);await upload(env,order,'bodyFront');const info=await call(env,`/v1/patient-intake?order=${order}`),id=info.body.evidence[0].id;
 await DB.prepare('UPDATE medicine_orders SET user_id=99 WHERE order_number=?').bind(order).run();for(const path of [`/v1/patient-intake?order=${order}`,`/v1/patient-intake/evidence?order=${order}&id=${id}`])assert.equal((await call(env,path)).status,404);
 const r=await medicineCommerceRoutes(new Request(`https://api.shiftsometimber.co.uk/v1/patient-intake?order=${order}`,{method:'POST',headers:{origin:'https://evil.example','cookie':'sst_session=e2e-member-session'},body:'{}'}),env,{});assert.equal(r.status,403);
 }finally{globalThis.fetch=realFetch;DB.close()}});
test('unapproved questionnaire prevents payment and invalid measurements do not become complete assessments',async()=>{const{env,DB}=await envSetup();try{delete env.PATIENT_CLINICAL_POLICY_JSON;let called=false;globalThis.fetch=async()=>{called=true;throw Error()};const r=await call(env,'/v1/commerce/medicine-checkout','POST',{variantId:11,assessmentTermsAccepted:true,checkoutRequestId:crypto.randomUUID()});assert.equal(r.status,503);assert.equal(r.body.error,'clinical_questionnaire_not_commissioned');assert.equal(called,false);assert.throws(()=>normaliseAnswers({...valid,weightLb:'14'},true));assert.throws(()=>normaliseAnswers({...valid,heightInches:'12'},true));assert.throws(()=>normaliseAnswers({...valid,dateOfBirth:'2020-02-30'},true));assert.throws(()=>normaliseAnswers({...valid,lastDoseDate:'2099-01-01'},true));}finally{globalThis.fetch=realFetch;DB.close()}});
test('cancellation refunds the original payment once and never reports a pending refund as completed',async()=>{const{env,DB}=await envSetup();try{const order=await pay(env);await call(env,`/v1/patient-intake?order=${order}`);let posts=0;globalThis.fetch=async(url,init)=>{if(init.method==='POST'){posts++;assert.equal(init.headers['idempotency-key'],`patient-refund-v2:${order}`);return Response.json({id:'re_test',status:'pending',payment_intent:'pi_patient_v2',amount:16900,currency:'gbp'})}assert.match(String(url),/refunds\/re_test$/);return Response.json({id:'re_test',status:'succeeded',payment_intent:'pi_patient_v2',amount:16900,currency:'gbp'})};let r=await call(env,`/v1/patient-intake/refund?order=${order}`,'POST');assert.equal(r.body.status,'refund_pending');r=await call(env,`/v1/patient-intake/refund?order=${order}`,'POST');assert.equal(r.body.status,'refunded');await call(env,`/v1/patient-intake/refund?order=${order}`,'POST');assert.equal(posts,1);assert.equal((await DB.prepare('SELECT status FROM medicine_orders WHERE order_number=?').bind(order).first()).status,'refunded');}finally{globalThis.fetch=realFetch;DB.close()}});
test('lookup has a manual fallback and rejects malformed evidence',async()=>{const{env,DB}=await envSetup();try{const order=await pay(env);await call(env,`/v1/patient-intake?order=${order}`);const r=await call(env,'/v1/patient-intake/lookup?kind=gp&q=test');assert.equal(r.body.manual,true);const f=new FormData();f.set('slot','bodyFront');f.set('file',new File(['<script>bad</script>'],'bad.jpg',{type:'image/jpeg'}));assert.equal((await call(env,`/v1/patient-intake/evidence?order=${order}`,'POST',f)).status,400);}finally{globalThis.fetch=realFetch;DB.close()}});
test('a failed Stripe connection releases stock and permits a fresh checkout attempt',async()=>{const{env,DB}=await envSetup();try{globalThis.fetch=async()=>{throw Error('Network failed')};const first=await call(env,'/v1/commerce/medicine-checkout','POST',{variantId:11,assessmentTermsAccepted:true,checkoutRequestId:crypto.randomUUID()});assert.equal(first.status,502);assert.equal(first.body.retryable,true);assert.equal((await DB.prepare('SELECT reserved FROM medicine_inventory WHERE variant_id=11').first()).reserved,0);globalThis.fetch=async()=>Response.json({id:'cs_test_retry_v2',url:'https://checkout.stripe.test/retry'});const next=await call(env,'/v1/commerce/medicine-checkout','POST',{variantId:11,assessmentTermsAccepted:true,checkoutRequestId:crypto.randomUUID()});assert.equal(next.status,201);assert.equal((await DB.prepare('SELECT reserved FROM medicine_inventory WHERE variant_id=11').first()).reserved,1);}finally{globalThis.fetch=realFetch;DB.close()}});

test('Start Here handoff changes only the enabled treatment page and preserves its approved HTML',async()=>{
 const html='<html><body><header>LOCKED HEADER</header><h1>Based on your answers, this could perhaps work for you…</h1><footer>LOCKED FOOTER</footer></body></html>';
 const original=()=>new Response(html,{headers:{'content-type':'text/html','etag':'source'}});
 for(const [path,env]of [['/treatment-order',{}],['/start-here',{MEDICINE_INTAKE_V2_ENABLED:'true'}],['/',{MEDICINE_INTAKE_V2_ENABLED:'true'}]]){const r=original();assert.equal(await withPatientStartHere(r,new Request('https://shiftsometimber.co.uk'+path),env),r)}
 const changed=await withPatientStartHere(original(),new Request('https://shiftsometimber.co.uk/treatment-order'),{MEDICINE_INTAKE_V2_ENABLED:'true'});
 assert.equal(changed.headers.get('cache-control'),'no-store');assert.equal(changed.headers.get('etag'),null);
 assert.equal((await changed.text()).replace('<script src="/patient-start-here-v2.js" defer></script>',''),html);
});
