import test from 'node:test';import assert from 'node:assert/strict';
import {verifyProgrammeCloseout,PROGRAMME_CLOSEOUT_BASE,PROGRAMME_CLOSEOUT_SOURCE,PROGRAMME_CLOSEOUT_PATHS,PROGRAMME_CLOSEOUT_MAINTENANCE,PROGRAMME_LIVE_GATE,withoutProgrammeLiveGate,RECONCILIATION_MANIFEST} from '../release/approved-runtime-composition.mjs';
function fixture(){const c={proof:'EXACT_PROGRAMME_LIVE_CLOSEOUT_V1',base:PROGRAMME_CLOSEOUT_BASE,source:PROGRAMME_CLOSEOUT_SOURCE,maintenanceSource:'a'.repeat(40),paths:PROGRAMME_CLOSEOUT_PATHS,maintenancePaths:PROGRAMME_CLOSEOUT_MAINTENANCE,runtimeChanged:false,publicCopyChanged:false,clinicalAvailabilityChanged:false,customerDataChanged:false,stockChanged:false,memberBehaviourChanged:false,privacyAssertionsWeakened:false,liveProgrammeVerificationAdded:true,approvedCopyComparisonFixed:true,rollbackReceiptRun:37853151026};return{c,o:{head:'b'.repeat(40),read:()=> 'same',ancestor:()=>{},diff:(a,b)=>a===c.base?c.paths:a===c.source?c.maintenancePaths:[RECONCILIATION_MANIFEST],content:(ref,path)=>ref===c.source?'existing-guards\n'+PROGRAMME_LIVE_GATE:'existing-guards\n'}};}
test('finite Programme closeout source retains every prior production guard and adds the exact live verification',()=>{const {c,o}=fixture();assert.equal(verifyProgrammeCloseout(c,o),c);assert.equal(withoutProgrammeLiveGate('before\n'+PROGRAMME_LIVE_GATE+'after'),'before\nafter');});
test('all current closeout payload and maintenance blobs are checked before historical mappings',()=>{for(const path of [...PROGRAMME_CLOSEOUT_PATHS,...PROGRAMME_CLOSEOUT_MAINTENANCE]){const {c,o}=fixture();o.read=(ref,p)=>ref==='HEAD'&&p===path?'changed':'same';assert.throws(()=>verifyProgrammeCloseout(c,o),/drift/);}});
test('unrelated paths, missing ancestry, content changes, privacy weakening and removed production guards are rejected',()=>{
 for(const flag of ['runtimeChanged','publicCopyChanged','clinicalAvailabilityChanged','customerDataChanged','stockChanged','memberBehaviourChanged','privacyAssertionsWeakened']){const {c,o}=fixture();c[flag]=true;assert.throws(()=>verifyProgrammeCloseout(c,o));}
 for(const key of ['base','source','proof','rollbackReceiptRun']){const {c,o}=fixture();c[key]='unknown';assert.throws(()=>verifyProgrammeCloseout(c,o));}
 for(const bad of [[],['worker-entry-v6.js'],[...PROGRAMME_CLOSEOUT_PATHS,'private-records.mjs']]){const {c,o}=fixture();o.diff=()=>bad;assert.throws(()=>verifyProgrammeCloseout(c,o));}
 {const {c,o}=fixture();o.ancestor=()=>{throw Error('Missing ancestor')};assert.throws(()=>verifyProgrammeCloseout(c,o));}
 {const {c,o}=fixture();o.content=ref=>ref===c.source?'changed-guards\n'+PROGRAMME_LIVE_GATE:'existing-guards\n';assert.throws(()=>verifyProgrammeCloseout(c,o),/Only the additional exact/);}
 for(const w of ['missing',PROGRAMME_LIVE_GATE+PROGRAMME_LIVE_GATE,PROGRAMME_LIVE_GATE.replace('PROGRAMME_DAY_LIVE=true','PROGRAMME_DAY_LIVE=false')])assert.throws(()=>withoutProgrammeLiveGate(w));
});