import test from 'node:test';
import assert from 'node:assert/strict';
import {memoryDB} from '../preview/newsroom-discovery/memory-db.mjs';
import {ensureRadarSchema,prepareVerifiedRadarQueue,reviewRadarActionCore} from '../radar-integration-v1.js';
import {radarNewsPageRoutes} from '../radar-news-pages-v1.js';
import {parseAuthoritativeFeed} from '../radar-authoritative-scan-v1.js';
import {permittedPublisherMode,originalNoticePackage,applyPublisherFormat,publisherPackageError,originalNoticeEligibility,originalFeedFields,originalNoticeHtml,publisherAttributionHtml} from '../radar-permitted-content-v1.js';
import {sourceReusePolicy} from '../radar-source-policy-v1.js';
const now=()=>new Date().toISOString(),date=()=>new Date(Date.now()-86400000).toISOString();
const gphc=()=>({source_tier:1,authority:'GPhC',title:'Weight management: patient safety',url:'https://www.pharmacyregulation.org/news/fictional-proof',source_feed:'https://www.pharmacyregulation.org/rss',source_date:date(),retrieved_at:now(),summary:'Original fictional feed notice.',feed_original_title:'Weight management: patient safety',feed_original_text:'This fictional notice tests exact source wording. The apostrophe in patients’ is preserved. It contains no genuine clinical update.'});
const nice=()=>({source_tier:1,authority:'NICE',title:'Overweight and obesity management',url:'https://www.nice.org.uk/guidance/ng246',source_date:date(),retrieved_at:now(),summary:'This fictional source excerpt describes the scope of a guideline on overweight and obesity management. It does not provide new recommendations, announce a new approval or establish access to a particular service. Its only purpose here is to test supported editorial summarisation without publication of a real medical claim.'});
function row(source,status='ready_for_review'){return{id:1,status,region:'UK',headline:source.title,source_evidence_json:JSON.stringify([source]),verification_json:'{"verified":true}'}}
async function seed(source){const DB=memoryDB();await ensureRadarSchema(DB);const r=row(source,'verified');await DB.prepare('INSERT INTO radar_events(id,event_key,status,headline,region,regulator,source_evidence_json,verification_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(1,'fictional-publisher-1',r.status,r.headline,'UK',source.authority,r.source_evidence_json,r.verification_json,now(),now()).run();return DB}
const pkg=()=>({headline:'NICE guideline scope explained for UK readers',standfirst:'The guideline covers overweight and obesity management; this summary does not establish access to treatment.',article_markdown:'The source describes the scope of the guideline on overweight and obesity management. Its recommendations should be read in the original.',shift_take:'Readers can use the source as a starting point for understanding the subject, not a promise of access.',known_facts:[{claim:'The source describes the guideline scope.',source_url:'https://www.nice.org.uk/guidance/ng246'}],unknowns:['Individual access'],review_flags:[],seo:{description:'A short attributed overview of the guidance scope for UK readers, with the original source and its limitations.',slug:'nice-fictional-proof'}});
test('publisher permission does not require a second email for supported NICE guidance',()=>{assert.equal(sourceReusePolicy(row(nice())).ok,true);assert.equal(permittedPublisherMode(row(nice())),'nice_editorial_summary')});
test('GPhC requires original feed fields, not an old rewritten package or arbitrary website text',()=>{const s=gphc();assert.equal(sourceReusePolicy(row(s)).ok,true);delete s.feed_original_text;assert.equal(sourceReusePolicy(row(s)).ok,false);s.feed_original_text='x';s.source_feed='https://example.test';assert.equal(sourceReusePolicy(row(s)).ok,false)});
test('CKS, BNF, consultations, forged hosts and mixed publishers retain a hold',()=>{for(const url of ['https://cks.nice.org.uk/topics/x','https://bnf.nice.org.uk/x','https://www.nice.org.uk/guidance/indevelopment/gid123','https://nice.org.uk.evil.test/guidance/ng246']){assert.equal(sourceReusePolicy(row({...nice(),url})).ok,false)}const r=row(nice());r.source_evidence_json=JSON.stringify([nice(),gphc()]);assert.equal(sourceReusePolicy(r).ok,false)});
test('RSS decoding preserves curly punctuation and original wording without executing markup',()=>{const b='<title><![CDATA[Patients’ safety &amp; care]]></title><description><![CDATA[Original <strong>feed</strong> wording.]]></description>';assert.deepEqual(originalFeedFields(b),{feed_original_title:'Patients’ safety & care',feed_original_text:'Original feed wording.'});assert.deepEqual(originalFeedFields('<title>x</title><description><script>bad()</script></description>'),{});const items=parseAuthoritativeFeed('<rss><item>'+b+'<link>https://www.pharmacyregulation.org/news/test</link></item></rss>',{id:'gphc-news',authority:'GPhC',url:'https://www.pharmacyregulation.org/rss'});assert.equal(items[0].feed_original_title,'Patients’ safety & care')});
test('an edited GPhC sentence, added SHIFT take or extra destination is rejected',()=>{const r=row(gphc()),p=applyPublisherFormat(r,originalNoticePackage(r));assert.equal(publisherPackageError(r,p,{}),null);for(const k of ['headline','article_markdown','shift_take'])assert.ok(publisherPackageError(r,{...p,[k]:'Changed'},{}));assert.ok(publisherPackageError(r,{...p,destinations:['medicine_news','member_email']},{}));assert.ok(publisherPackageError(r,p,{medicine_id:'not-authorised'}))});
test('missing dates, stale sources, owner holds and changed review generations cannot auto-publish',()=>{for(const s of [{...gphc(),source_date:null},{...gphc(),retrieved_at:'2020-01-01'}]){const r=row(s),p=applyPublisherFormat(r,originalNoticePackage(r));assert.equal(originalNoticeEligibility(r,p).ok,false)}for(const extra of [{status:'hold'},{reviewed_by:'owner'},{source_review_generation:1}]){const r={...row(gphc()),...extra},p=applyPublisherFormat(r,originalNoticePackage(r));assert.equal(originalNoticeEligibility(r,p).ok,false)}});
test('GPhC goes through guarded preparation, approval and publication with zero AI calls',async()=>{const s=gphc(),DB=await seed(s);let ai=0;const result=await prepareVerifiedRadarQueue({DB,AI:{run:async()=>{ai++;throw Error('No GPhC AI rewrite')}},RADAR_SUPPRESS_NOTIFICATIONS:true},{limit:1});assert.equal(result.prepared[0].status,'published',JSON.stringify(result));assert.equal(ai,0);const r=await DB.prepare('SELECT * FROM radar_events WHERE id=1').first();assert.equal(r.medicine_patch_json,'{}');const p=JSON.parse(r.content_package_json);assert.equal(p.article_markdown,s.feed_original_text);assert.deepEqual(p.destinations,['medicine_news','sitemap']);assert.equal((await DB.prepare('SELECT COUNT(*) n FROM radar_medicines').first()).n,0);const html=originalNoticeHtml(r);assert.ok(html.includes('patients’'));assert.doesNotMatch(html,/SHIFT’s take|automated accuracy check/);assert.match(html,/GPhC/);assert.match(html,/original GPhC announcement/)});
test('NICE uses the normal independent accuracy check, with attribution and no registry mutation',async()=>{const DB=await seed(nice());let ai=0;const AI={run:async()=>({response:JSON.stringify(++ai===1?pkg():{decision:'PASS',claims_supported:true,attribution_correct:true,uncertainty_preserved:true,interpretation_separated:true,no_treatment_advice:true,no_promotion:true,no_substantial_copying:true,issues:[]})})};const result=await prepareVerifiedRadarQueue({DB,AI,RADAR_SUPPRESS_NOTIFICATIONS:true},{limit:1});assert.equal(result.prepared[0].status,'published',JSON.stringify(result));assert.equal(ai,2);const r=await DB.prepare('SELECT * FROM radar_events WHERE id=1').first();assert.equal(r.medicine_patch_json,'{}');assert.match(publisherAttributionHtml(r),/© NICE/);assert.match(publisherAttributionHtml(r),/NICE accepts no responsibility/);const old=globalThis.fetch;globalThis.fetch=async()=>new Response('<html><head></head><body><main>Shell</main></body></html>');try{const html=await(await radarNewsPageRoutes(new Request('https://shiftsometimber.co.uk/medicine-news/nice-fictional-proof'),{DB})).text();assert.match(html,/SHIFT’s take/);assert.match(html,/NICE source and attribution/)}finally{globalThis.fetch=old}});
test('NICE accuracy HOLD stays held and a bare publisher label never becomes source evidence',async()=>{const DB=await seed(nice());let n=0;const AI={run:async()=>({response:JSON.stringify(++n===1?pkg():{decision:'HOLD',issues:['Unsupported sentence']})})};await prepareVerifiedRadarQueue({DB,AI,RADAR_SUPPRESS_NOTIFICATIONS:true},{limit:1});assert.equal((await DB.prepare('SELECT status FROM radar_events WHERE id=1').first()).status,'ready_for_review');assert.equal(sourceReusePolicy({regulator:'NICE'}).ok,false)});
