import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createHmac} from 'node:crypto';
import {commerceStripeRoutes} from '../commerce-stripe-v1.js';
import {mkdirSync,writeFileSync} from 'node:fs';
function fixture(){
 const sql=new DatabaseSync(':memory:');
 sql.exec(`CREATE TABLE products(id INTEGER PRIMARY KEY,name TEXT);CREATE TABLE orders(id INTEGER PRIMARY KEY,order_number TEXT,product_id INTEGER,quantity INTEGER,customer_email TEXT,customer_name TEXT,status TEXT,payment_status TEXT,subtotal_pence INTEGER,total_pence INTEGER,updated_at TEXT);CREATE TABLE commerce_order_details(order_id INTEGER PRIMARY KEY,size TEXT,stripe_payment_intent_id TEXT,shipping_name TEXT,shipping_address_json TEXT,stripe_payment_status TEXT,last_stripe_event_type TEXT,updated_at TEXT);CREATE TABLE commerce_order_items(id INTEGER PRIMARY KEY,order_id INTEGER,product_id INTEGER,sku TEXT,product_name TEXT,colour TEXT,size TEXT,quantity INTEGER,unit_price_pence INTEGER);CREATE TABLE commerce_inventory(product_id INTEGER,size TEXT,stock_on_hand INTEGER,reserved INTEGER,updated_at TEXT);CREATE TABLE stripe_events(stripe_event_id TEXT PRIMARY KEY,event_type TEXT,payload TEXT,received_at TEXT,processed_at TEXT,processing_error TEXT);INSERT INTO products VALUES(1,'Fictional shirt');INSERT INTO orders VALUES(1,'SYNTHETIC-ORDER',1,1,'fictional@example.test','Fictional','new','pending',1000,1299,NULL);INSERT INTO commerce_order_details(order_id,size) VALUES(1,'L');INSERT INTO commerce_inventory VALUES(1,'L',10,2,NULL);CREATE TABLE order_reference_registry(order_number TEXT PRIMARY KEY,channel TEXT,source_table TEXT,source_id INTEGER,user_id INTEGER,status TEXT,created_at TEXT,updated_at TEXT);INSERT INTO order_reference_registry(order_number,status) VALUES('SYNTHETIC-ORDER','pending');`);
 const state={failAt:null,emails:[],mailFailure:false};
 const DB={async exec(s){for(const line of s.split('\n').map(x=>x.trim()).filter(Boolean))sql.exec(line)},prepare(s){return {sql:s,args:[],bind(...args){return {...this,args}},async first(){return sql.prepare(this.sql).get(...this.args)||null},async all(){return {results:sql.prepare(this.sql).all(...this.args)}},async run(){return {meta:sql.prepare(this.sql).run(...this.args)}}}},async batch(ss){sql.exec('BEGIN');try{const rr=[];for(let i=0;i<ss.length;i++){if(i===state.failAt){state.failAt=null;throw Error('injected write failure')}rr.push({meta:sql.prepare(ss[i].sql).run(...ss[i].args)})}sql.exec('COMMIT');return rr}catch(e){sql.exec('ROLLBACK');throw e}}};
 const env={DB,STRIPE_WEBHOOK_SECRET:'fictional-secret',EMAIL:{async send(m){state.emails.push(m);if(state.mailFailure)throw Error('accepted then connection lost');return {id:'provider-'+state.emails.length}}}};
 async function send(id='evt_one',type='checkout.session.completed',overrides={}){const event={id,type,data:{object:{metadata:{order_number:'SYNTHETIC-ORDER'},payment_status:'paid',payment_intent:'pi_fictional'}},...overrides},payload=JSON.stringify(event),t=Math.floor(Date.now()/1000),sig=createHmac('sha256',env.STRIPE_WEBHOOK_SECRET).update(t+'.'+payload).digest('hex');const r=await commerceStripeRoutes(new Request('https://example.test/v1/commerce/stripe/webhook',{method:'POST',headers:{'stripe-signature':`t=${t},v1=${sig}`},body:payload}),env,{});return {status:r.status,body:await r.json()}}
 return {sql,state,env,send,read(){return {order:sql.prepare('SELECT payment_status FROM orders').get()?.payment_status,inventory:sql.prepare('SELECT stock_on_hand,reserved FROM commerce_inventory').get(),reference:sql.prepare('SELECT status FROM order_reference_registry').get()?.status,events:sql.prepare('SELECT processed_at,processing_error FROM stripe_events').all()}}};
}
for(let i=0;i<8;i++)test('shop settlement rolls back at '+i+' and same event recovers once',async()=>{const f=fixture();f.state.failAt=i;assert.equal((await f.send()).status,500);assert.equal(f.read().order,'pending');assert.equal(f.read().inventory.stock_on_hand,10);assert.equal(f.read().events[0].processed_at,null);assert.equal((await f.send()).status,200);assert.equal(f.read().order,'paid');assert.equal(f.read().inventory.stock_on_hand,9);assert.equal(f.read().inventory.reserved,1);assert.equal(f.read().reference,'paid');assert.equal((await f.send()).body.duplicate,true);assert.equal(f.state.emails.length,2)});
test('concurrent distinct successes settle once and claim each receipt once',async()=>{const f=fixture();await Promise.all([f.send('evt_a'),f.send('evt_b'),f.send('evt_c')]);assert.equal(f.read().inventory.stock_on_hand,9);assert.equal(f.read().inventory.reserved,1);assert.equal(f.state.emails.length,2)});
test('repeated failure releases once; late success does not release another reservation',async()=>{const f=fixture();await f.send('evt_fail','checkout.session.expired');await f.send('evt_fail2','checkout.session.async_payment_failed');assert.equal(f.read().inventory.reserved,1);await f.send();assert.equal(f.read().inventory.reserved,1);assert.equal(f.read().inventory.stock_on_hand,9);assert.equal(f.read().reference,'paid')});
test('late failure and refunded callbacks preserve terminal payment and reservations',async()=>{const f=fixture();await f.send();await f.send('evt_late','payment_intent.payment_failed');assert.equal(f.read().reference,'paid');assert.equal(f.read().inventory.reserved,1);f.sql.exec("UPDATE orders SET payment_status='refunded'");await f.send('evt_after_refund');assert.equal(f.read().order,'refunded');assert.equal(f.read().inventory.stock_on_hand,9)});
test('missing order is not acknowledged as completed',async()=>{const f=fixture();f.sql.exec('DELETE FROM orders');assert.equal((await f.send()).status,500);assert.equal(f.read().events[0].processed_at,null)});
test('missing email binding leaves durable pending receipts without undoing payment',async()=>{const f=fixture();delete f.env.EMAIL;await f.send();assert.equal(f.read().order,'paid');const rows=f.sql.prepare('SELECT state,last_error FROM commerce_receipt_delivery').all();assert.equal(rows.length,2);assert.ok(rows.every(r=>r.state==='pending'&&r.last_error==='email_binding_unavailable'))});
test('uncertain mail acceptance is recorded separately and never automatically resent',async()=>{const f=fixture();f.state.mailFailure=true;await f.send();assert.equal(f.read().order,'paid');assert.ok(f.sql.prepare('SELECT state FROM commerce_receipt_delivery').all().every(r=>r.state==='uncertain'));await f.send('evt_again');assert.equal(f.state.emails.length,2)});
test('wrong provider mode is rejected before recording or settling an event',async()=>{const f=fixture();assert.equal((await f.send('evt_live','checkout.session.completed',{livemode:true})).status,400);assert.equal(f.read().events.length,0);assert.equal(f.read().order,'pending')});
test('confirmed order alerts go to orders exactly once across duplicate and distinct paid callbacks',async()=>{
 const f=fixture();f.env.ORDER_NOTIFICATION_EMAIL='orders@shiftsometimber.co.uk';f.env.ADMIN_NOTIFICATION_EMAIL='hq@shiftsometimber.co.uk';await f.send();await f.send();await f.send('evt_second_paid');
 const alerts=f.state.emails.filter(m=>m.to==='orders@shiftsometimber.co.uk');assert.equal(alerts.length,1);assert.match(alerts[0].subject,/NEW ORDER.*SYNTHETIC-ORDER/);assert.match(alerts[0].text,/12\.99/);assert.equal(f.state.emails.filter(m=>m.to==='hq@shiftsometimber.co.uk').length,0);assert.equal(f.state.emails.filter(m=>m.to==='fictional@example.test').length,1);
 if(process.env.ALERT_PROOF_DIR){mkdirSync(process.env.ALERT_PROOF_DIR,{recursive:true});writeFileSync(process.env.ALERT_PROOF_DIR+'/order-preview.json',JSON.stringify(alerts[0],null,2));writeFileSync(process.env.ALERT_PROOF_DIR+'/order-preview.html',alerts[0].html)}
});
