import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {sourceReusePolicy,sourceReuseFailure,niceGuidanceStage,niceTopicListingLinks,scanNiceTopic,recentAuthorityCheck,migrateGphcFeed,NICE_TOPIC,GPHC_RSS} from '../radar-source-policy-v1.js';
function dbFixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());db.exec("CREATE TABLE radar_sources(id TEXT PRIMARY KEY,url TEXT,adapter TEXT,authority TEXT,region TEXT,event_type TEXT,tier INTEGER,confidence INTEGER,active INTEGER,updated_at TEXT);CREATE TABLE radar_scan_runs(id INTEGER PRIMARY KEY,source_id TEXT,source_url TEXT,status TEXT,detail_json TEXT,completed_at TEXT)");return {db,prepare(sql){let args=[];return{bind(...a){args=a;return this},async first(){return db.prepare(sql).get(...args)||null},async run(){const r=db.prepare(sql).run(...args);return{meta:{changes:Number(r.changes)}}}}}}}
test('NICE and GPhC declarations and canonical hosts enforce a separate permission gate',()=>{for(const row of [{regulator:'GPhC'},{authority:'NICE'},{source_evidence_json:JSON.stringify([{source_tier:1,url:'https://www.pharmacyregulation.org/news/update'}])},{source_evidence_json:JSON.stringify([{url:'https://www.nice.org.uk/guidance/ng246'}])}]){assert.equal(sourceReusePolicy(row).ok,false);assert.equal(sourceReuseFailure(row).error,'source_reuse_review_required')}});
test('mixed-source evidence cannot bypass the most restrictive publisher',()=>{const p=sourceReusePolicy({source_evidence_json:JSON.stringify([{authority:'MHRA',url:'https://www.gov.uk/example'},{authority:'NICE'},{publisher:'GPhC'}])});assert.deepEqual(p.publishers,['GPhC','NICE']);assert.equal(p.ok,false)});
test('unrelated sources retain their existing eligibility; impostor domains are not misidentified',()=>{for(const url of ['https://www.gov.uk/news/example','https://nice.org.uk.attacker.invalid/a','https://attacker.invalid/nice.org.uk'])assert.equal(sourceReusePolicy({url}).ok,true)});
test('GPhC feed migration is exact, idempotent and preserves paused/custom source settings',async t=>{const D=dbFixture(t);D.db.exec("INSERT INTO radar_sources VALUES('gphc-news','https://www.pharmacyregulation.org/about-us/news-and-updates','html','GPhC','UK','uk_pharmacy_regulation',1,99,0,'old')");await migrateGphcFeed(D);let row=D.db.prepare('SELECT * FROM radar_sources').get();assert.equal(row.url,GPHC_RSS);assert.equal(row.adapter,'feed');assert.equal(row.active,0);await migrateGphcFeed(D);assert.deepEqual(D.db.prepare('SELECT * FROM radar_sources').get(),row);D.db.prepare('UPDATE radar_sources SET url=?,adapter=?').run('https://www.pharmacyregulation.org/custom','html');row=D.db.prepare('SELECT * FROM radar_sources').get();await migrateGphcFeed(D);assert.deepEqual(D.db.prepare('SELECT * FROM radar_sources').get(),row)});
test('recent refusal is retained as failure without a new source request',async t=>{const D=dbFixture(t),time='2026-09-19T14:00:00.000Z',source={id:'gphc-news',url:GPHC_RSS};D.db.prepare('INSERT INTO radar_scan_runs VALUES(1,?,?,?,?,?)').run(source.id,source.url,'failed','{"error":"http_403"}',time);const r=await recentAuthorityCheck(D,source,Date.parse(time)+900000);assert.equal(r.ok,false);assert.equal(r.skipped,true);assert.equal(r.error,'http_403');assert.equal(r.checkedAt,time);assert.equal(await recentAuthorityCheck(D,source,Date.parse(time)+3600000),null);assert.equal(await recentAuthorityCheck(D,{...source,url:'https://example.test'},Date.parse(time)+900000),null)});
test('cached successful check is labelled and is not counted as new discovery',async t=>{const D=dbFixture(t);D.db.prepare('INSERT INTO radar_scan_runs VALUES(1,?,?,?,?,?)').run('gphc-news',GPHC_RSS,'completed','{}','2026-09-19T14:00:00Z');const r=await recentAuthorityCheck(D,{id:'gphc-news',url:GPHC_RSS},Date.parse('2026-09-19T14:30:00Z'));assert.equal(r.ok,true);assert.equal(r.newEvents,0);assert.equal(r.skipped,true)});
test('NICE discovery separates consultations, work in development and published links requiring status checks',()=>{assert.equal(niceGuidanceStage({url:'https://www.nice.org.uk/guidance/indevelopment/gid-ta123'}),'in_development');assert.equal(niceGuidanceStage({url:'https://www.nice.org.uk/guidance/ng246',title:'Draft guidance consultation closes'}),'consultation');assert.equal(niceGuidanceStage({url:'https://www.nice.org.uk/guidance/ng246'}),'published_guidance_link_status_requires_check');assert.equal(niceGuidanceStage({url:'https://www.nice.org.uk/guidance/ng246',title:'This guidance has been withdrawn'}),'withdrawal_or_replacement_reported');assert.equal(niceGuidanceStage({url:'https://www.nice.org.uk/guidance/published'}),'unknown');assert.equal(niceGuidanceStage({url:'https://other.test/guidance/ng246'}),'unknown')});
test('topic navigation follows only supplied same-host filtered listings, with a hard bound',()=>{const html='<a href="/guidance/published?topic=obesity&amp;ndt=Guidance">Published</a><a href="https://evil.test/guidance/published?topic=x">Bad</a><a href="/guidance/published">Unfiltered</a>';assert.deepEqual(niceTopicListingLinks(html),['https://www.nice.org.uk/guidance/published?topic=obesity&ndt=Guidance']);assert.equal(niceTopicListingLinks(Array.from({length:8},(_,i)=>`<a href="/guidance/published?topic=${i}">x</a>`).join('')).length,4)});
test('source URL is the exact link supplied by NICE, not stale double-hyphen route',()=>{assert.equal(NICE_TOPIC,'https://www.nice.org.uk/guidance/lifestyle-and-wellbeing/diet-nutrition-and-obesity')});
test('topic fetch does not retry refusals or classify empty pages as success',async()=>{let calls=0;await assert.rejects(scanNiceTopic(async()=>{calls++;return new Response('Forbidden',{status:403})},()=>[]),/http_403/);assert.equal(calls,1);await assert.rejects(scanNiceTopic(async()=>new Response('<html><a href="/">Home</a></html>'),()=>[]),/guidance_links_missing/)});
test('topic discovered links deduplicate while retaining honest stage metadata',async()=>{const item={url:'https://www.nice.org.uk/guidance/ng246',title:'Obesity management'};const rows=await scanNiceTopic(async()=>new Response('<a href="/guidance/ng246">Obesity management</a>'),()=>[item,item]);assert.equal(rows.length,1);assert.equal(rows[0].guidance_stage,'published_guidance_link_status_requires_check');assert.equal(rows[0].source_date,undefined)});
