import test from 'node:test';import assert from 'node:assert/strict';
import {verifySupportContent,verifyReconciledRelease,SUPPORT_CONTENT_BASE as base,SUPPORT_CONTENT_SOURCE as source,SUPPORT_CONTENT_PATHS as paths,SUPPORT_CONTENT_MAINTENANCE as maintenancePaths,RECONCILIATION_MANIFEST} from '../release/approved-runtime-composition.mjs';
const flags=['homepageChanged','campaignChanged','organicGrowthChanged','watchChanged','memberDataChanged','checkoutChanged','externalCommunicationsSent','clinicalGatesChanged','existingGatesWeakened'];
const receipt=()=>({proof:'EXACT_SUPPORT_CONTENT_DELIVERY_V1',base,source,paths:[...paths],maintenancePaths:[...maintenancePaths],maintenanceSource:'a'.repeat(40),ownerApproval:'Move the substantive content audit forward now; implement authorised improvements and verify affected mobile/desktop journeys',...Object.fromEntries(flags.map(k=>[k,false]))});
const opts=()=>({head:'b'.repeat(40),read:()=> 'same',content:()=> '{}',ancestor:()=>{},diff:(a,b)=>a===base?[...paths]:a===source?[...maintenancePaths]:[RECONCILIATION_MANIFEST]});
test('only finite support payload and maintenance accepted',()=>verifySupportContent(receipt(),opts()));
test('scope, source and prior receipts cannot drift',()=>{for(const patch of [{source:'f'.repeat(40)},{base:'f'.repeat(40)},{paths:[...paths,'other']},...flags.map(k=>({[k]:true}))])assert.throws(()=>verifySupportContent({...receipt(),...patch},opts()));for(const ref of [base,source,'a'.repeat(40)]){const o=opts(),diff=o.diff;o.diff=(a,b)=>a===ref?[...diff(a,b),'other']:diff(a,b);assert.throws(()=>verifySupportContent(receipt(),o));}const o=opts();o.content=ref=>JSON.stringify({prior:ref===base?'approved':'changed'});assert.throws(()=>verifySupportContent(receipt(),o));});
test('every approved blob remains immutable',()=>{for(const path of [...paths,...maintenancePaths]){const o=opts();o.read=(ref,p)=>ref==='HEAD'&&p===path?'drift':'same';assert.throws(()=>verifySupportContent(receipt(),o),/source drift/);}});
test('current owner composition preserved',()=>{const c=verifyReconciledRelease();assert.equal(c.supportContentUpgrade.source,source);assert.equal(c.continuityContentUpgrade.source,'4e0a31692d1b11a512499575046fd2843394a18e');});
