import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {renderContinuityDocument} from '../../public-continuity.mjs';
import {reconcilePublicDocument,reconcileSitemap} from '../../public-shell-contract.mjs';
import '../../work/staging/prepare.mjs';
const dir='work/staging/generated',assets=dir+'/assets',base='https://shiftsometimber.co.uk';
const config=JSON.parse(readFileSync(dir+'/config.json'));
config.name='shift-stabilisation-preview';config.main='../../../preview/stabilisation/worker.mjs';
config.vars.SHIFT_ENVIRONMENT='stabilisation-preview-20260917';
config.vars.STAGING_EXPIRES_AT=new Date(Date.now()+3*86400000).toISOString();
config.vars.PREVIEW_SOURCE_SHA=process.env.PREVIEW_SOURCE_SHA||process.env.GITHUB_SHA||'local';
config.vars.WORK_V1_ENABLED='false';config.vars.WORK_PILOT_COMMISSIONED='false';
config.d1_databases=[];delete config.ai;delete config.routes;delete config.route;delete config.triggers;delete config.send_email;
writeFileSync(dir+'/config.json',JSON.stringify(config,null,2));
const response=await fetch(base+'/sitemap.xml');if(!response.ok)throw Error('Public sitemap unavailable');
const xml=await response.text();
const paths=[...new Set(['/', '/programme','/start-here','/about','/contact','/shop','/member-login','/shift-health','/shift-for-work','/shift-newsroom','/life-back','/mens-mental-health','/good-to-talk',...[...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>new URL(m[1])).filter(u=>u.origin===base&&!/^\/(?:v1|member|hq)\//.test(u.pathname)).map(u=>u.pathname)])];
const previewAccountNote='<aside id="preview-registration-note" style="margin:16px auto;padding:14px 18px;max-width:760px;border:1px solid #707762;border-radius:10px;background:#050505;color:#e7e3da;font:600 14px/1.5 Arial"><strong>Preview account only.</strong> Do not enter your real name or email here. <a id="preview-create-account" href="/staging/register?next=life-back" style="color:#e7e3da;text-decoration:underline">Create a fictional preview account</a>.</aside>';
const previewAccountGuard='<script data-preview-registration-guard>(()=>{const dest="/staging/register?next=life-back";const create=el=>{const text=((el.getAttribute("aria-label")||"")+" "+(el.textContent||"")).replace(/\\s+/g," ").trim().toLowerCase();return /(?:create(?: an?)? account|create my timber|register|sign up|join my timber)/.test(text)};document.addEventListener("click",event=>{const target=event.target instanceof Element?event.target.closest("a,button,[role=button]"):null;if(!target||target.id==="preview-create-account"||!create(target))return;event.preventDefault();event.stopImmediatePropagation();location.assign(dest)},true)})();</script>';
const report={checkedAt:new Date().toISOString(),pages:[],writes:0};
let cursor=0;
await Promise.all(Array.from({length:8},async()=>{while(cursor<paths.length){const path=paths[cursor++];const res=await fetch(base+path);if(!res.ok)throw Error(path+' '+res.status);const source=await res.text();if(!source.includes('<html'))throw Error(path+' is not a document');const sha256=createHash('sha256').update(source).digest('hex');let body=path==='/life-back'?renderContinuityDocument(source,path):source;body=reconcilePublicDocument(body,path);if(path==='/member-login'){body=/<main\b/i.test(body)?body.replace(/(<main\b[^>]*>)/i,'$1'+previewAccountNote):body.replace(/(<body\b[^>]*>)/i,'$1'+previewAccountNote);body=body.replace('</body>',previewAccountGuard+'</body>');}const file=assets+'/public-documents/'+(path==='/'?'index':path.slice(1))+'.html';mkdirSync(file.slice(0,file.lastIndexOf('/')),{recursive:true});writeFileSync(file,body);report.pages.push({path,status:res.status,sha256,before:source,after:body});}}));
const updated=reconcileSitemap(xml);writeFileSync(assets+'/public-sitemap.xml',updated);
const count=s=>[...s.matchAll(/<loc>/g)].length;
writeFileSync(dir+'/public-baseline.json',JSON.stringify({pages:report.pages.map(({after,...x})=>x),sitemap:xml,checkedAt:report.checkedAt}));
writeFileSync(dir+'/public-preview.json',JSON.stringify({pages:report.pages.map(({before,...x})=>x),sitemap:updated,checkedAt:report.checkedAt}));
writeFileSync(dir+'/public-summary.json',JSON.stringify({checkedAt:report.checkedAt,pages:report.pages.length,sitemapBefore:count(xml),sitemapAfter:count(updated),sitemapRemoved:['/shift-for-work'],sitemapAdded:[],productionWrites:0},null,2));
const ticker=await fetch(base+'/v1/radar/ticker');writeFileSync(assets+'/public-ticker.json',ticker.ok?await ticker.text():JSON.stringify({current:false,items:[]}));
console.log('Prepared '+report.pages.length+' read-only public documents. Sitemap '+count(xml)+' -> '+count(updated)+'. No production writes.');
