import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {renderContinuityDocument} from '../../public-continuity.mjs';
import {reconcilePublicDocument,reconcileSitemap} from '../../public-shell-contract.mjs';
import '../../work/staging/prepare.mjs';
const dir='work/staging/generated',assets=dir+'/assets',base='https://shiftsometimber.co.uk';
const config=JSON.parse(readFileSync(dir+'/config.json'));
config.name='shift-stabilisation-preview';config.main='../../../preview/stabilisation/worker.mjs';
config.vars.SHIFT_ENVIRONMENT='stabilisation-preview-20260917';
config.vars.STAGING_EXPIRES_AT=new Date(Date.now()+3*86400000).toISOString();
config.vars.PREVIEW_SOURCE_SHA=process.env.PREVIEW_SOURCE_SHA||process.env.GITHUB_SHA||'local';
config.vars.WORK_V1_ENABLED='false';config.vars.WORK_PILOT_COMMISSIONED='false';
config.d1_databases=[];delete config.ai;delete config.routes;delete config.route;delete config.triggers;delete config.send_email;
writeFileSync(dir+'/config.json',JSON.stringify(config,null,2));
const response=await fetch(base+'/sitemap.xml');if(!response.ok)throw Error('Public sitemap unavailable');
const xml=await response.text();
const paths=[...new Set(['/', '/programme','/start-here','/about','/contact','/shop','/member-login','/shift-health','/shift-for-work','/shift-newsroom','/life-back','/mens-mental-health','/good-to-talk',...[...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>new URL(m[1])).filter(u=>u.origin===base&&!/^\/(?:v1|member|hq)\//.test(u.pathname)).map(u=>u.pathname)])];
const report={checkedAt:new Date().toISOString(),pages:[],writes:0};
let cursor=0;
await Promise.all(Array.from({length:8},async()=>{while(cursor<paths.length){const path=paths[cursor++];const res=await fetch(base+path);if(!res.ok)throw Error(path+' '+res.status);const html=await res.text();if(!html.includes('<html'))throw Error(path+' is not a document');const sha256=createHash('sha256').update(html).digest('hex');let body=path==='/life-back'?renderContinuityDocument(html,path):html;body=reconcilePublicDocument(body,path);const file=assets+'/public-documents/'+(path==='/'?'index':path.slice(1))+'.html';mkdirSync(file.slice(0,file.lastIndexOf('/')),{recursive:true});writeFileSync(file,body);report.pages.push({path,status:res.status,sha256,before:html,after:body});}}));
const updated=reconcileSitemap(xml);writeFileSync(assets+'/public-sitemap.xml',updated);
const count=s=>[...s.matchAll(/<loc>/g)].length;
writeFileSync(dir+'/public-baseline.json',JSON.stringify({pages:report.pages.map(({after,...x})=>x),sitemap:xml,checkedAt:report.checkedAt}));
writeFileSync(dir+'/public-preview.json',JSON.stringify({pages:report.pages.map(({before,...x})=>x),sitemap:updated,checkedAt:report.checkedAt}));
writeFileSync(dir+'/public-summary.json',JSON.stringify({checkedAt:report.checkedAt,pages:report.pages.length,sitemapBefore:count(xml),sitemapAfter:count(updated),sitemapRemoved:['/shift-for-work'],sitemapAdded:[],productionWrites:0},null,2));
const ticker=await fetch(base+'/v1/radar/ticker');writeFileSync(assets+'/public-ticker.json',ticker.ok?await ticker.text():JSON.stringify({current:false,items:[]}));
console.log('Prepared '+report.pages.length+' read-only public documents. Sitemap '+count(xml)+' -> '+count(updated)+'. No production writes.');
