-- Shift master integration: additive only. Existing users/member_state remain authoritative.
CREATE TABLE IF NOT EXISTS shift_personal_state (user_id INTEGER PRIMARY KEY, profile_json TEXT NOT NULL DEFAULT '{}', inventory_json TEXT NOT NULL DEFAULT '[]', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS shift_plans (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,plan_type TEXT NOT NULL,starts_on TEXT NOT NULL,ends_on TEXT,version INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'active',plan_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS shift_plan_actions (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,plan_id INTEGER,local_date TEXT,domain TEXT NOT NULL,action_key TEXT NOT NULL,planned_json TEXT NOT NULL DEFAULT '{}',actual_json TEXT,status TEXT NOT NULL DEFAULT 'planned',completed_at TEXT);
CREATE TABLE IF NOT EXISTS shift_knowledge_nodes (id TEXT PRIMARY KEY,node_type TEXT NOT NULL,domain TEXT NOT NULL,label TEXT NOT NULL,data_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'active',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS shift_knowledge_edges (id INTEGER PRIMARY KEY AUTOINCREMENT,from_id TEXT NOT NULL,edge_type TEXT NOT NULL,to_id TEXT NOT NULL,weight REAL NOT NULL DEFAULT 1,data_json TEXT NOT NULL DEFAULT '{}',UNIQUE(from_id,edge_type,to_id));
CREATE TABLE IF NOT EXISTS shift_knowledge_sources (id INTEGER PRIMARY KEY AUTOINCREMENT,node_id TEXT NOT NULL,source_type TEXT NOT NULL,source_ref TEXT NOT NULL,authority INTEGER DEFAULT 50,verified_at TEXT,expires_at TEXT,provenance_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS shift_recommendation_log (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,intent TEXT NOT NULL,context_json TEXT NOT NULL,recommendation_json TEXT NOT NULL,explanation_json TEXT NOT NULL,safety_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS radar_events (id INTEGER PRIMARY KEY AUTOINCREMENT,event_key TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'detected',headline TEXT NOT NULL,region TEXT,regulator TEXT,event_type TEXT,relevance_score INTEGER DEFAULT 50,urgency_score INTEGER DEFAULT 50,confidence_score INTEGER DEFAULT 50,clinical INTEGER DEFAULT 1,requires_review INTEGER DEFAULT 1,source_evidence_json TEXT NOT NULL DEFAULT '[]',verification_json TEXT NOT NULL DEFAULT '{}',medicine_patch_json TEXT NOT NULL DEFAULT '{}',content_package_json TEXT NOT NULL DEFAULT '{}',review_note TEXT,reviewed_by TEXT,reviewed_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS radar_audit (id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER,action TEXT NOT NULL,actor TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS radar_medicines (id TEXT PRIMARY KEY,brand TEXT,generic_name TEXT,developer TEXT,mechanism_json TEXT NOT NULL DEFAULT '[]',formulation TEXT,global_stage TEXT,uk_regulatory_status TEXT,uk_commercial_status TEXT,nice_status TEXT,nhs_status TEXT,latest_update_text TEXT,radar_score INTEGER DEFAULT 50,regions_json TEXT NOT NULL DEFAULT '[]',last_verified_at TEXT,provenance_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS radar_freshness_claims (id INTEGER PRIMARY KEY AUTOINCREMENT,claim_key TEXT NOT NULL UNIQUE,event_id INTEGER,claim_text TEXT NOT NULL,source_url TEXT,status TEXT NOT NULL DEFAULT 'active',next_check_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_shift_plans_user ON shift_plans(user_id,status,created_at);
CREATE INDEX IF NOT EXISTS idx_kg_type ON shift_knowledge_nodes(node_type,domain);
CREATE INDEX IF NOT EXISTS idx_rec_user ON shift_recommendation_log(user_id,created_at);
CREATE INDEX IF NOT EXISTS idx_radar_queue ON radar_events(status,urgency_score,relevance_score);
CREATE INDEX IF NOT EXISTS idx_radar_freshness ON radar_freshness_claims(status,next_check_at);
