import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {notifyArticlePublication} from './publication-email.mjs';import {ARTICLE,oralHTML} from './oral-public.mjs';
function setup(){const sqlite=new DatabaseSync(':memory:');sqlite.exec('CREATE TABLE knowledge_articles(id INTEGER PRIMARY KEY,slug,title,author,body,status,publish_at); CREATE TABLE knowledge_article_reviews(article_id,decision);');sqlite.prepare('INSERT INTO knowledge_articles VALUES(3,?,?,?,?,?,?)').run(ARTICLE.slug,ARTICLE.title,ARTICLE.author,ARTICLE.body,'published','2026-09-20T16:00:00Z');sqlite.exec("INSERT INTO knowledge_article_reviews VALUES(3,'approved')");const DB={prepare(sql){let args=[];return{bind(...v){args=v;return this},async first(){return sqlite.prepare(sql).get(...args)},async run(){return{meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}}}}}};let sent=[];return{sqlite,sent,env:{DB,RADAR_PUBLICATION_EMAIL_TO:'owner@example.invalid',EMAIL:{async send(m){sent.push(m);return{messageId:'fixture'}}}}};}
const live=async()=>new Response(oralHTML('2026-09-20T16:00:00Z'));
test('email follows exact live proof and concurrent checks send only once',async()=>{const f=setup();try{await Promise.all([notifyArticlePublication(f.env,{fetcher:live}),notifyArticlePublication(f.env,{fetcher:live})]);assert.equal(f.sent.length,1);assert.equal(f.sent[0].to,'owner@example.invalid');assert.match(f.sent[0].text,/SHIFT’s take/);assert.equal(f.sqlite.prepare('SELECT status FROM knowledge_publication_email').get().status,'sent');await notifyArticlePublication(f.env,{fetcher:live});assert.equal(f.sent.length,1);}finally{f.sqlite.close()}});
test('404 never sends and can recover after publication propagates',async()=>{const f=setup();try{await notifyArticlePublication(f.env,{fetcher:async()=>new Response('missing',{status:404})});assert.equal(f.sent.length,0);await notifyArticlePublication(f.env,{fetcher:live});assert.equal(f.sent.length,1);}finally{f.sqlite.close()}});
test('drafts never send; ambiguous provider failure does not auto-resend',async()=>{const f=setup();try{f.sqlite.exec("UPDATE knowledge_articles SET status='draft'");await notifyArticlePublication(f.env,{fetcher:live});assert.equal(f.sent.length,0);f.sqlite.exec("UPDATE knowledge_articles SET status='published'");f.env.EMAIL.send=async()=>{f.sent.push('attempt');throw Error('provider timeout')};await notifyArticlePublication(f.env,{fetcher:live});await notifyArticlePublication(f.env,{fetcher:live});assert.equal(f.sent.length,1);assert.equal(f.sqlite.prepare('SELECT status FROM knowledge_publication_email').get().status,'delivery_unknown');}finally{f.sqlite.close()}});
import {createHash} from 'node:crypto';
test('fresh externally checked exact body can notify when Worker origin fetch is 404; stale or different proof cannot',async()=>{
 for(const kind of ['fresh','stale','changed']){const f=setup();try{
  f.sqlite.exec('CREATE TABLE knowledge_publication_live_proof(slug TEXT PRIMARY KEY,body_sha256,url,verified_at,workflow_sha)');
  f.sqlite.prepare('INSERT INTO knowledge_publication_live_proof VALUES(?,?,?,?,?)').run(ARTICLE.slug,createHash('sha256').update(kind==='changed'?'Other body':ARTICLE.body).digest('hex'),ARTICLE.proposed_url,new Date(Date.now()-(kind==='stale'?3600000:0)).toISOString(),'a'.repeat(40));
  await notifyArticlePublication(f.env,{fetcher:async()=>new Response('origin missing',{status:404})});assert.equal(f.sent.length,kind==='fresh'?1:0);
 }finally{f.sqlite.close()}}
});
