import receipt from './reviews/2026-10-03-credibility-improvements.json' with {type:'json'};
import evidenceDesk from './reviews/2026-10-03-evidence-desk-zp6590.json' with {type:'json'};
import srsd384Publication from './reviews/2026-10-04-authorised-srsd384.json' with {type:'json'};
import rgt075Publication from './reviews/2026-10-04-authorised-rgt075.json' with {type:'json'};
import vct220Publication from './reviews/2026-10-04-authorised-vct220.json' with {type:'json'};
import vk2735Maintenance from './reviews/2026-10-04-authorised-vk2735-maintenance.json' with {type:'json'};
import azelapragDiscontinuation from './reviews/2026-10-04-authorised-azelaprag-discontinuation.json' with {type:'json'};
import taldefgrobepRv8451 from './reviews/2026-10-04-authorised-taldefgrobep-rv8451.json' with {type:'json'};
import foundayoAttainMaintain from './reviews/2026-10-04-authorised-foundayo-attain-maintain.json' with {type:'json'};
import internationalMaintenanceWave from './reviews/2026-10-04-authorised-international-maintenance-wave.json' with {type:'json'};
import novoSpecialistWave from './reviews/2026-10-05-authorised-novo-specialist-wave.json' with {type:'json'};
import petrelintideZupreme from './reviews/2026-10-05-authorised-petrelintide-zupreme-registry.json' with {type:'json'};
import ribupatideSpecialistWave from './reviews/2026-10-05-authorised-ribupatide-specialist-wave.json' with {type:'json'};
import gzc8072Publication from './reviews/2026-10-05-authorised-gzc8072.json' with {type:'json'};
export const registrySources=[...receipt.registrySources,...evidenceDesk.registrySources,...srsd384Publication.registrySources,...rgt075Publication.registrySources,...vct220Publication.registrySources,...azelapragDiscontinuation.registrySources,...taldefgrobepRv8451.registrySources,...foundayoAttainMaintain.registrySources,...internationalMaintenanceWave.registrySources,...novoSpecialistWave.registrySources,...petrelintideZupreme.registrySources,...ribupatideSpecialistWave.registrySources,...gzc8072Publication.registrySources];
export const supportSources=receipt.supportSources;
export const credibilitySources=[...registrySources,...supportSources];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/London'}).format(new Date(v)):'Not verified';
export const sourceStatus=state=>({current:'Source unchanged',awaiting_review:'Source review required',check_delayed:'Source check delayed',verification_pending:'Verification pending'}[state]||'Verification pending');
export function evidenceLabel(s) {
  if (/^https:\/\/clinicaltrials.gov\/study\/NCT\d{8}$/.test(s.url)) return 'Trial registry record';
  if (/post-hoc|predicted risk|modelling/i.test(s.checkScope||'')) return 'Post-hoc analysis / modelling — see limitations';
  if (/preclinical/i.test(s.checkScope||'') && !/human/i.test(s.checkScope||'')) return 'Preclinical research — see limitations';
  if (s.evidenceType) return s.evidenceType;
  const host=new URL(s.url).hostname;
  if (host==='www.medicines.org.uk') return 'Official product information';
  if (host==='www.nice.org.uk' || host.endsWith('.nhs.uk')) return 'NICE / NHS guidance or information';
  if (host==='www.gov.uk') return 'Government / regulator communication';
  if (host==='pmc.ncbi.nlm.nih.gov' || host==='pubmed.ncbi.nlm.nih.gov') return 'Published research — see study design';
  return 'Original source — see findings and limitations';
}
export function registryEvidenceMarkup(link,health) {
  const s=registrySources.find(s=>s.url===link.url);
  if(!s)return null;
  const h=health.sources?.find(h=>h.id===s.id);
  const labels={NOT_YET_RECRUITING:'Not yet recruiting',RECRUITING:'Recruiting',ENROLLING_BY_INVITATION:'Enrolling by invitation',ACTIVE_NOT_RECRUITING:'Active, not recruiting',COMPLETED:'Completed',SUSPENDED:'Suspended',TERMINATED:'Terminated',WITHDRAWN:'Withdrawn',UNKNOWN:'Unknown'};
  const lifecycle=s.lifecycle,typedDate=d=>d?`${date(d.date)} (${d.type==='ACTUAL'?'actual':'estimated'})`:'Not recorded';
  return `<li><a href="${esc(s.url)}" rel="noopener noreferrer">${esc(link.title)}</a><small>Trial registry record · Last reviewed record: ${labels[lifecycle.status]||'Unknown'} · ${lifecycle.hasResults?'Results posted; outcomes need separate assessment':'No results posted at record-status review'} · First posted ${date(s.sourcePublishedAt)} · Updated ${date(s.sourceUpdatedAt)}</small><small>Start ${typedDate(lifecycle.start)} · Primary completion ${typedDate(lifecycle.primaryCompletion)} · Completion ${typedDate(lifecycle.completion)}${lifecycle.whyStopped?' · Stopping reason: '+esc(lifecycle.whyStopped):''}</small><small>Medical evidence summary reviewed ${date(link.reviewedAt)} · Record status reviewed ${date(s.reviewedAt)} · ${sourceStatus(h?.status)} · These are the dated reviewed facts, not a newly assessed live record. Status checks do not assess clinical outcomes.</small></li>`;
}
export function industryReviewFlag(entry,health,now=Date.now()) {
  const ids=[...entry.sourceIds,...registrySources.filter(s=>s.entryIds.includes(entry.id)).map(s=>s.id)];
  const states=ids.map(id=>health.sources?.find(s=>s.id===id)?.status||'verification_pending');
  const overdue=now-Date.parse(entry.reviewedAt)>7*24*60*60*1000;
  if(overdue)return '<p class="mw-flag">This evidence summary is due for factual review. A successful source check does not renew it.</p>';
  if(states.some(s=>s!=='current'))return '<p class="mw-flag">Some evidence checks need attention or are pending. This is the dated reviewed summary; check the original record for the latest position.</p>';
  return '';
}
export const changes=[
 {date:'2026-10-05',kind:'Once-weekly oral-peptide omission corrected',text:'Added GZC8072 after the primary registry confirmed recruiting Phase 1 research with an actual 2 September start. The later 126-person registry estimate and earlier 112-person sponsor plan remain distinct; clinical-trial permission, first dosing and secondary weight outcomes are not presented as results, marketing authorisation, UK access or supply. The catalogue now contains 98 programmes.',anchor:'industry-gzc8072'},
 {date:'2026-10-05',kind:'Ribupatide specialist-indication and formulation coverage',text:'Added seven monitored registry records across injection, tablet, adolescent, sleep-apnoea, cardiovascular and MASH research, plus Hengrui’s sponsor-reported PCOS/PMOS Phase 2 results. The older registry discrepancy, absent registry-posted results and indication-specific limitations remain explicit; the catalogue stays at 97 programmes.',anchor:'industry-ribupatide-injection'},
 {date:'2026-10-05',kind:'Sponsor announcement and registry status reconciled',text:'Added the three Phase III ZUPREME records to Petrelintide. The sponsor describes programme initiation, while all three records remain not yet recruiting with passed estimated start dates, no listed locations and no posted results; specialist diabetes and cardiovascular studies are not presented as completed benefits.',anchor:'industry-petrelintide'},
 {date:'2026-10-05',kind:'Programme-level Novo and specialist-indication correction',text:'Added recruiting first-in-human NNC0721-8060, corrected NNC0662-0419 from a single completed Phase 1 record to its six-record programme including two Phase 2 obesity studies and a separate type 2 diabetes study, and added survodutide type 2 diabetes Phase 3 research. None of the reviewed records has posted results, and specialist-indication research is not presented as UK authorisation or completed weight-management evidence. The catalogue now contains 97 programmes.',anchor:'industry-nnc07218060'},
 {date:'2026-10-04',kind:'International maintenance and combination evidence',text:'Added the separately staged ZYNERGY petrelintide–enicepatide combination and monitored ASCEND-1 and ACCOMPLISH-2 registry records. Estimated dates are not treated as completed events; none of the three records has posted results. The catalogue now contains 96 programmes.',anchor:'industry-zynergy-petrelintide-enicepatide'},
 {date:'2026-10-04',kind:'Switching and maintenance evidence',text:'Added the peer-reviewed ATTAIN-MAINTAIN study and its monitored registry lifecycle to Foundayo. The US trial used an investigational capsule and placebo rescue design after injectable tirzepatide or semaglutide; it is not a UK dosing or switching recommendation.',anchor:'foundayo'},
 {date:'2026-10-04',kind:'Muscle-preservation and oral discovery',text:'Added taldefgrobep alfa as active, not-recruiting Phase 2 research with an automatically monitored registry lifecycle, and RV-8451 as a separate preclinical oral GLP-1 programme. Estimated completion and planned IND timing are not treated as completed results. The catalogue now contains 95 programmes.',anchor:'industry-taldefgrobep-alfa'},
 {date:'2026-10-04',kind:'Discontinued programme added',text:'Added azelaprag after primary review of the terminated STRIDES Phase 2 study and BioAge’s later programme termination. The registry has no posted results; no efficacy or muscle-preservation outcome is claimed. The catalogue now contains 93 programmes.',anchor:'industry-azelaprag'},
 {date:'2026-10-04',kind:'Maintenance evidence added',text:'Added Viking’s sponsor-reported VK2735 maintenance study after full primary-source review. Monthly and every-other-week regimens remain investigational; the 12-week maintenance period does not establish long-term durability or an approved dosing schedule.',anchor:'industry-vk2735'},
 {date:'2026-10-04',kind:'International omission corrected',text:'Added CX11/VCT220 after primary review of completed Chinese Phase II and III records, a completed US Phase II record and a separate active hypertension study. Sponsor-reported topline results, the 246-versus-250 US enrolment discrepancy and planned global Phase III remain explicit. The catalogue now contains 92 programmes.',anchor:'industry-vct220'},
 {date:'2026-10-04',kind:'Older omission corrected',text:'Added RGT-075 after primary review of its completed Phase 2a and COMO-1 Phase 2b records. Neither registry has posted results, and no Phase 3 start is inferred. The catalogue now contains 91 programmes.',anchor:'industry-rgt075'},
 {date:'2026-10-04',kind:'Muscle-preservation discovery',text:'Added ART27.13 as a non-clinical GLP-1 companion exploration. Its separate Phase 1/2 cancer-cachexia programme is retained only as context, not as human obesity or muscle-preservation evidence. The catalogue now contains 90 programmes.',anchor:'industry-art2713'},
 {date:'2026-10-04',kind:'Modality discovery',text:'Added preclinical RJVA-002 as an obesity gene-therapy programme, explicitly limited to mouse evidence. The separate Revita device procedure and type 2 diabetes RJVA-001 programme are not silently counted as medicines coverage. The catalogue now contains 89 programmes.',anchor:'industry-rjva002'},
 {date:'2026-10-04',kind:'Smaller-developer discovery',text:'Added SRSD384 with the sponsor-reported first participant and the older conflicting not-yet-recruiting registry status both retained. No human muscle-preservation benefit is claimed. The catalogue now contains 88 programmes.',anchor:'industry-srsd384'},
 {date:'2026-10-03',kind:'Evidence and discovery',text:'Added ZP6590 with its conflicting pipeline narrative retained, dated trial lifecycle details, developer and mechanism search, a source-review queue and manual-monitoring gaps. The catalogue now contains 87 programmes.',anchor:'watch-evidence-desk'},
 {date:'2026-10-03',kind:'Coverage and usability',text:'Added checks for 67 linked trial records, a regulator safety notice, UK nation access context, evidence labels and this change history. The catalogue remains 86 programmes.',anchor:'how-we-check'},
 {date:'2026-10-03',kind:'Research additions',text:'Added VK3019 Phase 1 and AT673 with semaglutide Phase 2 summaries. Neither record has posted results.',anchor:'industry-vk3019'},
 {date:'2026-10-03',kind:'Correction',text:'Clarified Wegovy injection’s separate UK MASH indication and the pending NICE appraisal. UK authorisation does not confirm NHS England MASH access.',anchor:'wegovy-injection'},
 {date:'2026-10-03',kind:'Evidence clarification',text:'Added the Foundayo ATTAIN-1 analysis as predicted-risk modelling, not observed prevention of diabetes or cardiovascular events.',anchor:'foundayo'},
];
export function credibilityMarkup(health={}) {
 const source=id=>{const s=supportSources.find(s=>s.id===id),h=health.sources?.find(h=>h.id===id);return `<p><a href="${esc(s.url)}">${esc(s.title)}</a><small>Published ${date(s.sourcePublishedAt)}${s.sourceUpdatedAt?' · Updated '+date(s.sourceUpdatedAt):''} · Reviewed ${date(s.reviewedAt)} · ${sourceStatus(h?.status)}</small></p>`;};
 return `<section id="watch-changes" class="mw-overview"><h2>What changed?</h2><p>Recent additions and corrections. Each item keeps its own evidence and review date.</p><ul>${changes.map(c=>`<li><strong>${date(c.date)} · ${esc(c.kind)}</strong><p>${esc(c.text)} <a href="/treatment-centre/medicines-watch#${esc(c.anchor)}">View the reference ↓</a></p></li>`).join('')}</ul></section>
 <section id="watch-safety" class="mw-overview"><h2>Safety updates matter too</h2><p>Weight-management medicines are prescribed medicines. New research and approvals do not remove the need to understand risks.</p><p>MHRA’s 29 January 2026 notice strengthened warnings about acute pancreatitis with GLP-1 and GLP-1/GIP medicines, including rare severe and fatal reports. Its patient advice is to seek urgent medical attention for severe, persistent abdominal pain, which may radiate to the back and come with nausea or vomiting.</p>${source('mhra-glp1-pancreatitis-20260129')}<p><a href="https://yellowcard.mhra.gov.uk/">Report suspected side effects through MHRA Yellow Card</a>. Reporting does not replace urgent medical care. This is one reviewed safety notice, not a complete list of risks; read the product leaflet and speak to your prescriber or pharmacist.</p></section>
 <section id="watch-uk-access" class="mw-overview"><h2>NHS access depends on where you live</h2><p>The medicine cards describe England. These additional national sources describe different pathways; a recommendation or announcement does not prove local appointments, prescribing capacity or pharmacy stock. This first access comparison concerns weight management, principally tirzepatide; it does not establish access for every medicine or indication.</p><div class="mw-card-grid"><section class="mw-cell"><h3>Scotland</h3><p>SMC accepted tirzepatide for restricted weight-management use in June 2024. Its public summary describes the eligible group; an individual’s suitability and local pathway still need checking.</p>${source('scotland-tirzepatide-access')}</section><section class="mw-cell"><h3>Wales</h3><p>The circular updated 7 July 2026 describes specialist weight-management prescribing, with specified exceptions for suitably competent prescribers in urgent clinical circumstances and approved innovation proposals. This is not general GP access for everyone meeting NICE criteria.</p>${source('wales-weight-access')}</section><section class="mw-cell"><h3>Northern Ireland</h3><p>The 29 June 2026 announcement planned the first phase of the Regional Obesity Management Service for autumn 2026, prioritising highest clinical need. That dated plan does not confirm the service is open or medicine is available now. Current operational access remains unverified here; check with your HSC team.</p>${source('ni-weight-access')}</section></div></section>`;
}
