import test from 'node:test';
import assert from 'node:assert/strict';
import {industry,industrySources} from './industry.mjs';
import {registrySources} from './credibility.mjs';
import {medicines,sources} from './data.mjs';
import {industryMarkup} from './industry-page.mjs';
import {discoveryDomains,queriesForDate,summariseDiscovery} from './discovery.mjs';
import evidence from './reviews/2026-09-29-industry-expansion.json' with {type:'json'};
import hrs1596Review from './reviews/2026-09-30-hrs1596-discovery.json' with {type:'json'};
import continuingReview from './reviews/2026-09-30-emugrobart-petrelintide-discovery.json' with {type:'json'};
import env308Review from './reviews/2026-09-30-env308-discovery.json' with {type:'json'};
import globeNewswireRepair from './reviews/2026-09-30-globenewswire-access-repair.json' with {type:'json'};
import berobenatideReview from './reviews/2026-09-30-berobenatide-vesper6.json' with {type:'json'};
import eloraTZPReview from './reviews/2026-10-01-eloratzp-phase2b.json' with {type:'json'};
import kaineticReview from './reviews/2026-10-01-kainetic-enrolment.json' with {type:'json'};
import macupatideReview from './reviews/2026-10-01-macupatide-discovery.json' with {type:'json'};
import broaderReview from './reviews/2026-10-01-authorised-broader-discovery.json' with {type:'json'};
import synt101Correction from './reviews/2026-10-01-synt101-mad-correction.json' with {type:'json'};
import internationalOmissions from './reviews/2026-10-02-authorised-international-omissions.json' with {type:'json'};
import abbvAsc30TernBimagrumab from './reviews/2026-10-02-authorised-abbv-asc30-tern-bimagrumab.json' with {type:'json'};
import registryOmissions from './reviews/2026-10-02-authorised-registry-omissions.json' with {type:'json'};
import enobosarmSemaglutide from './reviews/2026-10-02-authorised-enobosarm-semaglutide.json' with {type:'json'};
import pfizerPdfRepair from './reviews/2026-10-02-pfizer-pdf-monitor-repair.json' with {type:'json'};
import expandedRegistryWave from './reviews/2026-10-02-authorised-expanded-registry-wave.json' with {type:'json'};
import semaglutideSpecialistTrials from './reviews/2026-10-02-authorised-semaglutide-specialist-trials.json' with {type:'json'};
import glimrCopd from './reviews/2026-10-02-authorised-glimr-copd.json' with {type:'json'};
import specialistRegistryFollowup from './reviews/2026-10-02-authorised-specialist-registry-followup.json' with {type:'json'};
import switchingStudies from './reviews/2026-10-02-authorised-switching-studies.json' with {type:'json'};
import na931Publication from './reviews/2026-10-02-authorised-na931.json' with {type:'json'};
import earlierEloraNa931Proposal from './reviews/2026-09-30-eloratzp-na931-discovery.json' with {type:'json'};
import amylinMetabolicFollowup from './reviews/2026-10-03-authorised-amylin-metabolic-followup.json' with {type:'json'};
import nct05713799Correction from './reviews/2026-10-05-authorised-nct05713799-start-correction.json' with {type:'json'};
import azd1043Publication from './reviews/2026-10-03-authorised-azd1043.json' with {type:'json'};
import seleneCorrection from './reviews/2026-10-03-authorised-azd6234-selene.json' with {type:'json'};
import wve007Publication from './reviews/2026-10-03-authorised-wve007.json' with {type:'json'};
import specialistRegistryWave from './reviews/2026-10-03-authorised-specialist-registry-wave.json' with {type:'json'};
import leanMassEnergyFollowup from './reviews/2026-10-03-authorised-lean-mass-energy-followup.json' with {type:'json'};
import vikingAntagFollowup from './reviews/2026-10-03-authorised-vk3019-at673.json' with {type:'json'};
import srsd384Publication from './reviews/2026-10-04-authorised-srsd384.json' with {type:'json'};
import fractylModalityGap from './reviews/2026-10-04-authorised-fractyl-modality-gap.json' with {type:'json'};
import arteloMuscleGap from './reviews/2026-10-04-authorised-art2713-muscle-gap.json' with {type:'json'};
import rgt075Publication from './reviews/2026-10-04-authorised-rgt075.json' with {type:'json'};
import vct220Publication from './reviews/2026-10-04-authorised-vct220.json' with {type:'json'};
import vk2735Maintenance from './reviews/2026-10-04-authorised-vk2735-maintenance.json' with {type:'json'};
import azelapragDiscontinuation from './reviews/2026-10-04-authorised-azelaprag-discontinuation.json' with {type:'json'};
import taldefgrobepRv8451 from './reviews/2026-10-04-authorised-taldefgrobep-rv8451.json' with {type:'json'};
import ard201Pause from './reviews/2026-10-05-authorised-ard201-pause.json' with {type:'json'};
import asc36OralPublication from './reviews/2026-10-05-authorised-asc36-oral.json' with {type:'json'};
import internationalMaintenanceWave from './reviews/2026-10-04-authorised-international-maintenance-wave.json' with {type:'json'};
import asc30AuroraCorrection from './reviews/2026-10-05-authorised-asc30-aurora-phase3.json' with {type:'json'};
import novoSpecialistWave from './reviews/2026-10-05-authorised-novo-specialist-wave.json' with {type:'json'};
import petrelintideZupreme from './reviews/2026-10-05-authorised-petrelintide-zupreme-registry.json' with {type:'json'};
import ribupatideSpecialistWave from './reviews/2026-10-05-authorised-ribupatide-specialist-wave.json' with {type:'json'};
import hansohOlatorepatideReview from './reviews/2026-10-05-authorised-hansoh-olatorepatide-source-review.json' with {type:'json'};
import gzc8072Publication from './reviews/2026-10-05-authorised-gzc8072.json' with {type:'json'};
import te8105Phase2b from './reviews/2026-10-05-authorised-te8105-phase2b.json' with {type:'json'};
import semaglutideSpecialistSarcopeniaWave from './reviews/2026-10-05-authorised-semaglutide-specialist-sarcopenia-wave.json' with {type:'json'};
import coreTrialLifecycle from './reviews/2026-10-06-authorised-core-trial-lifecycle.json' with {type:'json'};
import {readFileSync} from 'node:fs';
test('new semaglutide specialist and sarcopenia records remain bounded research evidence',()=>{
 assert.equal(semaglutideSpecialistSarcopeniaWave.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(semaglutideSpecialistSarcopeniaWave.clinicalApproval,null);
 assert.equal(semaglutideSpecialistSarcopeniaWave.industryComplete,false);
 assert.equal(semaglutideSpecialistSarcopeniaWave.catalogueCounts.totalAfter,102);
 assert.equal(semaglutideSpecialistSarcopeniaWave.catalogueCounts.configuredSourcesAfter,171);
 const specialist=industry.find(e=>e.id==='semaglutide-specialist-trials');
 assert.match(specialist.stage,/Nine Phase 2\/4/);
 assert.match(specialist.summary,/five Phase 4 metabolic-and-bariatric-surgery studies/);
 assert.match(specialist.limitations,/All six new records remain not yet recruiting/);
 assert.equal(specialist.additionalEvidence.length,9);
 const observation=industry.find(e=>e.id==='glp1-sarcopenia-observation');
 assert.ok(observation);assert.equal(observation.group,'research');
 assert.match(observation.stage,/observational study.*no treatment assigned/i);
 assert.match(observation.summary,/hand-grip strength/);
 assert.match(observation.limitations,/do not establish muscle loss, muscle preservation, causation/);
 assert.match(observation.ukAuthorisation,/does not establish a new UK medicine authorisation/);
 assert.equal(observation.additionalEvidence.length,1);
 assert.equal(semaglutideSpecialistSarcopeniaWave.registrySources.length,7);
 assert.ok(semaglutideSpecialistSarcopeniaWave.registrySources.every(source=>!source.lifecycle.hasResults&&/^[a-f0-9]{64}$/.test(source.reviewedFingerprint)));
});
test('TE-8105 preserves not-yet-recruiting status and estimated Phase 2b plans',()=>{
 assert.equal(te8105Phase2b.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(te8105Phase2b.clinicalApproval,null);
 assert.equal(te8105Phase2b.industryComplete,false);
 assert.equal(te8105Phase2b.catalogueCounts.totalAfter,101);
 assert.equal(te8105Phase2b.catalogueCounts.configuredSourcesAfter,164);
 const e=industry.find(e=>e.id==='te8105');
 assert.ok(e);assert.equal(e.group,'research');
 assert.match(e.stage,/not yet recruiting/);
 assert.match(e.summary,/injectable GLP-1 receptor agonist/);
 assert.match(e.summary,/up to 204 participants/);
 assert.match(e.limitations,/October 2026 start.*204-participant enrolment.*February 2028 completion are estimates/);
 assert.match(e.limitations,/No results are posted/);
 assert.match(e.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(e.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(e.supply,/does not establish lawful UK retail supply/);
 assert.deepEqual(e.sourceIds,[]);
 assert.ok(e.additionalEvidence.some(s=>s.url==='https://clinicaltrials.gov/study/NCT07857473'));
 const registry=te8105Phase2b.registrySources[0];
 assert.equal(registry.lifecycle.status,'NOT_YET_RECRUITING');
 assert.deepEqual(registry.lifecycle.enrollment,{count:204,type:'ESTIMATED'});
 assert.equal(registry.lifecycle.start.type,'ESTIMATED');
 assert.equal(registry.lifecycle.hasResults,false);
 assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
});
test('VK2735 maintenance evidence stays sponsor-reported and does not create an approved regimen',()=>{
 const e=industry.find(e=>e.id==='vk2735');
 assert.equal(vk2735Maintenance.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(vk2735Maintenance.clinicalApproval,null);
 assert.equal(vk2735Maintenance.industryComplete,false);
 assert.match(e.stage,/sponsor-reported maintenance study completed/);
 assert.match(e.stage,/oral Phase 3 planned/);
 assert.match(e.summary,/approximately 180 adults/);
 assert.match(e.summary,/12 weeks/);
 assert.match(e.limitations,/sponsor-reported topline/);
 assert.match(e.limitations,/not peer-reviewed results/);
 assert.match(e.limitations,/do not establish switching from another medicine/);
 assert.ok(e.sourceIds.includes('vk2735-maintenance-viking'));
 assert.equal(e.reviewedAt,vk2735Maintenance.reviewedAt);
 const source=industrySources.find(s=>s.id==='vk2735-maintenance-viking');
 assert.match(source.reviewedFingerprint,/^[a-f0-9]{64}$/);
 assert.equal(vk2735Maintenance.catalogueCounts.configuredSourcesAfter,132);
});
test('WVE-007 separates monotherapy registry, sponsor combination and planned maintenance',()=>{
 const e=industry.find(e=>e.id==='wve007');
 assert.match(e.stage,/Recruiting Phase 1\/2a monotherapy/);
 assert.match(e.stage,/combination initiation sponsor-reported/);
 assert.match(e.summary,/296 estimated participants and no posted results/);
 assert.match(e.summary,/maintenance trial remains planned/);
 assert.match(e.limitations,/2 June 2026/);
 assert.match(e.limitations,/preclinical, not completed human combination evidence/);
 assert.match(e.limitations,/do not establish strength or function/);
 assert.match(e.supply,/UK research sites do not establish lawful UK retail supply/);
 assert.equal(e.clinicalApproval,null);
 assert.equal(e.sourceIds.length,0);
 assert.equal(e.reviewedAt,wve007Publication.reviewedAt);
 assert.equal(wve007Publication.registryEvidence.hasResults,false);
 assert.equal(wve007Publication.registryEvidence.combinationRegistryMatched,false);
 assert.equal(wve007Publication.registryEvidence.ukLocationsListed,2);
 assert.equal(wve007Publication.automatedMonitorChanges,false);
 assert.equal(wve007Publication.industryComplete,false);
 assert.equal(wve007Publication.sponsorRetrieval.automaticBaselineApproved,false);
 assert.ok(wve007Publication.discoveryPass.failedChecks.length);
 const html=industryMarkup({},new URLSearchParams({q:'WVE-007'}));
 assert.equal((html.match(/data-industry-card/g)||[]).length,1);
 assert.match(html,/Status checks do not assess clinical outcomes/);
});
test('SRSD384 retains sponsor initiation and the older conflicting registry status',()=>{
 const e=industry.find(e=>e.id==='srsd384');
 assert.equal(srsd384Publication.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(srsd384Publication.clinicalApproval,null);
 assert.equal(srsd384Publication.industryComplete,false);
 assert.match(e.stage,/Sponsor-reported first participant dosed/);
 assert.match(e.stage,/registry still not yet recruiting/);
 assert.match(e.summary,/Part A studies SRSD384 alone/);
 assert.match(e.summary,/Part B studies SRSD384 with tirzepatide/);
 assert.match(e.limitations,/last updated 5 June 2026/);
 assert.match(e.limitations,/no posted results/);
 assert.match(e.limitations,/not demonstrated human outcomes/);
 assert.equal(e.clinicalApproval,null);
 assert.equal(e.sourceIds.length,0);
 const registry=srsd384Publication.registrySources[0];
 assert.equal(registry.lifecycle.status,'NOT_YET_RECRUITING');
 assert.deepEqual(registry.lifecycle.start,{date:'2026-06',type:'ESTIMATED'});
 assert.equal(registry.lifecycle.hasResults,false);
 assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
 assert.equal(srsd384Publication.configuredSourcePass.configuredSources,124);
 assert.equal(srsd384Publication.configuredSourcePass.attention[0].error,'http_403');
 assert.equal(srsd384Publication.catalogueCounts.totalAfter,88);
 assert.equal(srsd384Publication.catalogueCounts.trialRecordsAfter,69);
 const html=industryMarkup({},new URLSearchParams({q:'Sirius INHBE'}));
 assert.equal((html.match(/data-industry-card/g)||[]).length,1);
 assert.match(html,/Status checks do not assess clinical outcomes/);
});
test('RJVA-002 stays preclinical and adjacent procedures do not blur catalogue scope',()=>{
 const e=industry.find(e=>e.id==='rjva002');
 assert.equal(fractylModalityGap.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(fractylModalityGap.clinicalApproval,null);
 assert.equal(fractylModalityGap.industryComplete,false);
 assert.equal(fractylModalityGap.automatedMonitorChanges,false);
 assert.ok(e);
 assert.equal(e.group,'research');
 assert.equal(e.clinicalApproval,null);
 assert.match(e.stage,/Preclinical dual GIP\/GLP-1 gene-therapy/);
 assert.match(e.summary,/diet-induced-obesity mouse model/);
 assert.match(e.limitations,/seven animals per group/);
 assert.match(e.limitations,/not in people/);
 assert.match(e.limitations,/RJVA-001 is a different candidate/);
 assert.match(e.limitations,/Revita is a separate endoscopic device procedure/);
 assert.match(e.ukAuthorisation,/do not establish UK marketing authorisation/);
 assert.match(e.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(e.supply,/does not establish lawful UK retail supply/);
 assert.equal(e.sourceIds.length,0);
 assert.equal(e.additionalEvidence.length,2);
 assert.equal(fractylModalityGap.reviewedButNotPublished.length,2);
 assert.ok(fractylModalityGap.reviewedButNotPublished.some(item=>item.id==='revita-remain1'));
 assert.ok(fractylModalityGap.reviewedButNotPublished.some(item=>item.id==='rjva001'));
 assert.ok(discoveryDomains.includes('fractyl.com'));
});
test('ART27.13 keeps non-clinical GLP-1 exploration separate from human cachexia evidence',()=>{
 const e=industry.find(e=>e.id==='art2713');
 assert.equal(arteloMuscleGap.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(arteloMuscleGap.clinicalApproval,null);
 assert.equal(arteloMuscleGap.industryComplete,false);
 assert.equal(arteloMuscleGap.automatedMonitorChanges,false);
 assert.ok(e);
 assert.equal(e.group,'research');
 assert.equal(e.clinicalApproval,null);
 assert.match(e.stage,/Non-clinical GLP-1 companion exploration/);
 assert.match(e.summary,/cannabinoid receptor agonist/);
 assert.match(e.summary,/non-clinical study/);
 assert.match(e.limitations,/cancer anorexia and cachexia/);
 assert.match(e.limitations,/not human obesity evidence/);
 assert.match(e.limitations,/does not establish preserved muscle strength or function/);
 assert.match(e.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(e.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(e.supply,/does not establish lawful UK retail supply/);
 assert.equal(e.sourceIds.length,0);
 assert.equal(e.additionalEvidence.length,2);
 assert.ok(discoveryDomains.includes('artelobio.com'));
 assert.ok(arteloMuscleGap.failedChecks.some(item=>item.source==='ISRCTN15607817'));
});
test('RGT-075 separates sponsor-reported Phase 2a topline evidence from completed result-free registries',()=>{
 const e=industry.find(e=>e.id==='rgt075');
 assert.equal(rgt075Publication.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(rgt075Publication.clinicalApproval,null);
 assert.equal(rgt075Publication.industryComplete,false);
 assert.ok(e);
 assert.equal(e.group,'research');
 assert.equal(e.clinicalApproval,null);
 assert.match(e.stage,/Completed Phase 2a and Phase 2b registry records/);
 assert.match(e.summary,/267-participant COMO-1 Phase 2b study as completed/);
 assert.match(e.summary,/neither registry record has posted results/);
 assert.match(e.limitations,/sponsor-reported topline observations/);
 assert.match(e.limitations,/positive Phase 2b outcome/);
 assert.match(e.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(e.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(e.supply,/do not establish lawful UK retail supply/);
 assert.equal(e.sourceIds.length,0);
 assert.equal(e.additionalEvidence.length,4);
 assert.equal(rgt075Publication.registrySources.length,2);
 assert.ok(rgt075Publication.registrySources.every(s=>s.lifecycle.status==='COMPLETED'&&!s.lifecycle.hasResults));
 assert.deepEqual(rgt075Publication.registrySources.map(s=>s.lifecycle.enrollment.count),[73,267]);
 assert.ok(rgt075Publication.registrySources.every(s=>/^[a-f0-9]{64}$/.test(s.reviewedFingerprint)));
 assert.ok(discoveryDomains.includes('regor.com'));
 assert.equal(rgt075Publication.catalogueCounts.totalAfter,91);
 assert.equal(rgt075Publication.catalogueCounts.configuredSourcesAfter,127);
 assert.equal(rgt075Publication.catalogueCounts.trialRecordsAfter,71);
 const html=industryMarkup({},new URLSearchParams({q:'Regor COMO-1'}));
 assert.equal((html.match(/data-industry-card/g)||[]).length,1);
 assert.match(html,/Last reviewed record: Completed/);
 assert.match(html,/No results posted at record-status review/);
});
test('CX11/VCT220 separates published, sponsor-reported and result-free registry evidence',()=>{
 const e=industry.find(e=>e.id==='vct220');
 assert.equal(vct220Publication.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(vct220Publication.clinicalApproval,null);
 assert.equal(vct220Publication.industryComplete,false);
 assert.ok(e);
 assert.equal(e.group,'research');
 assert.equal(e.clinicalApproval,null);
 assert.match(e.stage,/Completed China Phase III and US Phase II records/);
 assert.match(e.stage,/hypertension Phase II active, not recruiting/);
 assert.match(e.summary,/peer-reviewed publication/);
 assert.match(e.summary,/840-participant Chinese Phase III/);
 assert.match(e.limitations,/sponsor-reported topline observations/);
 assert.match(e.limitations,/246 adults were enrolled while its registry records 250/);
 assert.match(e.limitations,/planned global Phase III programme is not treated as started/);
 assert.match(e.limitations,/planned China NDA submission is not an NMPA approval/);
 assert.match(e.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(e.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(e.supply,/do not establish lawful UK retail supply/);
 assert.equal(e.sourceIds.length,0);
 assert.equal(e.additionalEvidence.length,8);
 assert.equal(vct220Publication.registrySources.length,4);
 assert.deepEqual(vct220Publication.registrySources.map(s=>s.lifecycle.status),['COMPLETED','COMPLETED','COMPLETED','ACTIVE_NOT_RECRUITING']);
 assert.deepEqual(vct220Publication.registrySources.map(s=>s.lifecycle.enrollment.count),[250,840,250,160]);
 assert.ok(vct220Publication.registrySources.every(s=>!s.lifecycle.hasResults&&/^[a-f0-9]{64}$/.test(s.reviewedFingerprint)));
 assert.ok(discoveryDomains.includes('corxelbio.com'));
 assert.equal(vct220Publication.catalogueCounts.totalAfter,92);
 assert.equal(vct220Publication.catalogueCounts.configuredSourcesAfter,131);
 assert.equal(vct220Publication.catalogueCounts.trialRecordsAfter,75);
 assert.ok(vct220Publication.discoveryPass.failedChecks.length>=2);
 const html=industryMarkup({},new URLSearchParams({q:'Corxel VCT220 hypertension'}));
 assert.equal((html.match(/data-industry-card/g)||[]).length,1);
 assert.match(html,/Last reviewed record: Active, not recruiting/);
 assert.match(html,/No results posted at record-status review/);
 assert.match(html,/Peer-reviewed Phase II publication/);
});
test('Viking and Antag follow-up separates actual starts, registry status and unproven outcomes',()=>{
 assert.equal(vikingAntagFollowup.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(vikingAntagFollowup.clinicalApproval,null);
 assert.equal(vikingAntagFollowup.industryComplete,false);
 assert.equal(vikingAntagFollowup.automatedMonitorChanges,false);
 assert.equal(vikingAntagFollowup.configuredSourcePass.configuredSources,51);
 const vk=industry.find(e=>e.id==='vk3019');
 assert.match(vk.stage,/Recruiting Phase 1/);
 assert.match(vk.summary,/actual 6 July 2026 start/);
 assert.match(vk.summary,/56 estimated participants/);
 assert.match(vk.limitations,/no posted results/);
 assert.match(vk.limitations,/24 June announcement preceded the registry's actual start/);
 const at=industry.find(e=>e.id==='at673-semaglutide');
 assert.match(at.stage,/Active, not recruiting Phase 2/);
 assert.match(at.summary,/actual 19 June 2026 start/);
 assert.match(at.summary,/150 estimated participants/);
 assert.match(at.limitations,/does not identify AT673's mechanism/);
 assert.match(at.limitations,/do not establish additional weight loss/);
 for(const e of [vk,at]){
  assert.equal(e.sourceIds.length,0);
  assert.equal(e.clinicalApproval,null);
  assert.equal(e.reviewedAt,vikingAntagFollowup.reviewedAt);
  for(const k of ['ukAuthorisation','nhsEngland','supply','limitations'])assert.ok(e[k]);
  assert.match(industryMarkup({},new URLSearchParams({q:e.name})),/Status checks do not assess clinical outcomes/);
 }
 assert.ok(vikingAntagFollowup.registryEvidence.every(record=>record.hasResults===false));
 assert.ok(vikingAntagFollowup.registryEvidence.every(record=>/^[a-f0-9]{64}$/.test(record.responseSha256)));
 assert.equal(vikingAntagFollowup.discoveryPass.currentDateRegistryMatches,0);
});
test('specialist registry wave adds one programme and updates existing indications without implying results',()=>{
 assert.equal(specialistRegistryWave.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(specialistRegistryWave.clinicalApproval,null);
 assert.equal(specialistRegistryWave.industryComplete,false);
 assert.equal(specialistRegistryWave.automatedMonitorChanges,false);
 assert.equal(specialistRegistryWave.configuredSourcePass.configuredSources,50);
 const nnc=industry.find(e=>e.id==='nnc0638-0355');
 assert.equal(nnc.group,'research');
 assert.match(nnc.stage,/Active, not recruiting Phase 1/);
 assert.match(nnc.summary,/actual 3 September 2024 start/);
 assert.match(nnc.summary,/63 actual participants/);
 assert.match(nnc.limitations,/does not identify a mechanism/);
 assert.equal(nnc.sourceIds.length,0);
 assert.equal(nnc.clinicalApproval,null);
 assert.equal(nnc.reviewedAt,specialistRegistryWave.reviewedAt);
 const ribupatide=industry.find(e=>e.id==='ribupatide-injection');
 assert.match(ribupatide.summary,/NCT07285902/);
 assert.match(ribupatide.summary,/NCT07709910/);
 assert.match(ribupatide.limitations,/knee-osteoarthritis start remains an estimate/);
 assert.match(ribupatide.limitations,/do not establish an authorised osteoarthritis indication/);
 const safiglipron=industry.find(e=>e.id==='kai7535');
 assert.match(safiglipron.stage,/recruiting hypertension Phase III/);
 assert.match(safiglipron.summary,/NCT07528027/);
 assert.match(safiglipron.limitations,/no posted results/);
 assert.ok(specialistRegistryWave.registryEvidence.every(record=>record.hasResults===false));
 assert.ok(specialistRegistryWave.registryEvidence.every(record=>/^[a-f0-9]{64}$/.test(record.responseSha256)));
 assert.equal(specialistRegistryWave.discoveryPass.failedChecks.length,2);
});
test('lean-mass and energy follow-up separates planned outcomes from demonstrated benefit',()=>{
 assert.equal(leanMassEnergyFollowup.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(leanMassEnergyFollowup.clinicalApproval,null);
 assert.equal(leanMassEnergyFollowup.industryComplete,false);
 assert.equal(leanMassEnergyFollowup.automatedMonitorChanges,false);
 assert.equal(leanMassEnergyFollowup.configuredSourcePass.configuredSources,50);
 const leanPro=industry.find(e=>e.id==='lean-pro-glp1-protein');
 assert.equal(leanPro.group,'research');
 assert.match(leanPro.stage,/Recruiting randomised dietary-support study/);
 assert.match(leanPro.summary,/130-participant Greek study/);
 assert.match(leanPro.summary,/grip strength/);
 assert.match(leanPro.limitations,/does not establish that higher protein preserves muscle/);
 assert.match(leanPro.limitations,/not dietary advice/);
 assert.equal(leanPro.sourceIds.length,0);
 assert.equal(leanPro.clinicalApproval,null);
 assert.equal(leanPro.reviewedAt,leanMassEnergyFollowup.reviewedAt);
 const zenagamtide=industry.find(e=>e.id==='zenagamtide');
 assert.match(zenagamtide.summary,/NNC0487-0111\/amycretin/);
 assert.match(zenagamtide.summary,/sleeping and 24-hour energy expenditure/);
 assert.match(zenagamtide.limitations,/do not demonstrate preserved muscle/);
 assert.match(zenagamtide.limitations,/does not advance the oral formulation/);
 assert.ok(zenagamtide.additionalEvidence.some(source=>source.url==='https://clinicaltrials.gov/study/NCT07757087'));
 assert.ok(leanMassEnergyFollowup.registryEvidence.every(record=>record.hasResults===false));
 assert.ok(leanMassEnergyFollowup.registryEvidence.every(record=>/^[a-f0-9]{64}$/.test(record.responseSha256)));
});
test('AZD1043 remains bounded Phase 1 research with site and access distinctions',()=>{
 const entry=industry.find(e=>e.id==='azd1043');
 assert.match(entry.stage,/Recruiting Phase 1/);
 assert.match(entry.summary,/actual 30 March 2026 start/);
 assert.match(entry.summary,/104 estimated participants/);
 assert.match(entry.limitations,/UK site remained not yet recruiting/);
 assert.match(entry.limitations,/does not establish weight-loss efficacy/);
 assert.equal(entry.clinicalApproval,null);
 assert.equal(entry.sourceIds.length,0);
 assert.equal(entry.reviewedAt,azd1043Publication.reviewedAt);
 assert.equal(azd1043Publication.registryEvidence.overallStatus,'RECRUITING');
 assert.equal(azd1043Publication.registryEvidence.ukSiteStatus,'NOT_YET_RECRUITING');
 assert.equal(azd1043Publication.registryEvidence.hasResults,false);
 assert.equal(azd1043Publication.automatedMonitorChanges,false);
 assert.equal(azd1043Publication.industryComplete,false);
});
test('authoritative README catalogue totals match exported entries',()=>{
 const readme=readFileSync(new URL('./README.md',import.meta.url),'utf8');
 assert.match(readme,new RegExp(`6 detailed references plus ${industry.length} concise industry summaries`));
 assert.match(readme,new RegExp(`${medicines.length+industry.length} medicines/programmes, with ${sources.length} configured source documents`));
});
test('amylin follow-up corrects actual research stage while retaining dated discrepancies',()=>{
 const abbv=industry.find(e=>e.id==='abbv295');
 assert.match(abbv.stage,/Phase 2 recruiting/);
 assert.match(abbv.summary,/actual 4 August 2026 start/);
 assert.match(abbv.limitations,/prospectively/);
 assert.match(abbv.limitations,/no posted results/);
 const azd=industry.find(e=>e.id==='azd6234');
 assert.match(azd.stage,/completed; no registry-posted results/);
 assert.match(azd.summary,/262 actual participants/);
 const pilot=industry.find(e=>e.id==='mirabegron-alpha-lipoic-acid');
 assert.match(pilot.stage,/not yet recruiting/);
 assert.match(pilot.summary,/estimated 8 October 2026 start/);
 assert.match(pilot.summary,/primary endpoint is insulin sensitivity/);
 assert.match(pilot.limitations,/48-person target.*estimates 60/);
 for(const e of [abbv,azd,pilot]){
  assert.equal(e.clinicalApproval,null);
  assert.equal(e.reviewedAt,e.id==='azd6234'?seleneCorrection.reviewedAt:e.id==='mirabegron-alpha-lipoic-acid'?nct05713799Correction.reviewedAt:amylinMetabolicFollowup.reviewedAt);
  assert.equal(e.sourceIds.length,0);
  for(const k of ['ukAuthorisation','nhsEngland','supply','limitations'])assert.ok(e[k]);
  const html=industryMarkup({},new URLSearchParams({q:e.name}));
  assert.match(html,/Status checks do not assess clinical outcomes/);
 }
 const correctedSource=registrySources.find(s=>s.id==='registry-nct05713799');
 assert.equal(correctedSource.lifecycle.start.date,'2026-10-08');
 assert.equal(correctedSource.sourceUpdatedAt,'2026-10-05');
 assert.equal(correctedSource.reviewedFingerprint,'f1f1502b85ec20feb6fa3aaa46b023e7a42a2a2c0ecba7f775b4bd77ff83471d');
 assert.equal(nct05713799Correction.clinicalApproval,null);
 assert.equal(nct05713799Correction.industryComplete,false);
 assert.equal(amylinMetabolicFollowup.automatedMonitorChanges,false);
 assert.equal(amylinMetabolicFollowup.clinicalApproval,null);
 assert.equal(amylinMetabolicFollowup.industryComplete,false);
 for(const record of amylinMetabolicFollowup.registryEvidence){
  assert.equal(record.hasResults,false);
  assert.match(record.responseSha256,/^[a-f0-9]{64}$/);
 }
 assert.ok(!industry.some(e=>/TIX100/.test(e.name)));
});
test('expanded registry distinguishes depth, clinical approval and access and joins every source',()=>{
 assert.equal(medicines.length,6);assert.equal(industry.length,97);assert.equal(sources.length,176);
 assert.equal(new Set([...medicines,...industry].map(e=>e.id)).size,103);
 for(const e of industry){assert.equal(e.clinicalApproval,null);for(const k of ['ukAuthorisation','nhsEngland','supply','limitations'])assert.ok(e[k],e.id+':'+k);for(const id of e.sourceIds)assert.ok(industrySources.some(s=>s.id===id),id);}
 for(const s of evidence.sources){assert.ok(Date.parse(s.reviewedAt));if(s.evidenceType==='NICE guidance')assert.equal(new URL(s.url).hostname,'www.nice.org.uk');if(s.reviewedFingerprint){assert.equal(s.httpStatus,200);assert.ok(s.responseSha256);assert.ok(s.bytes>0);}else assert.ok(!s.responseSha256);}
});
test('AZD6234 correction retains APRICUS and distinguishes recruiting SELENE 1 from results and access',()=>{
 const e=industry.find(e=>e.id==='azd6234');
 assert.match(e.stage,/Phase 3 SELENE 1 recruiting/);
 assert.match(e.stage,/Phase 2b APRICUS completed/);
 assert.match(e.summary,/actual 19 August 2026 start/);
 assert.match(e.summary,/2,500 estimated participants/);
 assert.match(e.summary,/Neither registry record has posted results/);
 assert.match(e.limitations,/suspended and withdrawn/);
 assert.match(e.limitations,/no UK location is listed/);
 assert.match(e.limitations,/identifier N\/A/);
 assert.equal(e.additionalEvidence.length,4);
 assert.equal(e.sourceIds.length,0);
 assert.equal(e.clinicalApproval,null);
 assert.equal(e.reviewedAt,seleneCorrection.reviewedAt);
 assert.equal(seleneCorrection.automatedMonitorChanges,false);
 assert.equal(seleneCorrection.industryComplete,false);
 assert.equal(seleneCorrection.registryEvidence[0].phase,'PHASE3');
 assert.equal(seleneCorrection.registryEvidence[0].hasResults,false);
 assert.equal(seleneCorrection.registryEvidence[0].ukLocationsListed,0);
 assert.match(e.ukAuthorisation,/do not establish UK marketing authorisation/);
 assert.match(industryMarkup({},new URLSearchParams({q:'SELENE'})),/not automatically content-monitored/);
});
test('macupatide discovery distinguishes recruiting Phase 2 from planned Phase 1',()=>{
 const entry=industry.find(item=>item.id==='macupatide');
 assert.match(entry.stage,/Recruiting Phase 2/);
 assert.match(entry.stage,/not yet recruiting/);
 assert.match(entry.summary,/actual 16 October 2025 start/);
 assert.match(entry.limitations,/Neither study has posted results/);
 assert.equal(entry.sourceIds.length,0);
 assert.equal(entry.additionalEvidence.length,2);
 assert.equal(entry.clinicalApproval,null);
 assert.match(entry.ukAuthorisation,/do not establish UK marketing authorisation/);
 const phase2=macupatideReview.registryEvidence.find(item=>item.nctId==='NCT07215559');
 const phase1=macupatideReview.registryEvidence.find(item=>item.nctId==='NCT07765511');
 assert.equal(phase2.overallStatus,'RECRUITING');
 assert.equal(phase2.actualStartDate,'2025-10-16');
 assert.equal(phase2.hasResults,false);
 assert.equal(phase1.overallStatus,'NOT_YET_RECRUITING');
 assert.equal(phase1.estimatedStart,'2026-10');
 assert.equal(macupatideReview.clinicalApproval,null);
});
test('berobenatide correction records VESPER-6 without implying access or results',()=>{
 const entry=industry.find(item=>item.id==='pf3944');
 assert.match(entry.name,/Berobenatide/);
 assert.match(entry.stage,/VESPER-6/);
 assert.match(entry.summary,/actual 10 June 2026 start/);
 assert.match(entry.limitations,/not results/);
 assert.equal(entry.clinicalApproval,null);
 assert.match(entry.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.ok(entry.sourceIds.includes('pf3944-pfizer-vesper6'));
 assert.equal(berobenatideReview.registryEvidence.status,'Recruiting');
 assert.equal(berobenatideReview.registryEvidence.actualStartDate,'2026-06-10');
 assert.equal(berobenatideReview.registryEvidence.lastUpdatePosted,'2026-09-28');
 assert.equal(berobenatideReview.ukPosition.nhsEnglandAccess,'Not established by either source.');
});
test('Pfizer monitor repair uses exact official investor-hosted PDF baselines',()=>{
 for(const id of ['pf3944-pfizer','danuglipron-pfizer']){
  const source=industrySources.find(item=>item.id===id);
  const receipt=pfizerPdfRepair.sources.find(item=>item.id===id);
  assert.equal(source.url,receipt.url);
  assert.equal(new URL(source.url).hostname,'www.pfizer.com');
  assert.equal(source.checkUrl,receipt.checkUrl);
  assert.equal(new URL(source.checkUrl).hostname,'s206.q4cdn.com');
  assert.equal(source.format,'pdf');
  assert.equal(source.reviewedFingerprint,receipt.reviewedFingerprint);
 }
 assert.equal(pfizerPdfRepair.monitoring.successesSeeded,false);
 assert.equal(pfizerPdfRepair.clinicalApproval,null);
});
test('EloraTZP correction replaces planned-result evidence without treating planned Phase 3 as started',()=>{
 const entry=industry.find(item=>item.id==='eloralintide');
 const source=industrySources.find(item=>item.id==='eloralintide-lilly');
 assert.equal(entry.name,'Eloralintide / EloraTZP');
 assert.match(entry.stage,/Phase 2b results reported/);
 assert.match(entry.summary,/completed 48-week Phase 2b study/);
 assert.match(entry.summary,/not treated as started/);
 assert.match(entry.limitations,/10\.8% to 27\.0%/);
 assert.equal(source.url,eloraTZPReview.source.url);
 assert.equal(source.reviewedFingerprint,eloraTZPReview.source.reviewedFingerprint);
 assert.equal(eloraTZPReview.registryEvidence.overallStatus,'COMPLETED');
 assert.equal(eloraTZPReview.registryEvidence.actualCompletionDate,'2026-09-14');
 assert.equal(eloraTZPReview.ukPosition.marketingAuthorisation.includes('Neither source establishes'),true);
 assert.equal(entry.clinicalApproval,null);
});
test('KaiNETIC update records completed Phase 3 enrolment without implying results or access',()=>{
 const entry=industry.find(item=>item.id==='ribupatide-injection');
 const source=industrySources.find(item=>item.id==='kailera-kainetic-20260930');
 assert.match(entry.stage,/fully enrolled/);
 assert.match(entry.summary,/enrolment is complete/);
 assert.match(entry.summary,/expected in mid-2028/);
 assert.match(entry.limitations,/not a trial result/);
 assert.ok(entry.sourceIds.includes(source.id));
 assert.equal(source.reviewedFingerprint,kaineticReview.source.reviewedFingerprint);
 assert.equal(kaineticReview.clinicalApproval,null);
 assert.match(kaineticReview.ukPosition.marketingAuthorisation,/does not establish/);
 assert.equal(entry.clinicalApproval,null);
});
test('unverified source baselines stay visible even if a caller supplies current status',()=>{
 const html=industryMarkup({sources:industrySources.map(s=>({id:s.id,status:'current'}))});
 assert.equal((html.match(/data-industry-card/g)||[]).length,industry.length);
 assert.equal((html.match(/Complete-response baseline not yet verified/g)||[]).length,industry.flatMap(e=>e.sourceIds).filter(id=>!industrySources.find(s=>s.id===id).reviewedFingerprint).length);
 assert.match(html,/not clinical approval/);assert.match(html,/Status checks do not assess clinical outcomes/);
});
test('paused and discontinued programmes remain distinct and searchable',()=>{
 const paused=industryMarkup({},new URLSearchParams({industry:'paused'}));
 assert.match(paused,/industry-dapiglutide/);assert.doesNotMatch(paused,/industry-danuglipron/);
 const stopped=industryMarkup({},new URLSearchParams({industry:'discontinued'}));
 assert.match(stopped,/industry-danuglipron/);assert.match(stopped,/industry-amg513/);
 const query=industryMarkup({},new URLSearchParams({q:'petrelintide'}));
 assert.equal((query.match(/data-industry-card/g)||[]).length,2);assert.match(query,/Phase 3 ZUPREME/);assert.match(query,/ZYNERGY/);
 assert.doesNotMatch(industryMarkup({},new URLSearchParams({q:'<script>evil</script>'})),/<script>/);
});
test('discovery can surface an untracked name and incomplete searches cannot imply coverage',()=>{
 assert.ok(discoveryDomains.includes('hengrui.com'));
 assert.ok(queriesForDate(new Date('2027-02-01')).every(q=>q.q.includes('February 2027')));
 const report=summariseDiscovery([{domain:'gov.uk',status:'searched',candidates:[{name:'Previously unknown candidate',url:'https://www.gov.uk/example'}]},{domain:'nice.org.uk',status:'unavailable'}]);
 assert.equal(report.candidates.length,1);assert.equal(report.scanComplete,false);assert.ok(report.failedDomains.includes('nice.org.uk'));assert.ok(report.missingDomains.length);
 const complete=summariseDiscovery(discoveryDomains.map(domain=>({domain,status:'searched',candidates:[]})));
 assert.equal(complete.scanComplete,true);assert.equal(complete.industryComplete,false);assert.equal(complete.evidenceReviewRequired,true);assert.equal(complete.clinicalApproval,null);
});
test('HRS-1596 stays a sourced proposal until separately authorised',()=>{
 assert.equal(hrs1596Review.publicationStatus,'proposal_only');
 assert.equal(hrs1596Review.clinicalApproval,null);
 assert.equal(hrs1596Review.industryComplete,false);
 assert.equal(hrs1596Review.proposal.id,'hrs1596');
 assert.equal(hrs1596Review.registry.overallStatus,'NOT_YET_RECRUITING');
 assert.equal(hrs1596Review.registry.phase,'Phase 1');
 assert.ok(hrs1596Review.sources[0].reviewedFingerprint);
 assert.equal(industry.some(entry=>entry.id==='hrs1596'),true);
 assert.equal(industrySources.some(source=>source.id==='hrs1596-hengrui-20260929'),true);
});
test('continuing discovery preserves the emugrobart stop and petrelintide repair as proposals',()=>{
 assert.equal(continuingReview.publicationStatus,'proposal_only');
 assert.equal(continuingReview.clinicalApproval,null);
 assert.equal(continuingReview.industryComplete,false);
 assert.equal(continuingReview.proposals.emugrobart.group,'discontinued');
 assert.equal(continuingReview.registry.nctId,'NCT06965413');
 assert.equal(continuingReview.registry.overallStatus,'ACTIVE_NOT_RECRUITING');
 assert.equal(continuingReview.proposals.petrelintideSourceRepair.liveClaimChangeRequired,false);
 assert.ok(continuingReview.sources.every(source=>source.reviewedFingerprint));
 assert.ok(discoveryDomains.includes('chugai-pharm.co.jp'));
 assert.equal(industry.some(entry=>entry.id==='emugrobart'),true);
 assert.equal(industrySources.some(source=>source.id==='emugrobart-chugai-20260928'),true);
});
test('ENV-308 stays a bounded early-stage proposal with registry absence visible',()=>{
 assert.equal(env308Review.publicationStatus,'proposal_only');
 assert.equal(env308Review.clinicalApproval,null);
 assert.equal(env308Review.industryComplete,false);
 assert.equal(env308Review.proposal.id,'env308');
 assert.equal(env308Review.proposal.group,'research');
 assert.equal(env308Review.proposal.stage,'Phase 1 sponsor-reported results; Phase 2 planned');
 assert.ok(env308Review.sources[0].reviewedFingerprint);
 assert.equal(env308Review.registrySearch.matches,0);
 assert.equal(env308Review.retrievalFailures.length,1);
 assert.ok(discoveryDomains.includes('enveda.com'));
 assert.equal(industry.some(entry=>entry.id==='env308'),true);
 assert.equal(industrySources.some(source=>source.id==='env308-enveda-20260818'),true);
});

test('authorised source repair preserves the original receipt and joins readable evidence',()=>{
 assert.equal(industrySources.find(s=>s.id==='petrelintide-zealand').url,continuingReview.proposals.petrelintideSourceRepair.candidateUrl);
 for(const id of ['hrs1596','emugrobart']){const html=industryMarkup({},new URLSearchParams({q:id==='hrs1596'?'HRS-1596':'emugrobart'}));assert.doesNotMatch(html,/href=""/);assert.match(html,/clinicaltrials.gov/);}
});

test('GlobeNewswire access repair changes only check URLs and preserves reviewed evidence',()=>{
 assert.equal(globeNewswireRepair.reviewRenewed,false);
 assert.equal(globeNewswireRepair.wordingChanged,false);
 assert.equal(globeNewswireRepair.clinicalApproval,null);
 for(const proof of globeNewswireRepair.proof){
  const source=industrySources.find(item=>item.id===proof.id);
  const repaired=globeNewswireRepair.sources.find(item=>item.id===proof.id);
  assert.equal(source.url,repaired.url);
  assert.equal(source.checkUrl,repaired.checkUrl);
  assert.equal(new URL(source.checkUrl).hostname,'rss.globenewswire.com');
  assert.equal(proof.previousReviewedFingerprint,proof.reviewedFingerprint);
  assert.equal(source.reviewedFingerprint,proof.reviewedFingerprint);
  assert.equal(source.reviewedAt,repaired.reviewedAt);
  assert.equal(proof.httpStatus,200);
  assert.equal(proof.withdrawn,false);
 }
});

test('evening evidence preserves safety, planned events and research access boundaries',()=>{
 const find=id=>industry.find(e=>e.id===id);
 assert.match(find('trevogrumab-semaglutide').limitations,/two deaths; causation was not established/);
 assert.match(find('trevogrumab-semaglutide').limitations,/does not establish improved strength or function/);
 assert.match(find('ibio600').limitations,/May 2027.*second half of 2027/);
 assert.match(find('ibio600').supply,/No UK retail availability/);
 assert.equal(find('ibio600').clinicalApproval,null);
 assert.equal(find('ibio600').sourceIds.length,0);
 assert.match(find('kai4729').summary,/outside-China Phase 1 remained planned/);
 assert.match(find('ribupatide-injection').summary,/mid-2028/);
 assert.match(find('kai7535').name,/Safiglipron/);
 assert.match(find('survodutide').limitations,/efficacy estimand assumes continued treatment/);
});

test('broader discovery adds bounded research summaries without inventing UK access',()=>{
 assert.equal(broaderReview.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(broaderReview.clinicalApproval,null);
 assert.equal(broaderReview.industryComplete,false);
 for(const id of ['mbx4291','aroinhbe','lx9851','nbip1968','crb913','synt101','alv100']){
  const item=industry.find(entry=>entry.id===id);
  assert.ok(item,id);
  assert.equal(item.clinicalApproval,null);
  assert.equal(item.sourceIds.length,0);
  assert.ok(item.additionalEvidence.length>=1,id);
  assert.match(item.ukAuthorisation,/does not establish UK marketing authorisation/);
  assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/);
  assert.match(item.supply,/does not establish lawful UK retail supply/);
 }
 assert.match(industry.find(entry=>entry.id==='crb913').stage,/Phase 2 planned/);
 assert.match(industry.find(entry=>entry.id==='alv100').limitations,/Recruitment and first dosing are not results/);
 assert.match(industry.find(entry=>entry.id==='synt101').limitations,/Small, early sponsor-reported study/);
 for(const domain of ['mbxbio.com','arrowheadpharma.com','lexpharma.com','neurocrine.com','corbuspharma.com','syntis.bio','alveustx.com'])assert.ok(discoveryDomains.includes(domain));
});

test('SYNT-101 correction replaces the stale pending multiple-dose claim without overstating early results',()=>{
 const entry=industry.find(item=>item.id==='synt101');
 assert.equal(synt101Correction.publicationStatus,'owner_authorised_factual_correction');
 assert.equal(synt101Correction.clinicalApproval,null);
 assert.match(entry.stage,/28-day multiple-dose sponsor results/);
 assert.match(entry.stage,/Phase 2 planned/);
 assert.match(entry.summary,/23 adults with overweight or obesity/);
 assert.match(entry.summary,/planned for 2027, not treated as started/);
 assert.doesNotMatch(entry.summary,/data still planned/);
 assert.match(entry.limitations,/does not provide complete cohort-level weight-loss estimates/);
 assert.match(entry.limitations,/Preclinical lean-muscle findings are not human evidence/);
 assert.equal(entry.additionalEvidence.at(-1).url,synt101Correction.source.url);
 assert.equal(entry.reviewedAt,synt101Correction.reviewedAt);
 assert.equal(entry.clinicalApproval,null);
 assert.match(entry.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(entry.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(entry.supply,/does not establish lawful UK retail supply/);
});

test('international omissions distinguish China approval from UK access and early US research',()=>{
 assert.equal(internationalOmissions.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(internationalOmissions.clinicalApproval,null);
 assert.equal(internationalOmissions.industryComplete,false);
 assert.equal(internationalOmissions.automatedMonitorChanges,false);
 for(const id of ['ecnoglutide','mazdutide','asc36-injection','asc36-35-fdc-injection','asc35-injection']){
  const item=industry.find(entry=>entry.id===id);
  assert.ok(item,id);
  assert.equal(item.clinicalApproval,null);
  assert.equal(item.sourceIds.length,0);
  assert.ok(item.additionalEvidence.length>=1,id);
  assert.match(item.ukAuthorisation,/does not establish UK marketing authorisation/);
  assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/);
  assert.match(item.supply,/does not establish lawful UK retail supply/);
 }
 assert.match(industry.find(entry=>entry.id==='ecnoglutide').stage,/China NMPA/);
 assert.equal(industry.find(entry=>entry.id==='ecnoglutide').group,'international');
 assert.equal(industry.find(entry=>entry.id==='mazdutide').group,'international');
 assert.match(industry.find(entry=>entry.id==='mazdutide').summary,/China-specific authorisation, not a UK approval/);
 assert.match(industry.find(entry=>entry.id==='asc36-injection').limitations,/Registry corroboration remains missing/);
 assert.match(industry.find(entry=>entry.id==='asc36-35-fdc-injection').limitations,/No completed human efficacy results/);
 assert.match(industry.find(entry=>entry.id==='asc35-injection').limitations,/No results are posted/);
 const international=industryMarkup({},new URLSearchParams({industry:'international'}));
 assert.equal((international.match(/data-industry-card/g)||[]).length,2);
 assert.match(international,/Authorised outside the UK/);
 const ukAuthorised=industryMarkup({},new URLSearchParams({status:'authorised'}));
 assert.doesNotMatch(ukAuthorised,/industry-ecnoglutide/);
 assert.doesNotMatch(ukAuthorised,/industry-mazdutide/);
});
test('expanded discovery keeps trial status and UK access boundaries explicit',()=>{
 for(const id of ['aroalk7','mwn105','ibi3032','hdm1005','npm139-semaglutide-implant']){
  const item=industry.find(entry=>entry.id===id);
  assert.ok(item,id);
  assert.equal(item.clinicalApproval,null,id);
  assert.match(item.ukAuthorisation,/do(?:es)? not establish UK marketing authorisation/,id);
  assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/,id);
  assert.match(item.supply,/do(?:es)? not establish lawful UK retail supply/,id);
  assert.ok(item.additionalEvidence.length>=1,id);
 }
 assert.match(industry.find(entry=>entry.id==='mwn105').limitations,/no results/i);
 assert.match(industry.find(entry=>entry.id==='ibi3032').limitations,/no results/i);
 assert.match(industry.find(entry=>entry.id==='npm139-semaglutide-implant').stage,/not yet recruiting/i);
});


test('UBT251 keeps completed Chinese evidence separate from global plans and UK access',()=>{
 const item=industry.find(entry=>entry.id==='ubt251');
 assert.ok(item);
 assert.equal(item.clinicalApproval,null);
 assert.match(item.stage,/Chinese Phase 2 results/i);
 assert.match(item.stage,/global Phase 1b\/2a ongoing/i);
 assert.match(item.summary,/sponsor-reported/i);
 assert.match(item.limitations,/Phase 3.*plan/i);
 assert.match(item.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(item.supply,/does not establish lawful UK retail supply/);
 assert.ok(item.additionalEvidence.length>=3);
});

test('SGB-7342 preserves the dated registry mismatch and human-evidence limits',()=>{
 const item=industry.find(entry=>entry.id==='sgb7342');
 assert.ok(item);
 assert.equal(item.clinicalApproval,null);
 assert.match(item.stage,/Phase 1 first participant dosed/i);
 assert.match(item.stage,/registry status predates sponsor update/i);
 assert.match(item.summary,/single-ascending-dose safety/i);
 assert.match(item.limitations,/not yet recruiting/i);
 assert.match(item.limitations,/preclinical/i);
 assert.match(item.limitations,/No human study results/i);
 assert.match(item.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(item.supply,/do not establish lawful UK retail supply/);
 assert.equal(item.additionalEvidence.length,2);
});

test('latest wider discovery keeps formulations, plans and stopped programmes distinct',()=>{
 assert.equal(abbvAsc30TernBimagrumab.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(abbvAsc30TernBimagrumab.clinicalApproval,null);
 assert.equal(abbvAsc30TernBimagrumab.industryComplete,false);
 assert.equal(abbvAsc30TernBimagrumab.automatedMonitorChanges,false);
 for(const id of ['abbv295','asc30-oral','asc30-depot','tern601','bimagrumab-tirzepatide']){
  const item=industry.find(entry=>entry.id===id);
  assert.ok(item,id);
  assert.equal(item.clinicalApproval,null,id);
  assert.equal(item.sourceIds.length,id==='asc30-oral'?1:0,id);
  assert.ok(item.additionalEvidence.length>=2,id);
  assert.match(item.ukAuthorisation,/does not establish UK marketing authorisation/,id);
  assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/,id);
  assert.match(item.supply,/do(?:es)? not establish lawful UK retail supply/,id);
 }
 assert.match(industry.find(entry=>entry.id==='abbv295').stage,/Phase 2 recruiting/);
 assert.match(industry.find(entry=>entry.id==='asc30-oral').stage,/Recruiting global Phase 3 AURORA programme/);
 assert.match(industry.find(entry=>entry.id==='asc30-depot').limitations,/not approved regimens/);
 assert.equal(industry.find(entry=>entry.id==='tern601').group,'discontinued');
 assert.match(industry.find(entry=>entry.id==='bimagrumab-tirzepatide').limitations,/do not establish improved strength/);
 for(const domain of ['abbvie.com','ascletis.com','ternspharma.com'])assert.ok(discoveryDomains.includes(domain));
});

test('international registry omissions preserve live, completed and delayed status boundaries',()=>{
 assert.equal(registryOmissions.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(registryOmissions.clinicalApproval,null);
 assert.equal(registryOmissions.industryComplete,false);
 assert.equal(registryOmissions.automatedMonitorChanges,false);
 for(const id of ['da302168s','nnc06620419','dr10624','cmsd008']){
  const item=industry.find(entry=>entry.id===id);
  assert.ok(item,id);
  assert.equal(item.clinicalApproval,null,id);
  assert.equal(item.sourceIds.length,0,id);
  assert.equal(item.additionalEvidence.length,id==='nnc06620419'?6:1,id);
  assert.match(item.ukAuthorisation,/does not establish UK marketing authorisation/,id);
  assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/,id);
  assert.match(item.supply,/does not establish lawful UK retail supply/,id);
 }
 assert.match(industry.find(entry=>entry.id==='da302168s').stage,/Recruiting Chinese Phase 3/);
 assert.match(industry.find(entry=>entry.id==='da302168s').limitations,/No results are posted/);
 assert.match(industry.find(entry=>entry.id==='nnc06620419').stage,/Phase 2 obesity and type 2 diabetes/);
 assert.match(industry.find(entry=>entry.id==='nnc06620419').limitations,/None of the six identified/);
 assert.match(industry.find(entry=>entry.id==='dr10624').summary,/GLP-1, glucagon and FGF21/);
 assert.match(industry.find(entry=>entry.id==='cmsd008').stage,/not yet recruiting/i);
 assert.match(industry.find(entry=>entry.id==='cmsd008').limitations,/estimated start was 2 April 2026/);
});

test('enobosarm combination keeps muscle-preservation research separate from results and UK access',()=>{
 assert.equal(enobosarmSemaglutide.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(enobosarmSemaglutide.clinicalApproval,null);
 assert.equal(enobosarmSemaglutide.industryComplete,false);
 assert.equal(enobosarmSemaglutide.automatedMonitorChanges,false);
 const item=industry.find(entry=>entry.id==='enobosarm-semaglutide');
 assert.ok(item);
 assert.equal(item.clinicalApproval,null);
 assert.equal(item.sourceIds.length,0);
 assert.equal(item.additionalEvidence.length,4);
 assert.match(item.stage,/active, not recruiting/);
 assert.match(item.summary,/239 older adults/);
 assert.match(item.summary,/lean and fat mass/);
 assert.match(item.limitations,/no posted results/i);
 assert.match(item.limitations,/Q1 2027/);
 assert.match(item.limitations,/not an endorsement/);
 assert.match(item.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(item.supply,/do(?:es)? not establish lawful UK retail supply/);
});

test('expanded registry wave preserves formulation, status and specialist-indication boundaries',()=>{
 assert.equal(expandedRegistryWave.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(expandedRegistryWave.clinicalApproval,null);
 assert.equal(expandedRegistryWave.industryComplete,false);
 assert.equal(expandedRegistryWave.automatedMonitorChanges,false);
 for(const id of ['mwn109-injection','mwn109-tablets','mwn110','tqf3250','kds2010','tlc6740-tirzepatide','bio101-semaglutide']){
  const item=industry.find(entry=>entry.id===id);
  assert.ok(item,id);
  assert.equal(item.clinicalApproval,null,id);
  assert.equal(item.sourceIds.length,0,id);
  assert.ok(item.additionalEvidence.length>=1,id);
  assert.match(item.ukAuthorisation,/do(?:es)? not establish UK marketing authorisation/,id);
  assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/,id);
  assert.match(item.supply,/lawful UK retail supply/,id);
  assert.match(item.supply,/SHIFT/,id);
 }
 assert.match(industry.find(entry=>entry.id==='mwn109-injection').stage,/not yet recruiting/i);
 assert.match(industry.find(entry=>entry.id==='mwn109-injection').limitations,/no results are posted/i);
 assert.match(industry.find(entry=>entry.id==='mwn109-tablets').summary,/daily and weekly oral dosing/i);
 assert.match(industry.find(entry=>entry.id==='mwn110').limitations,/does not state a mechanism/i);
 assert.match(industry.find(entry=>entry.id==='tqf3250').summary,/actual 25 August 2026 start/i);
 assert.match(industry.find(entry=>entry.id==='kds2010').stage,/Recruiting Phase 2a/);
 assert.match(industry.find(entry=>entry.id==='tlc6740-tirzepatide').limitations,/sponsor-reported/i);
 assert.match(industry.find(entry=>entry.id==='bio101-semaglutide').limitations,/Q1 2027/);
 const ecnoglutide=industry.find(entry=>entry.id==='ecnoglutide');
 assert.match(ecnoglutide.summary,/knee osteoarthritis/i);
 assert.match(ecnoglutide.summary,/actual 3 August 2026 start/i);
 assert.match(ecnoglutide.limitations,/not an additional authorised indication/i);
 assert.equal(expandedRegistryWave.registryEvidence.length,11);
 assert.ok(expandedRegistryWave.registryEvidence.every(record=>record.hasResults===false));
 for(const domain of ['biophytis.com','orsobio.com','neurobiogen.com','sbpgroup.com','lepumedical.com'])assert.ok(discoveryDomains.includes(domain));
});

test('semaglutide specialist research remains distinct from authorised weight-management use',()=>{
 assert.equal(semaglutideSpecialistTrials.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(semaglutideSpecialistTrials.clinicalApproval,null);
 assert.equal(semaglutideSpecialistTrials.industryComplete,false);
 assert.equal(semaglutideSpecialistTrials.automatedMonitorChanges,false);
 const item=industry.find(entry=>entry.id==='semaglutide-specialist-trials');
 assert.ok(item);
 assert.equal(item.group,'research');
 assert.equal(item.clinicalApproval,null);
 assert.equal(item.sourceIds.length,0);
 assert.equal(semaglutideSpecialistTrials.entries[0].additionalEvidence.length,3);
 assert.equal(item.additionalEvidence.length,9);
 assert.match(item.stage,/all not yet recruiting/i);
 assert.match(item.summary,/low-back-pain/i);
 assert.match(item.summary,/arthroplasty/i);
 assert.match(item.summary,/endometrial atypical hyperplasia/i);
 assert.match(item.ukAuthorisation,/do not establish UK marketing authorisation/i);
 assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/i);
 assert.match(item.supply,/does not establish lawful supply/i);
 assert.match(item.limitations,/no posted results/i);
 assert.ok(semaglutideSpecialistTrials.registryEvidence.every(record=>record.overallStatus==='NOT_YET_RECRUITING'));
 assert.ok(semaglutideSpecialistTrials.registryEvidence.every(record=>record.hasResults===false));
});

test('GLIMR COPD remains planned specialist tirzepatide research, not a UK treatment claim',()=>{
 assert.equal(glimrCopd.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(glimrCopd.clinicalApproval,null);
 assert.equal(glimrCopd.industryComplete,false);
 assert.equal(glimrCopd.automatedMonitorChanges,false);
 assert.equal(glimrCopd.configuredSourcePass.status,'current');
 assert.equal(glimrCopd.configuredSourcePass.currentCount,50);
 const item=industry.find(entry=>entry.id==='glimr-copd-tirzepatide');
 assert.ok(item);
 assert.equal(item.group,'research');
 assert.equal(item.clinicalApproval,null);
 assert.equal(item.sourceIds.length,0);
 assert.equal(item.additionalEvidence.length,1);
 assert.match(item.stage,/not yet recruiting/i);
 assert.match(item.summary,/30 adults with COPD/i);
 assert.match(item.summary,/grip strength/i);
 assert.match(item.summary,/lean mass/i);
 assert.match(item.ukAuthorisation,/does not establish UK marketing authorisation/i);
 assert.match(item.nhsEngland,/No NICE recommendation or NHS England access/i);
 assert.match(item.supply,/does not establish lawful supply/i);
 assert.match(item.limitations,/no posted results/i);
 assert.match(item.limitations,/registry estimates/i);
 assert.equal(glimrCopd.registryEvidence.overallStatus,'NOT_YET_RECRUITING');
 assert.equal(glimrCopd.registryEvidence.hasResults,false);
 assert.equal(glimrCopd.registryEvidence.estimatedEnrollment,30);
});

test('specialist registry follow-up separates active research, planned studies and UK access',()=>{
 assert.equal(specialistRegistryFollowup.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(specialistRegistryFollowup.clinicalApproval,null);
 assert.equal(specialistRegistryFollowup.industryComplete,false);
 assert.equal(specialistRegistryFollowup.automatedMonitorChanges,false);
 assert.equal(specialistRegistryFollowup.configuredSourcePass.status,'current');
 assert.equal(specialistRegistryFollowup.configuredSourcePass.currentCount,50);
 const oncology=industry.find(entry=>entry.id==='tirzepatide-endometrial-research');
 assert.ok(oncology);
 assert.equal(oncology.group,'research');
 assert.equal(oncology.clinicalApproval,null);
 assert.equal(oncology.sourceIds.length,0);
 assert.equal(oncology.additionalEvidence.length,2);
 assert.match(oncology.stage,/Early Phase 1 recruiting/);
 assert.match(oncology.stage,/Phase 2 not yet recruiting/);
 assert.match(oncology.summary,/actual 27 April 2026 start/);
 assert.match(oncology.ukAuthorisation,/do not establish UK marketing authorisation/i);
 assert.match(oncology.nhsEngland,/No NICE recommendation or NHS England access/i);
 assert.match(oncology.supply,/does not establish lawful supply/i);
 assert.match(oncology.limitations,/Neither record has posted results/);
 const active=specialistRegistryFollowup.registryEvidence.find(record=>record.nctId==='NCT07065552');
 const planned=specialistRegistryFollowup.registryEvidence.find(record=>record.nctId==='NCT07078838');
 assert.equal(active.overallStatus,'RECRUITING');
 assert.equal(active.actualStart,'2026-04-27');
 assert.equal(active.hasResults,false);
 assert.equal(planned.overallStatus,'NOT_YET_RECRUITING');
 assert.equal(planned.hasResults,false);
 const survodutide=industry.find(entry=>entry.id==='survodutide');
 assert.match(survodutide.summary,/SYNCHRONIZE-HERA/);
 assert.match(survodutide.summary,/600 women/);
 assert.match(survodutide.limitations,/remains not yet recruiting/);
 assert.ok(survodutide.additionalEvidence.some(source=>source.url==='https://clinicaltrials.gov/study/NCT07850050'));
 assert.equal(specialistRegistryFollowup.preservedCandidates[0].status,'not_yet_recruiting_incomplete');
});

test('switching studies remain planned research and do not inflate programme counts',()=>{
 assert.equal(switchingStudies.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(switchingStudies.clinicalApproval,null);
 assert.equal(switchingStudies.industryComplete,false);
 assert.equal(switchingStudies.automatedMonitorChanges,false);
 assert.equal(switchingStudies.configuredSourcePass.status,'current');
 assert.equal(switchingStudies.configuredSourcePass.currentCount,50);
 assert.equal(industry.length,97);
 const zenagamtide=industry.find(entry=>entry.id==='zenagamtide');
 assert.match(zenagamtide.summary,/switching from maintenance semaglutide/);
 assert.match(zenagamtide.summary,/60 adults/);
 assert.match(zenagamtide.limitations,/not yet recruiting/);
 assert.match(zenagamtide.limitations,/no posted results/);
 assert.match(zenagamtide.limitations,/recommended switching regimen/);
 assert.ok(zenagamtide.additionalEvidence.some(source=>source.url==='https://clinicaltrials.gov/study/NCT07855133'));
 const survodutide=industry.find(entry=>entry.id==='survodutide');
 assert.match(survodutide.summary,/SYNCHRONIZE-START/);
 assert.match(survodutide.summary,/350 adults/);
 assert.match(survodutide.summary,/semaglutide or tirzepatide/);
 assert.match(survodutide.limitations,/not yet recruiting/);
 assert.match(survodutide.limitations,/no posted results/);
 assert.match(survodutide.limitations,/estimated start/);
 assert.ok(survodutide.additionalEvidence.some(source=>source.url==='https://clinicaltrials.gov/study/NCT07855900'));
 assert.ok(switchingStudies.registryEvidence.every(record=>record.overallStatus==='NOT_YET_RECRUITING'));
 assert.ok(switchingStudies.registryEvidence.every(record=>record.hasResults===false));
});

test('NA-931 preserves the sponsor and registry discrepancy without implying access or results',()=>{
 assert.equal(na931Publication.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(na931Publication.clinicalApproval,null);
 assert.equal(na931Publication.industryComplete,false);
 assert.equal(na931Publication.automatedMonitorChanges,false);
 assert.equal(na931Publication.configuredSourcePass.currentCount,50);
 assert.equal(na931Publication.registryEvidence.nctId,'NCT06732245');
 assert.equal(na931Publication.registryEvidence.overallStatus,'NOT_YET_RECRUITING');
 assert.equal(na931Publication.registryEvidence.phase,'PHASE2');
 assert.equal(na931Publication.registryEvidence.estimatedStart,'2026-08-15');
 assert.equal(na931Publication.registryEvidence.hasResults,false);
 assert.equal(na931Publication.priorProposal.candidateId,'na931-tirzepatide');
 assert.equal(earlierEloraNa931Proposal.publicationStatus,'proposal_only');
 assert.ok(earlierEloraNa931Proposal.candidates.some(item=>item.id===na931Publication.priorProposal.candidateId));
 assert.equal(industry.filter(item=>item.id==='na931-tirzepatide').length,1);
 const entry=industry.find(item=>item.id==='na931-tirzepatide');
 assert.ok(entry);
 assert.equal(entry.group,'research');
 assert.equal(entry.clinicalApproval,null);
 assert.match(entry.stage,/Phase 2 registry not yet recruiting/);
 assert.match(entry.stage,/Phase 3 programme sponsor-reported/);
 assert.match(entry.summary,/estimated 224 adults/);
 assert.match(entry.limitations,/already-past 15 August 2026 estimated start/);
 assert.match(entry.limitations,/attributed claims/);
 assert.match(entry.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(entry.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(entry.supply,/do not establish lawful UK retail supply/);
 assert.equal(entry.sourceIds.length,0);
 assert.equal(entry.additionalEvidence.length,2);
 assert.ok(entry.additionalEvidence.some(source=>source.url==='https://clinicaltrials.gov/study/NCT06732245'));
 assert.ok(entry.additionalEvidence.some(source=>source.url==='https://www.biomedind.com/NA-931.html'));
 assert.ok(discoveryDomains.includes('biomedind.com'));
});
test('Survodutide distinguishes peer-reviewed treatment-regimen results from sponsor efficacy estimates',()=>{
 const entry=industry.find(item=>item.id==='survodutide');
 assert.ok(entry);
 assert.match(entry.summary,/treatment-regimen estimand/);
 assert.match(entry.summary,/-9\.8% with 6\.0 mg/);
 assert.match(entry.summary,/-3\.9% with placebo/);
 assert.match(entry.limitations,/not interchangeable with the sponsor's 13\.1% efficacy-estimand figure/);
 assert.match(entry.limitations,/full NEJM article returned HTTP 403 and was not reviewed/);
 assert.doesNotMatch(entry.limitations,/linked NEJM paper was unavailable in this review/);
 assert.equal(entry.clinicalApproval,null);
 const paper=entry.additionalEvidence.find(source=>source.url==='https://pubmed.ncbi.nlm.nih.gov/42820639/');
 assert.ok(paper);
 assert.equal(paper.sourcePublishedAt,'2026-10-01');
 assert.match(paper.checkScope,/complete PubMed bibliographic record and abstract|PubMed abstract read/);
 assert.match(paper.checkScope,/not automatically content-monitored/);
});
test('Azelaprag stays discontinued and preserves the registry and sponsor safety boundaries',()=>{
 assert.equal(azelapragDiscontinuation.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(azelapragDiscontinuation.clinicalApproval,null);
 assert.equal(azelapragDiscontinuation.industryComplete,false);
 const entry=industry.find(item=>item.id==='azelaprag');
 assert.ok(entry);
 assert.equal(entry.group,'discontinued');
 assert.equal(entry.clinicalApproval,null);
 assert.match(entry.stage,/Phase 2 STRIDES terminated/);
 assert.match(entry.stage,/development discontinued/);
 assert.match(entry.summary,/11 of 204 enrolled participants/);
 assert.match(entry.summary,/actual 12 February 2025 completion/);
 assert.match(entry.summary,/development of azelaprag was terminated/);
 assert.match(entry.limitations,/does not independently determine causation/);
 assert.match(entry.limitations,/registry has no posted results/);
 assert.match(entry.limitations,/does not make the laboratory finding clinically unimportant/);
 assert.match(entry.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(entry.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(entry.supply,/does not establish lawful UK retail supply/);
 assert.ok(entry.sourceIds.includes('azelaprag-bioage-discontinuation'));
 assert.ok(entry.additionalEvidence.some(source=>source.url==='https://clinicaltrials.gov/study/NCT06515418'));
 assert.ok(entry.additionalEvidence.some(source=>source.url.includes('sec.gov/Archives/edgar')));
 const registry=azelapragDiscontinuation.registrySources[0];
 assert.equal(registry.lifecycle.status,'TERMINATED');
 assert.equal(registry.lifecycle.enrollment.count,204);
 assert.equal(registry.lifecycle.enrollment.type,'ACTUAL');
 assert.equal(registry.lifecycle.completion.type,'ACTUAL');
 assert.equal(registry.lifecycle.hasResults,false);
 assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
 assert.ok(discoveryDomains.includes('bioagelabs.com'));
});

test('taldefgrobep and RV-8451 preserve clinical-stage and evidence boundaries',()=>{
 assert.equal(taldefgrobepRv8451.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(taldefgrobepRv8451.clinicalApproval,null);
 assert.equal(taldefgrobepRv8451.industryComplete,false);
 const taldefgrobep=industry.find(item=>item.id==='taldefgrobep-alfa');
 assert.ok(taldefgrobep);
 assert.match(taldefgrobep.stage,/Phase 2 active, not recruiting/);
 assert.match(taldefgrobep.summary,/estimated September 2026 completion/);
 assert.match(taldefgrobep.limitations,/no posted results/i);
 assert.match(taldefgrobep.limitations,/no efficacy, muscle-preservation, strength, function, durability, safety, superiority or combination benefit/i);
 assert.match(taldefgrobep.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(taldefgrobep.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(taldefgrobep.supply,/does not establish lawful UK retail supply/);
 const registry=taldefgrobepRv8451.registrySources[0];
 assert.equal(registry.nctId,'NCT07281495');
 assert.equal(registry.lifecycle.status,'ACTIVE_NOT_RECRUITING');
 assert.equal(registry.lifecycle.enrollment.type,'ESTIMATED');
 assert.equal(registry.lifecycle.completion.type,'ESTIMATED');
 assert.equal(registry.lifecycle.hasResults,false);
 assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
 const rv8451=industry.find(item=>item.id==='rv8451');
 assert.ok(rv8451);
 assert.match(rv8451.stage,/Preclinical/);
 assert.match(rv8451.summary,/plans a US IND submission for Q1 2027/);
 assert.match(rv8451.limitations,/do not establish human efficacy/);
 assert.match(rv8451.limitations,/not a completed filing or a started human trial/);
 assert.match(rv8451.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(rv8451.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(rv8451.supply,/do not establish lawful UK retail supply/);
});

test('international maintenance wave preserves separate programme, stage and results boundaries',()=>{
 assert.equal(internationalMaintenanceWave.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(internationalMaintenanceWave.clinicalApproval,null);
 assert.equal(internationalMaintenanceWave.industryComplete,false);
 assert.equal(internationalMaintenanceWave.catalogueCounts.totalAfter,96);
 assert.equal(internationalMaintenanceWave.catalogueCounts.configuredSourcesAfter,139);
 const zynergy=industry.find(item=>item.id==='zynergy-petrelintide-enicepatide');
 assert.ok(zynergy);
 assert.match(zynergy.stage,/not yet recruiting/);
 assert.match(zynergy.summary,/estimated 30 September 2026 start date has passed/);
 assert.match(zynergy.limitations,/no posted results/i);
 assert.match(zynergy.limitations,/separate from both monotherapy programmes/i);
 const mazdutide=industry.find(item=>item.id==='mazdutide');
 assert.match(mazdutide.stage,/recruiting weight-maintenance research/);
 assert.match(mazdutide.summary,/NCT07517042/);
 assert.match(mazdutide.limitations,/no posted results/i);
 const aleniglipron=industry.find(item=>item.id==='aleniglipron');
 assert.match(aleniglipron.stage,/ACCOMPLISH-2 recruiting/);
 assert.match(aleniglipron.summary,/NCT07654374/);
 assert.match(aleniglipron.limitations,/no posted results/i);
 for(const registry of internationalMaintenanceWave.registrySources){
  assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
  assert.equal(registry.lifecycle.hasResults,false);
  assert.ok(registry.entryIds.length===1);
 }
 assert.equal(internationalMaintenanceWave.registrySources.find(s=>s.nctId==='NCT07589686').lifecycle.start.type,'ESTIMATED');
 assert.equal(internationalMaintenanceWave.registrySources.find(s=>s.nctId==='NCT07517042').lifecycle.start.type,'ACTUAL');
 assert.equal(internationalMaintenanceWave.registrySources.find(s=>s.nctId==='NCT07654374').lifecycle.status,'RECRUITING');
});

test('programme-level Novo and specialist discovery preserves indication and evidence boundaries',()=>{
 assert.equal(novoSpecialistWave.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(novoSpecialistWave.clinicalApproval,null);
 assert.equal(novoSpecialistWave.industryComplete,false);
 assert.equal(novoSpecialistWave.catalogueCounts.totalAfter,97);
 assert.equal(novoSpecialistWave.catalogueCounts.configuredSourcesAfter,146);
 const nnc0721=industry.find(item=>item.id==='nnc07218060');
 assert.ok(nnc0721);
 assert.match(nnc0721.stage,/Recruiting first-in-human Phase 1/);
 assert.match(nnc0721.limitations,/does not state a mechanism/);
 assert.match(nnc0721.limitations,/no posted results/);
 const nnc0662=industry.find(item=>item.id==='nnc06620419');
 assert.match(nnc0662.stage,/Phase 2 obesity and type 2 diabetes/);
 assert.match(nnc0662.summary,/NCT07184632/);
 assert.match(nnc0662.summary,/NCT07639021/);
 assert.match(nnc0662.limitations,/must not be presented as weight-management evidence/);
 const survodutide=industry.find(item=>item.id==='survodutide');
 assert.match(survodutide.stage,/type 2 diabetes programmes/);
 assert.match(survodutide.summary,/NCT07754461/);
 assert.match(survodutide.limitations,/must not be presented as a completed weight-management result/);
 assert.equal(novoSpecialistWave.registrySources.length,7);
 for(const registry of novoSpecialistWave.registrySources){
  assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
  assert.equal(registry.lifecycle.hasResults,false);
 }
 assert.equal(novoSpecialistWave.failedChecks.length,2);
 assert.match(novoSpecialistWave.failedChecks[0].outcome,/timed out/);
});

test('Petrelintide ZUPREME review distinguishes sponsor initiation from registry recruitment',()=>{
 assert.equal(petrelintideZupreme.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(petrelintideZupreme.clinicalApproval,null);
 assert.equal(petrelintideZupreme.industryComplete,false);
 assert.equal(petrelintideZupreme.catalogueCounts.totalAfter,97);
 assert.equal(petrelintideZupreme.catalogueCounts.configuredSourcesAfter,149);
 const petrelintide=industry.find(item=>item.id==='petrelintide');
 assert.match(petrelintide.stage,/three records not yet recruiting/);
 assert.match(petrelintide.summary,/ZUPREME-3, ZUPREME-4 and ZUPREME-5/);
 assert.match(petrelintide.summary,/list no study locations/);
 assert.match(petrelintide.limitations,/passed estimated start date is not treated as dosing/);
 assert.match(petrelintide.limitations,/specialist-indication research/);
 assert.equal(petrelintideZupreme.registrySources.length,3);
 for(const registry of petrelintideZupreme.registrySources){
  assert.equal(registry.lifecycle.status,'NOT_YET_RECRUITING');
  assert.equal(registry.lifecycle.start.type,'ESTIMATED');
  assert.equal(registry.lifecycle.start.date,'2026-09-30');
  assert.equal(registry.lifecycle.hasResults,false);
  assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
 }
 assert.equal(petrelintideZupreme.configuredSourcePass.currentSources,145);
 assert.equal(petrelintideZupreme.configuredSourcePass.attention[0].id,'zealand-zp6590-pipeline');
});

test('ribupatide specialist wave keeps formulation, indication and conflicting evidence separate',()=>{
 assert.equal(ribupatideSpecialistWave.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(ribupatideSpecialistWave.clinicalApproval,null);
 assert.equal(ribupatideSpecialistWave.industryComplete,false);
 assert.equal(ribupatideSpecialistWave.catalogueCounts.totalAfter,97);
 assert.equal(ribupatideSpecialistWave.catalogueCounts.configuredSourcesAfter,157);
 const injection=industry.find(item=>item.id==='ribupatide-injection');
 assert.match(injection.stage,/specialist-indication studies active/);
 assert.match(injection.summary,/9,262-participant Phase 3 cardiovascular-outcomes study/);
 assert.match(injection.summary,/active-not-recruiting 48-participant Phase 1 adolescent-obesity study/);
 assert.match(injection.summary,/older registry record remains UNKNOWN/);
 assert.match(injection.limitations,/sponsor-reported topline results/);
 assert.match(injection.limitations,/None establishes UK authorisation/);
 const oral=industry.find(item=>item.id==='ribupatide-oral');
 assert.match(oral.stage,/Recruiting China Phase III/);
 assert.match(oral.summary,/NCT07670884/);
 assert.match(oral.limitations,/does not establish that the separately planned global Phase 3 programme has started/);
 const hrs4729=industry.find(item=>item.id==='kai4729');
 assert.match(hrs4729.stage,/recruiting China Phase II MASH study/);
 assert.match(hrs4729.summary,/separate HRS-4729, ribupatide and matching-placebo arms/);
 assert.equal(ribupatideSpecialistWave.registrySources.length,7);
 assert.equal(ribupatideSpecialistWave.registrySources.find(s=>s.nctId==='NCT07551492').lifecycle.enrollment.count,9262);
 assert.equal(ribupatideSpecialistWave.registrySources.find(s=>s.nctId==='NCT06595797').lifecycle.status,'UNKNOWN');
 assert.ok(ribupatideSpecialistWave.registrySources.every(s=>!s.lifecycle.hasResults&&/^[a-f0-9]{64}$/.test(s.reviewedFingerprint)));
 assert.equal(ribupatideSpecialistWave.configuredSourcePass.currentSources,148);
 assert.equal(ribupatideSpecialistWave.configuredSourcePass.attention[0].id,'zealand-zp6590-pipeline');
});

test('GZC8072 promotion separates trial initiation, estimates and UK access',()=>{
 assert.equal(gzc8072Publication.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(gzc8072Publication.clinicalApproval,null);
 assert.equal(gzc8072Publication.industryComplete,false);
 assert.equal(gzc8072Publication.catalogueCounts.totalAfter,98);
 assert.equal(gzc8072Publication.catalogueCounts.configuredSourcesAfter,159);
 const entry=industry.find(item=>item.id==='gzc8072');
 assert.match(entry.stage,/Recruiting China Phase 1/);
 assert.match(entry.stage,/once-weekly oral peptide/);
 assert.match(entry.summary,/actual 2 September 2026 start/);
 assert.match(entry.limitations,/planned 112 participants/);
 assert.match(entry.limitations,/estimates 126/);
 assert.match(entry.limitations,/no posted results/);
 assert.match(entry.ukAuthorisation,/not a marketing authorisation/);
 assert.match(entry.supply,/do not establish lawful UK retail supply/);
 assert.deepEqual(entry.sourceIds,['ganlee-gzc8072-20260907']);
 const registry=gzc8072Publication.registrySources[0];
 assert.equal(registry.lifecycle.status,'RECRUITING');
 assert.deepEqual(registry.lifecycle.start,{date:'2026-09-02',type:'ACTUAL'});
 assert.deepEqual(registry.lifecycle.enrollment,{count:126,type:'ESTIMATED'});
 assert.equal(registry.lifecycle.hasResults,false);
 assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
 const sponsor=industrySources.find(source=>source.id==='ganlee-gzc8072-20260907');
 assert.equal(sponsor.reviewedAt,gzc8072Publication.reviewedAt);
 assert.match(sponsor.reviewedFingerprint,/^[a-f0-9]{64}$/);
});

test('ASC30 AURORA correction separates trial populations, estimates and planned events',()=>{
 assert.equal(asc30AuroraCorrection.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(asc30AuroraCorrection.clinicalApproval,null);
 assert.equal(asc30AuroraCorrection.industryComplete,false);
 assert.equal(asc30AuroraCorrection.catalogueCounts.totalAfter,98);
 assert.equal(asc30AuroraCorrection.catalogueCounts.configuredSourcesAfter,162);
 const entry=industry.find(item=>item.id==='asc30-oral');
 assert.match(entry.stage,/Recruiting global Phase 3 AURORA programme/);
 assert.match(entry.stage,/completed Phase 2/i);
 assert.match(entry.summary,/AURORA-1 studies adults.*without type 2 diabetes/);
 assert.match(entry.summary,/AURORA-2 studies adults.*and type 2 diabetes/);
 assert.match(entry.limitations,/3,003 and 1,560 participants/);
 assert.match(entry.limitations,/approximately 4,600/);
 assert.match(entry.limitations,/not actual enrolment/);
 assert.match(entry.limitations,/(?:no|neither registry has) posted results/i);
 assert.match(entry.limitations,/plans, not completed events/);
 assert.match(entry.ukAuthorisation,/not UK approval/);
 assert.match(entry.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(entry.supply,/do not establish lawful UK retail supply/);
 assert.ok(entry.sourceIds.includes('ascletis-asc30-aurora-first-dose-20260830'));
 assert.ok(entry.additionalEvidence.some(source=>source.url==='https://clinicaltrials.gov/study/NCT07743463'));
 assert.ok(entry.additionalEvidence.some(source=>source.url==='https://clinicaltrials.gov/study/NCT07743450'));
 assert.equal(asc30AuroraCorrection.registrySources.length,2);
 for(const registry of asc30AuroraCorrection.registrySources){
  assert.equal(registry.lifecycle.status,'RECRUITING');
  assert.equal(registry.lifecycle.start.type,'ACTUAL');
  assert.equal(registry.lifecycle.completion.type,'ESTIMATED');
  assert.equal(registry.lifecycle.hasResults,false);
  assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
 }
 assert.deepEqual(asc30AuroraCorrection.registrySources.find(source=>source.nctId==='NCT07743463').lifecycle.enrollment,{count:3003,type:'ESTIMATED'});
 assert.deepEqual(asc30AuroraCorrection.registrySources.find(source=>source.nctId==='NCT07743450').lifecycle.enrollment,{count:1560,type:'ESTIMATED'});
 const sponsor=industrySources.find(source=>source.id==='ascletis-asc30-aurora-first-dose-20260830');
 assert.equal(sponsor.reviewedAt,asc30AuroraCorrection.reviewedAt);
 assert.match(sponsor.reviewedFingerprint,/^[a-f0-9]{64}$/);
});

test('Hansoh source review renews only the read claim-bearing baseline',()=>{
 assert.equal(hansohOlatorepatideReview.publicationStatus,'owner_authorised_source_review');
 assert.equal(hansohOlatorepatideReview.clinicalApproval,null);
 assert.equal(hansohOlatorepatideReview.industryComplete,false);
 assert.equal(hansohOlatorepatideReview.medicineWordingChanged,false);
 assert.equal(hansohOlatorepatideReview.monitoring.thresholdsChanged,false);
 assert.equal(hansohOlatorepatideReview.monitoring.successesSeeded,false);
 assert.match(hansohOlatorepatideReview.monitoring.result,/complete primary-source read/);
 const source=industrySources.find(item=>item.id==='hansoh-olatorepatide-20260604');
 assert.equal(source.reviewedAt,hansohOlatorepatideReview.reviewedAt);
 assert.equal(source.reviewedFingerprint,hansohOlatorepatideReview.source.reviewedFingerprint);
 assert.notEqual(source.reviewedFingerprint,hansohOlatorepatideReview.monitoring.previousReviewedFingerprint);
 const entry=industry.find(item=>item.id==='olatorepatide');
 assert.equal(entry.reviewedAt,hansohOlatorepatideReview.reviewedAt);
 assert.match(entry.stage,/Chinese NDA accepted following Phase III/);
 assert.match(entry.summary,/Acceptance is not marketing approval/);
 assert.match(entry.ukAuthorisation,/Not established.*reviewed evidence/);
 assert.match(entry.nhsEngland,/no routine access claim/i);
 assert.match(entry.supply,/stock unverified/i);
});

test('ARD-201 keeps the initiated trial, planned trial, pause and ARD-101 hold distinct',()=>{
 assert.equal(ard201Pause.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(ard201Pause.clinicalApproval,null);
 assert.equal(ard201Pause.industryComplete,false);
 assert.equal(ard201Pause.catalogueCounts.totalAfter,99);
 assert.equal(ard201Pause.catalogueCounts.configuredSourcesAfter,162);
 const entry=industry.find(item=>item.id==='ard201');
 assert.ok(entry);
 assert.equal(entry.group,'paused');
 assert.match(entry.stage,/POWER initiated, then voluntarily paused/);
 assert.match(entry.summary,/POWER began in December 2025/);
 assert.match(entry.summary,/STRENGTH was planned/);
 assert.match(entry.summary,/27 February 2026/);
 assert.match(entry.limitations,/clinical hold described in the filing applies to the ARD-101 IND/);
 assert.match(entry.limitations,/does not infer causation, severity, a restart, termination or a timetable/);
 assert.match(entry.ukAuthorisation,/does not establish UK marketing authorisation/);
 assert.match(entry.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(entry.supply,/does not establish lawful UK retail supply/);
 assert.equal(entry.sourceIds.length,0);
 assert.equal(entry.additionalEvidence.length,3);
});

test('oral ASC36 promotion stays formulation-specific and does not invent registry status',()=>{
 assert.equal(asc36OralPublication.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(asc36OralPublication.clinicalApproval,null);
 assert.equal(asc36OralPublication.industryComplete,false);
 assert.equal(asc36OralPublication.catalogueCounts.totalAfter,100);
 assert.equal(asc36OralPublication.catalogueCounts.configuredSourcesAfter,163);
 const entry=industry.find(item=>item.id==='asc36-oral');
 assert.ok(entry);
 assert.equal(entry.group,'research');
 assert.match(entry.stage,/US Phase 1 initiation sponsor-reported/);
 assert.match(entry.summary,/86 participants/);
 assert.match(entry.summary,/separate from ASC36 subcutaneous injection/);
 assert.match(entry.limitations,/does not identify first dosing, recruitment status/);
 assert.match(entry.limitations,/ClinicalTrials.gov API searches returned no matching public record/);
 assert.match(entry.limitations,/not proof that no registry or other record exists/);
 assert.match(entry.limitations,/non-human primates or rats/);
 assert.match(entry.ukAuthorisation,/not marketing approval in the US or UK/);
 assert.match(entry.nhsEngland,/No NICE recommendation or NHS England access/);
 assert.match(entry.supply,/does not establish lawful UK retail supply/);
 assert.deepEqual(entry.sourceIds,['ascletis-asc36-oral-phase1-20260908']);
 const source=industrySources.find(item=>item.id==='ascletis-asc36-oral-phase1-20260908');
 assert.equal(source.reviewedAt,asc36OralPublication.reviewedAt);
 assert.equal(source.contentSelector,'.team_text');
 assert.match(source.reviewedFingerprint,/^[a-f0-9]{64}$/);
 assert.equal(asc36OralPublication.discoveryPass.failedChecks.length,0);
});

test("710GO keeps sponsor dosing separate from animal findings and unknown registry",()=>{const e=industry.find(e=>e.id==='710go');assert.ok(e);assert.equal(e.clinicalApproval,null);assert.deepEqual(e.sourceIds,[]);assert.match(e.stage,/Sponsor-reported first dosing in Phase 1/);assert.match(e.limitations,/no human trial results/);assert.match(e.limitations,/registry discovery remains incomplete/);assert.match(e.limitations,/preclinical studies/);assert.match(e.additionalEvidence[0].checkScope,/HTTP 403/);assert.equal(e.additionalEvidence[0].sourcePublishedAt,'2026-05-28');assert.equal(e.additionalEvidence[0].sourceUpdatedAt,null);const html=industryMarkup({},new URLSearchParams({q:'710GO'}));assert.match(html,/710GO/);assert.match(html,/prnewswire.com/);});

test('SYNCHRONIZE-JP keeps sponsor results separate from the registry lifecycle and UK status',()=>{
 const entry=industry.find(e=>e.id==='survodutide');
 const registry=registrySources.find(s=>s.id==='registry-nct06176365');
 assert.ok(entry);assert.ok(registry);assert.equal(entry.clinicalApproval,null);
 assert.match(entry.stage,/Japanese Phase 3 sponsor results reported/);
 assert.match(entry.summary,/SYNCHRONIZE-JP/);assert.match(entry.summary,/274 participants/);
 assert.match(entry.summary,/-12\.5%/);assert.match(entry.summary,/-13\.1%/);
 assert.match(entry.limitations,/sponsor-reported conference results/);
 assert.match(entry.limitations,/MRI findings concern a subset/);
 assert.match(entry.limitations,/do not establish muscle strength, function or a muscle-preservation benefit/);
 assert.match(entry.limitations,/must not be treated as a UK indication/);
 assert.equal(registry.lifecycle.status,'COMPLETED');assert.equal(registry.lifecycle.enrollment.type,'ACTUAL');assert.equal(registry.lifecycle.hasResults,false);
 assert.equal(registry.sourcePublishedAt,'2023-12-19');assert.equal(registry.sourceUpdatedAt,'2026-04-30');
 assert.match(registry.reviewedFingerprint,/^[a-f0-9]{64}$/);
 const sponsor=entry.additionalEvidence.find(s=>s.url==='https://www.boehringer-ingelheim.com/jp/press-26-1005');assert.ok(sponsor);assert.match(sponsor.checkScope,/HTTP 403/);
});

test('MariTide and enicepatide lifecycle additions preserve status, estimates and absent results',()=>{
 assert.equal(coreTrialLifecycle.publicationStatus,'owner_authorised_factual_publication');
 assert.equal(coreTrialLifecycle.clinicalApproval,null);
 assert.equal(coreTrialLifecycle.industryComplete,false);
 assert.equal(coreTrialLifecycle.catalogueCounts.totalAfter,103);
 assert.equal(coreTrialLifecycle.catalogueCounts.configuredSourcesAfter,176);
 assert.equal(coreTrialLifecycle.registrySources.length,4);
 const maritide=industry.find(e=>e.id==='maritide');
 assert.match(maritide.stage,/extension and cardiovascular-outcomes studies recruiting/);
 assert.match(maritide.summary,/MARITIME-1-EXTENSION/);
 assert.match(maritide.summary,/cardiovascular-outcomes study/);
 assert.match(maritide.limitations,/enrolment of 12,800 remain estimates/);
 assert.match(maritide.limitations,/study arms, not approved regimens/);
 const enicepatide=industry.find(e=>e.id==='enicepatide');
 assert.match(enicepatide.summary,/NCT06525935/);
 assert.match(enicepatide.summary,/469 actual participants/);
 assert.match(enicepatide.limitations,/no posted results/);
 for(const source of coreTrialLifecycle.registrySources){
  assert.equal(source.lifecycle.hasResults,false);
  assert.match(source.reviewedFingerprint,/^[a-f0-9]{64}$/);
  assert.ok(registrySources.some(item=>item.id===source.id));
 }
});
