import {industry,industrySources} from './industry.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/London'}).format(new Date(v)):'Not stated by the source';
const labels={established:'Established and specialist',research:'Research programme',paused:'Paused programme',discontinued:'Discontinued programme'};
export function industryMarkup(health={},query=new URLSearchParams()) {
 const q=(query.get('q')||'').slice(0,100).toLowerCase();
 const group=Object.hasOwn(labels,query.get('industry'))?query.get('industry'):'';
 const uk=query.get('status');
 const selected=industry.filter(e=>(!q||[e.name,e.stage,e.summary].join(' ').toLowerCase().includes(q))&&(!group||e.group===group)&&(!['authorised','investigational'].includes(uk)||(uk==='authorised'?e.group==='established':e.group==='research')));
 return `<section id="industry-watch" aria-label="Wider industry watch"><h2>Wider industry watch</h2><p>${industry.length} additional medicines and programmes: established treatments, specialist indications, active research and programmes that stopped. These concise evidence summaries are not full prescribing guides. Trial stage, UK authorisation, NHS access and actual supply are separate.</p><p class="mw-result">Showing ${selected.length} of ${industry.length} industry summaries. The medicine-form filter above applies to the detailed reference cards only.</p>${selected.map(e=>`<details class="mw-card" id="industry-${esc(e.id)}" data-industry-card><summary><div><span class="mw-tag mw-tag-research">${labels[e.group]}</span><h3>${esc(e.name)}</h3><p>${esc(e.stage)}</p></div></summary><div class="mw-card-content"><p class="mw-review">Evidence summary reviewed ${date(e.reviewedAt)} · Factual source review, not clinical approval</p><p>${esc(e.summary)}</p><div class="mw-card-grid"><section class="mw-cell"><h4>UK authorisation</h4><p>${esc(e.ukAuthorisation)}</p></section><section class="mw-cell"><h4>NHS — England</h4><p>${esc(e.nhsEngland)}</p></section><section class="mw-cell"><h4>Actual supply</h4><p>${esc(e.supply)}</p></section><section class="mw-cell"><h4>Limits and uncertainty</h4><p>${esc(e.limitations)}</p></section></div><ul>${e.sourceIds.map(id=>{const s=industrySources.find(s=>s.id===id),h=health.sources?.find(s=>s.id===id);const status={current:'Source unchanged',awaiting_review:'Source review required',check_delayed:'Source check delayed',verification_pending:'Verification pending'}[s.reviewedFingerprint?h?.status:'verification_pending']||'Verification pending';return `<li><a href="${esc(s.url)}" rel="noopener noreferrer">${esc(s.title)}</a><small>${esc(s.evidenceType)} · Published/updated: ${date(s.sourcePublishedAt)} · Source review: ${date(s.reviewedAt)} · ${status}${!s.reviewedFingerprint?' · Complete-response baseline not yet verified':''}</small></li>`;}).join('')}${(e.additionalEvidence||[]).map(s=>`<li><a href="${esc(s.url)}" rel="noopener noreferrer">${esc(s.title)}</a><small>Published ${date(s.sourcePublishedAt)} · Reviewed ${date(s.reviewedAt)} · ${esc(s.checkScope)}</small></li>`).join('')}</ul></div></details>`).join('')||'<p>No industry summaries match these filters.</p>'}</section>`;
}
