import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {TREATMENTS_ENTRY,TREATMENTS_ENTRY_START,TREATMENTS_ENTRY_END,TREATMENT_RELATED_LEGACY as oldGuide,TREATMENT_RELATED_CURRENT as newGuide,publicPageEvidence,assertPublicPagesPreserved} from './preservation.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
const fp=(body,required=true)=>publicPageEvidence('/treatment-centre',200,body,{hash,requireTreatmentsEntry:required});
const page=(guide=oldGuide,entry=TREATMENTS_ENTRY)=>'<html><head><style>section[data-shift-link-repair]{color:#E7E3DA}section[data-shift-link-repair] a{color:inherit}</style></head><body><main><h1>Treatments</h1><p>Existing approved content.</p>'+guide+entry+'</main></body></html>';
test('unchanged existing entry and current links pass',()=>{const a=fp(page(newGuide));assert.equal(assertPublicPagesPreserved([a],[a]),'identical')});
test('exact approved link update passes with the already-live Watch entry retained',()=>{const a=fp(page(oldGuide)),b=fp(page(newGuide));assert.equal(assertPublicPagesPreserved([b],[a]),'preserved_with_exact_authority_links');assert.notEqual(a.sha256,b.sha256);assert.equal(a.authoritySha256,b.authoritySha256)});
test('first Watch addition still passes only at exact approved content',()=>{const a=fp(page(oldGuide,''),false),b=fp(page(newGuide));assert.equal(assertPublicPagesPreserved([b],[a]),'preserved_with_treatments_watch_entry')});
test('CSS attribute selectors are not counted as extra sections',()=>{assert.equal(fp(page()).relatedGuide,true)});
test('changed destination, added link, copy alteration or empty section cannot hide behind marker',()=>{for(const bad of [newGuide.replace('href="/comparisons/medications/mounjaro-vs-saxenda"','href="https://unapproved.example"'),newGuide.replace('</ul>','<li>Unapproved</li></ul>'),newGuide.replace('Planning around treatment','Changed'),'<section data-shift-link-repair></section>'])assert.throws(()=>fp(page(bad)),/differs/)});
test('missing and duplicate related-guide sections fail closed',()=>{assert.throws(()=>fp(page('')),/exactly one/);assert.throws(()=>fp(page(oldGuide+newGuide)),/exactly one/)});
test('unrelated text, CSS or H1 change remains hash-locked',()=>{for(const [from,to] of [['Existing approved content.','Changed content.'],['#E7E3DA','#000000'],['<h1>Treatments','<h1>Changed']]){assert.throws(()=>assertPublicPagesPreserved([fp(page(newGuide).replace(from,to))],[fp(page())]),/changed outside/)}});
test('moving an approved block is rejected',()=>{const moved=page('').replace('<h1>',newGuide+'<h1>');assert.throws(()=>assertPublicPagesPreserved([fp(moved)],[fp(page())]),/changed outside/)});
test('moving an existing Watch entry is rejected even when links change',()=>{const moved=TREATMENTS_ENTRY+page(newGuide,'');assert.throws(()=>assertPublicPagesPreserved([fp(moved)],[fp(page())]),/changed outside/)});
test('altered, duplicate and malformed Watch entries are rejected',()=>{for(const e of [TREATMENTS_ENTRY+TREATMENTS_ENTRY,TREATMENTS_ENTRY_START,TREATMENTS_ENTRY_END+TREATMENTS_ENTRY_START,TREATMENTS_ENTRY.replace('Explore the watch','Unexpected wording')])assert.throws(()=>fp(page(oldGuide,e)),/markers|differs/);assert.throws(()=>fp(page(oldGuide,'')),/missing/)});
test('path and response status changes remain rejected',()=>{const a=fp(page());assert.throws(()=>assertPublicPagesPreserved([{...a,status:404}],[a]),/status changed/);assert.throws(()=>assertPublicPagesPreserved([{...a,path:'/other'}],[a]),/paths changed/)});
test('other pages and login retain byte-exact hashes',()=>{for(const path of ['/','/start-here','/programme','/about','/member-login']){const a=publicPageEvidence(path,200,'Original',{hash}),b=publicPageEvidence(path,200,'Changed',{hash});assert.throws(()=>assertPublicPagesPreserved([b],[a]),/changed outside/)}});
test('SHIFT Health accepts only the exact approved Twitter image addition',()=>{const path='/shift-health',tag='<meta name="twitter:image" content="https://shiftsometimber.co.uk/assets/og-default.jpg">',a=publicPageEvidence(path,200,'Original',{hash}),b=publicPageEvidence(path,200,'Original'+tag,{hash});assert.equal(assertPublicPagesPreserved([b],[a]),'identical');assert.throws(()=>publicPageEvidence(path,200,'Original'+tag+tag,{hash}),/duplicate/);assert.throws(()=>assertPublicPagesPreserved([a],[b]),/missing/);assert.throws(()=>assertPublicPagesPreserved([publicPageEvidence(path,200,'Original'+tag.replace('og-default.jpg','wrong.jpg'),{hash})],[a]),/changed outside/)});

test('homepage preservation allows only the exact approved stigma alt improvement',()=>{
 const path='/',base='<html><body><img class="stigma" src="/assets/home-stigma-ruffled-v42p5.webp?v=1" alt=""><p>Keep</p></body></html>',approved=base.replace('alt=""','alt="Men&#39;s health stigma and asking for support"');
 const a=publicPageEvidence(path,200,base,{hash}),b=publicPageEvidence(path,200,approved,{hash});
 assert.equal(assertPublicPagesPreserved([b],[a]),'identical');
 assert.equal(a.preservedSha256,b.preservedSha256);
 assert.equal(b.homeStigmaAlt,true);
 assert.throws(()=>publicPageEvidence(path,200,base.replace('alt=""','alt="Different wording"'),{hash}),/alt differs/);
 assert.throws(()=>publicPageEvidence(path,200,base+base.match(/<img[^>]+>/)[0],{hash}),/duplicate/);
 const changed=publicPageEvidence(path,200,approved.replace('<p>Keep</p>','<p>Changed</p>'),{hash});
 assert.throws(()=>assertPublicPagesPreserved([changed],[a]),/changed outside/);
});
