import {chromium,webkit} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const base=process.env.PREVIEW_URL;assert.equal(base,'https://shift-stabilisation-preview.matobrien.workers.dev');const dir='account-completion-evidence/email-browser';fs.mkdirSync(dir,{recursive:true});const results=[],fixture=JSON.parse(fs.readFileSync('work/staging/generated/probe.json','utf8'));let index=0;
for(const [name,engine,width,height]of [['chromium-desktop',chromium,1280,900],['chromium-phone',chromium,390,844],['webkit-desktop',webkit,1280,900],['webkit-phone',webkit,390,844]]){
 const browser=await engine.launch(),context=await browser.newContext({viewport:{width,height}}),page=await context.newPage(),oldEmail='probe'+fixture.browserIds[index++]+'@example.invalid',newEmail='new-'+crypto.randomUUID()+'@example.invalid',password=fixture.password;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  // Reuse this build's seeded fictional member; do not consume public review account slots.
  const login=await context.request.post(base+'/v1/auth/login',{headers:{Origin:base},data:{email:oldEmail,password}});assert(login.ok(),'Fictional fixture sign-in failed');
  const original=(await (await context.request.get(base+'/v1/member/details')).json()).details;
  await page.goto(base+'/member/settings#memberEmailChangePanel');await page.locator('#memberEmailChangePanel').waitFor({state:'visible'});
  await page.locator('#memberEmailChangePassword').fill(password);await page.locator('#memberEmailChangeNew').fill(newEmail);await page.locator('#memberEmailChangeConfirm').fill(newEmail);await page.locator('#memberEmailChangeSubmit').click();await page.waitForFunction(()=>document.getElementById('memberEmailChangeStatus').textContent.startsWith('Pending:'),null,{timeout:30000});
  assert.equal(await page.locator('#memberEmailChangePassword').inputValue(),'');assert.equal(await page.locator('#memberEmail').inputValue(),oldEmail);
  const inbox=await (await context.request.get(base+'/__preview/email-inbox')).json();assert(inbox.fictional&&!inbox.realMailSent);assert.equal(inbox.messages.length,2);
  const old=inbox.messages.find(m=>m.recipient===oldEmail),next=inbox.messages.find(m=>m.recipient===newEmail);assert(old&&next);
  const link=m=>m.body_text.match(/https:\/\/[^\s]+/)[0];const oldPage=await context.newPage();await oldPage.goto(link(old));await oldPage.locator('#emailConfirmationAction').waitFor({state:'visible'});assert(!oldPage.url().includes('#'));assert((await (await context.request.get(base+'/v1/member/details')).json()).details.email===oldEmail);
  await oldPage.locator('#emailConfirmationAction').click();await oldPage.waitForFunction(()=>document.getElementById('emailConfirmationStatus').textContent.includes('other mailbox'));assert((await (await context.request.get(base+'/v1/member/details')).json()).details.email===oldEmail);
  const nextPage=await context.newPage();await nextPage.goto(link(next));await nextPage.locator('#emailConfirmationAction').click();await nextPage.waitForFunction(()=>document.getElementById('emailConfirmationStatus').textContent.startsWith('Your email has changed.'));
  assert.equal((await context.request.get(base+'/v1/member/details')).status(),401);
  const oldLogin=await context.request.post(base+'/v1/auth/login',{headers:{Origin:base},data:{email:oldEmail,password}});assert(!oldLogin.ok());
  await page.goto(base+'/staging/sign-in');await page.locator('input[name="email"]').fill(newEmail);await page.locator('input[name="password"]').fill(password);await page.locator('#stage-auth button[type="submit"]').click();await page.waitForURL('**/member/dashboard');await page.goto(base+'/member/settings#memberEmailChangePanel');await page.waitForFunction(()=>document.getElementById('memberDetailsFields')?.disabled===false);assert.equal(await page.locator('#memberEmail').inputValue(),newEmail);
  const after=(await (await context.request.get(base+'/v1/member/details')).json()).details;assert.deepEqual({...after,email:oldEmail},original);
  await page.locator('#memberEmailChangePanel').scrollIntoViewIfNeeded();await page.screenshot({path:dir+'/'+name+'-completed.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);
  results.push({name,status:'PASS',mailSimulated:true,realMailSent:false,passwordReentry:true,bothConfirmations:true,getLinksNonMutating:true,fragmentsRemoved:true,oldSessionsRevoked:true,oldLoginRejected:true,newLoginPassed:true,accountPreserved:true,noOverflow:true,pageErrors:errors});
 }catch(e){results.push({name,status:'FAIL',message:e.message.replaceAll(password,'[REDACTED]'),pageErrors:errors});await page.screenshot({path:dir+'/'+name+'-failure.png',fullPage:true}).catch(()=>{});}finally{await context.close();await browser.close();fs.writeFileSync(dir+'/results.json',JSON.stringify({source:process.env.PREVIEW_SOURCE_SHA,previewOnly:true,realEmailDelivery:false,physicalDevices:false,results},null,2));}
}
console.log(JSON.stringify(results,null,2));assert.equal(results.filter(r=>r.status==='FAIL').length,0);
