// Real provider probes are deliberately limited to the first browser case.
// Remaining UI/failure/race cases use labelled fixtures and make no upstream call.
import {chromium,webkit} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const base=process.env.PREVIEW_URL;assert.equal(base,'https://shift-stabilisation-preview.matobrien.workers.dev');
const fixture=JSON.parse(fs.readFileSync('work/staging/generated/probe.json','utf8')),dir='account-completion-evidence/photon-browser';fs.mkdirSync(dir,{recursive:true});
const sample=(postcode='SW1A 1AA',a='Buckingham Palace, Buckingham Gate',town='London')=>({ok:true,addresses:[{address1:a,address2:'',town,county:'',postcode,label:[a,town,postcode].join(', ')}],source:'Photon / OpenStreetMap',complete:false,postalValidation:false,needsReview:true});
const report={source:process.env.PREVIEW_SOURCE_SHA,previewOnly:true,physicalDevices:false,realProviderCalls:0,cases:[]};
const save=()=>fs.writeFileSync(dir+'/results.json',JSON.stringify(report,null,2));
const cases=[['chromium-desktop',chromium,1440,1000],['chromium-phone',chromium,390,844],['webkit-desktop',webkit,1440,1000],['webkit-phone',webkit,390,844]];
for(let i=0;i<cases.length;i++){
 const [name,engine,width,height]=cases[i],browser=await engine.launch(),context=await browser.newContext({viewport:{width,height}}),page=await context.newPage(),row={name,phase:'login',checks:[],status:'running',provider:i===0?'actual Photon via hosted Worker':'fixture UI only'};report.cases.push(row);const errors=[],requests=[],direct=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{const u=new URL(r.url());if(u.host==='photon.komoot.io')direct.push(r.url());if(u.pathname==='/v1/member/details/address-search')requests.push({method:r.method(),url:u.pathname+u.search,data:r.postDataJSON()});});
 try{
  const r=await context.request.post(base+'/v1/auth/login',{headers:{Origin:base},data:{email:'probe'+fixture.browserIds[i]+'@example.invalid',password:fixture.password}});assert(r.ok(),'Fictional fixture sign-in failed');
  await page.goto(base+'/member/settings#memberDetailsPanel');await page.waitForFunction(()=>document.querySelector('#memberDetailsFields')?.disabled===false&&document.querySelector('#memberDeliveryFields')?.disabled===false);
  await page.locator('#memberPostcode').fill('SW1A 1AA');await page.locator('#memberAddressQuery').fill('Buckingham Palace');await page.locator('#memberAddress2').fill('Keep my flat detail');assert.equal(requests.length,0);row.checks.push('Typing does not query any provider');
  if(i>0)await page.route('**/v1/member/details/address-search',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(sample())}));
  row.phase='explicit-home-search';const response=page.waitForResponse(r=>r.url()===base+'/v1/member/details/address-search'&&r.request().method()==='POST');await page.locator('#memberFindAddress').click();const res=await response,b=await res.json();assert.equal(res.status(),200,JSON.stringify(b));if(i===0){report.realProviderCalls++;fs.writeFileSync(dir+'/actual-home-provider.json',JSON.stringify(b,null,2));}
  assert(b.addresses.length>0,'Public landmark address was not returned');assert.equal(b.postalValidation,false);assert(b.addresses.every(a=>a.postcode==='SW1A 1AA'));
  await page.locator('#memberAddressSelect option[value="0"]').waitFor({state:'attached'});await page.locator('#memberAddressSelect').selectOption('0');assert.equal(await page.locator('#memberAddress1').inputValue(),b.addresses[0].address1);assert.equal(await page.locator('#memberAddress2').inputValue(),'Keep my flat detail');
  await page.locator('#memberDetailsSave').click();await page.waitForFunction(()=>document.getElementById('memberDetailsStatus').textContent==='Member details saved.');await page.reload();await page.waitForFunction(()=>document.querySelector('#memberDetailsFields')?.disabled===false&&document.querySelector('#memberDeliveryFields')?.disabled===false);assert.equal(await page.locator('#memberAddress1').inputValue(),b.addresses[0].address1);row.checks.push('Home selection and save/reload; flat information preserved');
  row.phase='explicit-delivery-search';await page.locator('#memberDeliveryMode').selectOption('separate');await page.locator('#memberDeliveryRecipient').fill('Fictional Recipient');await page.locator('#memberDeliveryPostcode').fill('BT1 5GS');await page.locator('#memberDeliveryAddressQuery').fill('Belfast City Hall');await page.locator('#memberDeliveryAddress2').fill('Keep delivery floor');
  if(i>0){await page.unroute('**/v1/member/details/address-search');await page.route('**/v1/member/details/address-search',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(sample('BT1 5GS','Belfast City Hall, Donegall Square South','Belfast City'))}));}
  if(i===0)await page.waitForTimeout(1900); // Respect the pilot provider spacing.
  const delivery=page.waitForResponse(r=>r.url()===base+'/v1/member/details/address-search');await page.locator('#memberDeliveryFind').click();const dr=await delivery,db=await dr.json();assert.equal(dr.status(),200,JSON.stringify(db));if(i===0){report.realProviderCalls++;fs.writeFileSync(dir+'/actual-delivery-provider.json',JSON.stringify(db,null,2));}assert(db.addresses.length>0);assert(db.addresses.every(a=>a.postcode==='BT1 5GS'));
  await page.locator('#memberDeliverySelect option[value="0"]').waitFor({state:'attached'});await page.locator('#memberDeliverySelect').selectOption('0');assert.equal(await page.locator('#memberDeliveryAddress1').inputValue(),db.addresses[0].address1);assert.equal(await page.locator('#memberDeliveryAddress2').inputValue(),'Keep delivery floor');assert.equal(await page.locator('#memberDeliveryRecipient').inputValue(),'Fictional Recipient');
  await page.locator('#memberDeliverySave').click();await page.waitForFunction(()=>document.getElementById('memberDeliveryStatus').textContent.startsWith('Delivery address saved.'));await page.reload();await page.waitForFunction(()=>document.querySelector('#memberDetailsFields')?.disabled===false&&document.querySelector('#memberDeliveryFields')?.disabled===false);assert.equal(await page.locator('#memberAddress1').inputValue(),b.addresses[0].address1);assert.equal(await page.locator('#memberDeliveryAddress1').inputValue(),db.addresses[0].address1);row.checks.push('Northern Ireland delivery selection remains independent of home; save/reload works');
  await page.unroute('**/v1/member/details/address-search');
  row.phase='empty-and-failure-fallback';await page.route('**/v1/member/details/address-search',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...sample(),addresses:[]})}));await page.locator('#memberAddressQuery').fill('Not mapped');await page.locator('#memberFindAddress').click();await page.waitForFunction(()=>document.getElementById('memberAddressHelp').textContent.includes('No complete matching address'));assert(await page.locator('#memberAddressLookup').isHidden());assert.equal(await page.locator('#memberAddress1').inputValue(),b.addresses[0].address1);await page.unroute('**/v1/member/details/address-search');
  await page.route('**/v1/member/details/address-search',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'lookup_unavailable',message:'Injected provider outage. Enter the address manually.'})}));await page.locator('#memberFindAddress').click();await page.waitForFunction(()=>document.getElementById('memberAddressHelp').textContent.includes('Injected provider outage'));assert.equal(await page.locator('#memberAddress1').inputValue(),b.addresses[0].address1);await page.unroute('**/v1/member/details/address-search');row.checks.push('Empty or unavailable provider leaves manual edits and saving intact');
  row.phase='late-response';let release;const seen=new Promise(resolve=>{release=resolve;});await page.route('**/v1/member/details/address-search',async route=>{release();await page.waitForTimeout(600);await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(sample())}).catch(()=>{});});await page.locator('#memberFindAddress').click();await seen;await page.locator('#memberAddress1').fill('Manual typed address');await page.waitForTimeout(850);assert(await page.locator('#memberAddressLookup').isHidden());assert.equal(await page.locator('#memberAddress1').inputValue(),'Manual typed address');await page.unroute('**/v1/member/details/address-search');row.checks.push('Late results cannot replace a manually edited address');
  await page.locator('#memberAddressManual').click();assert(await page.locator('#memberAddress1').evaluate(el=>document.activeElement===el));await page.locator('#memberDetailsSave').click();await page.waitForFunction(()=>document.getElementById('memberDetailsStatus').textContent==='Member details saved.');
  assert.equal(direct.length,0);for(const r of requests){assert.equal(r.method,'POST');assert.equal(r.url,'/v1/member/details/address-search');assert.deepEqual(Object.keys(r.data).sort(),['postcode','query']);}
  assert(await page.locator('#memberAddressSource a').isVisible());assert(await page.locator('#memberDeliveryAddressSource a').count()===1);assert.deepEqual(errors,[]);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('#memberAddressSource').scrollIntoViewIfNeeded();await page.screenshot({path:dir+'/'+name+'-home.png',fullPage:true});await page.locator('#memberDeliveryAddressSource').scrollIntoViewIfNeeded();await page.screenshot({path:dir+'/'+name+'-delivery.png',fullPage:true});row.checks.push('Attribution, explicit minimal search, manual focus and no overflow');row.status='PASS';row.requestCount=requests.length;
 }catch(e){row.status='FAIL';row.error=e.message.replaceAll(fixture.password,'[redacted]');await page.screenshot({path:dir+'/'+name+'-FAIL.png',fullPage:true}).catch(()=>{});}finally{save();await context.close();await browser.close();}
}
console.log(JSON.stringify(report,null,2));assert(report.cases.every(c=>c.status==='PASS'));
