// Public derived knowledge only; no model calls, member reads, runtime deploy or store export.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {extractPublicPage,storePublicPage,publicKnowledgeUrl,sitemapUrls} from '../../member-experience/ai-site-knowledge.mjs';
assert.equal(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.GITHUB_ACTOR_ID,'315011648');assert.equal(process.env.GITHUB_REF,'refs/heads/codex/full-website-content-20261002');
const dir='available-closeout-proof';mkdirSync(dir,{recursive:true});
const origin='https://shiftsometimber.co.uk',account='9e5386dcf455be34c582d93f8bfc79e6',db='88f40aed-cb23-4372-8c94-8a73f48bc847';
const save=(name,obj)=>writeFileSync(dir+'/'+name,JSON.stringify(obj,null,2));
const cf=async(path,method='GET',body)=>{const r=await fetch('https://api.cloudflare.com/client/v4/accounts/'+account+path,{method,headers:{Authorization:'Bearer '+process.env.CLOUDFLARE_API_TOKEN,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const j=await r.json();assert(r.ok&&j.success,'Cloudflare operation failed: HTTP '+r.status);return j.result;};
// Deliberately whitelist metadata. Never serialise secret values or full settings.
const settings=await cf('/workers/scripts/shift-core/settings');
save('live-binding-inventory.json',{at:new Date().toISOString(),readOnly:true,bindings:(settings.bindings||[]).map(b=>({name:b.name,type:b.type,databaseId:b.id??b.database_id??null,bucketName:b.bucket_name??null,className:b.class_name??null,namespaceId:b.namespace_id??null})),contractOrProcessorCertification:false});
// Wait for publication before inspecting restored public assets or refreshing
// derived copies. A failed publisher must never be treated as a live release.
const runUrl='https://api.github.com/repos/shiftsometimber/shift-core/actions/runs/37081829248';let release;
for(let i=0;i<24;i++){const r=await fetch(runUrl,{headers:{Authorization:'Bearer '+process.env.GITHUB_TOKEN},signal:AbortSignal.timeout(15000)});assert(r.ok);release=await r.json();if(release.status==='completed')break;await new Promise(resolve=>setTimeout(resolve,15000));}
assert.equal(release.head_sha,'d3ffb04c9578ed73c959f56e4acac7ac428d7a8e');assert.equal(release.conclusion,'success','FAQ/guide release did not complete; no derived-copy writes');
const legacyChecks=[];
for(const path of ['/tools','/my-weight-loss-roadmap','/programme']){
 const r=await fetch(origin+path,{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(25000)});assert(r.ok);const html=await r.text(),visible=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ');
 for(const old of ['coming soon','not live yet','still being developed','future Shift Programme','Tap Room'])assert(!visible.toLowerCase().includes(old.toLowerCase()),'Legacy public marketing remains: '+path+' '+old);
 legacyChecks.push({path,status:r.status,finalUrl:r.url,staleVisibleMarketing:false});
}
for(const path of ['/member/progress','/tap-room','/tap-room.html','/tap-room/']){
 const r=await fetch(origin+path,{redirect:'manual',signal:AbortSignal.timeout(25000)});assert([301,302].includes(r.status));const target=new URL(r.headers.get('location'),origin);assert.equal(target.origin,origin);assert.equal(target.pathname,path==='/member/progress'?'/member/dashboard':'/lounge');legacyChecks.push({path,status:r.status,location:target.pathname+target.hash,legacySurfaceRetired:true});
}
save('legacy-copy-reconciliation.json',{at:new Date().toISOString(),issue:650,readOnly:true,checks:legacyChecks,renderedOutcomeFromCurrentHtml:true,unrelatedClinicalAvailabilityCertified:false,homepageOrCheckoutChanged:false});
const paths=JSON.parse(readFileSync('release/content-closeout/media-refs.json')),pending=[...paths],media=[];
await Promise.all(Array.from({length:6},async()=>{while(pending.length){const path=pending.shift(),assetUrl=new URL(path.replace(/^\/?assets\//,'/assets/'),origin);assert.equal(assetUrl.origin,origin);assert(!assetUrl.search);assert(/^\/(fit-v3-images|assets)\//.test(assetUrl.pathname));try{const r=await fetch(assetUrl.href,{signal:AbortSignal.timeout(20000)}),bytes=Buffer.from(await r.arrayBuffer()),type=r.headers.get('content-type')||'',magic=bytes.subarray(0,12);const png=magic.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),webp=magic.subarray(0,4).toString()==='RIFF'&&magic.subarray(8,12).toString()==='WEBP',jpeg=magic[0]===255&&magic[1]===216,svg=/<svg\b/.test(bytes.toString('utf8'))&&/<\/svg>/.test(bytes.toString('utf8'));const fragment=assetUrl.hash.slice(1),fragmentPresent=!fragment||new RegExp('id=[\"\']'+fragment+'[\"\']').test(bytes.toString('utf8'));
media.push({path,status:r.status,type,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),validImage:r.ok&&/image\//.test(type)&&(png||webp||jpeg||svg)&&fragmentPresent});}catch(e){media.push({path,error:e.name,validImage:false});}}}));
save('published-media.json',{at:new Date().toISOString(),references:paths.length,checked:media.length,valid:media.filter(x=>x.validImage).length,broken:media.filter(x=>!x.validImage),distinctImageHashes:new Set(media.filter(x=>x.validImage).map(x=>x.sha256)).size,records:media,visualOrTrainerReviewClaimed:false});
assert.equal(media.length,318);assert(media.every(x=>x.validImage),'Published media has genuine failures; inspect receipt');
// Reading public source-monitor state is SELECT only, never a scan or bypass of a refusal.
const select=async(sql,params=[])=>{assert(/^SELECT\b/i.test(sql)&&!/;/.test(sql));const result=await cf('/d1/database/'+db+'/query','POST',{sql,params});assert(result.every(x=>x.success));return result.flatMap(x=>x.results||[]);};
const monitor=await select('SELECT source_id,source_url,last_http_status,last_attempt_at,last_success_at,last_error,last_fingerprint FROM medicines_watch_checks');
save('source-monitor-state.json',{at:new Date().toISOString(),readOnly:true,sources:monitor});
const status=await select("SELECT category,status,COUNT(*) AS documents,SUM(CASE WHEN julianday(updated_at)<julianday('now','-2 days') THEN 1 ELSE 0 END) AS stale FROM ai_knowledge_documents GROUP BY category,status");save('knowledge-before.json',status);
const hash=createHash('sha256').update(readFileSync('member-experience/ai-site-knowledge.mjs')).digest('hex');assert.equal(hash,'d54cb52289822c423bee294fc949f5153e9654e41ee4916d7dfa63e7997f3457');
const current=await fetch('https://api.github.com/repos/shiftsometimber/shift-core/contents/member-experience/ai-site-knowledge.mjs?ref=main',{headers:{Authorization:'Bearer '+process.env.GITHUB_TOKEN},signal:AbortSignal.timeout(15000)});assert(current.ok);const source=await current.json();assert.equal(createHash('sha256').update(Buffer.from(source.content,'base64')).digest('hex'),hash,'Current public-index implementation moved');
const sm=await fetch(origin+'/sitemap.xml',{signal:AbortSignal.timeout(15000)});assert(sm.ok);const eligible=sitemapUrls(await sm.text()),allowed=new Set(eligible);
const specs=[...JSON.parse(readFileSync('editorial/content-audit/static-articles.json')).articles.map(a=>({url:origin+'/articles/'+a.slug,expected:[a.intro]})),...JSON.parse(readFileSync('editorial/content-audit/faq-copy.json')).articles.map(a=>({url:origin+'/faq/'+a.slug,expected:[a.intro]})),...JSON.parse(readFileSync('editorial/content-audit/core-guides.json')).articles.map(a=>({url:origin+'/guides/'+a.slug,expected:[a.intro]})),...JSON.parse(readFileSync('editorial/content-audit/approved-corrections.json')).articles.map(a=>({url:origin+'/articles/'+a.slug,expected:a.expectedVisible}))];
const pages=[],skipped=[];
// Validate the entire repair set before writing any derived record.
for(const spec of specs){assert(publicKnowledgeUrl(spec.url));if(!allowed.has(spec.url)){skipped.push({url:spec.url,reason:'Not in current eligible sitemap; preserve indexing policy'});continue;}const r=await fetch(spec.url,{headers:{'Cache-Control':'no-cache'},redirect:'error',signal:AbortSignal.timeout(15000)});assert(r.ok,'Reviewed source unavailable: '+spec.url);const html=await r.text(),page=extractPublicPage(html,spec.url);assert(page,'Reviewed source not extractable');const plain=html.replaceAll('&amp;','&').replaceAll('&#x27;',"'").replaceAll('&#39;',"'").replaceAll('&quot;','"');for(const text of spec.expected)assert(plain.includes(text),'Reviewed copy changed: '+spec.url);assert(!page.chunks.join(' ').includes('That sounds straightforward'));pages.push(page);}
const safeStatement=(sql,params=[])=>{assert(/^(INSERT INTO ai_knowledge_(?:documents|chunks)\b|DELETE FROM ai_knowledge_chunks\b)/.test(sql),'Only reviewed public-derived mutations are permitted');if(sql.startsWith('INSERT INTO ai_knowledge_documents')){assert.equal(params[2],'shift_public_site');assert(publicKnowledgeUrl(params[1]));}return{sql,params};};
const DB={prepare(sql){return{bind(...params){return safeStatement(sql,params)}}},async batch(statements){assert(statements.length>=3&&statements.length<=38);const r=await cf('/d1/database/'+db+'/query','POST',{batch:statements});assert(r.every(x=>x.success),'Public derived-copy transaction failed');return r;}};
for(const page of pages)await storePublicPage(DB,page);
const checks=[];
for(const page of pages){const rows=await select("SELECT d.source_uri,d.status,d.title,d.updated_at,c.chunk_index,c.content FROM ai_knowledge_documents d JOIN ai_knowledge_chunks c ON c.document_id=d.id WHERE d.checksum=? ORDER BY c.chunk_index",['shift-public:'+page.url]);assert.equal(rows.length,page.chunks.length);assert(rows.every(x=>x.status==='published_site'));assert.deepEqual(rows.map(x=>x.content),page.chunks);checks.push({url:page.url,chunks:rows.length,title:rows[0].title,updatedAt:rows[0].updated_at,exactReviewedCopy:true});}
save('knowledge-refresh-receipt.json',{at:new Date().toISOString(),source:process.env.GITHUB_SHA,faqPublicationRun:release.id,eligibleSitemapPages:eligible.length,reviewedSources:specs.length,refreshed:pages.length,skipped,checks,scope:'Replace derived copies of already published owner-requested editorial corrections only',modelsCalled:0,customerRecordsRead:false,customerRecordsChanged:false,workerDeployed:false,fullAnswerCapacityClaimed:false});
save('knowledge-after.json',await select("SELECT category,status,COUNT(*) AS documents,SUM(CASE WHEN julianday(updated_at)<julianday('now','-2 days') THEN 1 ELSE 0 END) AS stale FROM ai_knowledge_documents GROUP BY category,status"));
console.log('PASS: 318 actual image responses and exact reviewed-public-copy refresh; no model or member-data access');
