import assert from 'node:assert/strict';
import fs from 'node:fs';
import {pathToFileURL} from 'node:url';
const {radarPublicRoutes,uniquePublishedArticles}=await import(pathToFileURL(process.cwd()+'/radar-public-v1.js'));
const now=new Date().toISOString();
const row=(id,slug,destinations,reviewed_at=now)=>({id,headline:'Fixture '+id,reviewed_at,updated_at:reviewed_at,source_evidence_json:'[]',content_package_json:JSON.stringify({headline:'Fixture '+id,seo:{slug},destinations})});
const rows=[row(9,'same',['dossier']),row(8,' /same/ ',['medicine_news']),row(7,'same',['medicine_news','ticker_knowledge']),row(6,'/same',['ticker_treatments']),row(5,'other',['medicine_news']),row(4,'',['medicine_news']),row(3,'',['medicine_news'])];
const original=JSON.stringify(rows);
let writes=0,reads=0;
const DB={prepare(sql){assert.ok(sql.startsWith('SELECT '));reads++;return{bind(){return this},async first(){if(sql.includes('event_key=?'))return{id:236,status:'published'};if(sql.includes('COUNT(*)'))return{c:0};return{created_at:now,updated_at:now,at:now}},async all(){assert.ok(sql.includes("WHERE status='published'"));return{results:rows}},async run(){writes++;throw Error('Database writes forbidden')}}},async batch(){writes++;throw Error('Database writes forbidden')}};
const news=await radarPublicRoutes(new Request('https://fixture.invalid/v1/radar/news'),{DB});
const body=await news.json();
assert.deepEqual(body.items.map(x=>x.id),[8,5,4,3]);
const ticker=await radarPublicRoutes(new Request('https://fixture.invalid/v1/radar/ticker'),{DB});
const tick=await ticker.json();
assert.deepEqual(tick.items.map(x=>x.id),[7]);
assert.equal(tick.current,true);assert.equal(tick.status,'GREEN');
assert.equal(news.headers.get('cache-control'),'public, max-age=60, stale-while-revalidate=240');
assert.equal(JSON.stringify(rows),original);assert.equal(writes,0);
assert.deepEqual(uniquePublishedArticles(),[]);
const beforeUnsupported=reads;
assert.equal(await radarPublicRoutes(new Request('https://fixture.invalid/v1/radar/news',{method:'POST'}),{DB}),null);
assert.equal(reads,beforeUnsupported);
fs.mkdirSync('release-evidence',{recursive:true});
const report={status:'PASS',tests:['destination filtering precedes deduplication','news retains first eligible item','ticker chooses its own eligible item','leading/trailing slashes and whitespace normalize','blank slugs are retained individually','input rows unchanged','freshness and cache contract unchanged','unsupported method does not read database','database writes rejected'],news_ids:body.items.map(x=>x.id),ticker_ids:tick.items.map(x=>x.id),database_writes:writes};
fs.writeFileSync('release-evidence/route-test.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
