import {mkdirSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {banner,css,insertBanner} from './banner.mjs';
mkdirSync('preview/home-banner/generated',{recursive:true});mkdirSync('home-banner-proof',{recursive:true});
const r=await fetch('https://shiftsometimber.co.uk/');assert(r.ok);const baseline=await r.text(),candidate=insertBanner(baseline);
assert.equal(candidate.replace(banner,'').replace(css,''),baseline);
const sha=s=>createHash('sha256').update(s).digest('hex');
writeFileSync('preview/home-banner/generated/page.mjs','export const baseline='+JSON.stringify(baseline)+';export const candidate='+JSON.stringify(candidate)+';');
writeFileSync('home-banner-proof/baseline.html',baseline);writeFileSync('home-banner-proof/candidate.html',candidate);
writeFileSync('home-banner-proof/capture.json',JSON.stringify({capturedAt:new Date().toISOString(),source:'https://shiftsometimber.co.uk/',sourceCommit:process.env.GITHUB_SHA||null,baseline:sha(baseline),candidate:sha(candidate),exactRestorationAfterRemovingBanner:true},null,2));
console.log('PASS: removing only banner and its scoped CSS restores exact current homepage bytes');
