import {mkdirSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {replaceFreeStrip,restoreFreeStrip} from './free-design.mjs';
mkdirSync('preview/home-banner/generated',{recursive:true});mkdirSync('home-compact-proof',{recursive:true});
const r=await fetch('https://shiftsometimber.co.uk/');assert(r.ok);const baseline=await r.text(),candidate=replaceFreeStrip(baseline);
assert.equal(restoreFreeStrip(candidate),baseline,'Entire homepage outside the free text strip must stay byte-identical');
assert.equal(replaceFreeStrip(candidate),candidate);
const sha=s=>createHash('sha256').update(s).digest('hex');
writeFileSync('preview/home-banner/generated/page.mjs','export const baseline='+JSON.stringify(baseline)+';export const candidate='+JSON.stringify(candidate)+';');
writeFileSync('home-compact-proof/baseline.html',baseline);writeFileSync('home-compact-proof/candidate.html',candidate);
writeFileSync('home-compact-proof/capture.json',JSON.stringify({capturedAt:new Date().toISOString(),source:'https://shiftsometimber.co.uk/',sourceCommit:process.env.GITHUB_SHA||null,baseline:sha(baseline),candidate:sha(candidate),exactOriginalPageRestoration:true},null,2));
console.log('PASS: exact restoration of current homepage after removing only the compact free strip and its scoped CSS');
