import {banner as previousBanner,css as previousCss} from '../../home-route-banner-legacy.mjs';
export {previousBanner,previousCss};
const myTimber='<li><span class="sst-route-number" aria-hidden="true">03</span><div><h3><a href="/member/dashboard">MY TIMBER</a></h3>';
const health='<li><span class="sst-route-number" aria-hidden="true">03</span><div><h3><a href="/shift-health">SHIFT HEALTH</a></h3><p class="sst-route-lead">Understand your options.</p><p>Clear information on men’s health, home tests and treatment routes.</p></div></li>\n';
const oldFree='<div class="sst-route-free"><p class="sst-route-free-title">My Timber is free for everyone.</p><p>Food, movement, check-ins and progress—all in one place.</p><p class="sst-route-free-end">No purchase needed. We’re happy to help.</p></div>';
const foodIcon='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M12 7v12m6-12v12m-6-5h6m-3 5v22M33 7c-4 4-6 9-6 15 0 4 2 7 5 7h2v12m-1-34v22"/></svg>';
const moveIcon='<svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="29" cy="9" r="4"/><path d="M20 18l8-4 7 7 6-2M28 16l-5 10-8 3m8-3 8 5-5 10M18 18l-5 7"/></svg>';
const checkIcon='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M17 10h14m-11-4h8v8h-8zM12 10h24v31H12zM17 22l3 3 6-7M17 32l3 3 6-7"/></svg>';
const progressIcon='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M10 39h28M14 35V24h6v11M24 35V17h6v18M34 35V9h6v26"/></svg>';
const newFree='<div class="sst-route-free" aria-label="My Timber is free for everyone"><div class="sst-free-copy"><p class="sst-route-free-title">MY TIMBER IS <span>FREE</span> FOR EVERYONE.</p><p class="sst-route-free-sub">Food, movement, check-ins and progress — all in one place.</p></div><div class="sst-free-features"><div class="sst-free-feature"><span class="sst-free-icon">'+foodIcon+'</span><div><strong>FOOD</strong><small>Simple, proper meals for real life.</small></div></div><div class="sst-free-feature"><span class="sst-free-icon">'+moveIcon+'</span><div><strong>MOVEMENT</strong><small>Doable workouts to feel better.</small></div></div><div class="sst-free-feature"><span class="sst-free-icon">'+checkIcon+'</span><div><strong>CHECK-INS</strong><small>Stay on track without the faff.</small></div></div><div class="sst-free-feature"><span class="sst-free-icon">'+progressIcon+'</span><div><strong>PROGRESS</strong><small>See the difference week by week.</small></div></div></div><p class="sst-free-callout">NO PURCHASE NEEDED. WE’RE HAPPY TO HELP.</p></div>';
const fourStep=previousBanner.replace(myTimber,health+myTimber.replace('>03</span>','>04</span>'));
export const banner=fourStep.replace(oldFree,newFree);
export const css=previousCss.replace('</style>',`
html body main#main-content #sst-home-route .sst-route-free{position:relative!important;overflow:hidden!important;background:#707762!important;color:#E7E3DA!important;padding:14px 28px 12px!important;border-top:3px solid #050505!important;border-bottom:3px solid #050505!important}
html body main#main-content #sst-home-route .sst-route-free:before{content:"";position:absolute;inset:0;pointer-events:none;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='520' height='170' viewBox='0 0 520 170'%3E%3Cg fill='none' stroke='%23050505' stroke-width='1'%3E%3Cpath d='M-20 20C70-20 110 70 195 32s150-38 205 10 95 45 145 12'/%3E%3Cpath d='M-30 42C65 4 112 95 202 56s146-38 202 8 99 42 150 8'/%3E%3Cpath d='M-25 145C55 100 118 178 210 138s142-33 205 9 100 25 145-8'/%3E%3C/g%3E%3C/svg%3E");background-position:left top,right bottom;background-repeat:no-repeat;background-size:520px 170px}
html body main#main-content #sst-home-route .sst-route-free>*{position:relative;z-index:1}
html body main#main-content #sst-home-route .sst-free-copy{text-align:center!important}
html body main#main-content #sst-home-route .sst-route-free .sst-route-free-title{font:700 clamp(28px,3vw,42px)/1 ShiftRouteCondensed,'Arial Narrow',sans-serif!important;letter-spacing:.01em!important;color:#E7E3DA!important;margin:0!important}
html body main#main-content #sst-home-route .sst-route-free .sst-route-free-title span{color:#050505!important;-webkit-text-fill-color:#050505!important}
html body main#main-content #sst-home-route .sst-route-free .sst-route-free-sub{font:700 15px/1.25 Arial,Helvetica,sans-serif!important;color:#E7E3DA!important;margin:4px 0 0!important}
html body main#main-content #sst-home-route .sst-free-features{max-width:1180px;margin:13px auto 10px;display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr));gap:0!important}
html body main#main-content #sst-home-route .sst-free-feature{display:grid!important;grid-template-columns:54px minmax(0,1fr);align-items:center;gap:10px;padding:0 18px;border-left:1px solid #050505!important;text-align:left!important}
html body main#main-content #sst-home-route .sst-free-feature:first-child{border-left:0!important}
html body main#main-content #sst-home-route .sst-free-icon{width:54px;height:54px;border-radius:50%;background:#E7E3DA!important;color:#050505!important;display:grid!important;place-items:center}
html body main#main-content #sst-home-route .sst-free-icon svg{width:34px;height:34px;display:block;fill:none;stroke:#050505;stroke-width:3;stroke-linecap:round;stroke-linejoin:round}
html body main#main-content #sst-home-route .sst-free-feature strong{display:block;font:700 20px/1 ShiftRouteCondensed,'Arial Narrow',sans-serif!important;color:#E7E3DA!important}
html body main#main-content #sst-home-route .sst-free-feature small{display:block;font:400 12px/1.2 Arial,Helvetica,sans-serif!important;color:#E7E3DA!important;margin-top:4px}
html body main#main-content #sst-home-route .sst-free-callout{width:max-content;max-width:92%;margin:0 auto!important;padding:7px 30px 6px!important;background:#E7E3DA!important;color:#050505!important;font:700 18px/1 ShiftRouteCondensed,'Arial Narrow',sans-serif!important;letter-spacing:.02em!important;clip-path:polygon(2% 8%,98% 0,100% 78%,97% 95%,3% 100%,0 80%)}
@media(min-width:1001px){html body main#main-content #sst-home-route .sst-route-steps{grid-template-columns:repeat(4,minmax(0,1fr))}html body main#main-content #sst-home-route li{grid-template-columns:40px minmax(0,1fr);gap:12px;padding:0 20px!important}html body main#main-content #sst-home-route li:first-child{padding-left:0!important}html body main#main-content #sst-home-route li:last-child{padding-right:0!important}}
@media(min-width:701px) and (max-width:1000px){html body main#main-content #sst-home-route .sst-route-steps{grid-template-columns:repeat(2,minmax(0,1fr));row-gap:18px}html body main#main-content #sst-home-route li:nth-child(3){border-left:0;padding-left:0!important}html body main#main-content #sst-home-route .sst-free-features{grid-template-columns:repeat(2,minmax(0,1fr));row-gap:12px}html body main#main-content #sst-home-route .sst-free-feature:nth-child(3){border-left:0!important}}
@media(max-width:700px){html body main#main-content #sst-home-route .sst-route-free{padding:14px 14px 13px!important}html body main#main-content #sst-home-route .sst-route-free .sst-route-free-title{font-size:29px!important}html body main#main-content #sst-home-route .sst-route-free .sst-route-free-sub{font-size:13px!important}html body main#main-content #sst-home-route .sst-free-features{grid-template-columns:repeat(2,minmax(0,1fr));margin-top:12px;row-gap:12px}html body main#main-content #sst-home-route .sst-free-feature{grid-template-columns:42px minmax(0,1fr);gap:8px;padding:0 8px!important}html body main#main-content #sst-home-route .sst-free-feature:nth-child(3){border-left:0!important}html body main#main-content #sst-home-route .sst-free-icon{width:42px;height:42px}html body main#main-content #sst-home-route .sst-free-icon svg{width:27px;height:27px}html body main#main-content #sst-home-route .sst-free-feature strong{font-size:17px!important}html body main#main-content #sst-home-route .sst-free-feature small{font-size:10.5px!important}html body main#main-content #sst-home-route .sst-free-callout{font-size:15px!important;padding:6px 16px!important}}
</style>`);
export function insertFourStep(html){
 if(html.split(previousBanner).length!==2||html.split(previousCss).length!==2)throw Error('Current live homepage no longer matches the reviewed banner');
 return html.replace(previousBanner,banner).replace(previousCss,css);
}
