import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,request,setupInput} from './test-fixture.mjs';
import {coachingRoutes} from './routes.mjs';import {load,mutate,activeConsent} from './store.mjs';
import {fastMemberStateRoute} from '../member-state-fast-v1.js';
import {myJourneyRoutes} from '../my-journey-v1.js';
import {privacyHealthErasureRoute} from '../privacy-health-erasure-route-v1.js';
import {runCoachingNight} from './night-job.mjs';
import {pendingFollowup,acknowledgeFollowup} from './followup-view.mjs';
import {withCoaching,coachingAsset} from './presentation.mjs';
import {readFileSync} from 'node:fs';
import {client} from './ui.mjs';
const env=DB=>({DB,MEMBER_EXPERIENCE_V1_ENABLED:'true'});
async function read(DB,id=1){const r=await coachingRoutes(request('GET',null,id),env(DB));return r.json();}
async function save(DB,input,id=1){return coachingRoutes(request('POST',{revision:(await read(DB,id)).revision,operationId:crypto.randomUUID(),...input},id),env(DB));}
async function start(DB,id=1){const r=await save(DB,setupInput((await read(DB,id)).revision),id);assert.equal(r.status,201);return read(DB,id);}
test('existing auth rejects anonymous, expired and cross-origin callers',async t=>{const DB=fixture(t);assert.equal((await coachingRoutes(new Request('https://shiftsometimber.co.uk/v1/shift-coach'),env(DB))).status,401);assert.equal((await coachingRoutes(request('POST',setupInput(0),1,{Origin:'https://evil.invalid'}),env(DB))).status,403);DB.sqlite.exec("UPDATE user_sessions SET expires_at='2020-01-01'");assert.equal((await coachingRoutes(request(),env(DB))).status,401);});
test('no context is a general read-only starter; setup prepares a reason with two confirmed facts',async t=>{const DB=fixture(t);const blank=await read(DB);assert.equal(blank.enabled,false);assert.equal(blank.action.general,true);assert.equal((await load(DB,1)).state,null);const data=await start(DB);assert.equal(data.enabled,true);assert.match(data.action.reason,/family/);assert.match(data.action.reason,/late shifts/);assert(data.action.dataUsed.every(id=>data.memory.facts.some(f=>f.id===id&&f.confirmed)));});
test('a second signed-in session reads the same action and feedback changes the next choice',async t=>{const DB=fixture(t);let a=await start(DB);const first=a.action.id;assert.equal((await read(DB)).action.id,first);assert.equal((await save(DB,{kind:'accept',id:first})).status,201);assert.equal((await read(DB)).action.status,'accepted');assert.equal((await save(DB,{kind:'outcome',id:first,value:'didnt-help'})).status,201);a=await read(DB);assert.notEqual(a.action.id,first);assert.notEqual(a.action.type,'food-plan');assert(a.memory.rejections.includes('food-plan'));});
test('did not fit makes the same goal smaller and did not try asks before accepting',async t=>{const DB=fixture(t);let a=await start(DB);await save(DB,{kind:'accept',id:a.action.id});await save(DB,{kind:'outcome',id:a.action.id,value:'didnt-fit'});a=await read(DB);assert.equal(a.action.minutes,1);await save(DB,{kind:'accept',id:a.action.id});await save(DB,{kind:'outcome',id:a.action.id,value:'didnt-try'});a=await read(DB);assert(a.action.awaitingWant);assert.equal((await save(DB,{kind:'accept',id:a.action.id})).status,409);await save(DB,{kind:'wanted',yes:false});assert(!(await read(DB)).action.awaitingWant);});
test('memory corrections cancel old plans and records do not leak across accounts',async t=>{const DB=fixture(t);let a=await start(DB);const old=a.action.id;await save(DB,{kind:'fact',key:'week',value:'Mornings are free now'});a=await read(DB);assert.notEqual(a.action.id,old);assert.match(a.action.reason,/Mornings/);assert(!a.memory.preparedActions.some(x=>x.id===old));assert.equal((await read(DB,2)).enabled,false);assert.equal((await save(DB,{kind:'accept',id:a.action.id},2)).status,409);assert.equal((await save(DB,{kind:'fact',key:'week',value:'x',userId:2})).status,400);});
test('health withdrawal and regrant cannot revive old context',async t=>{const DB=fixture(t);await start(DB);DB.sqlite.exec("INSERT INTO consents(user_id,consent_type,granted) VALUES(1,'my_shift_health_tracking',0)");assert.equal((await read(DB)).enabled,false);assert.equal((await save(DB,{kind:'fact',key:'week',value:'Free'})).status,409);DB.sqlite.exec("INSERT INTO consents(user_id,consent_type,granted) VALUES(1,'my_shift_health_tracking',1)");assert.equal((await read(DB)).enabled,false);await start(DB);assert.equal((await load(DB,1)).state.consentId,(await activeConsent(DB,1)).id);});
test('stale tabs fail without losing newer context, and duplicate operations are idempotent',async t=>{const DB=fixture(t);const a=await start(DB);const body={kind:'fact',key:'week',value:'One late shift',revision:a.revision,operationId:crypto.randomUUID()};assert.equal((await coachingRoutes(request('POST',body),env(DB))).status,201);const duplicate=await coachingRoutes(request('POST',body),env(DB));assert.equal(duplicate.status,200);assert((await duplicate.json()).duplicate);assert.equal((await coachingRoutes(request('POST',{...body,value:'Stale overwrite',operationId:crypto.randomUUID()}),env(DB))).status,409);assert.match((await read(DB)).action.reason,/One late shift/);});
test('old whole-profile and Journey saves preserve the entire coach snapshot',async t=>{const DB=fixture(t);await start(DB);const before=(await load(DB,1)).state;const headers={Cookie:'sst_session=fixture-token-1','Content-Type':'application/json'};await fastMemberStateRoute(new Request('https://shiftsometimber.co.uk/v1/member-state',{method:'PATCH',headers,body:JSON.stringify({preferences:{old:'value',lifeBack:{progress:{shiftAI:{facts:[]}}}}})}),env(DB));assert.deepEqual((await load(DB,1)).state,before);const response=await myJourneyRoutes(new Request('https://shiftsometimber.co.uk/v1/my-journey',{method:'PATCH',headers,body:JSON.stringify({setup:{why:'Keep going'},lifeBack:{}})}),env(DB));assert.equal(response.status,200);assert.deepEqual((await load(DB,1)).state,before);});
test('a concurrent Life Back revision prevents coaching overwrite',async t=>{const DB=fixture(t);const a=await start(DB);DB.sqlite.prepare("UPDATE member_state SET preferences=json_set(preferences,'$.lifeBack.progress.revision',?) WHERE user_id=1").run(a.revision+1);assert.equal((await coachingRoutes(request('POST',{kind:'fact',key:'week',value:'Stale',revision:a.revision,operationId:crypto.randomUUID()}),env(DB))).status,409);});
test('deleting a memory item removes it and its derived content from the actual store',async t=>{const DB=fixture(t);const a=await start(DB),f=a.memory.facts.find(f=>f.key==='week');await save(DB,{kind:'delete-item',id:f.id});const text=DB.sqlite.prepare('SELECT preferences FROM member_state WHERE user_id=1').get().preferences;assert(!text.includes(f.value));assert(!text.includes(f.id));});
test('delete-all blocks an in-flight old snapshot and leaves other Life Back records',async t=>{const DB=fixture(t);const a=await start(DB);DB.sqlite.exec("UPDATE member_state SET preferences=json_set(preferences,'$.lifeBack.progress.goal','Keep this goal') WHERE user_id=1");assert.equal((await coachingRoutes(request('DELETE'),env(DB))).status,200);assert.equal((await read(DB)).enabled,false);assert.equal((await coachingRoutes(request('POST',{kind:'fact',key:'week',value:'Old context',revision:a.revision,operationId:crypto.randomUUID()}),env(DB))).status,409);assert.equal(JSON.parse(DB.sqlite.prepare('SELECT preferences FROM member_state WHERE user_id=1').get().preferences).lifeBack.progress.goal,'Keep this goal');});
test('existing optional-health erasure removes all coaching data atomically',async t=>{const DB=fixture(t);await start(DB);await start(DB,2);const r=await privacyHealthErasureRoute(new Request('https://shiftsometimber.co.uk/v1/privacy/health-tracking',{method:'DELETE'}),env(DB),{},async()=>Response.json({user:{id:1}}));assert.equal(r.status,200);assert.equal((await load(DB,1)).state,null);assert.equal((await read(DB)).consent,false);assert((await load(DB,2)).state);});
test('night preparation is opted-in, paged, repeat-safe, and never calls AI or sends externally',async t=>{const DB=fixture(t);await start(DB);assert.deepEqual(await runCoachingNight(env(DB)),{checked:0,prepared:0,conflicts:0,modelCalls:0,externalNotifications:0});await save(DB,{kind:'settings',settings:{proactive:true,weeklyDay:4}});const now=Date.parse('2026-10-01T20:00:00Z');const once=await runCoachingNight(env(DB),now);assert.equal(once.prepared,1);const state=(await load(DB,1)).state;assert.equal(state.weeklyPlans.length,1);assert.equal((await runCoachingNight(env(DB),now)).prepared,0);assert.deepEqual((await load(DB,1)).state,state);});
test('global off leaves prepared Today readable',async t=>{const DB=fixture(t);const a=await start(DB);assert((await runCoachingNight({...env(DB),SHIFT_COACH_OFF:'true'})).disabled);const r=await coachingRoutes(request(),{...env(DB),SHIFT_COACH_OFF:'true'});assert.equal((await r.json()).action.id,a.action.id);});
test('two unanswered follow-ups pause the type and explicit restoration is required',async t=>{
 const DB=fixture(t);await start(DB);await save(DB,{kind:'settings',settings:{proactive:true,followup:true}});
 const now=Date.now()+3*86400000;
 await mutate(DB,1,'fixture_ignored',s=>{s.touches=[1,2].map(i=>({id:crypto.randomUUID(),type:'followup',at:now-(i+1)*86400000,answered:false}));return{};});
 await runCoachingNight(env(DB),now);let data=await read(DB);assert(data.memory.pausedTypes.includes('followup'));
 const prompt=data.memory.pauseRequests[0];assert.equal(prompt.status,'queued');
 await save(DB,{kind:'pause-choice',id:prompt.id,yes:true});data=await read(DB);
 assert(!data.memory.pausedTypes.includes('followup'));assert.equal(data.memory.pauseRequests[0].status,'restored');
 await runCoachingNight(env(DB),now+86400000);assert.equal((await read(DB)).memory.pauseRequests.filter(x=>x.status==='queued').length,0);
});
test('follow-up respects permission, quiet hours, weekly cap and once per day',async t=>{const DB=fixture(t);const a=await start(DB);await save(DB,{kind:'settings',settings:{proactive:true,followup:true}});await save(DB,{kind:'accept',id:a.action.id});const s=(await load(DB,1)).state;const now=s.queue[0].dueAt+12*3600000;const daytime=new Date(now);daytime.setUTCHours(12,0,0,0);const at=daytime.getTime();const p=pendingFollowup(s,at);assert(p);acknowledgeFollowup(s,p.id,at);assert.equal(pendingFollowup(s,at),null);s.queue.push({...s.queue[0],id:crypto.randomUUID(),status:'queued'});s.touches=[];assert.equal(pendingFollowup(s,Date.parse('2026-10-09T05:00:00Z')),null);s.touches=[1,2,3].map(i=>({at:at-i*1000,type:'weekly'}));assert.equal(pendingFollowup(s,at),null);});
test('stopped and elsewhere modes retain history without dose nudges or medicine plans',async t=>{const DB=fixture(t);await start(DB);await save(DB,{kind:'mode',mode:'stopped'});const a=await read(DB);assert.equal(a.memory.mode,'stopped');assert.equal(a.memory.facts.length,3);assert(!/dose|taper|restart/i.test(a.action.title));await save(DB,{kind:'mode',mode:'elsewhere'});assert.equal((await read(DB)).memory.mode,'elsewhere');});
test('return after absence has one welcome and no backlog',async t=>{const DB=fixture(t);await start(DB);await save(DB,{kind:'settings',settings:{proactive:true}});const s=(await load(DB,1)).state;const now=s.lastActivity+15*86400000;await runCoachingNight(env(DB),now);const after=(await read(DB));assert.match(after.action.title,/restart/);assert.equal((await load(DB,1)).state.queue.length,0);});
test('clinical text is blocked before saving and no invented hand-off exists',async t=>{const DB=fixture(t);const a=await start(DB);for(const value of ['Change my dose to 5mg','I have chest pain','I am barely eating and making myself sick','I want to end my life']){assert.equal((await save(DB,{kind:'fact',key:'goal',value})).status,422);}assert.deepEqual((await read(DB)).memory.facts,a.memory.facts);assert.match(a.help.text,/Nobody is monitoring/);});
test('typographic punctuation does not bypass the finite support boundary',async t=>{const DB=fixture(t);const a=await start(DB);for(const value of ['I can’t go on','I haven’t eaten for three days','I’m 17 years old','I have side–effects'])assert.equal((await save(DB,{kind:'fact',key:'goal',value})).status,422);assert.deepEqual((await read(DB)).memory.facts,a.memory.facts);});
test('oversized streamed writes are stopped before buffering the complete body',async t=>{const DB=fixture(t);let pulls=0;const stream=new ReadableStream({pull(controller){pulls++;controller.enqueue(new Uint8Array(4097));}});const req=new Request('https://shiftsometimber.co.uk/v1/shift-coach',{method:'POST',headers:{Cookie:'sst_session=fixture-token-1',Origin:'https://shiftsometimber.co.uk','Content-Type':'application/json'},body:stream,duplex:'half'});assert.equal((await coachingRoutes(req,env(DB))).status,413);assert(pulls<=2);assert.equal((await read(DB)).enabled,false);});
test('weekly assessment stays personal, honours weight-plus-components and changes tone',async t=>{const DB=fixture(t);await start(DB);assert.equal((await save(DB,{kind:'components',components:['weight']})).status,400);await save(DB,{kind:'review',rating:1});await save(DB,{kind:'review',rating:2});const a=await read(DB);assert.equal(a.review.combinedScore,null);assert.equal(a.memory.stage,'Hit a wall');assert.match(a.action.tone,/hard week/);});
test('wrapper changes only dashboard and preserves body, chrome and originals',async()=>{const publicResponse=new Response('<main>Public</main>',{headers:{'Content-Type':'text/html'}});assert.equal(await withCoaching(new Request('https://shiftsometimber.co.uk/treatment-centre'),publicResponse),publicResponse);const html='<html><body><header id="approved">Keep</header><section id="panel-today"><div id="todayActions">Original tools</div></section><footer id="sst-footer-c">Footer</footer></body></html>';const result=await withCoaching(new Request('https://shiftsometimber.co.uk/member/dashboard'),new Response(html,{headers:{'Content-Type':'text/html','Content-Length':'100'}}));const text=await result.text();assert(text.includes('<header id="approved">Keep</header>'));assert(text.includes('Original tools</div>'));assert(!text.includes('<body data-shift-coach-session>'));assert.equal((text.match(/id="todayActions"/g)||[]).length,1);assert(text.includes('<footer id="sst-footer-c">Footer</footer>'));assert.equal((text.match(/id="shiftCoach"/g)||[]).length,1);assert.equal(result.headers.get('Content-Length'),null);assert.match(result.headers.get('Cache-Control'),/private/);assert.equal((await coachingAsset(new Request('https://shiftsometimber.co.uk/assets/shift-coach.mjs')).text()),client);new Function(client);});
test('production config differs only in entrypoint; test fixture cannot be reached through production graph',()=>{const source=readFileSync('wrangler.jsonc','utf8');assert.equal(readFileSync('wrangler.coaching.jsonc','utf8'),source.replace('"main": "worker-entry-v6.js"','"main": "shift-coach/worker.mjs"'));for(const f of ['worker','routes','store','night-job','presentation'])assert(!readFileSync('shift-coach/'+f+'.mjs','utf8').includes('./test-fixture'));});

test('fresh prepared seed stays private and cannot inject instructions or executable HTML',async()=>{
 const seed={enabled:true,memory:{goal:'</script><script>window.bad=true</script> & <tag>'},action:{title:'Prepared',reason:'Confirmed context'}};
 const source='<html><head><title>Keep</title></head><body><section id="previewMember" hidden><section id="panel-today"><div id="todayActions">Keep tools</div></section></section></body></html>';
 const r=await withCoaching(new Request('https://shiftsometimber.co.uk/member/dashboard'),new Response(source,{headers:{'Content-Type':'text/html','ETag':'old'}}),seed);const text=await r.text();
 const json=text.match(/<script type="application\/json" id="shiftCoachInitial">(.*?)<\/script>/s)[1];assert.deepEqual(JSON.parse(json),seed);assert(!json.includes('<'));assert(!text.includes('<script>window.bad'));assert.match(r.headers.get('Cache-Control'),/no-store, private/);assert.equal(r.headers.get('Vary'),'Cookie, Accept-Encoding');assert.equal(r.headers.get('ETag'),null);assert(text.indexOf('data-shift-coach-styles')<text.indexOf('</head>'));assert(text.includes('<script data-shift-coach-client>'));assert(text.includes('<body data-shift-coach-session>'));assert(text.includes('<section id="previewMember">'));const anonymous=await withCoaching(new Request('https://shiftsometimber.co.uk/member/dashboard'),new Response(source,{headers:{'Content-Type':'text/html'}}));assert((await anonymous.text()).includes('<section id="previewMember" hidden>'));assert(!text.includes('<script async src="/assets/shift-coach.mjs">'));
 const unchanged=new Response('Public',{headers:{'Content-Type':'text/html'}});assert.equal(await withCoaching(new Request('https://shiftsometimber.co.uk/programme'),unchanged,seed),unchanged);
});

// A real browser receives the same private document after decoding; q=0
// explicitly keeps identity transport rather than silently compressing it.
test('private dashboard compression preserves content and honours gzip refusal',async()=>{
 const html='<html><head></head><body><div id="todayActions">Keep tools</div></body></html>';
 const respond=encoding=>withCoaching(new Request('https://shiftsometimber.co.uk/member/dashboard',{headers:{'Accept-Encoding':encoding}}),new Response(html,{headers:{'Content-Type':'text/html'}}));
 const plain=await respond('gzip;q=0, identity');assert.equal(plain.headers.get('Content-Encoding'),null);const expected=await plain.text();
 const compressed=await respond('br, gzip;q=0.8');assert.equal(compressed.headers.get('Content-Encoding'),'gzip');assert.equal(compressed.headers.get('Vary'),'Cookie, Accept-Encoding');assert.match(compressed.headers.get('Cache-Control'),/no-store, private/);
 assert.equal(await new Response(compressed.body.pipeThrough(new DecompressionStream('gzip'))).text(),expected);
});
