import {gzipSync,gunzipSync} from 'node:zlib';
import {createServer} from 'node:http';
import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import worker from './worker.mjs';
import {createHash} from 'node:crypto';
import {load,mutate} from './store.mjs';
import {prepareNight} from './night-job.mjs';
import {fixture} from './test-fixture.mjs';
import assert from 'node:assert/strict';
const blockedServerRequests=[];globalThis.fetch=async input=>{const u=new URL(String(input?.url||input));if(u.hostname==='projectshift.pages.dev'){let f=u.pathname==='/member/dashboard'?root+'/member-experience/test-support/dashboard.html':root+'/frontend/member'+({'/member/grub':'/member-grub.html','/member/fit':'/member-fit.html'}[u.pathname]||u.pathname);if(!existsSync(f))f+='.html';if(existsSync(f))return new Response(readFileSync(f),{headers:{'Content-Type':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'text/javascript'}});}blockedServerRequests.push(u.href);return new Response('External HTTP disabled in synthetic test',{status:503});};
const transport=process.env.COACHING_PROOF_TRANSPORT||'identity',wire=[];
const root=new URL('..',import.meta.url).pathname,out=process.env.COACHING_PROOF_DIR||'/tmp/my-timber-phantom-members-'+Date.now();mkdirSync(out,{recursive:true});const DB=fixture(null,out+'/synthetic.sqlite');DB.exec=async sql=>{DB.sqlite.exec(sql);return {success:true}};DB.sqlite.exec("DROP TABLE progress_entries;DROP TABLE check_ins;DROP TABLE audit_log;CREATE TABLE cases(id INTEGER PRIMARY KEY,user_id INTEGER);CREATE TABLE pharmacy_orders(id INTEGER PRIMARY KEY,user_id INTEGER);");for(const c of ['email','first_name','last_name','phone','postcode','created_at','updated_at'])DB.sqlite.exec('ALTER TABLE users ADD COLUMN '+c+' TEXT');for(const c of ['lifecycle_stage','membership_status','source'])DB.sqlite.exec('ALTER TABLE member_status ADD COLUMN '+c+' TEXT');DB.sqlite.exec("CREATE TABLE user_auth(user_id INTEGER PRIMARY KEY,email_verified INTEGER,last_login_at TEXT,password_hash TEXT);INSERT INTO user_auth(user_id,email_verified) VALUES(1,1),(2,1);UPDATE users SET email='synthetic-'||id||'@example.invalid',first_name='Synthetic',last_name='Member',created_at='2026-10-02',updated_at='2026-10-02';");DB.sqlite.exec(readFileSync(root+'/member-experience/checkin-followup.sql','utf8'));DB.sqlite.exec(readFileSync(root+'/migrations/002_personal_knowledge_radar.sql','utf8'));const env={DB,MEMBER_EXPERIENCE_V1_ENABLED:'true',MY_TIMBER_PWA_ENABLED:'true',MEMBER_ASSETS:{fetch:async req=>{let p=new URL(req.url).pathname;let f=root+'/frontend/member'+p;if(!existsSync(f))f+='.html';if(!existsSync(f))return new Response('Not found',{status:404});return new Response(readFileSync(f),{headers:{'Content-Type':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':f.endsWith('.js')||f.endsWith('.mjs')?'text/javascript':'application/octet-stream'}})}}};

// Third invented member uses the same session table and consent as the first two.
DB.sqlite.prepare('INSERT INTO users(id,date_of_birth,email,first_name,last_name) VALUES(3,?,?,?,?)').run('1977-01-01','synthetic-3@example.invalid','Steve','Test');
DB.sqlite.prepare('INSERT INTO member_state(user_id) VALUES(3)').run();
DB.sqlite.prepare('INSERT INTO member_status(user_id) VALUES(3)').run();
DB.sqlite.prepare('INSERT INTO user_sessions(id,user_id,token_hash,expires_at) VALUES(3,3,?,?)').run(createHash('sha256').update('fixture-token-3').digest('hex'),'2027-10-01');
DB.sqlite.prepare("INSERT INTO consents(id,user_id,consent_type,granted,created_at) VALUES(3,3,'my_shift_health_tracking',1,'2026-10-02')").run();
DB.sqlite.prepare('INSERT INTO user_auth(user_id,email_verified) VALUES(3,1)').run();

const server=createServer(async(req,res)=>{try{let url=new URL(req.url,'https://shiftsometimber.co.uk');const chunks=[];for await(const c of req)chunks.push(c);const h=new Headers(req.headers);if(h.get('Origin')==='http://'+req.headers.host)h.set('Origin',url.origin);const r=await worker.fetch(new Request(url,{method:req.method,headers:h,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})}),env,{waitUntil(){}});const raw=Buffer.from(await r.arrayBuffer()),rh=Object.fromEntries(r.headers),compress=!rh['content-encoding']&&transport==='gzip'&&String(req.headers['accept-encoding']||'').includes('gzip')&&/text\/|application\/(?:json|javascript)/.test(rh['content-type']||'');const body=compress?gzipSync(raw):raw;if(compress){rh['content-encoding']='gzip';rh['content-length']=body.length;}wire.push({path:url.pathname,decodedBytes:rh['content-encoding']==='gzip'?gunzipSync(body).length:raw.length,wireBytes:body.length,encoding:rh['content-encoding']||'identity'});res.writeHead(r.status,rh);res.end(body);}catch(e){console.error(req.url,e.message);res.writeHead(500);res.end('synthetic failure')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;

const require=createRequire(import.meta.url);
const {chromium}=process.env.PLAYWRIGHT_MODULE?require(process.env.PLAYWRIGHT_MODULE):await import('playwright');
const browser=await chromium.launch({headless:true,...(process.env.COACHING_CHROMIUM?{executablePath:process.env.COACHING_CHROMIUM}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});
const report={at:new Date().toISOString(),scope:'Repository-pinned My Timber dashboard HTML/scripts and integrated coaching candidate, local Node/SQLite. Three invented authenticated adult members; no production account, email, paid model or external notification.',candidateCommit:''+(await import('node:child_process')).execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),workingCopyFiles:['shift-coach/full-page-proof.mjs','shift-coach/integration.test.mjs','shift-coach/presentation.mjs','shift-coach/ui.mjs'],checks:[],profiles:[],pageErrors:[],fixtureResponses:[],limitations:['These are scenario-driven simulated users, not human feedback. Digital-confidence findings are usability heuristics, not measured reactions.','Existing production registration, password recovery, physical iPhone/Android binaries, live clinical team response, real push, calendar/device integrations and commercial outcomes are not covered.','Grub catalogue is not seeded in this isolated fixture; its 503 responses must not be reported as live failures.','The candidate is separate from GitHub main and is not established as deployed.'],timings:[]};
const profiles=[
 {id:1,name:'Dan',confidence:'Tech confident',width:1280,height:900,mode:'shift',goal:'Have enough energy to join in with the family',week:'Three late shifts and no free evenings',focus:'food',stage:'Already making changes'},
 {id:2,name:'Alan',confidence:'Low digital confidence',width:360,height:800,mode:'stopped',goal:'Feel more like myself and get out with my family',week:'I need simple instructions and meals I already know',focus:'food',stage:'Just starting'},
 {id:3,name:'Steve',confidence:'Comfortable with basics',width:390,height:844,mode:'elsewhere',goal:'Get out with the dog and join in at football',week:'I want a gentle option and a clear choice that fits my lunch break',focus:'movement',stage:'Hit a wall'}
];
const contexts=[];let activePage;
function record(member,name,pass,observed){report.checks.push({member,name,status:pass?'PASS':'FAIL',observed});writeFileSync(out+'/in-progress.json',JSON.stringify(report,null,2));console.log(JSON.stringify({member,name,status:pass?'PASS':'FAIL',observed:pass?undefined:observed}));}
async function check(member,name,fn){try{const result=await fn();record(member,name,result?.pass!==false,result?.observed??result??'Verified');}catch(e){if(activePage)writeFileSync(out+'/last-failed-page.html',await activePage.content().catch(()=>''));record(member,name,false,e.message);}}
const dump=name=>writeFileSync(out+'/'+name+'.json',JSON.stringify(DB.sqlite.prepare('SELECT user_id,preferences FROM member_state ORDER BY user_id').all().map(r=>({...r,preferences:JSON.parse(r.preferences)})),null,2));
async function state(ctx){const r=await ctx.request.get(origin+'/v1/shift-coach');return r.json();}
async function post(ctx,body){const s=await state(ctx);return ctx.request.post(origin+'/v1/shift-coach',{headers:{Origin:origin},data:{...body,revision:s.revision,operationId:crypto.randomUUID()}});}
async function saved(page){await page.waitForFunction(()=>document.querySelector('#shiftCoach [data-coach-status]')?.textContent==='Saved.',{},{timeout:10000});}
async function acceptFeedback(page,value){await page.locator('[data-coach-action=accept]').click();await saved(page);await page.locator('#shiftCoach summary').filter({hasText:'Tell Shift AI how it went'}).click();await page.locator('[data-coach-action=outcome][data-value="'+value+'"]').click();await saved(page);}
try{
 for(const profile of profiles){
  const ctx=await browser.newContext({viewport:{width:profile.width,height:profile.height},isMobile:profile.width<500,hasTouch:profile.width<500});contexts.push(ctx);
  await ctx.addCookies([{name:'sst_session',value:'fixture-token-'+profile.id,url:origin,httpOnly:true}]);
  await ctx.route('**/*',async route=>{if(new URL(route.request().url()).origin===origin)return route.continue();return route.fulfill({status:404,body:'External requests disabled in synthetic test'});});
  const page=await ctx.newPage();activePage=page;page.setDefaultTimeout(20000);profile.ctx=ctx;profile.page=page;
  page.on('pageerror',e=>report.pageErrors.push({member:profile.name,error:e.message}));page.on('response',r=>{if(r.status()>=400)report.fixtureResponses.push({member:profile.name,path:new URL(r.url()).pathname,status:r.status()});});
  await check(profile.name,'First visit: visible setup and no invented personal history',async()=>{
   await page.goto(origin+'/member/dashboard?view=app#today',{waitUntil:'commit'});await page.locator('[data-coach-setup]').waitFor({timeout:30000});
   if(await page.locator('[data-consent=necessary]').isVisible())await page.locator('[data-consent=necessary]').click();
   const s=await state(ctx);return{pass:s.memory===null&&s.action.general===true,observed:{title:s.action.title,enabled:s.enabled}};
  });
  await check(profile.name,'Blank required answers do not silently save',async()=>{await page.locator('[data-coach-setup] button[type=submit]').click();return{pass:(await state(ctx)).memory===null,observed:'Browser required-field validation; no coaching record created'};});
  await check(profile.name,'Create personal coaching through the visible form',async()=>{
   await page.getByLabel('What do you want back?',{exact:true}).fill(profile.goal);await page.getByLabel('What does your week look like?',{exact:true}).fill(profile.week);
   await page.locator('[data-coach-setup] [name=focus]').selectOption(profile.focus);await page.locator('[data-coach-setup] [name=stage]').selectOption(profile.stage);await page.locator('[data-coach-setup] [name=mode]').selectOption(profile.mode);
   await page.getByRole('button',{name:'Prepare my first action',exact:true}).click();await saved(page);await page.locator('[data-coach-action=accept]').waitFor();
   const s=await state(ctx);profile.firstAction=s.action;
   await page.locator('#shiftCoach').screenshot({path:out+'/'+profile.name.toLowerCase()+'-01-first-action.png'});
   return{pass:s.action.reason.includes(profile.goal)&&s.action.reason.includes(profile.week)&&s.memory.mode===profile.mode,observed:s.action};
  });
  await check(profile.name,'Accepting opens the practical meal/activity needed to do it',async()=>{
   await page.locator('[data-coach-action=accept]').click();await saved(page);const host=page.locator('#shiftCoach');const text=await host.innerText();
   const visible=await host.locator('a,button,input,select').evaluateAll(nodes=>nodes.filter(n=>n.checkVisibility()).map(n=>({tag:n.tagName,text:n.innerText||n.getAttribute('aria-label')||n.name,href:n.getAttribute('href')})));
   await host.screenshot({path:out+'/'+profile.name.toLowerCase()+'-02-accepted.png'});
   const direct=visible.some(x=>x.href&&/grub|fit|recipe|meal|movement/i.test(x.href))||visible.some(x=>/ingredient|open meal|start activity|save meal|add to.*list/i.test(x.text));
   const task=await host.locator('[data-coach-task]').innerText();const link=host.locator('[data-coach-task] a');if(await link.count()){const href=await link.getAttribute('href');const response=await ctx.request.get(origin+href);assert.equal(response.status(),200);assert.match(await response.text(),/Grub|Fit/i);}return{pass:direct&&task.length>50,observed:{visibleControls:visible,text,task,priorIssue:'No meal, ingredients, shopping-list entry, activity instructions or direct task link opens from the coaching action.'}};
  });
  await check(profile.name,'Did not fit: next action is a smaller commitment',async()=>{
   const before=(await state(ctx)).action;await page.locator('#shiftCoach summary').filter({hasText:'Tell Shift AI how it went'}).click();await page.locator('[data-coach-action=outcome][data-value=didnt-fit]').click();await saved(page);const after=(await state(ctx)).action;
   return{pass:after.minutes<before.minutes&&after.title!==before.title&&after.task.steps.length<before.task.steps.length,observed:{before:before.title,beforeMinutes:before.minutes,after:after.title,afterMinutes:after.minutes}};
  });
  await check(profile.name,'Did not help: different approach, rejected approach stays excluded',async()=>{const before=(await state(ctx)).action;await acceptFeedback(page,'didnt-help');const after=await state(ctx);return{pass:before.type!==after.action.type&&after.memory.rejections.includes(before.type),observed:{before:before.type,after:after.action.type,rejections:after.memory.rejections}};});
  await check(profile.name,'Did not try: ask whether the person still wants it',async()=>{await acceptFeedback(page,'didnt-try');const s=await state(ctx);assert(s.action.awaitingWant);await page.locator('[data-coach-action=wanted][data-yes=true]').click();await saved(page);return{observed:'Wanted confirmation appeared and saved; no automatic failure label'};});
  await check(profile.name,'Helpful result is saved and survives reload',async()=>{await acceptFeedback(page,'helped');await page.reload({waitUntil:'commit'});await page.locator('[data-coach-action=accept]').waitFor();const s=await state(ctx);return{pass:s.memory.outcomes.some(x=>x.value==='helped'),observed:{outcomes:s.memory.outcomes,action:s.action.title}};});
  await check(profile.name,'Correct a bad-week record and persist the correction',async()=>{
   await page.getByText('What SHIFT knows about me',{exact:true}).click();const f=page.locator('[data-coach-fact=week]');const correction='A difficult week; keep the next step simple for '+profile.name;
   await f.locator('input').fill(correction);await f.getByRole('button',{name:'Save correction'}).click();await saved(page);await page.reload({waitUntil:'commit'});await page.locator('[data-coach-action=accept]').waitFor();const s=await state(ctx);return{pass:s.action.reason.includes(correction)&&!s.action.reason.includes(profile.week),observed:s.action.reason};
  });
  await check(profile.name,'All treatment modes retain the person and their history',async()=>{
   const before=await state(ctx);const titles=[];
   for(const mode of ['shift','elsewhere','stopped']){await page.getByText('What SHIFT knows about me',{exact:true}).click();await page.locator('[data-coach-mode] select').selectOption(mode);await page.getByRole('button',{name:'Save my situation'}).click();await saved(page);const s=await state(ctx);assert.equal(s.memory.mode,mode);assert.equal(s.memory.outcomes.length,before.memory.outcomes.length);titles.push({mode,title:s.action.title,reason:s.action.reason});}
   profile.modeComparison=titles;assert.notEqual(titles[0].reason,titles[2].reason);assert.match((await state(ctx)).treatment.title,/After treatment/);return{observed:titles};
  });
  await check(profile.name,'Weekly personal assessment saves without invented progress',async()=>{await page.getByText('My weekly Life Back review',{exact:true}).click();await page.locator('[data-coach-action=review][data-rating="2"]').click();await saved(page);await page.reload({waitUntil:'commit'});await page.locator('[data-coach-action=accept]').waitFor();const s=await state(ctx);return{pass:s.review.weeklyAssessment.rating===2,observed:s.review};});
  await check(profile.name,'Follow-up is off until permission is given; due follow-up appears in-app',async()=>{
   const before=await state(ctx);assert.equal(before.memory.settings.proactive,false);assert.equal(before.memory.settings.followup,false);
   await page.getByText('My permissions and follow-up',{exact:true}).click();const form=page.locator('[data-coach-settings]');await form.locator('input[name=proactive]').check();await form.locator('input[name=followup]').check();await form.getByRole('button',{name:'Save my choices'}).click();await saved(page);await page.locator('[data-coach-action=accept]').click();await saved(page);
   await mutate(DB,profile.id,'synthetic_clock_advance',s=>{for(const q of s.queue)q.dueAt=Date.now()-1000;return{outcome:'due_time_simulated'};});
   await page.reload({waitUntil:'commit'});await page.locator('[data-coach-action=outcome][data-value=helped]').waitFor({state:'visible'});await page.evaluate(()=>document.querySelector('[data-coach-action=outcome][data-value=helped]')?.scrollIntoView({block:'center'}));for(let i=0;i<40&&(await load(DB,profile.id)).state.touches.length===0;i++)await new Promise(r=>setTimeout(r,50));const s=await state(ctx);return{pass:(await load(DB,profile.id)).state.touches.length===1,observed:'Due time advanced only in synthetic storage; follow-up presented and acknowledged once'};
  });
  await check(profile.name,'Return after two-week break offers a warm restart',async()=>{
   await mutate(DB,profile.id,'synthetic_absence',s=>{s.lastActivity=Date.now()-15*86400000;s.nightRuns=[];const r=prepareNight(s);return r;});
   await page.reload({waitUntil:'commit'});await page.locator('[data-coach-action=accept]').waitFor();const s=await state(ctx);await page.locator('#shiftCoach').screenshot({path:out+'/'+profile.name.toLowerCase()+'-03-return.png'});return{pass:s.action.title==='Pick one thing to restart your week'&&s.action.tone.includes('Good to have you back'),observed:{title:s.action.title,tone:s.action.tone,simulation:'lastActivity advanced, no claim of real retention'}};
  });
  await check(profile.name,'Matched medicine request is not saved as everyday coaching',async()=>{
   const before=await state(ctx);const r=await post(ctx,{kind:'fact',key:'week',value:'Should I increase my dose to 10 mg?'});const s=await state(ctx);return{pass:r.status()===422&&JSON.stringify(s.memory.facts)===JSON.stringify(before.memory.facts),observed:{status:r.status(),response:await r.json()}};
  });
  await check(profile.name,'Plain-language illness concern is interrupted rather than used as coaching context',async()=>{
   const before=await state(ctx);const phrase='I keep being sick and cannot keep water down';const r=await post(ctx,{kind:'fact',key:'week',value:phrase});const s=await state(ctx);const accepted=s.memory.facts.some(f=>f.value===phrase);if(accepted){await post(ctx,{kind:'fact',key:'week',value:before.memory.facts.find(f=>f.key==='week').value});await page.reload({waitUntil:'commit'});await page.locator('[data-coach-action=accept]').waitFor();}return{pass:r.status()===422&&!accepted,observed:{phrase,status:r.status(),savedAsContext:accepted,limitation:'Finite boundary detection is not validated triage; no clinical recommendation was generated.'}};
  });
  await check(profile.name,'Repeated rejection leads to a usable next-choice control',async()=>{
   const sequence=[];for(let i=0;i<5;i++){const s=await state(ctx);sequence.push({type:s.action.type,title:s.action.title});if(s.action.type==='member-choice')break;await page.locator('[data-coach-action=decline]').click();await saved(page);}
   const s=await state(ctx);const visibleChoices=await page.locator('#shiftCoach select').evaluateAll(xs=>xs.filter(x=>x.checkVisibility()).map(x=>({name:x.name,options:[...x.options].map(o=>o.text)})));
   await page.locator('#shiftCoach').screenshot({path:out+'/'+profile.name.toLowerCase()+'-04-exhausted.png'});return{pass:s.action.type!=='member-choice'||visibleChoices.some(x=>x.name==='focus'),observed:{sequence,lastType:s.action.type,title:s.action.title,visibleChoices}};
  });
  await check(profile.name,'Next-choice form changes focus and preserves rejected history',async()=>{const before=await state(ctx);assert.equal(before.action.type,'member-choice');const form=page.locator('[data-coach-focus]');await form.locator('select').selectOption('reflection');await form.getByRole('button',{name:'Prepare my next step'}).click();await saved(page);await page.reload({waitUntil:'commit'});await page.locator('[data-coach-action=accept]').waitFor();const after=await state(ctx);return{pass:after.action.type==='review-plan'&&JSON.stringify(after.memory.rejections)===JSON.stringify(before.memory.rejections),observed:{type:after.action.type,rejections:after.memory.rejections}};});
  await check(profile.name,'Illness submitted in the visible form opens help and leaves earlier context intact',async()=>{const before=await state(ctx);await page.getByText('What SHIFT knows about me',{exact:true}).click();const f=page.locator('[data-coach-fact=week]');await f.locator('input').fill('I keep being sick and cannot keep water down');await f.getByRole('button',{name:'Save correction'}).click();await page.waitForFunction(()=>document.querySelector('[data-coach-status]')?.textContent.includes('professional help'));const help=page.locator('[data-coach-help]');const after=await state(ctx);return{pass:await help.getAttribute('open')!==null&&JSON.stringify(after.memory.facts)===JSON.stringify(before.memory.facts),observed:'Help opens; rejected concern is not saved or sent to a clinician.'};});
  await check(profile.name,'Mobile/desktop layout does not overflow and has one coaching section',async()=>{const widths=[360,390,1280];const observations=[];for(const width of widths){await page.setViewportSize({width,height:900});await page.reload({waitUntil:'commit'});await page.locator('#shiftCoach').waitFor();const v=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,cards:document.querySelectorAll('#shiftCoach').length}));observations.push(v);assert(v.scroll<=v.width+1);assert.equal(v.cards,1);}return{observed:observations};});
  report.profiles.push({id:profile.id,name:profile.name,confidence:profile.confidence,goal:profile.goal,week:profile.week,focus:profile.focus,initialMode:profile.mode,modeComparison:profile.modeComparison,heuristic:'Each profile is a scripted scenario; no real user satisfaction rating is fabricated.'});dump(profile.name.toLowerCase()+'-complete');await page.goto('about:blank');
 }
 for(const p of profiles){await check(p.name,'Account isolation: no other phantom member facts',async()=>{const s=await state(p.ctx);const strings=JSON.stringify(s.memory.facts);return{pass:profiles.filter(x=>x.id!==p.id).every(x=>!strings.includes(x.goal)),observed:'Confirmed goal and week scoped to original authenticated session'};});}
 const slow=profiles[1],page=slow.page;await page.goto(origin+'/member/dashboard?view=app#today',{waitUntil:'commit'});await page.locator('[data-coach-action=accept]').waitFor();const cdp=await slow.ctx.newCDPSession(page);await page.setViewportSize({width:360,height:800});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750});
 for(let i=0;i<7;i++){await page.reload({waitUntil:'commit'});await page.locator('#shiftCoach [data-coach-action=accept]').waitFor();const sample=await page.evaluate(()=>({timeOrigin:performance.timeOrigin,ready:performance.getEntriesByName('shift-coach-ready').at(-1).startTime,visible:document.querySelector('#shiftCoach [data-coach-action=accept]').checkVisibility()}));report.timings.push(sample);}
 const timingP95=report.timings.map(x=>x.ready).sort((a,b)=>a-b)[Math.ceil(.95*report.timings.length)-1];record('Alan','Prepared full-page action reaches under-one-second target on slower device/network',timingP95<1000,{p95:timingP95,samples:report.timings,conditions:'360×800 Chromium touch, 4× CPU, 150ms/request, 1.6Mbps down; local original Worker and synthetic SQLite, not production performance'});
 await cdp.send('Emulation.setCPUThrottlingRate',{rate:1});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
 const p=profiles[2];await p.page.goto(origin+'/member/dashboard?view=app#today',{waitUntil:'commit'});await p.page.locator('[data-coach-action=accept]').waitFor();await check(p.name,'Withdrawal removes personal coaching; regrant does not resurrect it',async()=>{
  DB.sqlite.prepare("INSERT INTO consents(user_id,consent_type,granted) VALUES(?,'my_shift_health_tracking',0)").run(p.id);await p.page.reload({waitUntil:'commit'});await p.page.locator('#shiftCoach').waitFor({state:'attached'});await p.page.getByText('To save a personal coaching plan, review your existing optional health-tracking choice in',{exact:false}).waitFor();const s=await state(p.ctx);assert.equal(s.enabled,false);assert.equal(s.memory,null);assert.equal(await p.page.locator('#shiftCoach [data-coach-action=accept]').count(),0);
  DB.sqlite.prepare("INSERT INTO consents(user_id,consent_type,granted) VALUES(?,'my_shift_health_tracking',1)").run(p.id);await p.page.reload({waitUntil:'commit'});await p.page.locator('[data-coach-setup]').waitFor();return{observed:'After regrant, setup needed; former personalized plan not revived'};
 });
 const low=profiles[1];await check(low.name,'Expired session removes personal coaching',async()=>{DB.sqlite.prepare("UPDATE user_sessions SET expires_at='2020-01-01' WHERE user_id=?").run(low.id);await low.page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await low.page.waitForFunction(()=>document.querySelector('#shiftCoach')?.hidden===true);return{observed:'Coaching section and its personal content hidden; original account flow outside test scope'};});
 dump('final-store');report.blockedServerRequests=blockedServerRequests;report.summary={pass:report.checks.filter(x=>x.status==='PASS').length,fail:report.checks.filter(x=>x.status==='FAIL').length,total:report.checks.length};writeFileSync(out+'/phantom-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({summary:report.summary,pageErrors:report.pageErrors,p95:timingP95}));assert.equal(report.checks.filter(c=>c.status==='FAIL'&&!c.name.includes('under-one-second')).length,0,'Functional phantom-member checks failed; see phantom-report.json');assert.equal(report.pageErrors.length,0,'Browser errors were observed');
}finally{for(const c of contexts)await c.close();await browser.close();await new Promise(r=>server.close(r));DB.close();}
