export const client=String.raw`(()=>{
 'use strict';const host=document.getElementById('shiftCoach');if(!host)return;const content=host.querySelector('[data-coach-content]'),status=host.querySelector('[data-coach-status]');let data,pending=false;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={goal:'What you want back',week:'Your week',focus:'Your focus',helped:'Done and helped','didnt-help':"Done, didn't help",'didnt-fit':"Didn't fit my day",'didnt-try':"Didn't try",shift:'Prescribed through SHIFT',elsewhere:'Prescribed elsewhere',stopped:'Stopped medication'};
 const button=(text,action,extra='')=>'<button type="button" data-coach-action="'+action+'" '+extra+'>'+esc(text)+'</button>';
 async function api(method='GET',body){const r=await fetch('/v1/shift-coach',{method,credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const b=await r.json();if(!r.ok)throw Object.assign(Error(b.error||'unavailable'),{status:r.status,body:b});return b;}
 function errorText(e){if(e.status===409)return 'Your saved context or tracking choice changed. I’ve refreshed it; please try again.';if(e.status===422)return 'This needs professional help. Open Get the right help below. That text has not been saved as coaching context.';return 'Shift AI could not save this. Your earlier records are still there. Please retry.';}
 async function update(body){if(pending)return;pending=true;host.setAttribute('aria-busy','true');host.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='Saving…';try{await api('POST',{...body,revision:data.revision,operationId:crypto.randomUUID()});await refresh();status.textContent='Saved.';}catch(e){try{await refresh();}catch{}status.textContent=errorText(e);}finally{pending=false;host.removeAttribute('aria-busy');host.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 const help=()=>'<details data-coach-help><summary>Get the right help</summary><p>'+esc(data.help.text)+'</p><ul>'+data.help.links.map(l=>'<li><a href="'+esc(l.url)+'" target="_blank" rel="noopener noreferrer">'+esc(l.label)+'</a></li>').join('')+'</ul></details>';
 function setupForm(){return '<h2>'+esc(data.action?.title||'Make this fit your week')+'</h2><p>'+esc(data.action?.reason||'Share what matters to you and what your week looks like.')+'</p>'+(!data.consent?'<p>To save a personal coaching plan, review your existing optional health-tracking choice in <a href="/member/settings">Settings</a>.</p>':'<form data-coach-setup><label>What do you want back?<input name="goal" maxlength="240" required autocomplete="off" placeholder="More time and energy for the family"></label><label>What does your week look like?<input name="week" maxlength="240" required autocomplete="off" placeholder="Three late shifts; mornings are easier"></label><label>One focus<select name="focus"><option value="food">Food that fits my day</option><option value="movement">Movement that fits my day</option><option value="reflection">How the week feels</option></select></label><label>Where are you now?<select name="stage"><option>Just starting</option><option>Already making changes</option><option>Hit a wall</option></select></label><label>Your medication situation<select name="mode"><option value="elsewhere">Prescribed elsewhere</option><option value="shift">Prescribed through SHIFT</option><option value="stopped">Stopped medication</option></select></label><p>Shift AI uses only what you save here for everyday plans. No medicine advice or automatic messages.</p><button type="submit">Prepare my first action</button></form>')+help();}
 function render(){
  host.hidden=false;host.closest('#panel-today')?.toggleAttribute('data-shift-coach-enabled',data.enabled);
  if(!data.enabled){content.innerHTML=setupForm();bind();return;}
  const m=data.memory,a=data.action;
  let card=a?'<h2>'+esc(a.title)+'</h2><p>'+esc(a.tone)+'</p><p class="coach-reason">'+esc(a.reason)+'</p>':'<h2>Your previous action has moved on</h2><p>Refresh your plan from your latest saved context.</p>'+button('Prepare my next action','refresh');
  if(a?.awaitingWant)card+='<div class="coach-buttons">'+button('Yes, keep this goal','wanted','data-yes="true"')+button('No, try something else','wanted','data-yes="false" class="secondary"')+'</div>';
  else if(a?.status==='prepared')card+='<div class="coach-buttons">'+button('That works — accept','accept')+button('Not for me — change it','decline','class="secondary"')+'</div>';
  else if(a?.status==='accepted')card+='<p><strong>Accepted. It’s saved for when it suits you.</strong></p><details '+(data.followup?'open':'')+'><summary>Tell Shift AI how it went</summary><div class="coach-buttons">'+['helped','didnt-help','didnt-fit','didnt-try'].map(v=>button(labels[v],'outcome','data-value="'+v+'"')).join('')+'</div></details>';
  const memory='<details data-coach-memory><summary>What SHIFT knows about me</summary>'+m.facts.map(f=>'<form data-coach-fact="'+esc(f.key)+'"><label>'+esc(labels[f.key]||f.key)+'<input name="value" value="'+esc(f.value)+'" maxlength="240" required></label><div class="coach-buttons"><button type="submit">Save correction</button>'+button('Delete','delete-item','data-id="'+esc(f.id)+'" class="secondary"')+'</div></form>').join('')+'<p>Stage: '+esc(m.stage)+'. Situation: '+esc(labels[m.mode])+'. Life Back focus: '+m.components.map(esc).join(', ')+'.</p><form data-coach-mode><label>My situation<select name="mode">'+['elsewhere','shift','stopped'].map(v=>'<option value="'+v+'" '+(m.mode===v?'selected':'')+'>'+esc(labels[v])+'</option>').join('')+'</select></label><button type="submit">Save my situation</button></form><form data-coach-stage><label>Where I am now<select name="stage">'+['Just starting','Already making changes','Hit a wall'].map(v=>'<option '+(m.stage===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label><button type="submit">Save my stage</button></form><h3>What you said helped</h3><ul>'+m.outcomes.map(o=>'<li>'+esc(labels[o.value])+' · '+esc(new Date(o.at).toLocaleDateString('en-GB'))+'</li>').join('')+'</ul><h3>Advice you rejected</h3>'+m.rejections.map(type=>'<p>'+esc(type.replace(/-/g,' '))+' '+button('Restore','restore','data-type="'+esc(type)+'" class="secondary"')+'</p>').join('')+'<h3>Prepared plans</h3><ul>'+m.derivedPlans.map(p=>'<li>'+esc(p.title)+' — '+esc(p.reason)+(p.accepted?' — Accepted':button('Accept this plan','plan-accept','data-id="'+esc(p.id)+'"'))+'</li>').join('')+'</ul><p>Confirmed information is kept until you delete it. History older than 90 days is removed on the next saved update. No model is trained on these records.</p>'+button('Delete all coaching records','delete-all','class="secondary"')+'</details>';
  const settings='<details><summary>My permissions and follow-up</summary><form data-coach-settings><label><input type="checkbox" name="proactive" '+(m.settings.proactive?'checked':'')+'>Prepare my plan in the background inside My Timber</label><label><input type="checkbox" name="followup" '+(m.settings.followup?'checked':'')+'>Prepare a follow-up for actions I accept</label><label>Weekly plan day<select name="weeklyDay"><option value="">Off</option>'+['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i)=>'<option value="'+i+'" '+(m.settings.weeklyDay===i?'selected':'')+'>'+d+'</option>').join('')+'</select></label><label>Quiet hours start<input type="time" name="quietStart" value="'+esc(m.settings.quietStart)+'" required></label><label>Quiet hours end<input type="time" name="quietEnd" value="'+esc(m.settings.quietEnd)+'" required></label><p>These choices apply inside My Timber. No push, calendar, wearable or scale connection is enabled.</p><button type="submit">Save my choices</button></form></details>';
  const r=data.review;const review='<details><summary>My weekly Life Back review</summary><p>'+esc(r.win?.text||'Record what fitted and helped; your own assessment counts.')+'</p><p>'+esc(r.weeklyAssessment?'You rated your last week '+r.weeklyAssessment.rating+' out of 5.':'No weekly assessment saved yet.')+'</p><div class="coach-buttons">'+[1,2,3,4,5].map(v=>button('Week: '+v+'/5','review','data-rating="'+v+'"')).join('')+'</div><p>'+esc(r.next)+'</p><form data-coach-components><fieldset><legend>What counts for my Life Back</legend>'+['energy','sleep','activity','mood','waist','weight'].map(v=>'<label><input type="checkbox" name="component" value="'+v+'" '+(m.components.includes(v)?'checked':'')+'>'+v+'</label>').join('')+'</fieldset><p>Your own weekly assessment always stays alongside these choices.</p><button type="submit">Save my Life Back choices</button></form></details>';
  const audit='<details><summary>Why Shift AI acted</summary><ul>'+data.audit.slice(-20).reverse().map(x=>'<li>'+esc(new Date(x.at).toLocaleString('en-GB'))+' · '+esc(x.type.replace(/[-_]/g,' '))+' · '+esc(x.outcome.replace(/_/g,' '))+'</li>').join('')+'</ul></details>';
  const paused=(m.pauseRequests||[]).filter(x=>x.status==='queued').map(x=>'<p>Follow-ups are paused after two unanswered prompts. Keep them? '+button('Yes, keep follow-ups','pause-choice','data-id="'+esc(x.id)+'" data-yes="true"')+button('Leave them off','pause-choice','data-id="'+esc(x.id)+'" data-yes="false" class="secondary"')+'</p>').join('');
  content.innerHTML=card+paused+memory+settings+review+audit+help()+'<p><a href="/member/ask-timber">Ask Shift AI a question</a></p>';bind();performance.mark('shift-coach-ready');
  if(data.followup){const id=data.followup.id;api('POST',{kind:'followup-seen',id,revision:data.revision,operationId:crypto.randomUUID()}).then(r=>data.revision=r.revision).catch(()=>{content.querySelector('details')?.removeAttribute('open');});}
 }
 function bind(){
  content.querySelector('[data-coach-setup]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);update({kind:'setup',goal:f.get('goal'),week:f.get('week'),focus:f.get('focus'),stage:f.get('stage'),mode:f.get('mode')});});
  content.querySelectorAll('[data-coach-fact]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();update({kind:'fact',key:f.dataset.coachFact,value:new FormData(f).get('value')});}));
  content.querySelector('[data-coach-mode]')?.addEventListener('submit',e=>{e.preventDefault();update({kind:'mode',mode:new FormData(e.target).get('mode')});});
  content.querySelector('[data-coach-stage]')?.addEventListener('submit',e=>{e.preventDefault();update({kind:'stage',stage:new FormData(e.target).get('stage')});});
  content.querySelector('[data-coach-components]')?.addEventListener('submit',e=>{e.preventDefault();update({kind:'components',components:new FormData(e.target).getAll('component')});});
  content.querySelector('[data-coach-settings]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),day=f.get('weeklyDay');update({kind:'settings',settings:{proactive:f.has('proactive'),followup:f.has('followup'),weeklyDay:day===''?null:Number(day),quietStart:f.get('quietStart'),quietEnd:f.get('quietEnd')}});});
  content.querySelectorAll('[data-coach-action]').forEach(b=>b.addEventListener('click',async()=>{const kind=b.dataset.coachAction;if(kind==='delete-all'){if(!confirm('Delete all Shift AI coaching context, plans, outcomes and decision history?'))return;try{await api('DELETE');await refresh();status.textContent='Your coaching records have been deleted.';}catch(e){status.textContent=errorText(e);}return;}update({kind,id:b.dataset.id||data.action?.id,value:b.dataset.value,yes:b.dataset.yes==='true',type:b.dataset.type,rating:Number(b.dataset.rating)});}));
 }
 async function refresh(){data=await api();render();}
 refresh().catch(e=>{if(e.status===401){host.hidden=true;return;}host.hidden=false;content.innerHTML='<h2>Shift AI</h2><p>Your saved coaching plan could not load.</p>';status.textContent='Please refresh to try again. The rest of My Timber is available.';});
 document.addEventListener('sst:consentchange',()=>refresh().catch(()=>{}));
})();`;
