export const client=String.raw`(()=>{
 'use strict';const host=document.getElementById('shiftCoach');if(!host)return;const content=host.querySelector('[data-coach-content]'),status=host.querySelector('[data-coach-status]');let data,pending=false,followupObserver,supportAlert=false,refreshGeneration=0;
 let actions,positionObserver;
 function position(){const hero=actions?.querySelector(':scope > .mtm-hero');if(hero&&hero.nextElementSibling!==host)hero.after(host);else if(!hero&&!actions?.contains(host))actions?.prepend(host);}
 function attachPosition(){const found=document.getElementById('todayActions');if(!found||found===actions)return;positionObserver?.disconnect();actions=found;positionObserver=new MutationObserver(position);positionObserver.observe(actions,{childList:true});position();}
 attachPosition();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attachPosition,{once:true});
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={goal:'What you want back',week:'Your week',focus:'Your focus',helped:'Done and helped','didnt-help':"Done, didn't help",'didnt-fit':"Didn't fit my day",'didnt-try':"Didn't try",shift:'Prescribed through SHIFT',elsewhere:'Prescribed elsewhere',stopped:'Stopped medication',none:'Not taking medication','planning-stop':'Planning for treatment to end'};
 const button=(text,action,extra='')=>'<button type="button" data-coach-action="'+action+'" '+extra+'>'+esc(text)+'</button>';
 async function api(method='GET',body){const r=await fetch('/v1/shift-coach',{method,credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const b=await r.json();if(!r.ok)throw Object.assign(Error(b.error||'unavailable'),{status:r.status,body:b});return b;}
 function errorText(e){if(e.status===409)return 'Your saved context or tracking choice changed. I’ve refreshed it; please try again.';if(e.status===422)return 'This needs professional help. Open Get the right help below. That text has not been saved as coaching context.';return 'Ask Timber could not save this. Your earlier records are still there. Please retry.';}
 async function update(body){if(pending)return;pending=true;refreshGeneration++;host.setAttribute('aria-busy','true');host.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='Saving…';try{await api('POST',{...body,revision:data.revision,operationId:crypto.randomUUID()});supportAlert=false;await refresh({afterWrite:true});status.textContent='Saved.';}catch(e){supportAlert=e.status===422;try{await refresh({afterWrite:true});}catch{}status.textContent=errorText(e);if(supportAlert){const h=content.querySelector('[data-coach-help]');if(h){h.open=true;h.querySelector('summary')?.focus();h.scrollIntoView({block:'nearest'});}}}finally{pending=false;host.removeAttribute('aria-busy');host.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 const help=()=>'<p>Coaching carries on after treatment and without a medication purchase. Treatment question? Use your prescriber’s contact details.</p><details data-coach-help '+(supportAlert||data.supportRequired?'open':'')+'><summary>Get the right help — coaching or treatment</summary><p>'+esc(data.help.text)+'</p><ul>'+data.help.links.map(l=>'<li><a href="'+esc(l.url)+'" target="_blank" rel="noopener noreferrer">'+esc(l.label)+'</a></li>').join('')+'</ul></details>';
 const practicalFields=(v={})=>'<label>Time for preparation<select name="time"><option value="flexible">Some flexibility</option><option value="short" '+(v.time==='short'?'selected':'')+'>Keep preparation short</option></select></label><label>Food budget<select name="budget"><option value="regular">Use my usual budget</option><option value="tight" '+(v.budget==='tight'?'selected':'')+'>Keep costs down</option></select></label><label>Cooking facilities<select name="kitchen"><option value="cook">I can cook a familiar meal</option><option value="no-cook" '+(v.kitchen==='no-cook'?'selected':'')+'>Choose meals without cooking</option></select></label>';
 const constraintsFrom=f=>({time:f.get('time'),budget:f.get('budget'),kitchen:f.get('kitchen')});
 const challengeOptions=(value='everyday')=>Object.entries(data.challenges||{}).map(([v,label])=>'<option value="'+esc(v)+'" '+(value===v?'selected':'')+'>'+esc(label)+'</option>').join('');
 function supportPanel(canRequest){return '<details data-coach-support><summary>Ask SHIFT for everyday coaching help</summary><p>This request goes into the SHIFT support queue. It is not monitored clinical chat or urgent care. No response time is currently promised. Only the message you explicitly choose to send is shared; your coaching records are not attached.</p>'+(data.support?.available?(canRequest?'<form data-coach-support-request><label>What everyday help do you need?<textarea name="message" maxlength="1000" required></textarea></label><label><input type="checkbox" name="share" required>Send this message to the SHIFT team</label><button type="submit">Send help request</button></form>':'')+'<h3>My help requests</h3><ul>'+data.support.tickets.map(t=>'<li data-coach-ticket>'+esc(t.reference)+' — '+esc(t.status==='closed'?'Team marked closed':t.status==='waiting'?'Waiting':t.assigned?'Assigned to a team member':'Open — awaiting team assignment')+' · updated '+esc(new Date(t.updated_at).toLocaleString('en-GB'))+(t.message?'<p>Your request: '+esc(t.message)+'</p>':'')+(t.replies||[]).map(r=>'<blockquote data-coach-reply><strong>'+esc(r.author)+'</strong> · '+esc(new Date(r.at).toLocaleString('en-GB'))+'<p>'+esc(r.text)+'</p></blockquote>').join('')+(t.resolution?'<p data-coach-resolved>You confirmed this reply answered your request.</p>':t.replies?.length?'<p>'+button('This answered my request','support-resolve','data-reference="'+esc(t.reference)+'" data-reply="'+esc(t.replies.at(-1).id)+'"')+'</p>':'')+(t.needsUpdate?'<p>This request has had no recorded update for at least two days. <a href="/contact?type=support">Contact SHIFT for an update</a> and quote the reference above. This is not an urgent or clinical service.</p>':'')+(t.status==='closed'?'<p>Still need help? '+button('Reopen this request','support-reopen','data-reference="'+esc(t.reference)+'"')+'</p>':'')+'</li>').join('')+'</ul>':'<p>The tracked queue is unavailable here. Use <a href="/contact?type=support">SHIFT contact</a> instead.</p>')+'</details>';}
 function setupForm(){return '<h2>Today, handled.</h2><p>One question first. We can learn the rest when it is actually useful.</p>'+(!data.consent?'<p>To save a personal coaching plan, review your existing optional health-tracking choice in <a href="/member/settings">Settings</a>.</p>':'<form data-coach-setup><label>What would make today feel a bit better?<input name="goal" maxlength="240" required autocomplete="off" placeholder="Sort dinner, move a bit, get my head straight…"></label><p>That is enough to start. No medicine purchase is required.</p><button type="submit">Give me one useful step</button></form>')+help()+supportPanel(false);}
 function quotePanel(visible=false){return '<details data-coach-quote-panel'+(visible?'':' hidden')+'><summary>Check my next three supply quotes</summary><p>Use complete quotes for the supplies you expect to need. Check the repeat price as well as any introductory offer.</p><form data-coach-quote-budget><fieldset><legend>Next three supply quotes, in GBP</legend><p>Include required fees. Leave unknown prices blank. These numbers stay on this page and are not saved or sent to SHIFT.</p>'+[1,2,3].map(i=>'<label>Supply '+i+' total (£)<input name="quote'+i+'" type="number" inputmode="decimal" min="0" max="100000" step="0.01" autocomplete="off" placeholder="Unknown"></label>').join('')+'</fieldset><button type="submit">Add up my quotes</button><p data-coach-quote-result role="status" aria-live="polite"></p></form><p>Three supplies may cover different periods; this total is not a monthly price or confirmed order.</p><details><summary>What to check before committing</summary><p>Get the medicine, dose, pack quantity and supply duration for each quote. Include required delivery, consultation and membership fees, and confirm discount eligibility. Check payment dates, minimum term, cancellation deadline, any exit fee and what happens if your clinician advises stopping. Quotes can change.</p><p><a href="/articles/wegovy-cost-uk">Read the full-price and supply-period checklist</a></p></details><p>Medication affordability or changing treatment? Take the quotes and your questions to your prescriber. My Timber does not select a cheaper medicine or alter your dose.</p></details>';}
 function render(){
  followupObserver?.disconnect();
  host.hidden=false;host.closest('#panel-today')?.toggleAttribute('data-shift-coach-enabled',data.enabled);
  if(!data.enabled){content.innerHTML=setupForm();bind();return;}
  const m=data.memory,a=data.action;
  const chooseFocus='<form data-coach-focus><label>What would help next?<select name="focus">'+(data.choices||[]).map(c=>'<option value="'+esc(c.focus)+(c.restore?':restore':'')+'">'+esc(c.label)+(c.restore?' — try these suggestions again':'')+'</option>').join('')+'</select></label><p>Choosing “try these suggestions again” restores the suggestions you rejected in that focus. Your feedback stays saved.</p><button type="submit">Prepare my next step</button></form>';
  let card=a?'<h2>'+esc(a.title)+'</h2><p>'+esc(a.tone)+'</p><p class="coach-reason">'+esc(a.reason)+'</p>':'<h2>Your previous action has moved on</h2><p>Refresh your plan from your latest saved context.</p>'+button('Prepare my next action','refresh');
  if(data.supportRequired)card='<h2>Get health advice for this concern</h2><p>This saved concern belongs with a healthcare professional. Everyday suggestions are paused. Open Get the right help below; you can correct or delete the saved context in What SHIFT knows about me.</p>';
  else if(m.pendingBlocker)card+='<p>Let’s avoid another guess. What got in the way?</p><form data-coach-blocker><label>Main obstacle<select name="blocker">'+Object.entries(data.blockers).map(([key,label])=>'<option value="'+esc(key)+'">'+esc(label)+'</option>').join('')+'</select></label><button type="submit">Change the approach</button></form>'+chooseFocus+button('Ask SHIFT to help me choose','open-support','class="secondary"');
  else if(a?.type==='member-choice')card+='<p>The suggestions in this focus did not work for you. Choose another focus, or explicitly try that focus again.</p>'+chooseFocus;
  else if(a?.awaitingWant)card+='<div class="coach-buttons">'+button('Yes, keep this goal','wanted','data-yes="true"')+button('No, try something else','wanted','data-yes="false" class="secondary"')+'</div>';
  else if(a?.status==='prepared')card+='<label><input type="checkbox" data-coach-followup '+(m.settings.proactive&&m.settings.followup?'checked':'')+'>Ask me how it went when I return to My Timber tomorrow. No push or email.</label>'+(a.keepSuccessful?'<p>You said the previous version helped. Keep this version or choose another step.</p>'+button('Choose another step','different-step'):'')+'<div class="coach-buttons">'+button('That works — accept','accept')+button('Not for me — change it','decline','class="secondary"')+'</div>';
  else if(a?.status==='accepted')card+='<p><strong>Accepted. It’s saved for when it suits you.</strong></p><details '+(data.followup?'open':'')+'><summary>Tell Shift AI how it went</summary>'+(data.followup?'<p>Still working for you, or do we need a smaller step?</p>':'')+'<div class="coach-buttons">'+['helped','didnt-help','didnt-fit','didnt-try'].map(v=>button(labels[v],'outcome','data-value="'+v+'"')).join('')+'</div></details>';
  if(a?.task&&!a.awaitingWant&&!data.supportRequired)card+='<div data-coach-task><h3>'+esc(a.task.title)+'</h3><p>Time to plan this step: about '+esc(a.minutes)+' '+(a.minutes===1?'minute':'minutes')+'. Doing it can take longer.</p><ol>'+a.task.steps.map(step=>'<li>'+esc(step)+'</li>').join('')+'</ol>'+(a.task.link?'<p><a class="coach-button" href="'+esc(a.task.link.url)+'">'+esc(a.task.link.label)+'</a></p>':'')+'</div>';
  const lastHelp=[...m.outcomes].reverse().find(o=>o.value==='helped');
  const capture=lastHelp&&!(m.workingRoutines||[]).some(r=>r.outcomeId===lastHelp.id)&&!data.supportRequired?'<details data-coach-working-capture open><summary>What exactly worked? Optional</summary><form data-coach-working data-outcome="'+esc(lastHelp.id)+'"><label>Your own meal, timing or practical workaround<textarea name="text" maxlength="400" required placeholder="A tuna wrap before my late shift"></textarea></label><p>Save everyday details you want SHIFT to remember. You can edit or delete them later.</p><button type="submit">Save what worked for me</button></form></details>':'';
  const routines='<details data-coach-routines><summary>My routines that worked</summary>'+((m.workingRoutines||[]).length?(m.workingRoutines||[]).map(r=>'<form data-coach-working data-outcome="'+esc(r.outcomeId)+'"><label>You reported this helped<textarea name="text" maxlength="400" required>'+esc(r.text)+'</textarea></label><p>Saved '+esc(new Date(r.at).toLocaleDateString('en-GB'))+'. Your own experience; no clinical benefit is inferred.</p>'+(r.status==='needs-change'?'<p>This version no longer fits. SHIFT will leave it out until you change it.</p>':'')+'<div class="coach-buttons"><button type="submit">Save correction</button>'+(r.status==='needs-change'?'':button('This no longer works for me','working-pause','data-id="'+esc(r.id)+'" class="secondary"'))+button('Forget this routine','working-delete','data-id="'+esc(r.id)+'" class="secondary"')+'</div></form>').join(''):'<p>When a step helps, you can save the specific version that worked for you.</p>')+'</details>';
  if(a?.routineSuggestion&&!data.supportRequired)card+='<aside data-coach-working-suggestion><h3>Something you said worked</h3><p>'+esc(a.routineSuggestion.text)+'</p><p>'+esc(a.routineSuggestion.needsFitReview?'Your week or circumstances have changed since this worked. Check that it still fits before using it.':'Does this still fit your day? You can keep today’s suggestion or choose your saved routine.')+'</p>'+button(a.routineSuggestion.needsFitReview?'Still fits — use this routine':'Use my saved routine','working-use','data-id="'+esc(a.routineSuggestion.id)+'"'+(a.routineSuggestion.needsFitReview?' data-confirm-fit="true"':''))+'</aside>';
  card+='<p data-coach-reminder-link><a href="/member/settings#pwaReminderSettings">Choose or change an optional daily reminder</a>. Notifications use your existing device settings and keep health details off the lock screen.</p>';
  const guidance=a?.guidance&&!data.supportRequired?'<details data-coach-guidance><summary>Useful detail for my situation</summary>'+a.guidance.map(g=>'<section data-coach-guide="'+esc(g.id)+'"><h3>'+esc(g.title)+'</h3>'+g.paragraphs.map(p=>'<p>'+esc(p)+'</p>').join('')+(g.sources.length?'<p>Sources checked '+esc(g.checkedAt)+'. General guidance; this coaching copy has not been independently clinically reviewed.</p><ul>'+g.sources.map(source=>'<li><a href="'+esc(source.url)+'" target="_blank" rel="noopener noreferrer">'+esc(source.label)+'</a></li>').join('')+'</ul>':'<p>SHIFT practical planning examples; no clinical outcome is claimed.</p>')+'</section>').join('')+'</details>':'';
  const treatment=data.treatment?'<aside data-coach-treatment><h3>'+esc(data.treatment.title)+'</h3><p>'+esc(data.treatment.text)+'</p><p>'+esc(data.treatment.clinical)+'</p></aside>':'';
  const challengeForm='<details data-coach-difficulty><summary>Make this fit today</summary><form data-coach-challenge><label>What is hardest right now?<select name="challenge">'+challengeOptions(m.facts.find(f=>f.key==='challenge')?.value)+'</select></label><button type="submit">Save what is hardest</button></form></details>';
  const memory='<details data-coach-memory><summary>What SHIFT knows about me</summary>'+m.facts.map(f=>'<form data-coach-fact="'+esc(f.key)+'"><label>'+esc(labels[f.key]||f.key)+(f.key==='challenge'?'<select name="value">'+challengeOptions(f.value)+'</select>':f.key==='focus'?'<select name="value">'+(data.choices||[]).map(c=>'<option value="'+esc(c.focus)+'" '+(c.focus===f.value?'selected':'')+'>'+esc(c.label)+'</option>').join('')+'</select>':'<input name="value" value="'+esc(f.value)+'" maxlength="240" required>')+'</label><div class="coach-buttons"><button type="submit">Save correction</button>'+button('Delete','delete-item','data-id="'+esc(f.id)+'" class="secondary"')+'</div></form>').join('')+'<p>Stage: '+esc(m.stage)+'. Situation: '+esc(labels[m.mode])+'. Life Back focus: '+m.components.map(esc).join(', ')+'.</p><form data-coach-mode><label>My situation<select name="mode">'+['none','elsewhere','shift','planning-stop','stopped'].map(v=>'<option value="'+v+'" '+(m.mode===v?'selected':'')+'>'+esc(labels[v])+'</option>').join('')+'</select></label><button type="submit">Save my situation</button></form><form data-coach-stage><label>Where I am now<select name="stage">'+['Just starting','Already making changes','Hit a wall'].map(v=>'<option '+(m.stage===v?'selected':'')+'>'+v+'</option>').join('')+'</select></label><button type="submit">Save my stage</button></form><h3>What you said helped</h3><ul>'+m.outcomes.map(o=>'<li>'+esc(o.title||'Your saved step')+' — '+esc(labels[o.value])+' · '+esc(new Date(o.at).toLocaleDateString('en-GB'))+'</li>').join('')+'</ul><h3>Advice you rejected</h3>'+m.rejections.map(type=>'<p>'+esc(type.replace(/-/g,' '))+' '+button('Restore','restore','data-type="'+esc(type)+'" class="secondary"')+'</p>').join('')+'<h3>Prepared plans</h3><ul>'+m.derivedPlans.map(p=>'<li data-coach-plan="'+esc(p.id)+'">'+(p.status==='superseded'?'Earlier plan — ':'')+esc(p.title)+' — '+esc(p.reason)+(p.accepted?' — Accepted':p.status==='superseded'?' — Replaced by your current step':button('Accept this plan','plan-accept','data-id="'+esc(p.id)+'"'))+'</li>').join('')+'</ul><p>Confirmed information is kept until you delete it. Decision history older than 90 days is removed on the next saved update. Your feedback stays until you delete your coaching records. No model is trained on these records.</p>'+button('Delete all coaching records','delete-all','class="secondary"')+'</details>';
  const settings='<details><summary>My permissions and follow-up</summary><form data-coach-settings><label><input type="checkbox" name="proactive" '+(m.settings.proactive?'checked':'')+'>Prepare my plan in the background inside My Timber</label><label><input type="checkbox" name="followup" '+(m.settings.followup?'checked':'')+'>Prepare a follow-up for actions I accept</label><label>Weekly plan day<select name="weeklyDay"><option value="">Off</option>'+['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i)=>'<option value="'+i+'" '+(m.settings.weeklyDay===i?'selected':'')+'>'+d+'</option>').join('')+'</select></label><label>Quiet hours start<input type="time" name="quietStart" value="'+esc(m.settings.quietStart)+'" required></label><label>Quiet hours end<input type="time" name="quietEnd" value="'+esc(m.settings.quietEnd)+'" required></label><p>These choices apply inside My Timber. No push, calendar, wearable or scale connection is enabled.</p><button type="submit">Save my choices</button></form></details>';
  const r=data.review;const review='<details><summary>My weekly Life Back review</summary><p>'+esc(r.win?.text||'Record what fitted and helped; your own assessment counts.')+'</p><p>'+esc(r.weeklyAssessment?'You rated your last week '+r.weeklyAssessment.rating+' out of 5.':'No weekly assessment saved yet.')+'</p><div class="coach-buttons">'+[1,2,3,4,5].map(v=>button('Week: '+v+'/5','review','data-rating="'+v+'"')).join('')+'</div><p>'+esc(r.next)+'</p><form data-coach-components><fieldset><legend>What counts for my Life Back</legend>'+['energy','sleep','activity','mood','waist','weight'].map(v=>'<label><input type="checkbox" name="component" value="'+v+'" '+(m.components.includes(v)?'checked':'')+'>'+v+'</label>').join('')+'</fieldset><p>Your own weekly assessment always stays alongside these choices.</p><button type="submit">Save my Life Back choices</button></form></details>';
  const audit='<details><summary>Why Ask Timber acted</summary><ul>'+data.audit.slice(-20).reverse().map(x=>'<li>'+esc(new Date(x.at).toLocaleString('en-GB'))+' · '+esc(x.type.replace(/[-_]/g,' '))+' · '+esc(x.outcome.replace(/_/g,' '))+'</li>').join('')+'</ul></details>';
  const paused=(m.pauseRequests||[]).filter(x=>x.status==='queued').map(x=>'<p>Follow-ups are paused after two unanswered prompts. Keep them? '+button('Yes, keep follow-ups','pause-choice','data-id="'+esc(x.id)+'" data-yes="true"')+button('Leave them off','pause-choice','data-id="'+esc(x.id)+'" data-yes="false" class="secondary"')+'</p>').join('');
  const changes='<details data-coach-change-panel><summary>Something’s changed</summary><p>Tell us what needs changing. Your goal and earlier feedback stay saved; this replaces your current step.</p><form data-coach-circumstances><label>What has changed?<select name="change" required><option value="" selected disabled>Choose what has changed</option><option value="stopped">I have stopped treatment</option><option value="cost">I need everyday support on a tighter budget</option><option value="provider">My treatment provider or situation has changed</option><option value="appetite">My appetite or food noise has changed</option><option value="routine">My routine has gone out of the window</option></select></label><div data-change-provider hidden><label>My medication situation now<select name="mode">'+['none','elsewhere','shift','planning-stop','stopped'].map(v=>'<option value="'+v+'" '+(m.mode===v?'selected':'')+'>'+esc(labels[v])+'</option>').join('')+'</select></label></div><div data-change-appetite hidden><label>What feels different?<select name="challenge"><option value="returning-food-noise">Food thoughts are getting in the way</option><option value="low-appetite">A small appetite makes meals awkward</option></select></label></div><label>What is different about your week? <span data-change-week-label>(optional)</span><input name="week" maxlength="240" autocomplete="off" placeholder="Mornings work better now; evenings are difficult"></label><p data-change-cost hidden>This keeps everyday food costs down. Treatment prices and medicine choices belong with your prescribing team.</p><label><input type="checkbox" name="followup" '+(m.settings.proactive&&m.settings.followup?'checked':'')+'>When I accept the new step, ask how it went on a return to My Timber from tomorrow.</label><p>No email or push reminder. My Timber does not contact your prescriber or change treatment.</p><button type="submit">Update my next step</button></form>'+quotePanel()+'</details>';
  const practical='<details><summary>What fits my day</summary><form data-coach-constraints>'+practicalFields(m.constraints)+'<p>These explicit choices shape the next step. Saving a change replaces the current plan.</p><button type="submit">Save what fits</button></form></details>';
  const journey=data.journey?'<div data-coach-journey><h3>'+esc(data.journey.title)+'</h3><p>'+esc(data.journey.text)+'</p><p>'+esc(data.journey.reported)+' actions reported; '+esc(data.journey.helpful)+' marked helpful. Unreported days stay unknown.</p></div>':'';
  const support=supportPanel(true);
  content.innerHTML=journey+card+capture+changes+guidance+routines+challengeForm+treatment+practical+support+paused+memory+settings+review+audit+help()+'<p><a href="/member/ask-timber">Ask Shift AI a question</a></p>';bind();performance.mark('shift-coach-ready');
  if(data.followup){const id=data.followup.id,revision=data.revision;followupObserver=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting)||document.hidden||pending)return;followupObserver.disconnect();api('POST',{kind:'followup-seen',id,revision,operationId:crypto.randomUUID()}).then(r=>{if(data.revision===revision)data.revision=r.revision;}).catch(()=>{content.querySelector('details')?.removeAttribute('open');});});followupObserver.observe(host);}
 }
 function bind(){
  content.querySelector('[data-coach-quote-budget]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),values=[1,2,3].map(i=>String(f.get('quote'+i)||'').trim()),known=values.filter(v=>v!==''),result=e.target.querySelector('[data-coach-quote-result]');if(known.some(v=>!/^\d+(?:\.\d{1,2})?$/.test(v)||Number(v)>100000)){result.textContent='Use GBP amounts with up to two decimal places, or leave an unknown quote blank.';return;}if(!known.length){result.textContent='No quotes entered yet. Ask for complete prices before comparing.';return;}const pennies=known.reduce((sum,v)=>sum+Math.round(Number(v)*100),0),money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(pennies/100);result.textContent=known.length===3?'Your three entered quotes add up to '+money+'. Check each supply period and the terms before committing.':'Known quotes subtotal: '+money+'. '+(3-known.length)+' '+(known.length===2?'quote is':'quotes are')+' missing, so the full three-supply cost is still unknown.';});
  const changeForm=content.querySelector('[data-coach-circumstances]');if(changeForm){const select=changeForm.elements.change;const show=()=>{const v=select.value;changeForm.querySelector('[data-change-provider]').hidden=v!=='provider';changeForm.querySelector('[data-change-appetite]').hidden=v!=='appetite';changeForm.querySelector('[data-change-cost]').hidden=v!=='cost';changeForm.closest('[data-coach-change-panel]').querySelector('[data-coach-quote-panel]').hidden=v!=='cost';changeForm.elements.week.required=v==='routine';changeForm.querySelector('[data-change-week-label]').textContent=v==='routine'?'(needed to fit your new routine)':'(optional)';};select.addEventListener('change',show);show();changeForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(changeForm);update({kind:'circumstances',change:f.get('change'),mode:f.get('mode'),challenge:f.get('challenge'),week:f.get('week'),followup:f.has('followup')});});}

  content.querySelectorAll('[data-coach-working]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();update({kind:'working-detail',outcomeId:f.dataset.outcome,text:new FormData(f).get('text')});}));
  content.querySelector('[data-coach-constraints]')?.addEventListener('submit',e=>{e.preventDefault();update({kind:'constraints',constraints:constraintsFrom(new FormData(e.target))});});
  content.querySelector('[data-coach-blocker]')?.addEventListener('submit',e=>{e.preventDefault();update({kind:'blocker',blocker:new FormData(e.target).get('blocker')});});
  content.querySelector('[data-coach-support-request]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);update({kind:'support-request',message:f.get('message'),share:f.has('share')});});
  content.querySelector('[data-coach-focus]')?.addEventListener('submit',e=>{e.preventDefault();const [focus,restore]=new FormData(e.target).get('focus').split(':');update({kind:'focus',focus,restore:restore==='restore'});});
  content.querySelector('[data-coach-setup]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);update({kind:'setup',goal:f.get('goal')});});
  content.querySelector('[data-coach-challenge]')?.addEventListener('submit',e=>{e.preventDefault();update({kind:'fact',key:'challenge',value:new FormData(e.target).get('challenge')});});
  content.querySelectorAll('[data-coach-fact]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();update({kind:'fact',key:f.dataset.coachFact,value:new FormData(f).get('value')});}));
  content.querySelector('[data-coach-mode]')?.addEventListener('submit',e=>{e.preventDefault();update({kind:'mode',mode:new FormData(e.target).get('mode')});});
  content.querySelector('[data-coach-stage]')?.addEventListener('submit',e=>{e.preventDefault();update({kind:'stage',stage:new FormData(e.target).get('stage')});});
  content.querySelector('[data-coach-components]')?.addEventListener('submit',e=>{e.preventDefault();update({kind:'components',components:new FormData(e.target).getAll('component')});});
  content.querySelector('[data-coach-settings]')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),day=f.get('weeklyDay');update({kind:'settings',settings:{proactive:f.has('proactive'),followup:f.has('followup'),weeklyDay:day===''?null:Number(day),quietStart:f.get('quietStart'),quietEnd:f.get('quietEnd')}});});
  content.querySelectorAll('[data-coach-action]').forEach(b=>b.addEventListener('click',async()=>{const kind=b.dataset.coachAction;if(kind==='open-support'){const panel=content.querySelector('[data-coach-support]');if(panel){panel.open=true;const field=panel.querySelector('textarea')||panel.querySelector('a');field?.focus();panel.scrollIntoView({block:'nearest'});}return;}if(kind==='delete-all'){if(!confirm('Delete all Shift AI coaching context, plans, outcomes and decision history?'))return;try{await api('DELETE');await refresh();status.textContent='Your coaching records have been deleted.';}catch(e){status.textContent=errorText(e);}return;}update({kind,reference:b.dataset.reference,replyId:b.dataset.reply,confirmFit:b.dataset.confirmFit==='true',...(kind==='accept'?{followup:!!content.querySelector('[data-coach-followup]')?.checked}:{}),id:b.dataset.id||data.action?.id,value:b.dataset.value,yes:b.dataset.yes==='true',type:b.dataset.type,rating:Number(b.dataset.rating)});}));
 }
 async function refresh({afterWrite=false}={}){if(pending&&!afterWrite)return;const generation=++refreshGeneration;try{const next=await api();if(generation!==refreshGeneration)return;if(JSON.stringify(next)!==JSON.stringify(data)){data=next;render();}}catch(error){if(error.status===401){data=null;followupObserver?.disconnect();host.hidden=true;content.replaceChildren();status.textContent='';host.closest('#panel-today')?.removeAttribute('data-shift-coach-enabled');document.body.removeAttribute('data-shift-coach-session');}throw error;}}
 const initial=document.getElementById('shiftCoachInitial');let seeded=false;if(initial){try{data=JSON.parse(initial.textContent);render();seeded=true;}catch{}initial.remove();}
 if(!seeded)refresh().catch(e=>{if(e.status===401){host.hidden=true;return;}host.hidden=false;content.innerHTML='<h2>Ask Timber</h2><p>Your saved coaching plan could not load.</p>';status.textContent='Please refresh to try again. The rest of My Timber is available.';});
 document.addEventListener('sst:consentchange',()=>refresh().catch(()=>{}));
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!pending)refresh().catch(()=>{});});
 window.addEventListener('pageshow',e=>{if(e.persisted)refresh().catch(()=>{});});
 new MutationObserver(()=>{if(document.body.dataset.appTool==='today'&&!pending)refresh().catch(()=>{});}).observe(document.body,{attributes:true,attributeFilter:['data-app-tool']});
})();`;