export const stages=['Just starting','Already making changes','Hit a wall'];
export const library=Object.freeze([
 {type:'food-plan',focus:'food',component:'energy',title:'Choose one straightforward meal',small:'Pick a familiar meal for your busiest day',alternative:'Put the ingredients for one meal on your shopping list',minutes:5,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'food-shop',focus:'food',component:'energy',title:'Put one useful meal on your shopping list',small:'Save the ingredients for a familiar meal',alternative:'Prepare a short shopping list for your next food shop',minutes:3,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'food-prepare',focus:'food',component:'energy',title:'Choose what you can get ready before a busy day',small:'Put one meal item where you will remember it',alternative:'Make your busy day easier by getting one thing ready',minutes:3,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'movement-plan',focus:'movement',component:'activity',title:'Choose a bit of movement that fits your day',small:'Choose a short movement break when it suits you',alternative:'Find a movement option you would enjoy trying',minutes:10,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'movement-choice',focus:'movement',component:'activity',title:'Find a movement option you would enjoy',small:'Save one option you would like to try',alternative:'Choose an option from Fit for a day that suits you',minutes:3,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'review-plan',focus:'reflection',component:'energy',title:'Record how your week actually felt',small:'Save one word for how this week felt',alternative:'Write down one thing that made the week easier',minutes:2,url:'https://shiftsometimber.co.uk/life-back'}
]);
export function tone(stage){return stage==='Hit a wall'?'A hard week counts too. Keep this small.':stage==='Already making changes'?'Keep what works. Change what gets in the way.':'Start with one thing you can actually use.';}
export const knowledgePolicy=Object.freeze({state:'integration_candidate',source:'https://shiftsometimber.co.uk/life-back',retrieved:'2026-10-01',approval:'Matt authorised website content as the knowledge foundation; these new action strings still require independent voice/relevance review.',clinicalApproval:false,scope:'Everyday action planning and personal check-ins only',version:'coaching-integration-1',noAutomaticApprovalFromPublication:true});
