export const stages=['Just starting','Already making changes','Hit a wall'];
const actions=[
 {type:'food-assemble',focus:'food',component:'energy',title:'Put together a meal without a cooker',small:'Choose one familiar no-cook meal',alternative:'Use a no-cook option for the difficult part of your day',minutes:3},
 {type:'food-cupboard',focus:'food',component:'energy',title:'Build a meal from what you already have',small:'Check one food you already have',alternative:'Use what is already in before buying more',minutes:3},
 {type:'food-backup',focus:'food',component:'energy',title:'Save a fallback for a rushed day',small:'Name one easy fallback meal',alternative:'Choose a backup instead of a new recipe',minutes:2},
 {type:'food-plan',focus:'food',component:'energy',title:'Choose one straightforward meal',small:'Pick a familiar meal for your busiest day',alternative:'Put the ingredients for one meal on your shopping list',minutes:5,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'food-shop',focus:'food',component:'energy',title:'Put one useful meal on your shopping list',small:'Save the ingredients for a familiar meal',alternative:'Prepare a short shopping list for your next food shop',minutes:3,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'food-prepare',focus:'food',component:'energy',title:'Choose what you can get ready before a busy day',small:'Put one meal item where you will remember it',alternative:'Make your busy day easier by getting one thing ready',minutes:3,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'movement-plan',focus:'movement',component:'activity',title:'Choose a bit of movement that fits your day',small:'Choose a short movement break when it suits you',alternative:'Find a movement option you would enjoy trying',minutes:10,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'movement-choice',focus:'movement',component:'activity',title:'Find a movement option you would enjoy',small:'Save one option you would like to try',alternative:'Choose an option from Fit for a day that suits you',minutes:3,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'movement-anchor',focus:'movement',component:'activity',title:'Fit movement around something you already do',small:'Choose an existing moment in your day',alternative:'Use an everyday cue instead of a timetable',minutes:2},
 {type:'reflection-obstacle',focus:'reflection',component:'mood',title:'Change one awkward part of your week',small:'Name one thing getting in the way',alternative:'Choose one practical obstacle to change',minutes:2},
 {type:'review-plan',focus:'reflection',component:'energy',title:'Record how your week actually felt',small:'Save one word for how this week felt',alternative:'Write down one thing that made the week easier',minutes:2,url:'https://shiftsometimber.co.uk/life-back'}
];
const practical=new Set(['food-assemble','food-cupboard','food-backup','movement-anchor','reflection-obstacle']);
export const library=Object.freeze([...actions.filter(a=>!practical.has(a.type)),...actions.filter(a=>practical.has(a.type))]);
export function tone(stage){return stage==='Hit a wall'?'A hard week counts too. Keep this small.':stage==='Already making changes'?'Keep what works. Change what gets in the way.':'Start with one thing you can actually use.';}
export const focusLabels=Object.freeze({food:'Food that fits my day',movement:'Movement that fits my day',reflection:'How the week feels'});
export function focusChoices(state){return Object.entries(focusLabels).map(([focus,label])=>({focus,label,restore:!library.some(a=>a.focus===focus&&!state.rejected.includes(a.type)&&!state.pausedTypes.includes(a.type))}));}
export function treatmentSupport(mode){if(mode==='none')return {title:'Everyday support, with or without medication',text:'You can use My Timber without taking medication. Choose food, movement and routines that fit your day; tell us what helped.',clinical:'Treatment questions belong with a qualified clinician. This space is for everyday coaching.'};if(mode==='planning-stop')return {title:'Before treatment ends: keep a useful routine',text:'Choose one routine you can carry forward, and a fallback for a difficult day. Tell us what helps so it stays in your plan.',clinical:'Discuss stopping or changing treatment with your prescriber. My Timber does not choose when or how to stop.'};return mode==='stopped'
 ?{title:'After treatment: keep what works',text:'Your everyday support carries on here when medication purchases stop. Keep one routine you can repeat. If food noise returns, note when it gets in the way and plan one familiar meal for that part of the day. A setback is a reason to adjust the plan, not write off the week.',clinical:'Questions about restarting, symptoms or treatment belong with your prescriber or GP. Saving them here does not contact anyone.'}
 :{title:'During treatment: make the week easier',text:'Use this space for meals, movement and difficult weeks alongside your prescribed care. Choose something that fits today; tell us what helped and what needs changing.',clinical:mode==='shift'?'Your prescribing team handles treatment questions. Use the contact details supplied with your treatment. This coaching card does not send them a message.':'Your own prescriber handles treatment questions, even when your everyday coaching is here. Use their contact details; this card does not send them a message.'};}
// Fixed, reviewable everyday tasks. These do not choose medicine, doses or exercise therapy.
export function everydayTask(type,tiny=false,mode='elsewhere',week=''){
 const tasks={
  'food-plan':{title:tiny?'Name one familiar meal':'Tonight: one familiar meal',steps:tiny?['Choose one meal you already know how to make. That is enough for today.']:['One option: beans on toast. You need bread and a tin of beans; use foods that suit your preferences and allergies.','Toast the bread, heat the beans following the tin instructions, and serve. Already have another familiar meal in mind? Use that instead.','Choose when it will fit your day.'],link:{label:'Choose another meal in Grub',url:'/member/grub'}},
  'food-shop':{title:tiny?'One item on the shopping list':'Make the next food shop easier',steps:tiny?['Write down one ingredient for a familiar meal. You do not have to finish the list today.']:['Choose a meal you already enjoy. For beans on toast, the list is bread and a tin of beans.','Check what you already have; write only the missing items on the list you normally use.'],link:{label:'Find a meal in Grub',url:'/member/grub'}},
  'food-prepare':{title:tiny?'Put one thing ready':'Help tomorrow-you out',steps:tiny?['Put one shelf-stable ingredient for tomorrow’s meal where you will remember it. Leave chilled food in the fridge.']:['Choose tomorrow’s familiar meal.','Put the shelf-stable ingredients together, or leave yourself a note about what is in the fridge. Follow the food’s storage instructions.'],link:{label:'Choose tomorrow’s meal in Grub',url:'/member/grub'}},
  'movement-plan':{title:tiny?'Choose a moment for movement':'Movement that fits your day',steps:tiny?['Choose one moment today when a comfortable movement break could fit. Planning it is the whole step.']:['Choose a short, comfortable walk or a movement option you already know suits you.','Pick a time that fits your day. You can make it shorter or leave it for another day.','If movement causes pain or you are unsure what is suitable, ask a healthcare professional; this is not an exercise prescription.'],link:{label:'Choose an option in Fit',url:'/member/fit'}},
  'movement-choice':{title:tiny?'Name an option you like':'Find movement you would actually choose',steps:tiny?['Name one movement option you would like to look at. No need to do it now.']:['Open Fit and look for an option that suits your interests and ability.','Choose when you would like to try it. You do not have to start today.'],link:{label:'Browse Fit',url:'/member/fit'}},
  'review-plan':{title:tiny?'One word for this week':'Keep one thing that worked',steps:tiny?['Pick one word for how this week felt.']:['Name one thing that made the week easier, and one thing that got in the way.','Keep the useful bit; change one part of the difficult bit. Use your weekly review below to record how the week felt.']}
 };
 Object.assign(tasks,{
 'food-assemble':{title:tiny?'Name a familiar no-cook meal':'A meal without a cooker',steps:tiny?['Name one familiar meal you can assemble without cooking.']:['Choose a no-cook meal you already like. One option is a sandwich using bread and a ready-to-eat filling that suits your preferences and allergies.','Check the label and storage instructions. Put the missing ingredients on your usual list.','Choose when you will use it; you do not need new cooking equipment.'],link:{label:'Find another option in Grub',url:'/member/grub'}},
 'food-cupboard':{title:tiny?'Check one thing already in':'Use what is already in',steps:tiny?['Check one food in your cupboard or fridge that you can use.']:['Check what you already have and the use-by or storage instructions.','Choose a familiar meal around those ingredients. Write down only what is missing.','If money is tight, keep to ingredients you already use rather than buying a new recipe’s extras.'],link:{label:'Find a familiar meal in Grub',url:'/member/grub'}},
 'food-backup':{title:tiny?'Name one fallback meal':'Your rushed-day fallback',steps:tiny?['Name a familiar meal you can put together quickly.']:['Choose one familiar meal with very little preparation. Use something that suits your preferences and allergies.','Save its name and the ingredients on the list you normally use.','Choose the busy part of your week when this fallback will be useful.'],link:{label:'Choose a fallback in Grub',url:'/member/grub'}},
 'movement-anchor':{title:tiny?'Choose one everyday cue':'Use a moment already in your day',steps:tiny?['Choose an everyday cue, such as finishing a task, when you could consider a comfortable movement break.']:['Choose an everyday cue that happens naturally, such as finishing a task.','At that moment, consider a short movement option you already know is comfortable and suitable for you. Planning it is enough today.','Pain or uncertainty about suitable movement belongs with a healthcare professional.'],link:{label:'Look at options in Fit',url:'/member/fit'}},
 'reflection-obstacle':{title:tiny?'Name one practical obstacle':'Change one awkward bit',steps:tiny?['Name one practical thing making your routine difficult.']:['Choose one practical obstacle: time, cost, preparation or a plan you do not enjoy.','Pick one thing you can change, such as keeping an easy fallback or choosing another time.','Use What fits my day below to save the practical choices that should shape your next step.']}
 });
 const task=tasks[type];if(!task)return null;
 if(mode==='stopped'&&type.startsWith('food-'))return {...task,title:tiny?'Keep one familiar meal':'After treatment: keep one meal routine',steps:[...task.steps,...(!tiny?[/food noise|hungry again|cravings|thinking about food/i.test(week)?'Note when food thoughts get in the way. Choose a familiar meal for that point in your day; do not turn a difficult day into a punishment.':'Choose one day to repeat this meal routine. Keeping it familiar can make the week easier.']:[])]};
 if(mode==='planning-stop'&&type.startsWith('food-'))return {...task,steps:[...task.steps,...(!tiny?['Keep a note of whether this routine helps. It can be part of your everyday plan if treatment ends; stopping or changing medication belongs with your prescriber.']:[])]};
 return task;
}
export const knowledgePolicy=Object.freeze({state:'owner_authorised_everyday_coaching',source:'https://shiftsometimber.co.uk/life-back',retrieved:'2026-10-02',approval:'Matt authorised the website knowledge foundation and instructed the progressive everyday coaching repairs. The fixed task copy is builder-verified; independent relevance and clinical review are not claimed.',clinicalApproval:false,scope:'Everyday action planning and personal check-ins only',version:'coaching-progressive-loop-1',noAutomaticApprovalFromPublication:true});
