export const stages=['Just starting','Already making changes','Hit a wall'];
export const challengeLabels=Object.freeze({everyday:'Just the everyday basics','busy-days':'Busy days and awkward shifts',evenings:'Evenings are hardest',weekends:'Weekends and social plans','returning-food-noise':'Food thoughts are getting in the way',setback:'Getting going after a setback','low-motivation':'Motivation is low'});
const approaches={'food-plan':'meal-planning','food-shop':'meal-planning','food-prepare':'meal-planning','movement-plan':'scheduling','movement-choice':'enjoyment','review-plan':'reflection'};
const expandedActions=[
 {type:'food-default',focus:'food',approach:'easy-default',challenges:['busy-days','setback','low-motivation'],title:'Keep an easy meal option ready',small:'Name one easy meal option',minutes:2,steps:['Pick a familiar meal that needs little effort and uses foods that suit you. It can be something you already buy.','Keep its ingredients on your next shopping list, or note where you can get it. This is an option for a difficult day, not a whole new food plan.'],tiny:['Name one familiar meal you could use on a difficult day.']},
 {type:'food-evening',focus:'food',approach:'routine-cue',challenges:['evenings','returning-food-noise'],title:'Give your evening a familiar starting point',small:'Choose one evening cue',minutes:2,steps:['Choose a regular point in your evening, such as getting home, when you can pause and decide what you need.','If you are hungry, choose food that suits you. If food thoughts are getting in the way, note the situation so you can discuss what would help next. The aim is a useful routine, not ignoring hunger.'],tiny:['Choose one point in your evening to pause and decide what you need, including food if you are hungry.']},
 {type:'food-social',focus:'food',approach:'social-support',challenges:['weekends'],title:'Make one social food plan with someone',small:'Tell someone what would make the plan easier',minutes:2,steps:['Think of your next meal out or gathering. Choose one thing that would make it easier to enjoy.','Tell the person you are going with: for example, agree where to eat before setting off. You do not need to make up for the meal by skipping food afterwards.'],tiny:['Tell someone one thing that would make your next meal out easier to enjoy.']},
 {type:'food-notice',focus:'food',approach:'noticing',challenges:['returning-food-noise','evenings'],title:'Notice when food thoughts get in the way',small:'Note one difficult moment',minutes:2,steps:['When food thoughts get in the way, make one short note: when it happened and what was going on. No calorie counts or judgement needed.','Use that note to change your everyday routine, or share it with your prescriber if you want treatment advice. Writing it here does not send it to anyone.'],tiny:['Note when one difficult food-thought moment happened and what was going on.']},
 {type:'food-environment',focus:'food',approach:'environment',challenges:['busy-days','low-motivation'],title:'Make one useful food option easier to reach',small:'Put one useful item where you will remember it',minutes:2,steps:['Choose a food option you already like and that suits your needs.','Make it easier to find: put a shelf-stable ingredient together with the other meal items, or leave a note about what is in the fridge. Keep food stored according to its instructions.'],tiny:['Leave yourself a note about one food option you already have.']},
 {type:'food-restart',focus:'food',approach:'fresh-start',challenges:['setback'],title:'Make your next meal an ordinary meal',small:'Name your next ordinary meal',minutes:1,steps:['A difficult day does not need a punishment plan. Choose your next ordinary meal using foods that suit you.','Decide one thing that would make getting it ready easier. Start there.'],tiny:['Name your next ordinary meal. A difficult day does not need a punishment plan.']},
 {type:'movement-company',focus:'movement',approach:'social-support',challenges:['low-motivation','weekends'],title:'Ask someone to join you',small:'Name someone you could ask',minutes:2,steps:['Choose someone you would enjoy spending time with.','Ask whether they fancy a short outing or a familiar activity that suits your ability. Agree a time together; planning it is enough for today.'],tiny:['Name one person you could ask to join you for a familiar activity.']},
 {type:'movement-cue',focus:'movement',approach:'routine-cue',challenges:['busy-days','setback'],title:'Attach movement to something already in your day',small:'Choose one point in your day',minutes:2,steps:['Pick something already in your day, such as a lunch break or finishing work.','Decide whether a comfortable bit of movement could fit there. Choose an option you already know suits you. Planning is enough; this is not an exercise prescription.'],tiny:['Choose one existing point in your day when a comfortable bit of movement could fit.']},
 {type:'movement-ready',focus:'movement',approach:'environment',challenges:['low-motivation','busy-days'],title:'Remove one bit of getting-ready hassle',small:'Put one thing ready',minutes:1,steps:['Think of a familiar activity that suits you. What makes getting started a hassle?','Put one useful thing ready, such as your coat or comfortable shoes. You do not have to do the activity today.'],tiny:['Put one thing ready for a familiar activity, such as your coat.']},
 {type:'review-barrier',focus:'reflection',approach:'problem-solving',challenges:['busy-days','setback'],title:'Change one thing that got in the way',small:'Name one obstacle',minutes:2,steps:['Name one thing that made the week awkward: time, getting organised or a plan that was too much.','Choose one adjustment you control, such as a different time or an easier first step. Keep it to one change.'],tiny:['Name one practical thing that got in the way. You do not have to solve the whole week.']},
 {type:'review-support',focus:'reflection',approach:'social-support',challenges:['low-motivation','setback'],title:'Ask for one practical bit of help',small:'Name one bit of help you could ask for',minutes:2,steps:['Choose one practical thing someone could help with, such as company for an outing or sharing a cooking job.','Ask someone you trust for that specific bit of help. You do not have to explain everything.'],tiny:['Name one practical bit of help you could ask someone for.']},
 {type:'review-restart',focus:'reflection',approach:'fresh-start',challenges:['setback','low-motivation'],title:'Pick one thing to keep from the week',small:'Name one useful bit',minutes:1,steps:['Think of one thing that was useful, even in a difficult week.','Choose when you would like to try that useful bit again. Leave the rest of the week alone for now.'],tiny:['Name one useful bit from the week, however small.']}
];
const actions=[
 {type:'food-assemble',focus:'food',component:'energy',title:'Put together a meal without a cooker',small:'Choose one familiar no-cook meal',alternative:'Use a no-cook option for the difficult part of your day',minutes:3},
 {type:'food-cupboard',focus:'food',component:'energy',title:'Build a meal from what you already have',small:'Check one food you already have',alternative:'Use what is already in before buying more',minutes:3},
 {type:'food-backup',focus:'food',component:'energy',title:'Save a fallback for a rushed day',small:'Name one easy fallback meal',alternative:'Choose a backup instead of a new recipe',minutes:2},
 {type:'food-plan',focus:'food',component:'energy',title:'Choose one straightforward meal',small:'Pick a familiar meal for your busiest day',alternative:'Put the ingredients for one meal on your shopping list',minutes:5,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'food-shop',focus:'food',component:'energy',title:'Put one useful meal on your shopping list',small:'Save the ingredients for a familiar meal',alternative:'Prepare a short shopping list for your next food shop',minutes:3,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'food-prepare',focus:'food',component:'energy',title:'Choose what you can get ready before a busy day',small:'Put one meal item where you will remember it',alternative:'Make your busy day easier by getting one thing ready',minutes:3,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'movement-plan',focus:'movement',component:'activity',title:'Choose a bit of movement that fits your day',small:'Choose a short movement break when it suits you',alternative:'Find a movement option you would enjoy trying',minutes:10,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'movement-choice',focus:'movement',component:'activity',title:'Find a movement option you would enjoy',small:'Save one option you would like to try',alternative:'Choose an option from Fit for a day that suits you',minutes:3,url:'https://shiftsometimber.co.uk/life-back'},
 {type:'movement-anchor',focus:'movement',component:'activity',title:'Fit movement around something you already do',small:'Choose an existing moment in your day',alternative:'Use an everyday cue instead of a timetable',minutes:2},
 {type:'reflection-obstacle',focus:'reflection',component:'mood',title:'Change one awkward part of your week',small:'Name one thing getting in the way',alternative:'Choose one practical obstacle to change',minutes:2},
 {type:'review-plan',focus:'reflection',component:'energy',title:'Record how your week actually felt',small:'Save one word for how this week felt',alternative:'Write down one thing that made the week easier',minutes:2,url:'https://shiftsometimber.co.uk/life-back'}
];
const practical=new Set(['food-assemble','food-cupboard','food-backup','movement-anchor','reflection-obstacle']);
export const library=Object.freeze([...actions.filter(a=>!practical.has(a.type)),...actions.filter(a=>practical.has(a.type)),...expandedActions.map(a=>({...a,component:a.focus==='movement'?'activity':'energy',alternative:a.title,url:'https://shiftsometimber.co.uk/life-back'}))].map(a=>({...a,approach:a.approach||approaches[a.type]||a.type,challenges:a.challenges||['everyday']})));
export function tone(stage){return stage==='Hit a wall'?'A hard week counts too. Keep this small.':stage==='Already making changes'?'Keep what works. Change what gets in the way.':'Start with one thing you can actually use.';}
export const focusLabels=Object.freeze({food:'Food that fits my day',movement:'Movement that fits my day',reflection:'How the week feels'});
export function availableActions(state){
 const failed=new Set(state.rejected.map(type=>library.find(a=>a.type===type)).filter(Boolean).map(a=>a.focus+':'+a.approach));
 return library.filter(a=>!state.rejected.includes(a.type)&&!state.pausedTypes.includes(a.type)&&!failed.has(a.focus+':'+a.approach));
}
export function focusChoices(state){const available=availableActions(state);return Object.entries(focusLabels).map(([focus,label])=>({focus,label,restore:!available.some(a=>a.focus===focus)}));}
export function treatmentSupport(mode){if(mode==='none')return {title:'Everyday support, with or without medication',text:'You can use My Timber without taking medication. Choose food, movement and routines that fit your day; tell us what helped.',clinical:'Treatment questions belong with a qualified clinician. This space is for everyday coaching.'};if(mode==='planning-stop')return {title:'Before treatment ends: keep a useful routine',text:'Choose one routine you can carry forward, and a fallback for a difficult day. Tell us what helps so it stays in your plan.',clinical:'Discuss stopping or changing treatment with your prescriber. My Timber does not choose when or how to stop.'};return mode==='stopped'
 ?{title:'After treatment: keep what works',text:'Your everyday support carries on here when medication purchases stop. Keep one routine you can repeat. If food noise returns, note when it gets in the way and plan one familiar meal for that part of the day. A setback is a reason to adjust the plan, not write off the week.',clinical:'Questions about restarting, symptoms or treatment belong with your prescriber or GP. Saving them here does not contact anyone.'}
 :{title:'During treatment: make the week easier',text:'Use this space for meals, movement and difficult weeks alongside your prescribed care. Choose something that fits today; tell us what helped and what needs changing.',clinical:mode==='shift'?'Your prescribing team handles treatment questions. Use the contact details supplied with your treatment. This coaching card does not send them a message.':'Your own prescriber handles treatment questions, even when your everyday coaching is here. Use their contact details; this card does not send them a message.'};}
// Fixed, reviewable everyday tasks. These do not choose medicine, doses or exercise therapy.
export function everydayTask(type,tiny=false,mode='elsewhere',week=''){
 const tasks={
  'food-plan':{title:tiny?'Name one familiar meal':'Tonight: one familiar meal',steps:tiny?['Choose one meal you already know how to make. That is enough for today.']:['One option: beans on toast. You need bread and a tin of beans; use foods that suit your preferences and allergies.','Toast the bread, heat the beans following the tin instructions, and serve. Already have another familiar meal in mind? Use that instead.','Choose when it will fit your day.'],link:{label:'Choose another meal in Grub',url:'/member/grub'}},
  'food-shop':{title:tiny?'One item on the shopping list':'Make the next food shop easier',steps:tiny?['Write down one ingredient for a familiar meal. You do not have to finish the list today.']:['Choose a meal you already enjoy. For beans on toast, the list is bread and a tin of beans.','Check what you already have; write only the missing items on the list you normally use.'],link:{label:'Find a meal in Grub',url:'/member/grub'}},
  'food-prepare':{title:tiny?'Put one thing ready':'Help tomorrow-you out',steps:tiny?['Put one shelf-stable ingredient for tomorrow’s meal where you will remember it. Leave chilled food in the fridge.']:['Choose tomorrow’s familiar meal.','Put the shelf-stable ingredients together, or leave yourself a note about what is in the fridge. Follow the food’s storage instructions.'],link:{label:'Choose tomorrow’s meal in Grub',url:'/member/grub'}},
  'movement-plan':{title:tiny?'Choose a moment for movement':'Movement that fits your day',steps:tiny?['Choose one moment today when a comfortable movement break could fit. Planning it is the whole step.']:['Choose a short, comfortable walk or a movement option you already know suits you.','Pick a time that fits your day. You can make it shorter or leave it for another day.','If movement causes pain or you are unsure what is suitable, ask a healthcare professional; this is not an exercise prescription.'],link:{label:'Choose an option in Fit',url:'/member/fit'}},
  'movement-choice':{title:tiny?'Name an option you like':'Find movement you would actually choose',steps:tiny?['Name one movement option you would like to look at. No need to do it now.']:['Open Fit and look for an option that suits your interests and ability.','Choose when you would like to try it. You do not have to start today.'],link:{label:'Browse Fit',url:'/member/fit'}},
  'review-plan':{title:tiny?'One word for this week':'Keep one thing that worked',steps:tiny?['Pick one word for how this week felt.']:['Name one thing that made the week easier, and one thing that got in the way.','Keep the useful bit; change one part of the difficult bit. Use your weekly review below to record how the week felt.']}
 };
 Object.assign(tasks,{
 'food-assemble':{title:tiny?'Name a familiar no-cook meal':'A meal without a cooker',steps:tiny?['Name one familiar meal you can assemble without cooking.']:['Choose a no-cook meal you already like. One option is a sandwich using bread and a ready-to-eat filling that suits your preferences and allergies.','Check the label and storage instructions. Put the missing ingredients on your usual list.','Choose when you will use it; you do not need new cooking equipment.'],link:{label:'Find another option in Grub',url:'/member/grub'}},
 'food-cupboard':{title:tiny?'Check one thing already in':'Use what is already in',steps:tiny?['Check one food in your cupboard or fridge that you can use.']:['Check what you already have and the use-by or storage instructions.','Choose a familiar meal around those ingredients. Write down only what is missing.','If money is tight, keep to ingredients you already use rather than buying a new recipe’s extras.'],link:{label:'Find a familiar meal in Grub',url:'/member/grub'}},
 'food-backup':{title:tiny?'Name one fallback meal':'Your rushed-day fallback',steps:tiny?['Name a familiar meal you can put together quickly.']:['Choose one familiar meal with very little preparation. Use something that suits your preferences and allergies.','Save its name and the ingredients on the list you normally use.','Choose the busy part of your week when this fallback will be useful.'],link:{label:'Choose a fallback in Grub',url:'/member/grub'}},
 'movement-anchor':{title:tiny?'Choose one everyday cue':'Use a moment already in your day',steps:tiny?['Choose an everyday cue, such as finishing a task, when you could consider a comfortable movement break.']:['Choose an everyday cue that happens naturally, such as finishing a task.','At that moment, consider a short movement option you already know is comfortable and suitable for you. Planning it is enough today.','Pain or uncertainty about suitable movement belongs with a healthcare professional.'],link:{label:'Look at options in Fit',url:'/member/fit'}},
 'reflection-obstacle':{title:tiny?'Name one practical obstacle':'Change one awkward bit',steps:tiny?['Name one practical thing making your routine difficult.']:['Choose one practical obstacle: time, cost, preparation or a plan you do not enjoy.','Pick one thing you can change, such as keeping an easy fallback or choosing another time.','Use What fits my day below to save the practical choices that should shape your next step.']}
 });
 const extra=expandedActions.find(a=>a.type===type);const task=tasks[type]||(extra?{title:tiny?extra.small:extra.title,steps:tiny?extra.tiny:extra.steps,...(extra.focus==='movement'?{link:{label:'Browse Fit',url:'/member/fit'}}:extra.focus==='food'?{link:{label:'Find a meal in Grub',url:'/member/grub'}}:{})}:null);if(!task)return null;
 if(mode==='stopped'&&type.startsWith('food-'))return {...task,title:tiny?'Keep one familiar meal':'After treatment: keep one meal routine',steps:[...task.steps,...(!tiny?[/food noise|hungry again|cravings|thinking about food/i.test(week)?'Note when food thoughts get in the way. Choose a familiar meal for that point in your day; do not turn a difficult day into a punishment.':'Choose one day to repeat this meal routine. Keeping it familiar can make the week easier.']:[])]};
 if(mode==='planning-stop'&&type.startsWith('food-'))return {...task,steps:[...task.steps,...(!tiny?['Keep a note of whether this routine helps. It can be part of your everyday plan if treatment ends; stopping or changing medication belongs with your prescriber.']:[])]};
 return task;
}
export const knowledgePolicy=Object.freeze({state:'owner_authorised_everyday_coaching',source:'https://shiftsometimber.co.uk/life-back',retrieved:'2026-10-02',approval:'Matt authorised the website knowledge foundation and instructed the progressive everyday coaching repairs. The fixed task copy is builder-verified; independent relevance and clinical review are not claimed.',clinicalApproval:false,scope:'Everyday action planning and personal check-ins only',version:'coaching-progressive-loop-1',noAutomaticApprovalFromPublication:true});
