import {chromium,webkit} from 'playwright';import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const origin=process.env.PREVIEW_URL,dir='work/staging/generated/five-points-evidence/food-entry';mkdirSync(dir,{recursive:true});
assert(process.env.GITHUB_ACTIONS==='true'&&origin==='https://shift-stabilisation-preview.matobrien.workers.dev');
const fixture=JSON.parse(readFileSync('work/staging/generated/probe.json')),report={source:process.env.GITHUB_SHA,cases:[],productionWrites:0};
const meta=await(await fetch(origin+'/__preview/meta')).json();assert.equal(meta.sourceSha||meta.source||meta.commit||meta.sourceSHA,process.env.GITHUB_SHA);
async function api(ctx,path,body){const response=await ctx.request.fetch(origin+path,{method:body?'POST':'GET',headers:{Origin:origin},...(body?{data:body}:{}),timeout:45000});assert(response.ok(),path+' '+response.status());return response.json()}
const matrix=[['chromium-desktop',chromium,{width:1440,height:1000}],['chromium-phone',chromium,{width:390,height:844}],['webkit-desktop',webkit,{width:1440,height:1000}],['webkit-phone',webkit,{width:390,height:844}]];
for(const [index,[name,engine,viewport]]of matrix.entries()){
 const browser=await engine.launch(),ctx=await browser.newContext({viewport}),page=await ctx.newPage(),row={name,checks:[]};report.cases.push(row);
 try{
  await ctx.route('**/*',route=>{const r=route.request();return new URL(r.url()).origin!==origin&&!['GET','HEAD'].includes(r.method())?route.abort():route.continue()});
  await page.goto(origin+'/staging/member-auth/dashboard');const link=page.getByRole('link',{name:'Forgotten your password?',exact:true});await link.waitFor({state:'visible'});await link.click();
  await page.locator('#previewReset input[name=email]').waitFor({state:'visible'});assert.equal(new URL(page.url()).pathname,'/member-login');await page.screenshot({path:dir+'/'+name+'-password.png',fullPage:true});
  await page.getByRole('button',{name:'Back to sign in',exact:true}).click();await page.locator('#previewRegister input[name=password]').waitFor({state:'visible'});await page.getByRole('button',{name:'Forgotten your password?',exact:true}).click();await page.locator('#previewReset input[name=email]').waitFor({state:'visible'});row.checks.push('legacy dashboard recovery link opens canonical reset; back and canonical recovery work; no email sent');
  await api(ctx,'/v1/auth/login',{email:'probe'+fixture.browserIds[index]+'@example.invalid',password:fixture.password});await page.goto(origin+'/member/grub');await page.waitForFunction(()=>document.querySelector('#grubAccountStatus')?.textContent.includes('up to date'),null,{timeout:45000});
  const before=await api(ctx,'/v1/grub/workspace');assert(before.ingredientOptions.length>20);await page.getByRole('tab',{name:'My fridge',exact:true}).click();
  assert.match(await page.locator('#grubIngredientHelp').innerText(),/Add one ingredient at a time/);const field=page.getByRole('combobox',{name:'Add an ingredient',exact:true}),add=page.getByRole('button',{name:'Add ingredient',exact:true}),chips=page.locator('#sgIngredientChips button');
  await field.fill('chic');const options=page.getByRole('listbox',{name:'Matching ingredients'});await options.waitFor({state:'visible'});assert((await options.getByRole('option').count())>0);const selected=await options.getByRole('option').first().innerText();await options.getByRole('option').first().click();assert.equal(await field.inputValue(),selected);assert.equal(await chips.count(),0);await add.click();assert.equal(await chips.count(),1);assert.equal(await field.inputValue(),'');row.checks.push('typing gives catalogue suggestions; tap fills field; Add ingredient adds one item');
  await field.fill(selected.toUpperCase());await add.click();assert.equal(await chips.count(),1);assert.match(await page.locator('#grubIngredientNotice').innerText(),/already/);
  await field.fill('chicken, rice');await add.click();assert.equal(await chips.count(),1);assert.match(await page.locator('#grubIngredientNotice').innerText(),/one ingredient at a time/);row.checks.push('duplicates and multiple foods in one entry do not add unwanted items');
  await field.fill('rice');await field.press('ArrowDown');assert(await field.getAttribute('aria-activedescendant'));await field.press('Enter');assert.match(await field.inputValue(),/rice/i);assert.equal(await chips.count(),1);await field.press('Enter');assert.equal(await chips.count(),2);row.checks.push('arrow keys select; Enter fills; next Enter adds');
  await field.fill('tofu');await field.press('Escape');assert.equal(await field.getAttribute('aria-expanded'),'false');await field.fill('fictional pantry ingredient');assert.equal(await field.getAttribute('aria-expanded'),'false');await field.press('Enter');assert.equal(await chips.count(),3);await page.getByRole('button',{name:'Remove fictional pantry ingredient',exact:true}).click();assert.equal(await chips.count(),2);row.checks.push('Escape closes; unmatched typed ingredient can be added and removed');
  await field.fill('chic');await options.waitFor({state:'visible'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await page.screenshot({path:dir+'/'+name+'-suggestions.png',fullPage:true});await field.fill('');
  const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/v1/grub/search'&&r.request().method()==='POST');await page.locator('#grubGenerate').click();const response=await pending;assert.equal(response.status(),200);assert((await response.json()).top.length>0);await page.locator('#grubOutput .grub-recipe').first().waitFor();
  const after=await api(ctx,'/v1/grub/workspace');assert.equal(after.revision,before.revision);assert.deepEqual(after.week,before.week);assert.deepEqual(after.shopping,before.shopping);row.checks.push('selected ingredients find real recipes without changing the saved week or shopping list');row.pass=true;
 }catch(e){row.pass=false;row.error=String(e.stack).replaceAll(fixture.password,'[redacted]');await page.screenshot({path:dir+'/'+name+'-failure.png',fullPage:true});throw e}finally{writeFileSync(dir+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(row));await ctx.close();await browser.close()}
}
