import icons from '/life-back-icons.mjs';
const $=s=>document.querySelector(s),dialog=$('#support'),body=$('#dialogBody');
for(const el of document.querySelectorAll('[data-icon]'))el.innerHTML=icons[el.dataset.icon]||icons.sun;
let screen='',symptom='Nausea',severity='Mild',fluids='Yes',rest=false,follow=false;
const sources=`<div class="sources">Information sources · checked 15 September 2026<br><a href="https://www.medicines.org.uk/emc/product/15485/pil" target="_blank" rel="noopener noreferrer">Mounjaro patient leaflet</a><a href="https://www.nhs.uk/symptoms/feeling-sick-nausea/" target="_blank" rel="noopener noreferrer">NHS nausea guidance</a><a href="https://www.nhs.uk/conditions/dehydration/" target="_blank" rel="noopener noreferrer">NHS dehydration guidance</a><p>Design demonstration. Requires clinical review before use as an aftercare service.</p></div>`;
const btn=(label,next,cls='')=>`<button class="${cls}" data-screen="${next}">${label}</button>`;
function page(title,html){body.innerHTML=`<p class="dialog-label">AFTERCARE · PREVIEW ONLY</p><h2 id="dialogTitle" tabindex="-1">${title}</h2>${html}`;if(!dialog.open)dialog.showModal();$('#dialogTitle').focus();dialog.scrollTop=0;}
function open(next){screen=next;
 if(next==='rough')page('First, a quick safety check.',`<p>Choose a sample route to see how support would work. If these symptoms are happening now, seek help rather than continuing the preview.</p><div class="choices">${btn('Chest pain, breathing difficulty, throat swelling or collapse','emergency')}${btn('Severe, persistent stomach pain, possibly into the back','pain')}${btn('Repeated vomiting, cannot keep fluids down or signs of dehydration','urgent')}${btn('None of these — continue','symptoms','solid')}</div><p class="result-note">This short list does not rule out other serious problems. If unsure or getting worse, contact NHS 111.</p>`);
 else if(next==='emergency')page('Call 999 now.',`<p class="warning">Chest pain, breathing difficulty, throat swelling or collapse needs emergency help.</p><p>Do not wait for an online reply or continue the symptom check.</p><a class="action solid" href="tel:999">Call 999</a>${sources}`);
 else if(next==='pain')page('Seek urgent medical help now.',`<p class="warning">Severe stomach pain that does not go away, especially spreading to your back, can be a sign of pancreatitis.</p><p>The Mounjaro leaflet says to stop using it and seek urgent medical help with these symptoms. Do not wait for a routine pharmacy message.</p><a class="action solid" href="https://111.nhs.uk/" target="_blank" rel="noopener noreferrer">Get urgent NHS help</a><p>If you collapse or have difficulty breathing, call 999.</p>${sources}`);
 else if(next==='urgent')page('Get medical advice now.',`<p class="warning">Repeated vomiting, difficulty keeping fluids down, very little urine or persistent dizziness need prompt assessment.</p><p>Contact NHS 111 or an urgent GP service. Do not wait for a reminder or a routine reply from your pharmacy.</p><a class="action solid" href="https://111.nhs.uk/" target="_blank" rel="noopener noreferrer">Open NHS 111</a>${sources}`);
 else if(next==='symptoms')page('What’s bothering you?',`<p>Use sample answers to explore the flow. Nothing is stored or sent.</p><label class="field">Main symptom<select id="symptom"><option>Nausea</option><option>Vomiting</option><option>Diarrhoea</option><option>Constipation</option><option>Something else</option></select></label><label class="field">How does it feel?<select id="severity"><option>Mild</option><option>Moderate</option><option>Severe or getting worse</option></select></label><label class="field">Can you keep fluids down?<select id="fluids"><option>Yes</option><option>No</option><option>Not sure</option></select></label><button class="solid wide" id="advice">Show the next step</button>`);
 else if(next==='nausea')page('Let’s make today easier.',`<p>Nausea can happen with Mounjaro. That does not mean you have to put up with symptoms that persist or interfere with eating and drinking.</p><ul><li>Try small, regular sips of a cold drink.</li><li>Eat smaller meals more often, if you can.</li><li>Avoid greasy foods and strong cooking smells; stay upright after eating.</li></ul><p>Contact your prescriber if symptoms persist, worsen or affect eating and drinking. Discuss dose concerns with them; this preview cannot advise a dose change.</p><div class="choices">${btn('Prepare a prescriber summary','summary','solid')}${btn('Show urgent warning signs','rough')}</div><label class="check"><input id="follow" type="checkbox" ${follow?'checked':''}><span>Show a follow-up check-in in this demo<br><small>Illustration only — no notification will be scheduled.</small></span></label><p id="followStatus" role="status">${follow?'Demo follow-up shown on Today.':''}</p>${sources}`);
 else if(next==='clinical')page('Ask your treating pharmacist.',`<p>Your sample answers need more context than this preview covers. A pharmacist or prescriber can review the symptom, your medicines and treatment history.</p><p>If symptoms are severe, getting worse, or you are unsure how urgent they are, use NHS 111. Do not wait for an online response.</p><div class="choices">${btn('Prepare a prescriber summary','summary','solid')}${btn('Show urgent warning signs','rough')}</div>${sources}`);
 else if(next==='summary')page('Ready for a real conversation.',`<p>This is a sample note to show your treating pharmacist. Nothing has been sent.</p><pre id="summaryText"></pre><div class="choices">${btn('How to contact my prescriber','help','solid')}${btn('Back to symptom choices','symptoms')}</div><p class="result-note">In a connected version, you would confirm your medicine, dose, injection date and symptom history before sharing.</p>`),$('#summaryText').textContent=`DEMONSTRATION — fictional answers\nSymptom: ${symptom}\nSeverity: ${severity}\nCan keep fluids down: ${fluids}\nMedicine / dose / injection time: not confirmed\nQuestion: Could you review my symptoms and advise what to do next?`;
 else if(next==='help')page('Find the right support.',`<p>For treatment or dose questions, contact the pharmacy or clinician who prescribed your medicine using your order confirmation or patient account.</p><p>This preview has no clinical inbox, assigned provider or promised response time.</p><div class="choices">${btn('Check urgent warning signs','rough','solid')}${btn('Prepare a sample symptom summary','summary')}</div><a class="action" href="https://111.nhs.uk/" target="_blank" rel="noopener noreferrer">NHS 111 — help when you need it ↗</a><p>Call 999 for a life-threatening emergency.</p>`);
 else if(next==='okay'){page('Good to hear.',`<p>You can carry on with your day at your own pace. If how you feel changes, support is one tap away.</p><p class="result-note">Sample check-in shown on this page only. No account record changed.</p><button class="solid wide" data-close>Back to today</button>`);$('#careStatus').textContent='Demo check-in: feeling okay. Support is here if that changes.';}
 else if(next==='history')page('Your symptom history.',`<p>Fictional examples — not your medical record.</p><div class="record"><strong>Tuesday · 9:00</strong><span>Nausea · mild · keeping fluids down</span></div><div class="record"><strong>Wednesday · 9:00</strong><span>Feeling better · follow-up example</span></div><p>A real history would keep your timestamps and help you describe changes to your prescriber.</p>${btn('Try a symptom check-in','rough','solid')}`);
 else if(next==='progress')page('Small steps, over time.',`<p>Sample week · Monday and Tuesday logged.</p><div class="record"><strong>Movement, meals and wellbeing</strong><span>Logging is not proof that a meal was eaten or a workout completed.</span></div><a class="action solid" href="/member/life-back">Explore the Life Back preview ↗</a><p>Personal goals, check-in history and daily averages sit together here.</p>`);
}
document.addEventListener('click',e=>{const trigger=e.target.closest('[data-open],[data-screen]');if(trigger)open(trigger.dataset.open||trigger.dataset.screen);if(e.target.closest('[data-close],.close'))dialog.close();if(e.target.id==='advice'){symptom=$('#symptom').value;severity=$('#severity').value;fluids=$('#fluids').value;open(fluids!=='Yes'?'urgent':severity==='Severe or getting worse'?'urgent':symptom==='Nausea'?'nausea':'clinical');}});
document.addEventListener('change',e=>{if(e.target.id==='follow'){follow=e.target.checked;$('#followStatus').textContent=follow?'Demo follow-up shown on Today. No reminder scheduled.':'';$('#careStatus').textContent=follow?'Demo follow-up: check how you feel later. No reminder scheduled.':'A quick check-in can help you find your next step.';}});
$('#rest').addEventListener('click',()=>{rest=!rest;$('#fitText').textContent=rest?'Rest selected in this demo':'Your movement plan';$('#pace').textContent=rest?'A quieter day':'At your pace';$('#rest').textContent=rest?'Put exercise back on today’s list':'Take exercise off today’s list';});
