import icons from '/life-back-icons.mjs';
const $=s=>document.querySelector(s),dialog=$('#support'),body=$('#dialogBody');
for(const el of document.querySelectorAll('[data-icon]'))el.innerHTML=icons[el.dataset.icon]||icons.sun;
let screen='',symptom='Nausea',severity='Mild',fluids='Yes',rest=false,follow=false;
const sources=`<div class="sources">Information sources · checked 15 September 2026<br><a href="https://www.medicines.org.uk/emc/product/15485/pil" target="_blank" rel="noopener noreferrer">Mounjaro patient leaflet</a><a href="https://www.nhs.uk/symptoms/feeling-sick-nausea/" target="_blank" rel="noopener noreferrer">NHS nausea guidance</a><a href="https://www.nhs.uk/conditions/dehydration/" target="_blank" rel="noopener noreferrer">NHS dehydration guidance</a><p>Design demonstration. Requires clinical review before use as an aftercare service.</p></div>`;
const btn=(label,next,cls='')=>`<button class="${cls}" data-screen="${next}">${label}</button>`;
function page(title,html){$('#memberMenu').open=false;body.innerHTML=`<p class="dialog-label">MY TIMBER · PREVIEW ONLY</p><h2 id="dialogTitle" tabindex="-1">${title}</h2>${html}`;if(!dialog.open)dialog.showModal();$('#dialogTitle').focus();dialog.scrollTop=0;}
function open(next){screen=next;
 if(next==='rough')page('First, a quick safety check.',`<p>Choose a sample route to see how support would work. If these symptoms are happening now, seek help rather than continuing the preview.</p><div class="choices">${btn('Chest pain, breathing difficulty, throat swelling or collapse','emergency')}${btn('Severe, persistent stomach pain, possibly into the back','pain')}${btn('Repeated vomiting, cannot keep fluids down or signs of dehydration','urgent')}${btn('None of these — continue','symptoms','solid')}</div><p class="result-note">This short list does not rule out other serious problems. If unsure or getting worse, contact NHS 111.</p>`);
 else if(next==='emergency')page('Call 999 now.',`<p class="warning">Chest pain, breathing difficulty, throat swelling or collapse needs emergency help.</p><p>Do not wait for an online reply or continue the symptom check.</p><a class="action solid" href="tel:999">Call 999</a>${sources}`);
 else if(next==='pain')page('Seek urgent medical help now.',`<p class="warning">Severe stomach pain that does not go away, especially spreading to your back, can be a sign of pancreatitis.</p>${treatment==='injection'?'<p>The Mounjaro leaflet says to stop using it and seek urgent medical help with these symptoms. Do not wait for a routine pharmacy message.</p>':'<p>Do not wait for an online reply. Tell the clinician about any medicines you take.</p>'}<a class="action solid" href="https://111.nhs.uk/" target="_blank" rel="noopener noreferrer">Get urgent NHS help</a><p>If you collapse or have difficulty breathing, call 999.</p>${sources}`);
 else if(next==='urgent')page('Get medical advice now.',`<p class="warning">Repeated vomiting, difficulty keeping fluids down, very little urine or persistent dizziness need prompt assessment.</p><p>Contact NHS 111 or an urgent GP service. Do not wait for a reminder or a routine reply from your pharmacy.</p><a class="action solid" href="https://111.nhs.uk/" target="_blank" rel="noopener noreferrer">Open NHS 111</a>${sources}`);
 else if(next==='symptoms')page('What’s bothering you?',`<p>Use sample answers to explore the flow. Nothing is stored or sent.</p><label class="field">Main symptom<select id="symptom"><option>Nausea</option><option>Vomiting</option><option>Diarrhoea</option><option>Constipation</option><option>Something else</option></select></label><label class="field">How does it feel?<select id="severity"><option>Mild</option><option>Moderate</option><option>Severe or getting worse</option></select></label><label class="field">Can you keep fluids down?<select id="fluids"><option>Yes</option><option>No</option><option>Not sure</option></select></label><button class="solid wide" id="advice">Show the next step</button>`);
 else if(next==='nausea')page('Let’s make today easier.',`<p>${treatment==='injection'?'Nausea can happen with Mounjaro. ':''}You do not have to put up with symptoms that persist or interfere with eating and drinking.</p><ul><li>Try small, regular sips of a cold drink.</li><li>Eat smaller meals more often, if you can.</li><li>Avoid greasy foods and strong cooking smells; stay upright after eating.</li></ul><p>Contact ${treatment==='none'?'a pharmacist or GP':'your prescriber'} if symptoms persist, worsen or affect eating and drinking. ${treatment==='none'?'':'Discuss dose concerns with them; this preview cannot advise a dose change.'}</p><div class="choices">${btn('Prepare a symptom summary','summary','solid')}${btn('Show urgent warning signs','rough')}</div><label class="check"><input id="follow" type="checkbox" ${follow?'checked':''}><span>Show a follow-up check-in in this demo<br><small>Illustration only — no notification will be scheduled.</small></span></label><p id="followStatus" role="status">${follow?'Demo follow-up shown on Today.':''}</p>${sources}`);
 else if(next==='clinical')page(treatment==='none'?'Ask a pharmacist or GP.':'Ask your treating pharmacist.',`<p>Your sample answers need more context than this preview covers. A pharmacist or clinician can review the symptom and any relevant history.</p><p>If symptoms are severe, getting worse, or you are unsure how urgent they are, use NHS 111. Do not wait for an online response.</p><div class="choices">${btn('Prepare a symptom summary','summary','solid')}${btn('Show urgent warning signs','rough')}</div>${sources}`);
 else if(next==='summary')page('Ready for a real conversation.',`<p>This is a sample note to show a pharmacist or clinician. Nothing has been sent.</p><pre id="summaryText"></pre><div class="choices">${btn('Find the right support','help','solid')}${btn('Back to symptom choices','symptoms')}</div><p class="result-note">Before sharing a real summary, you would confirm the symptoms and any relevant medicines and treatment history.</p>`),$('#summaryText').textContent=`DEMONSTRATION — fictional answers\nSymptom: ${symptom}\nSeverity: ${severity}\nCan keep fluids down: ${fluids}\n${treatment==='injection'?'Medicine / dose / injection time: not confirmed':treatment==='tablet'?'Medicine / dose / last taken: not confirmed':'Sample profile: no medication'}\nQuestion: Could you review my symptoms and advise what to do next?`;
 else if(next==='help')page('Find the right support.',`<p>${treatment==='none'?'For health questions, speak to a pharmacist or GP. You can check in and use the everyday tools without taking medication.':'For treatment or dose questions, contact the pharmacy or clinician who prescribed your medicine using your order confirmation or patient account.'}</p><p>This preview has no clinical inbox, assigned provider or promised response time.</p><div class="choices">${btn('Check urgent warning signs','rough','solid')}${btn('Prepare a sample symptom summary','summary')}${btn('Talk about SHIFT','human')}</div><a class="action" href="https://111.nhs.uk/" target="_blank" rel="noopener noreferrer">NHS 111 — help when you need it ↗</a><p>Call 999 for a life-threatening emergency.</p>`);
 else if(next==='okay'){recordEntry('Feeling okay','');page('Good to hear.',`<p>You can carry on with your day at your own pace. If how you feel changes, support is one tap away.</p><p class="result-note">Sample check-in added to this preview’s history. No account record changed.</p><button class="solid wide" data-close>Back to today</button>`);}
 else openMaster(next);
}
document.addEventListener('click',e=>{const trigger=e.target.closest('[data-open],[data-screen]');if(trigger)open(trigger.dataset.open||trigger.dataset.screen);if(e.target.closest('[data-close],.close'))dialog.close();if(e.target.id==='advice'){symptom=$('#symptom').value;severity=$('#severity').value;fluids=$('#fluids').value;open(fluids!=='Yes'?'urgent':severity==='Severe or getting worse'?'urgent':symptom==='Nausea'?'nausea':'clinical');}});
document.addEventListener('change',e=>{if(e.target.id==='follow'){follow=e.target.checked;$('#followStatus').textContent=follow?'Demo follow-up shown on Today. No reminder scheduled.':'';$('#careStatus').textContent=follow?'Demo follow-up: check how you feel later. No reminder scheduled.':'A quick check-in can help you find your next step.';}});
$('#rest').addEventListener('click',()=>{rest=!rest;renderRest();});

// The master template uses disposable, fictional state. Reloading starts over.
let treatment='injection',water=750,waterUndo=[],reminder=false,reminderTime='07:30',tracking=true,continuity=false;
const entries=[],weekly=[],goals={weight:'95',waist:'100'},esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const demo='<p class="result-note">Fictional profile. Changes stay in this open preview and reset on reload. No account record changed.</p>';
const options=(values,selected)=>values.map(v=>`<option${v===selected?' selected':''}>${esc(v)}</option>`).join('');
function renderRest(){
 $('#fitText').textContent=rest?'Rest selected in this demo':'20-minute home session';
 $('#fitMeta').textContent=rest?'Session deferred · no completion recorded':'0 exercises logged · explore the Fit preview';
 $('#pace').textContent=rest?'A quieter day':'At your pace';
 $('#rest').textContent=rest?'Put exercise back on today’s list':'Take exercise off today’s list';
}
function renderTreatment(){
 const titles={injection:['AFTER YOUR INJECTION','Sample check-in · 24 hours later'],tablet:['TREATMENT CHECK-IN','Sample tablet member'],none:['YOUR DAILY CHECK-IN','Sample member · no medication']};
 [$('#careEyebrow').textContent,$('#careContext').textContent]=titles[treatment];
 $('#sampleOrder').disabled=treatment==='none';
 if(treatment==='none')$('#sampleOrder').checked=false;
 $('#orderCard').hidden=!$('#sampleOrder').checked;
 follow=false;$('#careStatus').textContent='A quick check-in can help you find your next step.';
}
function renderWater(){
 $('#waterTotal').textContent=`${water.toLocaleString('en-GB')} ml`;
 $('#undoWater').hidden=!waterUndo.length;
 $('#dailyStatus').textContent=`Sample water total ${water} millilitres. No account record changed.`;
}
function recordEntry(mood,note){
 entries.unshift({time:new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),mood,note});
 $('#weekCount').textContent='3 days logged.';$('#todayMark').textContent='✓';
 $('#weekDays').setAttribute('aria-label','Sample week: Monday, Tuesday and Wednesday logged');
 $('#careStatus').textContent=`Demo check-in: ${mood.toLowerCase()}. ${entries.length} ${entries.length===1?'entry':'entries'} added in this preview.`;
 $('#nextTitle').textContent='Your next step is yours.';
 $('#nextDetail').textContent='You have checked in. Choose a meal, explore Fit or take a quieter day.';
}
function historyRows(){return entries.map(e=>`<div class="record"><strong>Preview today · ${esc(e.time)}</strong><span>${esc(e.mood)}</span>${e.note?`<p>${esc(e.note)}</p>`:''}</div>`).join('')+'<div class="record"><strong>Sample Tuesday · 18:30</strong><span>Feeling okay · managed the longer dog walk.</span></div><div class="record"><strong>Sample Monday · 08:15</strong><span>A steady start · planned meals for the week.</span></div>';}
function trend(){
 const values=[108,107.8,107.1,106.4],points=values.map((v,i)=>`${40+i*100},${110-(v-106)*45}`);
 return `<div class="journey-chart"><p class="eyebrow">SAMPLE WEIGHT TREND</p><svg viewBox="0 0 390 150" role="img" aria-label="Fictional weekly weights: 108, 107.8, 107.1 and 106.4 kilograms. Illustrative only, not an expected rate of change."><path d="M40 115 H350" stroke="#aaaE9e" fill="none"/><polyline points="${points.join(' ')}" fill="none" stroke="#414638" stroke-width="3"/>${points.map((p,i)=>{const [x,y]=p.split(',');return `<circle cx="${x}" cy="${y}" r="4" fill="#414638"/><text x="${x}" y="${Number(y)-12}" text-anchor="middle">${values[i]} kg</text><text x="${x}" y="139" text-anchor="middle">Week ${i+1}</text>`;}).join('')}</svg><p class="result-note">Four fixed sample weeks. Illustrative values, not an expected rate of change. Any new preview records are listed separately below.</p></div>`;
}
function openMaster(next){
 if(next==='checkin')page('How’s your day going?',`<p>An everyday check-in, whether you take medication or not. Use fictional details to try it.</p><form id="checkinForm"><label class="field">How are you feeling?<select id="dailyFeeling">${options(['Feeling okay','A bit flat','A good day','Feeling rough'])}</select></label><label class="field">A win, a sticking point, or a note for yourself<textarea id="dailyNote" rows="3" maxlength="600" placeholder="Small things count."></textarea></label><button class="solid wide" type="submit">Add sample check-in</button></form>${demo}<div class="choices">${btn('View check-in history','history')}${btn('I need symptom support','rough')}</div>`);
 else if(next==='history')page('Your check-in history.',`<p>Every entry has its own time. More entries on one day still count as one logged day.</p>${historyRows()}${btn('Add another sample check-in','checkin','solid')}${demo}`);
 else if(next==='journey'||next==='progress')page(next==='journey'?'Your Journey.':'Your week, at your pace.',`<p>A fictional example of your starting point, goals and weekly records.</p><div class="metric-grid"><div><small>Starting weight</small><strong>112 kg</strong></div><div><small>Latest weight</small><strong>${esc(weekly[0]?.weight||'106.4')} kg</strong></div><div><small>Latest waist</small><strong>${esc(weekly[0]?.waist||'108')} cm</strong></div><div><small>Weight goal</small><strong>${esc(goals.weight)} kg</strong></div></div><p class="result-note">Sample waist goal: ${esc(goals.waist)} cm. These are illustrative values, not recommended targets.</p><div class="choices">${btn('Edit sample goals','goals','solid')}${btn('Add a weekly record','weekly')}${btn('Read check-in history','history')}${btn('View printable 12-week record','report')}</div>${trend()}<h3>Weekly records</h3>${weekly.map(w=>`<div class="record"><strong>Added in this preview</strong><span>${esc(w.weight)} kg · ${esc(w.waist)} cm</span></div>`).join('')}<div class="record"><strong>Sample week 4</strong><span>106.4 kg · 108 cm · clothes feel more comfortable.</span></div><div class="record"><strong>Sample week 3</strong><span>107.1 kg · 109 cm · finding a routine.</span></div><a class="action" href="/member/life-back">Personal goals &amp; wins in Life Back ↗</a>${demo}`);
 else if(next==='goals')page('A starting point that’s yours.',`<form id="goalsForm"><label class="field">Sample weight goal (kg)<input id="goalWeight" type="number" min="1" max="500" step="0.1" required value="${esc(goals.weight)}"></label><label class="field">Sample waist goal (cm)<input id="goalWaist" type="number" min="1" max="500" step="0.1" required value="${esc(goals.waist)}"></label><button class="solid wide" type="submit">Update sample goals</button></form>${demo}`);
 else if(next==='report')page('Your 12-week record.',`<p>Fictional example. A printable view keeps the starting point, weekly weight and waist measurements together.</p><div class="report-table"><table><caption>Sample baseline: 112 kg · waist not recorded</caption><thead><tr><th scope="col">Week</th><th scope="col">Weight</th><th scope="col">Waist</th></tr></thead><tbody>${Array.from({length:12},(_,i)=>{const row=[{weight:'108',waist:'110'},{weight:'107.8',waist:'109.5'},{weight:'107.1',waist:'109'},{weight:'106.4',waist:'108'},...weekly.slice().reverse()][i];return `<tr><th scope="row">${i+1}</th><td>${row?`${esc(row.weight)} kg`:'—'}</td><td>${row?`${esc(row.waist)} cm`:'—'}</td></tr>`;}).join('')}</tbody></table></div><p class="result-note">Blank weeks have no sample entry. This contains no member account data.</p><button class="solid wide" id="printReport">Print / save sample PDF</button>${btn('Back to Journey','journey')}`);
 else if(next==='weekly')page('One week at a time.',`<form id="weeklyForm"><label class="field">Example weight (kg)<input id="weeklyWeight" type="number" min="1" max="500" step="0.1" required value="${esc(weekly[0]?.weight||'106.4')}"></label><label class="field">Example waist (cm)<input id="weeklyWaist" type="number" min="1" max="500" step="0.1" required value="${esc(weekly[0]?.waist||'108')}"></label><button class="solid wide" type="submit">Add sample weekly record</button></form>${demo}`);
 else if(next==='change')page('Life happens. Adjust today.',`<p>Choose a sample situation. You can change your pace without losing your chosen meal or recording a workout as complete.</p><form id="changeForm"><label class="field">What has changed?<select id="dayChange">${options(['Less time today','Low energy','Feeling rough','Poor sleep','Shift pattern changed','Working away','No kitchen access','No equipment','Eating out','Something else'])}</select></label><button class="solid wide" type="submit">Adjust the sample day</button></form>${demo}`);
 else if(next==='reminder')page('A morning nudge.',`<p>Your ordinary daily reminder is separate from an aftercare follow-up.</p><form id="reminderForm"><label class="check"><input id="reminderOn" type="checkbox"${reminder?' checked':''}><span>Turn on the sample morning reminder</span></label><label class="field">Preferred UK time<select id="reminderTime">${options(['06:00','06:30','07:00','07:30','08:00','08:30','09:00','09:30','10:00'],reminderTime)}</select></label><button class="solid wide" type="submit">Apply to preview</button></form><p class="result-note">No reminder scheduled. This demonstrates the setting; it cannot send a notification or email.</p>`);
 else if(next==='saved')page('Everything in reach.',`<div class="choices">${btn('Saved food & meals','savedFood','solid')}${btn('My Journey & weekly records','journey')}${btn('Check-in history','history')}${btn('Account & privacy','settings')}</div><a class="action" href="/member/fit">Your Fit session preview ↗</a><a class="action" href="/member/life-back">Life Back goals &amp; history preview ↗</a>${demo}`);
 else if(next==='savedFood')page('Meals worth repeating.',`<p>Example saved meals, separate from what you have chosen for today.</p><div class="record"><strong>Chicken traybake</strong><span>Sample choice for today · not recorded as eaten.</span></div><div class="record"><strong>BBQ chickpea wrap</strong><span>Sample saved meal · another option for the week.</span></div><a class="action solid" href="/member/grub">Explore meals in the Grub preview ↗</a><p class="result-note">The Grub preview has its own sample choices. This design page does not save or transfer a meal plan.</p>`);
 else if(next==='comingoff')page('Keep your support around you.',`<p>If your clinic has gone quiet, or you are thinking about coming off treatment, your food, movement and personal goals still belong together.</p><div class="record"><strong>Food you can come back to</strong><span>Keep your chosen meals and practical food tools close.</span></div><div class="record"><strong>Movement at your pace</strong><span>Keep a manageable routine and adjust when life changes.</span></div><div class="record"><strong>Headspace & human support</strong><span>Keep checking in, notice your wins and ask for help.</span></div><p>Treatment, dose changes and stopping decisions need your treating pharmacist or clinician.</p><button class="solid wide" id="continuityToggle">${continuity?'Remove sample continuity focus':'Show a continuity focus on Today'}</button><div class="choices">${btn('Find treatment support','help')}${btn('Talk to Matt about SHIFT','human')}</div>${demo}`);
 else if(next==='human'||next==='goodtalk')page(next==='human'?'Message Matt.':'Good to Talk.',`<p>${next==='human'?'A place to ask about SHIFT or explain what is making the day difficult.':'Space to put how you are feeling into words and ask for support.'}</p><p>This is a message-composer demonstration, not a staffed inbox or urgent support service. It does not contact anyone.</p><form id="messageForm"><label class="field">Example message<textarea id="messageText" rows="4" maxlength="1000" required placeholder="Use fictional details in this preview."></textarea></label><button class="solid wide" type="submit">Preview message</button></form>${btn('Find treatment or urgent support','help')}`);
 else if(next==='fridge')page('Start with what you have.',`<p>A sample of the fridge tool, ready to sit alongside your saved food.</p><label class="field">Try an example basket<select id="fridgeBasket">${options(['Chicken, peppers & rice','Chickpeas, peppers & wraps'])}</select></label><button id="fridgeIdea" class="solid wide">Show sample meal idea</button><div id="fridgeResult" role="status"></div><p class="result-note">Two fixed examples for design review. No live ingredient matching or dietary-profile checks.</p>`);
 else if(next==='ask'){dialog.close();$('#memberMenu').open=false;$('#askQuestion').focus();$('#askQuestion').scrollIntoView({block:'center',behavior:'instant'});}
 else if(next==='settings')page('Your account. Your choices.',`<p>Example member: Alex. No account is signed in to this preview.</p><label class="check"><input id="tracking" type="checkbox"${tracking?' checked':''}><span>Health tracking preference<br><small>Preview setting only. Does not change consent or stored records.</small></span></label><p id="trackingStatus" role="status">Sample preference: ${tracking?'on':'off'}.</p><div class="choices">${btn('Preview a data export','export')}${btn('Preview deletion controls','delete')}${btn('Morning reminder settings','reminder')}${btn('Sign out information','signout')}</div>${demo}`);
 else if(next==='export')page('Your records, together.',`<p>A connected account export would include the records held for that member. This preview has only these fictional examples.</p><pre id="summaryText">Sample member: Alex\nDaily check-ins added: ${entries.length}\nWeekly records added: ${weekly.length}\nWater shown: ${water} ml\nSample tracking preference: ${tracking?'on':'off'}</pre><p class="result-note">No member data accessed and no file exported.</p>${btn('Back to account & privacy','settings','solid')}`);
 else if(next==='delete')page('Clear choices before deletion.',`<p>The account design keeps deletion separate from switching tracking off. Turning tracking off does not claim to erase historical records.</p><div class="record"><strong>Delete health records</strong><span>Confirmation and a clear account-specific explanation would appear before a real deletion.</span></div><p class="result-note">Preview only. No deletion is available here and nothing has been erased.</p>${btn('Back to account & privacy','settings','solid')}`);
 else if(next==='signout')page('No account is signed in.',`<p>Sign out belongs in the member menu. This public design preview has no member session to end.</p><button class="solid wide" data-close>Back to the preview</button>`);
 else if(next==='order')page('A clear next treatment step.',`<p>Example tracker — only relevant when a member has a treatment order. Explore separate example stages below; the home card remains the clinical-checks example.</p><label class="field">Explore an example stage<select id="orderStage">${options(['Clinical information requested','Journey setup requested','Clinical review in progress','Reorder available'])}</select></label><div id="orderStageDetail" class="record"><strong>Complete the requested clinical information</strong><span>The real member flow would reopen the existing intake for that order.</span></div><p class="result-note">No order exists in this preview. No clinical approval, supply decision, checkout or reorder is performed.</p>${btn('View sample Journey setup','journey','solid')}`);
}
document.addEventListener('submit',e=>{
 const id=e.target.id;if(!['checkinForm','goalsForm','weeklyForm','changeForm','reminderForm','messageForm','askForm'].includes(id))return;e.preventDefault();
 if(id==='checkinForm'){const mood=$('#dailyFeeling').value;recordEntry(mood,$('#dailyNote').value.trim());if(mood==='Feeling rough')open('rough');else open('history');}
 if(id==='goalsForm'){goals.weight=$('#goalWeight').value;goals.waist=$('#goalWaist').value;open('journey');}
 if(id==='weeklyForm'){weekly.unshift({weight:$('#weeklyWeight').value,waist:$('#weeklyWaist').value});open('journey');}
 if(id==='changeForm'){
  const change=$('#dayChange').value;rest=['Low energy','Feeling rough','Poor sleep'].includes(change);renderRest();
  $('#pace').textContent=change;$('#nextTitle').textContent='Make room for today.';
  $('#nextDetail').textContent=`Sample adjustment: ${change.toLowerCase()}. Your chosen meal stays in place; review food or Fit when you are ready.`;
  if(change==='Feeling rough')open('rough');else page('Today has a little more room.',`<p>Sample situation: ${esc(change)}.</p><p>${rest?'The example Fit session is deferred.':'Review the meal or Fit session to make an adjustment that suits you.'} Your chosen meal has not changed, and no activity is marked complete.</p><button class="solid wide" data-close>Back to today</button>${demo}`);
 }
 if(id==='reminderForm'){
  reminder=$('#reminderOn').checked;reminderTime=$('#reminderTime').value;
  $('#reminderSummary').textContent=reminder?`Demo on · ${reminderTime} UK time`:'Off · choose a time that suits you';
  page('Your sample preference is set.',`<p>${reminder?`Morning reminder shown as on at ${esc(reminderTime)} UK time.`:'Morning reminder shown as off.'}</p><p class="result-note">No reminder scheduled. Nothing has been sent.</p><button class="solid wide" data-close>Back to today</button>`);
 }
 if(id==='messageForm'){const message=$('#messageText').value.trim();page('Your example message.',`<blockquote>${esc(message)}</blockquote><p class="result-note">Nothing has been sent. This is the preview of a composer, not a working inbox.</p><button class="solid wide" data-close>Back to today</button>`);}
 if(id==='askForm'){
  const question=$('#askQuestion').value.trim();if(!question){$('#askQuestion').focus();return;}
  page('A place to ask.',`<blockquote>${esc(question)}</blockquote><p class="dialog-label">SAMPLE RESPONSE LAYOUT</p><p>Start with one manageable step. Your food, movement and check-ins are all close by.</p><div class="choices">${btn('Adjust today','change')}${btn('Log how I feel','checkin')}${btn('Find symptom support','rough')}</div><a class="action" href="/member/grub">Explore Grub ↗</a><p class="result-note">This is a fixed example, not an AI answer to your question. No question was sent and no member history was accessed.</p>`);
 }
});
document.addEventListener('click',e=>{
 const target=e.target.closest('button');if(!target)return;
 if(target.id==='addWater'){waterUndo.push(water);water+=250;renderWater();}
 if(target.id==='undoWater'&&waterUndo.length){water=waterUndo.pop();renderWater();}
 if(target.dataset.prompt){$('#askQuestion').value=target.dataset.prompt;$('#askForm').requestSubmit();}
 if(target.id==='continuityToggle'){continuity=!continuity;$('#nextTitle').textContent=continuity?'Keep your support around you.':'A quick check-in.';$('#nextDetail').textContent=continuity?'Sample continuity focus: food, movement, check-ins and human support. Treatment decisions stay with your prescriber.':'Notice how you feel before deciding what comes next.';page(continuity?'Continuity focus shown.':'Back to your everyday view.',`<p>The example next-step card has changed. This does not start or stop treatment.</p><button class="solid wide" data-close>Back to today</button>${demo}`);}
 if(target.id==='fridgeIdea'){$('#fridgeResult').innerHTML=`<div class="record"><strong>${$('#fridgeBasket').value.startsWith('Chicken')?'Chicken & pepper rice bowl':'Chickpea & pepper wrap'}</strong><span>Fixed sample meal idea — explore Grub for the full food preview.</span></div><a class="action" href="/member/grub">Open Grub ↗</a>`;}
 if(target.id==='printReport')window.print();
});
document.addEventListener('change',e=>{
 if(e.target.id==='sampleTreatment'){treatment=e.target.value;renderTreatment();}
 if(e.target.id==='sampleOrder')$('#orderCard').hidden=!e.target.checked;
 if(e.target.id==='tracking'){tracking=e.target.checked;$('#trackingStatus').textContent=`Sample preference: ${tracking?'on':'off'}. No account consent changed.`;}
 if(e.target.id==='orderStage'){
  const stages={'Clinical information requested':['Complete the requested clinical information','The real member flow would reopen the existing intake for that order.'],'Journey setup requested':['Complete your Journey setup','The real member flow would open the existing setup, without asking for the same information twice.'],'Clinical review in progress':['Your information is being reviewed','Example only. Payment does not mean treatment has been approved.'],'Reorder available':['Review your treatment before reordering','Example only. Availability, clinical eligibility and supply would be checked by the real service.']};
  const [title,detail]=stages[e.target.value];$('#orderStageDetail').innerHTML=`<strong>${title}</strong><span>${detail}</span>`;
 }
});
