const $=s=>document.querySelector(s),status=$('#status'),content=$('#content');let current='today';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body,method='POST'){const r=await fetch('/v1/coaching-test'+path,{method:body===undefined?'GET':method,headers:body===undefined?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const j=await r.json();if(!r.ok)throw Error(j.error);return j;}
const notify=text=>status.textContent=text;
function help(panel){$('#help').innerHTML=`<p>${esc(panel.text)}</p><ul>${panel.links.map(l=>`<li><a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.label)}</a></li>`).join('')}</ul>`;}
async function action(path,b){await api(path,b);await render(current);notify('Saved in this test account.');}
function button(label,fn,secondary=false){const b=document.createElement('button');b.textContent=label;if(secondary)b.className='secondary';b.addEventListener('click',()=>run(fn,b));return b;}
async function run(fn,b){if(b)b.disabled=true;try{await fn();}catch(e){notify(e.message.replaceAll('_',' '));}finally{if(b)b.disabled=false;}}
function setupForm(){const form=document.createElement('form');form.className='card';form.innerHTML='<h2>Give today a bit of context</h2><p>Three short answers. No medical details needed.</p><label for="goal">What do you want your life back for?</label><input id="goal" name="goal" maxlength="240" required placeholder="More time joining in with the family"><label for="week">What does this week look like?</label><input id="week" name="week" maxlength="240" required placeholder="Three late shifts, no free evenings"><label for="focus">What would be useful?</label><select id="focus" name="focus"><option value="food">Food planning</option><option value="movement">Movement</option><option value="reflection">Looking back at the week</option></select><label for="stage">Where are you?</label><select id="stage" name="stage"><option>Just starting</option><option>Already making changes</option><option>Hit a wall</option></select><p><button type="submit">Prepare my action</button></p>';form.addEventListener('submit',e=>{e.preventDefault();run(async()=>action('/setup',Object.fromEntries(new FormData(form))),form.querySelector('button'));});return form;}
async function render(view){current=view;notify('');document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-current',b.dataset.view===view?'page':'false'));const route=view==='records'?'readings':view;const {data}=await api('/'+route);content.replaceChildren();history.replaceState(null,'','/member/coaching-test/'+view);
 if(view==='today'){
  $('#account').textContent=data.member+' · test storage · no model generation on Today';help(data.help);
  const a=data.action;if(!a){content.innerHTML='<section><h2>Your action needs preparing</h2><p>A correction or permission change cancelled the previous plan. No stale advice is shown.</p></section>';content.append(setupForm());return;}
  const section=document.createElement('section');section.className='action-card';section.dataset.action=a.id;
  section.innerHTML=`<span class="tag">${a.general?'GENERAL STARTER':'PREPARED FOR YOUR DAY'}</span><span class="tag">${esc(a.component)}</span><h2>${esc(a.title)}</h2><p>${esc(a.tone)}</p><p class="muted">About ${a.minutes} minute${a.minutes===1?'':'s'} to set up · prepared before you opened Today</p><div class="reason"><strong>Why this one?</strong><p>${esc(a.reason)}</p><small>${a.dataUsed.length} saved record${a.dataUsed.length===1?'':'s'} used. <a href="/member/coaching-test/memory" data-memory-link>See and correct them</a></small></div>`;
  section.querySelector('[data-memory-link]').addEventListener('click',e=>{e.preventDefault();run(()=>render('memory'));});
  const controls=document.createElement('div');controls.className='row';
  if(a.awaitingWant){controls.append(button('Yes, keep it',()=>action('/wanted',{yes:true})),button('No, leave it',()=>action('/wanted',{yes:false}),true));}
  else if(a.status==='prepared'){controls.append(button('Use this today',()=>action('/accept',{actionId:a.id})),button('Leave this one',()=>action('/decline',{actionId:a.id}),true));}
  else{const feedback=document.createElement('div');feedback.className='feedback';for(const [label,value]of [['Done and helped','helped'],["Done, didn’t help",'didnt-help'],["Didn’t fit my day",'didnt-fit'],["Didn’t try",'didnt-try']])feedback.append(button(label,()=>action('/outcomes',{actionId:a.id,value}),value!=='helped'));section.append(feedback);}
  section.append(controls);content.append(section);
  if(a.status==='accepted'){
   const cal=document.createElement('details');cal.className='card';cal.innerHTML='<summary>Preview a reminder</summary><p>Choose a time. Previewing writes nothing. This test uses a simulated calendar.</p><label>Start time<input type="datetime-local" name="reminder-start"></label><div class="row"></div><div class="calendar-preview"></div>';
   cal.querySelector('.row').append(button('Preview calendar entry',async()=>{const raw=cal.querySelector('input').value;if(!raw)throw Error('Choose a reminder time first');const start=new Date(raw).toISOString();const p=(await api('/calendar/preview',{actionId:a.id,start})).data;const preview=cal.querySelector('.calendar-preview');preview.replaceChildren();const text=document.createElement('p');text.textContent=p.title+' · '+new Date(start).toLocaleString()+' · nothing written yet';preview.append(text,button('Add this test reminder',()=>action('/calendar/accept',{actionId:a.id,start,explicitTap:true})));}));content.append(cal);
  }
  for(const event of data.calendar){const row=document.createElement('section');row.innerHTML=`<h3>Test reminder</h3><p>${esc(event.title)} · ${esc(event.start)}</p>`;row.append(button('Undo this reminder',()=>action('/calendar/undo',{id:event.id}),true));content.append(row);}
  for(const request of data.pauseRequests){const row=document.createElement('section');row.innerHTML='<h3>Should I keep this follow-up?</h3><p>You have not answered this message type twice. It is paused unless you choose to keep it.</p>';row.append(button('Keep it',()=>action('/pause-request-answer',{id:request.id,yes:true})),button('Leave it paused',()=>action('/pause-request-answer',{id:request.id,yes:false}),true));content.append(row);await api('/pause-request-seen',{id:request.id});}
  if(a.general)content.append(setupForm());
  if(data.weeklyPlan){const p=document.createElement('section');p.innerHTML=`<h3>This week’s prepared plan</h3><p>${esc(data.weeklyPlan.title)}</p><p>${esc(data.weeklyPlan.reason)}</p>`;p.append(button(data.weeklyPlan.accepted?'Plan accepted':'Accept this week’s plan',()=>action('/plans/accept',{id:data.weeklyPlan.id})));content.append(p);}
 }else if(view==='memory'){
  content.innerHTML='<h2>What SHIFT knows about you</h2><p>Confirmed facts drive plans. Suggestions stay suggestions until you confirm them.</p>';
  for(const f of data.facts){const row=document.createElement('section');row.innerHTML=`<label>${esc(f.key)} · ${f.confirmed?'confirmed':'unconfirmed suggestion'}</label><input value="${esc(f.value)}" maxlength="240"><small class="muted">Saved record ${esc(f.id)}</small><p class="row"></p>`;row.querySelector('.row').append(button('Save correction',()=>action('/memory',{key:f.key,value:row.querySelector('input').value})),button('Delete',()=>action('/memory',{id:f.id},'DELETE'),true));content.append(row);}
  const rejected=document.createElement('section');rejected.innerHTML='<h3>Advice you have declined</h3>';if(!data.rejections.length)rejected.append('None saved.');for(const type of data.rejections)rejected.append(button('Restore '+type,()=>action('/restore',{type}),true));content.append(rejected);
  const all=document.createElement('details');all.innerHTML='<summary>All saved memory and derived plans</summary><pre></pre>';all.querySelector('pre').textContent=JSON.stringify(data,null,2);content.append(all);content.append(setupForm());
 }else if(view==='permissions'){
  const section=document.createElement('section');section.innerHTML='<h2>You decide what SHIFT uses</h2><p>Every source starts off. Switching one off cancels plans and queued messages that depend on it.</p>';
  for(const [source,enabled]of Object.entries(data.permissions)){const label=document.createElement('label');label.className='switch';label.textContent=source+' · synthetic test data';const input=document.createElement('input');input.type='checkbox';input.checked=enabled;input.setAttribute('aria-label',source);input.addEventListener('change',()=>run(()=>action('/permissions',{source,enabled:input.checked})));label.append(input);section.append(label);}content.append(section);
  const form=document.createElement('form');form.className='card';form.innerHTML=`<h3>Follow-up and quiet hours</h3><label><input name="proactive" type="checkbox" ${data.settings.proactive?'checked':''}> Allow proactive messages in this test</label><label><input name="followup" type="checkbox" ${data.settings.followup?'checked':''}> Ask once the next day about an accepted action</label><label>Quiet hours start<input name="quietStart" type="time" value="${esc(data.settings.quietStart)}"></label><label>Quiet hours end<input name="quietEnd" type="time" value="${esc(data.settings.quietEnd)}"></label><label>Timezone<input name="timezone" value="${esc(data.settings.timezone)}"></label><label>Weekly plan day<select name="weeklyDay"><option value="">No weekly message</option>${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i)=>`<option value="${i}" ${data.settings.weeklyDay===i?'selected':''}>${d}</option>`).join('')}</select></label><p>At most 3 proactive touches in 7 days. No real push notifications.</p><button type="submit">Save permissions</button>`;form.addEventListener('submit',e=>{e.preventDefault();const f=form.elements;run(()=>action('/settings',{proactive:f.proactive.checked,followup:f.followup.checked,quietStart:f.quietStart.value,quietEnd:f.quietEnd.value,timezone:f.timezone.value,weeklyDay:f.weeklyDay.value===''?null:Number(f.weeklyDay.value)}));});content.append(form);
  const mode=document.createElement('section');mode.innerHTML=`<h3>Your treatment situation</h3><p>The everyday coaching loop works in all three. Medicine decisions stay with your own prescriber.</p><select aria-label="Treatment situation">${[['shift','Prescribed through SHIFT'],['elsewhere','Prescribed elsewhere'],['stopped','Stopped medication']].map(([v,l])=>`<option value="${v}" ${v===data.mode?'selected':''}>${l}</option>`).join('')}</select><p class="row"></p>`;mode.querySelector('.row').append(button('Save situation',()=>action('/mode',{mode:mode.querySelector('select').value})));content.append(mode);
 }else if(view==='weekly-review'){
  const section=document.createElement('section');section.innerHTML=`<h2>Your Life Back review</h2><p>Your personal measure. No combined or medical score.</p><p>${data.weeklyAssessment?'You rated your last week '+data.weeklyAssessment.rating+' out of 5.':'Your own weekly rating is missing.'}</p><p>${data.win?esc(data.win.text):'No helpful action recorded yet. No win invented.'}</p><p>${esc(data.next)}</p>`;const row=document.createElement('div');row.className='row';for(let i=1;i<=5;i++)row.append(button('This week: '+i+'/5',()=>action('/weekly-review',{rating:i}),true));section.append(row);content.append(section);const detail=document.createElement('pre');detail.textContent=JSON.stringify(data.components,null,2);content.append(detail);
  const choose=document.createElement('section');choose.innerHTML='<h3>Choose what counts for you</h3>';for(const c of ['energy','sleep','activity','mood','waist','weight']){const label=document.createElement('label');label.innerHTML=`<input type="checkbox" value="${c}" ${data.components.some(x=>x.key===c)?'checked':''}> ${c}`;choose.append(label);}choose.append(button('Save Life Back components',()=>action('/components',{components:[...choose.querySelectorAll('input:checked')].map(x=>x.value)})));content.append(choose);
 }else if(view==='records'){
  content.innerHTML=`<section><h2>Your test records</h2><p>Scale: ${data.missing.scale?'missing':'saved'}. Wearable: ${data.missing.wearable?'missing':'saved'}. Dose: ${data.missing.dose?'no dose logged':'logged'}.</p><div class="row" id="dose-buttons"></div></section>`;$('#dose-buttons').append(button('Log dose today',()=>action('/doses',{}),true));const raw=document.createElement('pre');raw.textContent=JSON.stringify(data,null,2);content.append(raw);
 }else{const section=document.createElement('section');section.innerHTML='<h2>Your audit trail</h2><p>Test activity and decisions. Saving a record does not contact a clinician.</p>';const raw=document.createElement('pre');raw.textContent=JSON.stringify(data,null,2);section.append(raw);content.append(section);}
 if(view==='today')performance.mark('coaching-today-ready');
}
document.querySelectorAll('[data-login]').forEach(b=>b.addEventListener('click',()=>run(async()=>{await api('/test/session',{account:b.dataset.login,admin:true});$('#login').hidden=true;$('#workspace').hidden=false;await render('today');},b)));
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>run(()=>render(b.dataset.view),b)));
for(const [id,path,b]of [['run-night','/test/night-job',{}],['enable-global','/test/global-off',{enabled:true}],['disable-global','/test/global-off',{enabled:false}],['dispatch','/test/push',{}]])$('#'+id).addEventListener('click',()=>run(async()=>{$('#test-result').textContent=JSON.stringify(await api(path,b),null,2);}));
run(async()=>{const requested=location.pathname.split('/').at(-1);await render(['today','memory','permissions','weekly-review','records','audit'].includes(requested)?requested:'today');$('#login').hidden=true;$('#workspace').hidden=false;}).catch(()=>{});
