const api='/v1/tap-room';let state,current;const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(path,options={}){const r=await fetch(api+path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(r.status===401){location.href='/member-login?returnTo=%2Ftap-room';throw new Error('Sign in required')}const b=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(b.error||'That did not work.'),{body:b,status:r.status});return b}
function showNotice(message){const n=$('#notice');n.textContent=message;n.hidden=!message}
function renderRooms(){current=null;$('#conversation').hidden=true;$('#rooms').hidden=false;if(state.demo)showNotice('STAGING DEMONSTRATION — review content, not live member activity.');$('#rooms').innerHTML=state.rooms.map(r=>`<button class="room" data-room="${r.slug}"><h2>${esc(r.name)}</h2><p>${esc(r.purpose)}</p></button>`).join('');document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>openRoom(b.dataset.room))}
async function openRoom(slug){current=slug;const data=await call(`/rooms/${slug}/posts`);$('#rooms').hidden=true;$('#conversation').hidden=false;$('#roomHead').innerHTML=`<h2>${esc(data.room.name)}</h2><p>${esc(data.room.purpose)}</p>${data.notice?`<div class="room-notice">${esc(data.notice)}</div>`:''}`;$('#posts').innerHTML=data.posts.length?data.posts.map(postHtml).join(''):'<p>The stools are ready. The founding conversations will appear here at launch.</p>';document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>report(b.dataset.report));document.querySelectorAll('[data-replies]').forEach(b=>b.onclick=()=>showReplies(b.dataset.replies,b.closest('.post')));scrollTo({top:0,behavior:'smooth'})}
function postHtml(p){return `<article class="post"><div class="post-meta">${esc(p.display_name||'Founding prompt')} · ${new Date(p.created_at).toLocaleString('en-GB')}</div><p>${esc(p.body)}</p><div class="post-actions"><button data-report="${p.id}" class="secondary">REPORT</button><button data-replies="${p.id}" class="secondary">${Number(p.reply_count||0)} REPLIES</button></div><div class="replies" hidden></div></article>`}
async function showReplies(id,post){const box=post.querySelector('.replies');if(!box.hidden){box.hidden=true;return}const data=await call(`/posts/${id}/replies`);box.innerHTML=data.replies.map(r=>`<div class="reply"><div class="post-meta">${esc(r.display_name)} · ${new Date(r.created_at).toLocaleString('en-GB')}</div><p>${esc(r.body)}</p></div>`).join('')||'<p>No replies yet.</p>';box.hidden=false}
async function post(){const body=$('#postBody').value.trim();if(!body)return;try{const r=await call(`/rooms/${current}/posts`,{method:'POST',body:JSON.stringify({body})});$('#postBody').value='';await call('/acknowledgements/privacy',{method:'POST',body:'{}'});await openRoom(current);showNotice(r.crisisSupport||r.reviewMessage||'Posted.')}catch(e){if(e.status===428&&current==='treatment-experiences'){$('#rules').showModal();return}showNotice(e.body?.crisisSupport||e.message)}}
async function report(id){const category=prompt('Report as: unsafe_treatment_advice, medication_sales, harassment, spam, crisis, or other');if(!category)return;const detail=category==='other'?prompt('Tell us what happened:')||'':'';try{const r=await call(`/posts/${id}/report`,{method:'POST',body:JSON.stringify({category,detail})});showNotice(r.holdingMessage||'Thanks. A human moderator will review it.')}catch(e){showNotice(e.message)}}
$('#backRooms').onclick=renderRooms;$('#composer').onsubmit=e=>{e.preventDefault();post()};$('#cancelRules').onclick=()=>$('#rules').close();$('#acceptRules').onclick=async()=>{await call('/acknowledgements/treatment-experiences',{method:'POST',body:'{}'});state.member.treatmentRulesAcknowledged=true;$('#rules').close();post()};try{state=await call('');renderRooms()}catch(e){showNotice(e.message)}
