const api='/v1/lounge',room='treatment-experiences',promptText='Anyone else’s clinic gone silent this week?';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,prompt;
async function call(path,options={}){const r=await fetch(api+path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(r.status===401){location.href='/member-login?returnTo=%2Flounge';throw Error('Sign in required')}const b=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(Error(b.error||'That did not work.'),{status:r.status,body:b});return b}
function ago(v){const s=Math.max(0,Math.floor((Date.now()-new Date(v))/1000));return s<60?'now':s<3600?`${Math.floor(s/60)}m`:s<86400?`${Math.floor(s/3600)}h`:new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}
function card(r){const name=r.display_name||'Member';return `<article class="reply-card"><span class="avatar" aria-hidden="true">${esc(name[0].toUpperCase())}</span><div><header><strong>${esc(name)}</strong><time datetime="${esc(r.created_at)}">${esc(ago(r.created_at))}</time></header><p>${esc(r.body)}</p></div></article>`}
function render(rows){$('#replies').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty"><strong>The door is open.</strong><p>Be the first to answer this week’s prompt.</p></div>'}
async function load(){state=await call('');const data=await call(`/rooms/${room}/posts`);prompt=data.posts.find(x=>x.is_founder_prompt&&x.body===promptText)||data.posts.find(x=>x.is_founder_prompt);if(!prompt){$('#replies').innerHTML='<div class="empty"><strong>The Lounge is open.</strong><p>The next approved host prompt is being pinned.</p></div>';$('#composer').hidden=true;return}$('#host-question').textContent=prompt.body;render((await call(`/posts/${prompt.id}/replies`)).replies||[])}
async function submit(e){e.preventDefault();const input=$('#replyBody'),button=$('#composer button'),text=input.value.trim();if(!text||!prompt)return;button.disabled=true;$('#notice').hidden=true;try{if(!state.member.treatmentRulesAcknowledged){await call('/acknowledgements/treatment-experiences',{method:'POST',body:'{}'});state.member.treatmentRulesAcknowledged=true}const result=await call(`/posts/${prompt.id}/replies`,{method:'POST',body:JSON.stringify({body:text})});if(result.flagged){$('#router').hidden=false;$('#notice').textContent=result.reviewMessage||'This was not published. A human moderator will review it.'}else{input.value='';input.style.height='auto';$('#router').hidden=true;render((await call(`/posts/${prompt.id}/replies`)).replies||[]);$('#notice').textContent='Reply posted.'}$('#notice').hidden=false}catch(error){$('#notice').textContent=error.status===429?'Give it a moment before posting again.':'We could not post that. Please try again.';$('#notice').hidden=false}finally{button.disabled=false}}
$('#replyBody').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=`${Math.min(e.target.scrollHeight,120)}px`});$('#composer').addEventListener('submit',submit);load().catch(e=>{if(e.message!=='Sign in required')$('#replies').innerHTML='<div class="empty"><strong>The Lounge could not open.</strong><p>Try refreshing the page.</p></div>'});
