import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fixture} from '../test-support/fixtures.mjs';
import {sqliteAdapter} from '../test-support/db.mjs';
import {SCHEMA,ProgrammeStore} from '../store.mjs';
import {mutate,execute,emptyState,publicState,currentState} from '../service.mjs';
import {evaluate,previewChange,requirements,shopping,dateAdd,weekStart} from '../engine.mjs';
import {suitable,RECIPES} from '../content.mjs';
import {programmeRoutes} from '../routes.mjs';
import {authenticateMember} from '../../member-state-fast-v1.js';
const options={fixtureMode:true};
function reviewed(s=fixture()){s=mutate(s,{type:'review'},options);s.revision++;return s}
function accept(s){return mutate(s,{type:'accept',proposalId:s.review.proposals[0].id,recipeId:'tuna'},options)}
test('Dave: explicit recurring Thursday only; no Saturday or invented takeaway/shift cause',()=>{const r=evaluate(fixture(),options);assert.deepEqual(r.proposals.map(p=>p.slotKey),['thu-dinner']);assert.doesNotMatch(r.summary+r.proposals[0].text,/Saturday|takeaway|isn.t your shift|logging/);assert.match(r.proposals[0].text,/does not tell us why/);assert(r.proposals[0].options.some(o=>RECIPES[o.recipeId].noCook))});
test('Gaz: completed manageable week produces same again without escalation',()=>{const r=evaluate(fixture('Gaz'),options);assert.equal(r.kind,'same-again');assert.equal(r.proposals.length,0)});
test('No reports and explicit unknown are never counted as failure or success',()=>{const s=fixture();s.reports=[];assert.equal(evaluate(s,options).kind,'keep');s.reports=[{slotKey:'thu-dinner',period:'2026-09-07',date:'2026-09-10',status:'unknown'}];assert.equal(evaluate(s,options).proposals.length,0)});
test('Recurrence checks only latest two observed periods and does not invent matching reasons',()=>{const s=fixture();s.reports.find(r=>r.slotKey==='thu-dinner').reason='oven unavailable';assert.doesNotMatch(evaluate(s,options).proposals[0].text,/Both times/);s.reports.push({period:'2026-09-07',date:'2026-09-11',slotKey:'fri-dinner',status:'done'});s.reports.filter(r=>r.slotKey==='thu-dinner'&&r.period==='2026-09-07').forEach(r=>r.status='done');assert.equal(evaluate(s,options).proposals.length,0)});
test('Unknown restrictions block meal alternatives; fish and vegetarian constraints are real filters',()=>{const s=fixture();s.preferences.allergies='unknown';assert.equal(evaluate(s,options).proposals[0].options.length,0);s.preferences.allergies=['fish'];s.preferences.diet='vegetarian';for(const p of evaluate(s,options).proposals)for(const o of p.options){assert(!RECIPES[o.recipeId].allergens.includes('fish'));assert(RECIPES[o.recipeId].vegetarian)}});
test('Unapproved fixture content cannot be selected outside the isolated environment',()=>{assert(!suitable(RECIPES.tuna,fixture().preferences));assert(!suitable({...RECIPES.tuna,reviewStatus:'withdrawn'},fixture().preferences,options))});
test('Exact preview changes no state and specifies dates, portions and quantities',()=>{const s=reviewed(),before=JSON.stringify(s),p=previewChange(s,s.review,s.review.proposals[0].id,'tuna',options);assert.equal(JSON.stringify(s),before);assert.deepEqual(p.target.map(s=>s.date),['2026-09-17','2026-09-24']);assert.equal(p.recipe.name,'Tuna and sweetcorn pasta');assert.equal(p.target[0].servings,4)});
test('Accept changes only confirmed future dinners; shared mince and leftovers remain correct',()=>{const s=reviewed(),a=accept(s);const before=requirements(s.slots,'2026-09-14','2026-09-20'),after=requirements(a.slots,'2026-09-14','2026-09-20');assert.equal(before['mince|g'].quantity,1500);assert.equal(after['mince|g'].quantity,1000);for(const slot of s.slots)if(!['2026-09-17:thu-dinner','2026-09-24:thu-dinner'].includes(slot.id))assert.deepEqual(a.slots.find(t=>t.id===slot.id),slot);assert.deepEqual(a.manualItems,s.manualItems);assert.deepEqual(a.acquired,s.acquired)});
test('Bought amounts survive a serving increase and show only extra quantity',()=>{const s=fixture(),slot=s.slots.find(s=>s.id==='2026-09-14:mon-dinner'),a=mutate(s,{type:'edit-slot',slotId:slot.id,recipeId:slot.recipeId,servings:12},options);const i=shopping(a,'2026-09-14','2026-09-20').items.find(i=>i.id==='mince');assert.equal(i.acquired,1000);assert.equal(i.quantity,2000);assert.equal(i.remaining,1000)});
test('Decline freezes the recurring slot and no rule routes around it; old evidence is insufficient later',()=>{const s=reviewed(),a=mutate(s,{type:'decline',proposalId:s.review.proposals[0].id},options);assert.deepEqual(a.slots,s.slots);a.cycle++;assert.equal(evaluate(a,options).proposals.length,0);a.cycle++;assert.equal(evaluate(a,options).proposals.length,0);a.requests.push({slotKey:'thu-dinner',date:'2026-09-14',reason:'I want to revisit it'});assert.equal(evaluate(a,options).proposals[0].priority,0)});
test('Skip keeps plan, quantities, manual items and stock',()=>{const s=reviewed(),a=mutate(s,{type:'skip'},options);for(const key of ['slots','manualItems','acquired'])assert.deepEqual(a[key],s[key])});
test('Undo preserves unrelated manual additions and changes',()=>{const s=reviewed(),a=accept(s);a.manualItems.push({id:'coffee2',name:'Tea',period:'2026-09-14..2026-09-20'});const unrelated=a.slots.find(s=>s.id==='2026-09-14:mon-dinner');unrelated.servings=10;const u=mutate(a,{type:'undo',decisionId:a.decisions[0].id},options);assert.equal(u.slots.find(s=>s.id===unrelated.id).servings,10);assert.equal(u.manualItems.length,2);assert.equal(u.slots.find(s=>s.id==='2026-09-17:thu-dinner').recipeId,'ragu')});
test('Undo refuses to overwrite subsequent edits to a changed item',()=>{const a=accept(reviewed());a.slots.find(s=>s.id==='2026-09-17:thu-dinner').servings=6;assert.throws(()=>mutate(a,{type:'undo',decisionId:a.decisions[0].id},options),/edited/)});
test('Stale proposal cannot overwrite manual plan edits',()=>{const s=reviewed();s.revision++;assert.throws(()=>accept(s),/fresh review/)});
test('Expired suggestions do not retire member plan items',()=>{const s=reviewed();s.cycle+=2;const before=JSON.stringify(s.slots);assert.throws(()=>accept(s),/expired/);assert.equal(JSON.stringify(s.slots),before)});
test('Repeat is explicit, includes 14 days and preserves past and existing future records',()=>{const s=fixture('Gaz'),a=mutate(s,{type:'repeat'},options);assert.deepEqual(a.slots,s.slots);assert.equal(a.decisions[0].start,'2026-09-14');assert.equal(a.decisions[0].end,'2026-09-27')});
test('Missing ingredient information stops calculation instead of assuming zero',()=>{assert.throws(()=>requirements([{kind:'meal',recipeId:'missing',servings:4,date:'2026-09-14'}],'2026-09-14','2026-09-20'),/Incomplete/)});
test('R10 applies member request before recurrence, caps at three and resolves ties stably',()=>{const s=fixture();s.requests=['sat-walk','tue-walk','thu-walk','sun-dinner','thu-dinner'].map(slotKey=>({slotKey,date:'2026-09-13'}));const r=evaluate(s,options);assert.equal(r.proposals.length,3);assert.deepEqual(r.proposals.map(p=>p.slotKey),['sat-walk','sun-dinner','thu-dinner']);assert(r.proposals.every(p=>p.priority===0));assert.equal(r.suppressed.filter(p=>p.rule==='R10').length,2)});
test('Member-initiated change still appears after a wholly good week',()=>{const s=fixture('Gaz');s.requests=[{slotKey:'thu-dinner',date:'2026-09-13'}];assert.equal(evaluate(s,options).kind,'proposal')});
test('Standalone setup requires no medicine, weight, photographs or clinical questionnaire',()=>{const s=emptyState('2026-09-13');s.entitlement.active=true;const a=mutate(s,{type:'setup',goal:'Family time',focus:'movement',preferences:fixture().preferences,choices:[{day:2,kind:'move',minutes:12}],measures:[]},options);assert(a.setup);assert.equal(a.slots[0].minutes,12);assert.deepEqual(a.measures,[]);assert(!('medication' in a))});
test('Real SQLite save is owner-scoped, retrievable, idempotent and rejects conflicting retries',async()=>{const db=sqliteAdapter();db.sqlite.exec(SCHEMA);const store=new ProgrammeStore(db);await store.create(1,fixture());await store.create(2,fixture('Gaz'));const action={type:'review',revision:0,operationId:'operation-111'};const a=await execute(store,1,action,options),b=await execute(store,1,action,options);assert.equal(a.revision,b.revision);assert.equal((await store.get(1)).reviews.length,1);assert.equal((await store.get(2)).reviews.length,0);await assert.rejects(execute(store,1,{...action,type:'skip'},options),/different action/);assert.equal((await store.get(1)).name,'Dave')});
test('Concurrent writes commit once; stale loser cannot alter accepted state',async()=>{const db=sqliteAdapter();db.sqlite.exec(SCHEMA);const store=new ProgrammeStore(db);await store.create(1,fixture());const outcomes=await Promise.allSettled([execute(store,1,{type:'review',revision:0,operationId:'operation-211'},options),execute(store,1,{type:'review',revision:0,operationId:'operation-212'},options)]);assert.equal(outcomes.filter(o=>o.status==='fulfilled').length,1);assert.equal((await store.get(1)).reviews.length,1)});
test('Database save failure leaves prior aggregate intact',async()=>{const db=sqliteAdapter();db.sqlite.exec(SCHEMA);const store=new ProgrammeStore(db);await store.create(1,fixture());const original=await store.get(1);const broken={get:store.get.bind(store),save:async()=>{throw Error('Injected write failure')}};await assert.rejects(execute(broken,1,{type:'review',revision:0,operationId:'operation-311'},options));assert.deepEqual(await store.get(1),original)});
test('Expired service preserves saved records, shopping and manual actions',()=>{const s=fixture();s.entitlement.active=false;assert.throws(()=>mutate(s,{type:'review'},options),/paused/);const a=mutate(s,{type:'manual-item',start:'2026-09-14',name:'Coffee'},options);assert.equal(a.manualItems.length,s.manualItems.length+1);assert.deepEqual(a.slots,s.slots)});
test('Pinned authentication and route checks reject anonymous/expired/foreign sessions; userId input cannot impersonate',async()=>{const db=sqliteAdapter();db.sqlite.exec(SCHEMA+'CREATE TABLE users(id INTEGER PRIMARY KEY,first_name TEXT);CREATE TABLE user_sessions(id INTEGER PRIMARY KEY,user_id INTEGER,token_hash TEXT,expires_at TEXT,revoked_at TEXT,last_used_at TEXT);');const store=new ProgrammeStore(db);for(const [id,name,token] of [[1,'Dave','fixture-token-a'],[2,'Gaz','fixture-token-b']]){db.sqlite.prepare('INSERT INTO users VALUES(?,?)').run(id,name);db.sqlite.prepare('INSERT INTO user_sessions(user_id,token_hash,expires_at) VALUES(?,?,?)').run(id,createHash('sha256').update(token).digest('hex'),'2099-01-01');await store.create(id,fixture(name))}const env={DB:db,PROGRAMME_DB:db,PROGRAMME_V1_ENABLED:'true'},deps={authenticate:authenticateMember,html:'PRIVATE-WORKSPACE',fixtureMode:true};
 const req=(path,token,body,origin='https://test.invalid')=>new Request('https://test.invalid'+path,{method:body?'POST':'GET',headers:{...(token?{Cookie:'sst_session='+token}:{}),'Content-Type':'application/json',Origin:origin},body:body?JSON.stringify(body):undefined});
 assert.equal((await programmeRoutes(req('/v1/programme'),env,deps)).status,401);
 const html=await programmeRoutes(req('/member/programme'),env,deps);assert.equal(html.status,303);assert(!((await html.text()).includes('PRIVATE')));
 const a=await programmeRoutes(req('/v1/programme','fixture-token-a',{type:'review',userId:2,revision:0,operationId:'operation-411'}),env,deps);assert.equal(a.status,200);assert.equal((await store.get(2)).reviews.length,0);assert.equal(a.headers.get('Cache-Control'),'no-store, private, max-age=0');
 assert.equal((await programmeRoutes(req('/v1/programme','fixture-token-a',{type:'skip',revision:1,operationId:'operation-412'},'https://attacker.invalid'),env,deps)).status,403);
 db.sqlite.prepare('UPDATE user_sessions SET revoked_at=? WHERE user_id=1').run('2026-09-11');assert.equal((await programmeRoutes(req('/v1/programme','fixture-token-a'),env,deps)).status,401);
 assert.equal((await programmeRoutes(req('/v1/programme','fixture-token-b'),{...env,PROGRAMME_V1_ENABLED:'false'},deps)).status,404);
 assert.equal(await programmeRoutes(req('/v1/newsroom'),env,deps),null);
});

test('Repeated leftovers reference the new source cook and keep ingredient need counted once',()=>{const s=fixture('Gaz');s.clock='2026-09-27';s.cycle=4;const a=mutate(s,{type:'repeat'},options);const l=a.slots.find(s=>s.id==='2026-09-29:tue-leftovers');assert.equal(l.sourceId,'2026-09-28:mon-dinner');assert.equal(requirements(a.slots,'2026-09-28','2026-10-04')['mince|g'].quantity,1500)});
test('Serving reductions cannot spend portions already reserved for another day',()=>{const s=fixture();assert.throws(()=>mutate(s,{type:'edit-slot',slotId:'2026-09-14:mon-dinner',recipeId:'chilli',servings:4},options),/leftovers/);assert.equal(s.slots.find(s=>s.id==='2026-09-14:mon-dinner').servings,8)});

test('Chosen Tuesday review day anchors seven-day windows; joining never creates a past action',()=>{const s=emptyState('2026-09-16');s.entitlement.active=true;const a=mutate(s,{type:'setup',preferences:{...fixture().preferences,reviewDay:2},choices:[{day:0,kind:'meal',recipeId:'chilli',servings:4}]},options);assert.equal(a.anchor,'2026-09-15');assert.equal(a.slots[0].date,'2026-09-21');const next=currentState(a,{today:'2026-09-22'});assert.equal(next.cycle,1);assert.equal(publicState(next,options).lists[0].start,'2026-09-23')});
test('Refreshing a weekly review versions one cycle record',()=>{let s=reviewed();const id=s.review.id;s=mutate(s,{type:'review'},options);assert.equal(s.reviews.length,1);assert.equal(s.review.id,id);assert.equal(s.review.version,2)});

test('An ingredient no longer required still shows the member’s already bought quantity',()=>{const s=reviewed();s.acquired['2026-09-14..2026-09-20']['celery|stalk']={status:'bought',quantity:2};const a=accept(s),item=shopping(a,'2026-09-14','2026-09-20').items.find(i=>i.id==='celery');assert.equal(item.quantity,0);assert.equal(item.acquired,2);assert.equal(item.noLongerNeeded,true)});
