import {reconciliationGitArgs,reconciliationHistoricalRead,reconciliationPath,RECONCILIATION_PATHS,verifyReconciledRelease,LATER_UNATTRIBUTED_WATCH_RECOVERY_PRESERVED} from './approved-runtime-composition.mjs';
import {METRICS_PATHS,verifyMetricsConnection} from './metrics-connection-scope.mjs';
import {rankingGrowthHistoricalRef} from './seo-growth-scope.mjs';
import {originalPwaLiveReadVerifier} from './seo-follow-through-preservation.mjs';
import {WATCH_RECONCILIATION_BASE,ZENAGAMTIDE_BASE,ZENAGAMTIDE_PATHS,FIT300_PATHS,READONLY_ORGANIC_PATHS,validateFit300} from './fit-300-scope.mjs';
import {RECIPE_IMAGE_PATHS,validateRecipeImages} from './recipe-image-scope.mjs';
import {DEVICE_HEALTH_PATHS,historicalDeviceHealthRef,validateDeviceHealthSource,verifyDeviceHealthProof} from './device-health-scope.mjs';
import {COACH_BASE,COACH_PATHS,WATCH_CURRENT_PATHS,coachingHistoricalRef,withoutCoachEntrypoint,verifyCoachingRelease} from '../shift-coach/release-contract.mjs';
import {MEMBER_DESIGN_PATHS,MEMBER_LAYOUT_PATHS,validateMemberDesignSource} from './member-design-scope.mjs';
import {FOOTER_CANDIDATE,FOOTER_PATHS,FOOTER_RUNTIME_PATHS,historicalFooterRef,validateFooterSource} from './footer-scope.mjs';
import {validateHomeBanner} from './home-banner-scope.mjs';
import {MEMBER_FOCUS_APPROVED,MEMBER_FOCUS_PATHS,validateMemberFocus} from './member-focus-scope.mjs';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
export const PWA_DISMISS_APPROVED='fbbc8e592549f48280e32009edcbb73d1dd42669';
export const PWA_DISMISS_PATHS=['my-timber-pwa/ui.mjs','my-timber-pwa/presentation.mjs','my-timber-pwa/pwa.test.mjs','my-timber-pwa/preservation.mjs','my-timber-pwa/preservation.test.mjs','preview/pwa-dismiss/verify.cjs','.github/workflows/pwa-dismiss-preview.yml'];
export const APP_BASE='8c6902c8e0c6a53863282c6c4378f82ec1a70f6f';
export const APP_APPROVED=MEMBER_FOCUS_APPROVED;
export const APP_HASHES=JSON.parse(readFileSync(new URL('./app-manifest.json',import.meta.url))).sha256;
// Exact full-history checkout for the separately pinned recipe imagery release.
APP_HASHES['.github/workflows/readiness-preservation.yml']='ecd1538ae921da46a9e6afc8c6b08dd2df8db6b64e59f71f47def3708c6d145c';
export const ARTICLE_REPAIR_SOURCE='f5184e4ffefd6bc2eb105e86e7107e5c61f00327';
export const ARTICLE_REPAIR_PATHS=new Set(['.github/workflows/evidence-article-repair-snapshot.yml','.github/workflows/evidence-based-article-live-release.yml','babylove/dynamic-public.mjs','babylove/dynamic-public.test.mjs','babylove/repair-evidence-based-article.mjs','public-continuity.mjs']);
export const APP_PATHS=new Set([...FIT300_PATHS,...READONLY_ORGANIC_PATHS,...RECIPE_IMAGE_PATHS,...DEVICE_HEALTH_PATHS,...ARTICLE_REPAIR_PATHS,...Object.keys(APP_HASHES),'release/app-manifest.json','release/app-scope.mjs','release/growth-scope.mjs','docs/content-review/2026-10-03-public-copy-preview.json','docs/content-review/2026-10-03-public-copy-residual.json','medicines-watch/reviews/2026-10-01-authorised-broader-discovery.json','medicines-watch/reviews/2026-10-01-synt101-mad-correction.json','medicines-watch/reviews/2026-10-02-authorised-international-omissions.json','medicines-watch/reviews/2026-10-02-authorised-expanded-discovery.json','medicines-watch/reviews/2026-10-02-authorised-ubt251.json','medicines-watch/reviews/2026-10-02-authorised-sgb7342.json','medicines-watch/reviews/2026-10-02-authorised-abbv-asc30-tern-bimagrumab.json','medicines-watch/reviews/2026-10-02-source-monitor-repairs.json','medicines-watch/reviews/2026-10-02-authorised-registry-omissions.json','medicines-watch/reviews/2026-10-02-pfizer-pdf-monitor-repair.json','medicines-watch/reviews/2026-10-02-authorised-enobosarm-semaglutide.json','medicines-watch/reviews/2026-10-02-authorised-semaglutide-specialist-trials.json','medicines-watch/reviews/2026-10-02-authorised-glimr-copd.json','medicines-watch/reviews/2026-10-02-authorised-specialist-registry-followup.json','medicines-watch/reviews/2026-10-02-authorised-switching-studies.json','medicines-watch/reviews/2026-10-02-authorised-na931.json','medicines-watch/reviews/2026-10-03-authorised-amylin-metabolic-followup.json','medicines-watch/reviews/2026-10-03-authorised-azd1043.json','medicines-watch/reviews/2026-10-03-authorised-azd6234-selene.json','medicines-watch/reviews/2026-10-03-authorised-wve007.json','medicines-watch/reviews/2026-10-03-authorised-specialist-registry-wave.json','medicines-watch/reviews/2026-10-03-authorised-lean-mass-energy-followup.json','medicines-watch/reviews/2026-10-03-authorised-foundayo-predicted-risk.json','medicines-watch/reviews/2026-10-03-authorised-wegovy-mash-correction.json','medicines-watch/reviews/2026-10-03-authorised-vk3019-at673.json','medicines-watch/reviews/2026-10-04-authorised-srsd384.json','medicines-watch/reviews/2026-10-04-authorised-fractyl-modality-gap.json','medicines-watch/reviews/2026-10-04-authorised-art2713-muscle-gap.json',...FOOTER_PATHS,...MEMBER_DESIGN_PATHS,...MEMBER_LAYOUT_PATHS,'release/member-design-scope.mjs','tests/member-design-release.test.mjs','.github/workflows/member-design-release-proof.yml',...COACH_PATHS]);
APP_PATHS.add('medicines-watch/reviews/2026-10-06-authorised-zenagamtide-ambience.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-05-authorised-710go.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-06-authorised-survodutide-synchronize-jp.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-06-authorised-core-trial-lifecycle.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-06-authorised-gub-ucn2-mbl949.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-06-authorised-at7687-at673-alias.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-06-authorised-viking-rhythm-registry-review.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-06-overdue-source-renewal.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-06-authorised-gs4571-tirzepatide-menopause.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-07-authorised-registry-lifecycle-followup.json');
APP_PATHS.add('medicines-watch/reviews/2026-10-07-authorised-enicepatide-emugrobart-registry.json');
export const originalAppHashRef=p=>rankingGrowthHistoricalRef('HEAD',p,undefined,false)!=='HEAD'?rankingGrowthHistoricalRef('HEAD',p,undefined,false):['release/app-scope.mjs','release/watch-registry-wave-scope.mjs','shift-coach/release-contract.mjs','tests/b1-release-scope.test.mjs','tests/watch-ownership-release.test.mjs'].includes(p)?'HEAD':p==='my-timber-pwa/presentation.mjs'?PWA_DISMISS_APPROVED:historicalDeviceHealthRef(coachingHistoricalRef(historicalFooterRef(ZENAGAMTIDE_PATHS.includes(p)?ZENAGAMTIDE_BASE:'HEAD',p),p),p);
export function originalMemberWorkerPresentation(source){
 return source.replace("\nexport function memberWorkerHtml(html){\n return html.replace(/(<script\\b[^>]*\\bsrc=[\"'])(\\/(?:app\\.js|register-sw-v3a\\.js)(?:\\?[^\"']*)?)([\"'][^>]*>)/gi,(_,before,src,after)=>before+src+(/[?&](?:amp;)?member_worker=1(?:&|$)/.test(src)?'':(src.includes('?')?'&amp;':'?')+'member_worker=1')+after);\n}\nexport async function memberWorkerAsset(request,response){\n const u=new URL(request.url);\n if(request.method!=='GET'||u.searchParams.get('member_worker')!=='1'||!['/app.js','/register-sw-v3a.js'].includes(u.pathname))return null;\n if(!response.ok||!/(?:javascript|ecmascript)/i.test(response.headers.get('Content-Type')||''))return response;\n const before=await response.text(),legacy=u.pathname==='/app.js'?\"navigator.serviceWorker.register('/service-worker.js')\":\"navigator.serviceWorker.register('/service-worker-v3a.js?v=cos-live-recovery-20260909-r2',{updateViaCache:'none'})\",shared=\"navigator.serviceWorker.register('/shift-push-sw-v1.js',{scope:'/',updateViaCache:'none'})\";\n const h=new Headers(response.headers);for(const k of ['Content-Length','Content-Encoding','ETag','Last-Modified'])h.delete(k);h.set('Cache-Control','no-store');\n if(before.split(legacy).length!==2)return new Response('Member worker registration source changed; please retry later.',{status:503,headers:h});\n return new Response(before.replace(legacy,shared),{status:response.status,statusText:response.statusText,headers:h});\n}\n",'').replace("\n const memberAsset=await memberWorkerAsset(request,response);if(memberAsset)return memberAsset;",'').replace("\n if(/^\\/member\\//.test(path))html=memberWorkerHtml(html);",'');
}
for(const p of [...METRICS_PATHS,...RECONCILIATION_PATHS,...LATER_UNATTRIBUTED_WATCH_RECOVERY_PRESERVED])APP_PATHS.add(p);
export function validateAppSource(){
 verifyReconciledRelease();
 verifyMetricsConnection();
 validateFit300();
 validateRecipeImages();
 verifyCoachingRelease();
 validateDeviceHealthSource();
 const git=(...args)=>execFileSync('git',reconciliationGitArgs(args),{encoding:'utf8'}).trim();
 git('merge-base','--is-ancestor',APP_BASE,'HEAD');
 validateFooterSource();
 validateMemberDesignSource();
 validateHomeBanner();
 for(const p of PWA_DISMISS_PATHS)if(p==='my-timber-pwa/presentation.mjs')assert.equal(originalMemberWorkerPresentation(execFileSync('git',['show','HEAD:'+p],{encoding:'utf8'})),execFileSync('git',['show',PWA_DISMISS_APPROVED+':'+p],{encoding:'utf8'}),'Complete PWA presentation differs beyond exact shared member worker registration');else assert.equal(git('rev-parse','HEAD:'+p),git('rev-parse',PWA_DISMISS_APPROVED+':'+p),'Reviewed PWA install dismissal drift: '+p);
 validateMemberFocus((ref,path)=>git('rev-parse',(ref==='HEAD'&&path==='preview/app-layout/tabs.mjs'?FOOTER_CANDIDATE:ref)+':'+path));
 const changed=git('diff','--name-only',APP_BASE,'HEAD').split('\n').filter(Boolean);
 assert(changed.every(p=>APP_PATHS.has(p)),'Unapproved files in app release: '+changed.filter(p=>!APP_PATHS.has(p)).join(','));
 for(const [p,sha]of Object.entries(APP_HASHES))assert.equal(createHash('sha256').update(execFileSync('git',reconciliationGitArgs(['show',originalAppHashRef(p)+':'+p]))).digest('hex'),sha,'App release drift: '+p);
 for(const p of ['presentation.mjs','screens.mjs','tabs.mjs','refinement.mjs','verify.cjs'])assert.equal(git('rev-parse',historicalFooterRef('HEAD','preview/app-layout/'+p)+':preview/app-layout/'+p),git('rev-parse',APP_APPROVED+':preview/app-layout/'+p),'Approved app design changed: '+p);
 assert.equal(originalPwaLiveReadVerifier(execFileSync('git',['show','HEAD:my-timber-pwa/verify-live.mjs'],{encoding:'utf8'})),execFileSync('git',['show',APP_BASE+':my-timber-pwa/verify-live.mjs'],{encoding:'utf8'}),'PWA verifier differs beyond the exact bounded GET retry repair');
 assert.equal(execFileSync('git',['show','HEAD:my-timber-pwa/service-worker.mjs'],{encoding:'utf8'}).replace(" const panel=['/member/fit','/member/grub','/member/life-back'].includes(u.pathname)&&u.searchParams.get('app_panel')==='1'&&['app','web'].includes(u.searchParams.get('view'))&&u.searchParams.size===2;\n if(event.request.method!=='GET'||event.request.mode!=='navigate'||u.origin!==self.location.origin||!/^\\/member\\//.test(u.pathname)||(u.search&&!panel))return;"," if(event.request.method!=='GET'||event.request.mode!=='navigate'||u.origin!==self.location.origin||!/^\\/member\\//.test(u.pathname)||u.search)return;"),execFileSync('git',['show',FOOTER_CANDIDATE+':my-timber-pwa/service-worker.mjs'],{encoding:'utf8'}),'Service worker differs beyond exact authenticated inline panel fetch');
 assert.equal(git('diff',APP_BASE,'HEAD','--','member-experience','my-timber-pwa','migrations',':(exclude)my-timber-pwa/verify-live.mjs',':(exclude)member-experience/orders.mjs',':(exclude)member-experience/tablet-routine.mjs',':(exclude)member-experience/tablet-routine-client.mjs',':(exclude)member-experience/ai-site-knowledge.mjs',':(exclude)member-experience/ai-stream.mjs',':(exclude)member-experience/tests/lookup-continuation.test.mjs',':(exclude)member-experience/tests/continuity-measurement.test.mjs',':(exclude)member-experience/public-preservation.mjs',':(exclude)member-experience/verify-production-member.mjs',':(exclude)member-experience/dashboard-tools.mjs',':(exclude)member-experience/tests/dashboard-tools.test.mjs',...[...RECONCILIATION_PATHS].filter(reconciliationPath).map(p=>':(exclude)'+p),...[...DEVICE_HEALTH_PATHS].map(p=>':(exclude)'+p),...[...FOOTER_RUNTIME_PATHS].map(p=>':(exclude)'+p),...PWA_DISMISS_PATHS.map(p=>':(exclude)'+p),...MEMBER_FOCUS_PATHS.map(p=>':(exclude)'+p),...[...RECIPE_IMAGE_PATHS].map(p=>':(exclude)'+p)),'','Protected runtime, data and PWA source changed');
 assert.equal(withoutCoachEntrypoint(readFileSync('wrangler.jsonc','utf8')),execFileSync('git',['show',APP_BASE+':wrangler.jsonc'],{encoding:'utf8'}),'Protected configuration changed outside the separately pinned coaching entrypoint');
}
