plugins {
    id 'com.android.library' version '8.13.2'
    id 'org.jetbrains.kotlin.android' version '2.2.21'
}
android {
    namespace 'uk.co.shiftsometimber.mytimber.health'
    compileSdk 36
    defaultConfig { minSdk 28 }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    kotlinOptions { jvmTarget = '17' }
}
dependencies { implementation 'androidx.health.connect:connect-client:1.1.0' }
