// Literal browser source: Worker bundling must not inject server-side helpers.
// No browser storage, analytics or third-party calls.
export const workClientSource=String.raw`(function workClient(){
 const root=document.querySelector('#work-app'),mode=root.dataset.mode,status=document.querySelector('#work-status');
 let generation=0,controller=new AbortController();
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const request=async(path,body)=>{const gen=generation,r=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(gen!==generation)throw new DOMException('Stale response','AbortError');if(r.status===401||r.status===403){clear();status.textContent=data.error||'Sign in again.';throw new Error(data.error)}if(!r.ok)throw new Error(data.error||'Request failed.');return data};
 const clear=()=>{generation++;controller.abort();controller=new AbortController();records=[];root.replaceChildren();status.textContent='Your private view is closed.'};
 addEventListener('pagehide',clear);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')clear();else load()});addEventListener('pageshow',e=>{if(e.persisted)load()});
 const button=(text,act,id,extra='')=>'<button type="button" data-action="'+act+'" data-id="'+esc(id)+'" '+extra+'>'+text+'</button>';
 const show=(name,value)=>'<p><strong>'+name+':</strong> '+esc(value)+'</p>';
 const reportHTML=r=>r.status?show('Report',r.reason||r.status):'<p>Reporting period: '+esc(r.programmeStart)+' to '+esc(r.programmeEnd)+'</p><table><thead><tr><th>Measure</th><th>Released result</th></tr></thead><tbody>'+[['Invitations',r.invitations],['Activations',r.activations],['Engagement',r.engagement],['Completion',r.completion],['Wellbeing',r.wellbeing]].map(([label,v])=>'<tr><th>'+label+'</th><td>'+esc(v.status==='reported'?v.count+' ('+v.precision+')':v.reason)+'</td></tr>').join('')+'</tbody></table><p>Engagement means at least one weekly review marked complete. Completion means all twelve. These are participation measures, not clinical outcomes.</p>';
 const controls=()=>{root.querySelectorAll('form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();run(()=>submit(f))}));root.querySelectorAll('button[data-action]').forEach(b=>b.addEventListener('click',()=>run(()=>action(b),b)));};
 let records=[];
 const run=async(fn,source)=>{status.textContent='Working…';root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){if(e.name!=='AbortError')status.textContent=e.message}finally{root.querySelectorAll('button').forEach(b=>b.disabled=false);if(source){const next=[...root.querySelectorAll('button[data-action]')].find(b=>b.dataset.action===source.dataset.action&&b.dataset.id===source.dataset.id&&b.dataset.week===source.dataset.week);next?.focus()}}};
 const fields=c=>'<div class="work-grid">'+[['name','Organisation','text',160],['start','Shared start (UTC date)','date'],['end','End date (exclusive; 12 weeks later)','date'],['seats','Pilot seats (1–150)','number']].map(([k,l,t,max])=>'<label>'+l+'<input name="'+k+'" type="'+t+'" '+(max?'maxlength="'+max+'"':'')+' value="'+esc(c[k]??'')+'" required></label>').join('')+'<label>Agreed programme fee (pence; blank if unconfirmed)<input type="number" min="0" name="feePence" value="'+esc(c.feePence??'')+'"></label><label>Proposed testing allowance (pence; does not enable tests)<input type="number" min="0" name="testingAllowancePence" value="'+esc(c.testingAllowancePence??'')+'"></label><label>Employer contact account IDs (comma separated)<input name="reporterIds" value="'+esc((c.reporterIds??[]).join(','))+'"></label></div><label>Programme deliverables<textarea name="scope" maxlength="1600" required>'+esc(c.scope??'')+'</textarea></label><label>Human support limits and response times<textarea name="support" maxlength="600" required>'+esc(c.support??'')+'</textarea></label>';
 const config=f=>{const d=Object.fromEntries(new FormData(f));return {name:d.name,start:d.start,end:d.end,seats:Number(d.seats),feePence:d.feePence===''?null:Number(d.feePence),testingAllowancePence:d.testingAllowancePence===''?null:Number(d.testingAllowancePence),reporterIds:d.reporterIds.trim()?d.reporterIds.split(',').map(Number):[],scope:d.scope,support:d.support}};
 const date=s=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(s+'T00:00:00Z'));
 const privacy='<p>My Timber is free. Your employer funds the workplace programme. Your employer cannot open your account, view named participation, personal answers or progress. Reports may be withheld for small groups. Joining is optional; declining a blood test does not affect programme access. Testing is not available.</p><p>Authorised SHIFT staff can see which accounts belong to each company to administer access; employers cannot use this view. We store your account link, joining date, notice version and which weekly reviews you mark complete. You can withdraw here and remove that link and review history; your free account remains. Previously released anonymous reports cannot identify and remove a person. Read the <a href="/privacy">SHIFT privacy notice</a>. Do not enter health information in invitation fields.</p>';
 const joinForm=()=>'<section class="work-panel work-join"><p class="work-eyebrow">YOUR INVITATION</p><h2>Join your workplace programme</h2><p>Use the private code supplied with your workplace invitation. Your existing My Timber account stays yours.</p><div class="work-notice"><h3>Your choice. Your privacy.</h3>'+privacy+'</div><form data-kind="join"><label>Private invitation code<input name="code" autocomplete="off" spellcheck="false" required maxlength="101" placeholder="Paste your company invitation code"></label><label class="check"><input type="checkbox" name="consent" required>I choose to join and have read the workplace information above.</label><button>Join privately</button></form></section>';
 const toolsHTML=()=>'<div class="work-tools" aria-label="Your My Timber tools">'+[['01','My Journey','Your goals and your own starting point.','/member/journey'],['02','SHIFT Grub','Return to your food tools and meal planning.','/member/grub'],['03','SHIFT Fit','Return to your movement and fitness tools.','/member/fit'],['04','My check-in','Take a moment to review how you are doing.','/member/check-in']].map(([n,title,copy,url])=>'<a class="work-tool" href="'+url+'"><span class="work-tool-number" aria-hidden="true">'+n+'</span><strong>'+title+'</strong><span>'+copy+'</span><span class="work-tool-arrow" aria-hidden="true">↗</span></a>').join('')+'</div>';
 const cohortHTML=s=>{
  const done=s.completedWeeks.includes(s.week),available=s.active&&s.week>0;
  const label=available?'WEEK '+s.week+' OF 12':s.week===0?'YOUR SHARED START':'YOUR WORKPLACE PROGRAMME';
  const title=available?(done?'Your review is saved.':'A moment for your weekly review.'):s.week===0?'Your place is confirmed.':'Weekly updates are closed.';
  const copy=available?(done?(s.week<12?'You can return to your own tools whenever you need them. Your next weekly review opens with the programme calendar.':'You have marked the final week’s review complete. Your free My Timber tools remain available.'):'Open your private check-in, then mark this week’s review complete when you have worked through it.'):s.week===0?'Everyone starts together on '+date(s.start)+'. Your weekly reviews open then.':'Your programme may be paused or have ended. Your free My Timber tools are still available.';
  return '<section class="work-cohort" data-cohort="'+esc(s.employerId)+'"><div class="work-lead"><div class="work-lead-copy"><p class="work-eyebrow">'+label+'</p><p class="work-company">'+esc(s.name)+'</p><h2 tabindex="-1">'+title+'</h2><p>'+copy+'</p><div class="work-next-actions"><a class="work-primary" href="/member/check-in">Open my check-in <span aria-hidden="true">→</span></a>'+(available?button(done?'Mark incomplete':'Mark review complete','review',s.employerId,'data-week="'+s.week+'" data-done="'+done+'" class="work-secondary"'):'')+'</div></div><img src="/assets/home-hero-men-v32o.jpg" alt="" width="720" height="500"></div><div class="work-cohort-body"><div class="work-stats"><div><span>Shared start</span><strong>'+date(s.start)+'</strong></div><div><span>Programme ends</span><strong>'+date(s.end)+'</strong></div><div><span>Your weekly reviews</span><strong>'+s.completedWeeks.length+' of 12 complete</strong><progress max="12" value="'+s.completedWeeks.length+'" aria-label="Weekly reviews marked complete">'+s.completedWeeks.length+' of 12</progress></div></div><h3 class="work-section-title">Your tools. All in one place.</h3>'+toolsHTML()+'<details class="work-fold"><summary>Your 12-week record <span>'+s.completedWeeks.length+' reviews complete</span></summary><p>These are the reviews you have marked complete. They are participation records, not health scores.</p><ol class="work-weeks">'+Array.from({length:12},(_,i)=>{const w=i+1,complete=s.completedWeeks.includes(w);return '<li class="'+(complete?'is-complete':w===s.week?'is-current':'')+'"><span class="work-week-title">Week '+w+'</span><span>'+ (complete?'Review complete':w===s.week&&available?'This week':w>s.week?'Not open yet':'Not marked complete')+'</span>'+(s.active&&w<s.week?button(complete?'Mark incomplete':'Mark review complete','review',s.employerId,'data-week="'+w+'" data-done="'+complete+'"'):'')+'</li>'}).join('')+'</ol></details><details class="work-fold"><summary>Programme details and support</summary>'+show('Included in your programme',s.scope)+show('Support limits',s.support)+'<p>'+esc(s.testing.message)+'</p></details><details class="work-fold work-leave"><summary>Leave this workplace programme</summary><p>This removes your workplace link and review-completion history. Your free My Timber account and its existing tools remain.</p>'+button('Confirm withdrawal','withdraw',s.employerId)+'</details></div></section>';
 };
 const memberHTML=workplaces=>workplaces.length?workplaces.map(cohortHTML).join('')+'<div class="work-account"><details class="work-fold"><summary>Your privacy and workplace data</summary>'+privacy+'<p><a href="/v1/work/export" download>Download my workplace data</a></p></details><details class="work-fold"><summary>Have another workplace invitation?</summary>'+joinForm()+'</details></div>':'<div class="work-welcome"><div><p class="work-eyebrow">SHIFT FOR WORK</p><h2>Your next chapter starts here.</h2><p>Join your colleagues for a shared start, with your own goals and a private My Timber account.</p><p class="work-welcome-note">Your employer funds the programme. Your personal answers stay private.</p></div><img src="/assets/home-hero-men-v32o.jpg" alt="" width="720" height="500"></div>'+joinForm()+'<p class="work-data-link"><a href="/v1/work/export" download>Download my workplace data</a></p>';
 async function load(){if(document.visibilityState==='hidden')return false;generation++;controller.abort();controller=new AbortController();const gen=generation;try{
  if(mode==='hq'){
   const d=await request('/v1/hq/work');if(gen!==generation)return;records=d.employers;
   root.innerHTML='<section class="work-panel"><h2>Create a draft pilot</h2><p>Pricing is private. Testing is disabled. Record actual agreements; a readiness reference does not itself approve a pilot.</p><form data-kind="create">'+fields({seats:50})+'<button>Create draft</button></form></section>'+records.map(s=>'<section class="work-panel" data-org="'+s.id+'"><h2>'+esc(s.config.name)+'</h2>'+show('Status',s.status)+show('Dates',s.config.start+' to '+s.config.end)+show('Seats',s.config.seats)+button('View company memberships (SHIFT staff only)','members',s.id)+'<div data-members="'+s.id+'"></div><details><summary>Employer reporting access</summary><form data-kind="reporters" data-id="'+s.id+'"><label>Existing contact account IDs; clear to revoke all<input name="reporterIds" value="'+esc(s.config.reporterIds.join(','))+'"></label><button>Save reporting access</button></form></details>'+show('Programme fee',s.config.feePence===null?'Unconfirmed':'£'+(s.config.feePence/100).toFixed(2))+show('Deliverables',s.config.scope)+show('Support',s.config.support)+(s.status==='draft'?'<details><summary>Edit draft contract</summary><form data-kind="configure" data-id="'+s.id+'">'+fields(s.config)+'<button>Save draft</button></form></details>':'')+(['draft','paused'].includes(s.status)?'<form data-kind="activate" data-id="'+s.id+'"><label>Reviewed contract, DPIA and commissioning record reference<input name="privacyReference" maxlength="200" required></label><button>Activate only if commissioned</button></form>':'')+(s.status==='active'?button('Pause programme','pause',s.id)+'<form data-kind="invite" data-id="'+s.id+'"><label>Invitation expiry (UTC)<input name="expiry" type="datetime-local" required></label><button>Issue private invitation code</button></form>':'')+'<div>'+s.invites.map(i=>'<p>Invitation '+esc(i.id)+' · expires '+esc(i.expiresAt)+(i.revokedAt?' · revoked':button('Revoke code','revoke',s.id,'data-invite="'+i.id+'"'))+'</p>').join('')+'</div>'+(s.report?'<h3>Released closing report</h3>'+reportHTML(s.report):'<details><summary>Release one closing report</summary><p>Only after the pilot ends and a contextual privacy review. Thresholds alone do not establish anonymity. No later refresh or team/site filters.</p>'+(s.candidateReport?reportHTML(s.candidateReport):'<p>The candidate report becomes available after the pilot ends.</p>')+'<form data-kind="report" data-id="'+s.id+'"><label>Review record reference<input name="reviewReference" required maxlength="200"></label><label class="check"><input type="checkbox" name="safe" required>I have reviewed this cohort, billing and previous disclosures for identification risk.</label><button>Release fixed closing report</button></form></details>')+'</section>').join('');
  }else if(mode==='employer'){
   const d=await request('/v1/employer/work');if(gen!==generation)return;root.innerHTML='<p>These are fixed reports released after privacy review. Named participation, health records and test redemptions are never available here.</p>'+ (d.reports.length?d.reports.map(s=>'<section class="work-panel"><h2>'+esc(s.name)+'</h2>'+show('Pilot',s.start+' to '+s.end)+reportHTML(s.report)+'</section>').join(''):'<p>No employer reporting access has been assigned to this account.</p>');
  }else{
   const d=await request('/v1/work');if(gen!==generation)return;records=d.workplaces;
   root.innerHTML=memberHTML(records);
  }
  controls();status.textContent='';return true;
 }catch(e){if(e.name!=='AbortError')status.textContent=e.message;return false}}
 async function submit(f){
  const kind=f.dataset.kind,d=Object.fromEntries(new FormData(f));let result;
  if(kind==='join'){await request('/v1/work/join',{code:d.code.trim(),consent:d.consent==='on',noticeVersion:'work-pilot-2026-09-12-v1'});if(await load()){status.textContent='Workplace programme joined privately.';root.querySelector('.work-lead h2')?.focus()}return}
  const s=records.find(s=>s.id===f.dataset.id),body={action:kind,...(s?{id:s.id,revision:s.revision}:{})};
  if(['create','configure'].includes(kind))body.config=config(f);
  if(kind==='activate')body.privacyReference=d.privacyReference;
  if(kind==='reporters')body.reporterIds=d.reporterIds.trim()?d.reporterIds.split(',').map(Number):[];
  if(kind==='invite')body.expiresAt=new Date(d.expiry+':00Z').toISOString();
  if(kind==='report'){body.reviewReference=d.reviewReference;body.safeToRelease=d.safe==='on'}
  result=await request('/v1/hq/work',body);if(!await load())return;
  if(result.code){const box=document.createElement('div');box.className='work-panel';const note=document.createElement('p');note.textContent='Copy this private code now and distribute through the agreed general invitation. It is not stored in readable form and will clear when this tab is hidden.';const field=document.createElement('textarea');field.readOnly=true;field.value=result.code;box.append(note,field);root.prepend(box);status.textContent='Invitation created.'}else status.textContent='Saved.';
 }
 async function action(b){
  const id=b.dataset.id,act=b.dataset.action;
  if(mode==='hq'){
   const s=records.find(s=>s.id===id),result=await request('/v1/hq/work',{action:act,id,revision:s.revision,...(act==='revoke'?{inviteId:b.dataset.invite}:{}),...(act.endsWith('-member')?{userId:Number(b.dataset.user)}:{})});
   if(act==='members'){
    if(!await load())return;
    const box=root.querySelector('[data-members="'+id+'"]');if(!box)return;
    box.innerHTML='<p>SHIFT operations only. Account membership for access administration; no health answers or individual engagement.</p>'+result.members.map(m=>'<p>'+esc(m.firstName)+' · account '+esc(m.userId)+' · '+esc(m.status)+'</p><details><summary>'+ (m.status==='revoked'?'Allow this account to join again':'Revoke this workplace entitlement')+'</summary><p>Revocation removes workplace review history and blocks rejoining. The free My Timber account remains. Restoring permission requires a new voluntary code claim.</p>'+button(m.status==='revoked'?'Confirm permission to rejoin':'Confirm workplace revocation',m.status==='revoked'?'restore-member':'revoke-member',id,'data-user="'+m.userId+'"')+'</details>').join('');
    box.querySelectorAll('button[data-action]').forEach(b=>b.addEventListener('click',()=>run(()=>action(b),b)));status.textContent='Membership access recorded in the HQ audit.';return;
   }
  }
  else if(act==='review')await request('/v1/work/review',{employerId:id,week:Number(b.dataset.week),completed:b.dataset.done!=='true'});
  else if(act==='withdraw')await request('/v1/work/withdraw',{employerId:id,confirm:true});
  if(await load())status.textContent='Saved.';
 }
 const menu=document.querySelector('.menu-trigger'),drawer=document.querySelector('#site-drawer'),backdrop=document.querySelector('.drawer-backdrop');
 if(menu&&drawer){
  const setMenu=open=>{drawer.hidden=!open;if(backdrop)backdrop.hidden=!open;menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('drawer-open',open);if(open)drawer.querySelector('button')?.focus();else menu.focus()};
  menu.addEventListener('click',()=>setMenu(drawer.hidden));drawer.querySelector('.drawer-close')?.addEventListener('click',()=>setMenu(false));backdrop?.addEventListener('click',()=>setMenu(false));
  document.addEventListener('keydown',e=>{if(drawer.hidden)return;if(e.key==='Escape')setMenu(false);if(e.key==='Tab'){const items=[...drawer.querySelectorAll('button,a[href]')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
 }
 for(const [id,css]of [['toggleLargeText','work-large-text'],['toggleMotion','work-reduce-motion']]){const b=document.querySelector('#'+id);if(b){b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>b.setAttribute('aria-pressed',String(document.body.classList.toggle(css))))}}
 load();
})();`;
