// Served as an external script. No browser storage, analytics or third-party calls.
export function workClient(){
 const root=document.querySelector('#work-app'),mode=root.dataset.mode,status=document.querySelector('#work-status');
 let generation=0,controller=new AbortController();
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const request=async(path,body)=>{const gen=generation,r=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(gen!==generation)throw new DOMException('Stale response','AbortError');if(r.status===401||r.status===403){clear();status.textContent=data.error||'Sign in again.';throw new Error(data.error)}if(!r.ok)throw new Error(data.error||'Request failed.');return data};
 const clear=()=>{generation++;controller.abort();controller=new AbortController();records=[];root.replaceChildren();status.textContent='Your private view is closed.'};
 addEventListener('pagehide',clear);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')clear();else load()});addEventListener('pageshow',e=>{if(e.persisted)load()});
 const button=(text,act,id,extra='')=>'<button type="button" data-action="'+act+'" data-id="'+esc(id)+'" '+extra+'>'+text+'</button>';
 const show=(name,value)=>'<p><strong>'+name+':</strong> '+esc(value)+'</p>';
 const reportHTML=r=>r.status?show('Report',r.reason||r.status):'<p>Reporting period: '+esc(r.programmeStart)+' to '+esc(r.programmeEnd)+'</p><table><thead><tr><th>Measure</th><th>Released result</th></tr></thead><tbody>'+[['Invitations',r.invitations],['Activations',r.activations],['Engagement',r.engagement],['Completion',r.completion],['Wellbeing',r.wellbeing]].map(([label,v])=>'<tr><th>'+label+'</th><td>'+esc(v.status==='reported'?v.count+' ('+v.precision+')':v.reason)+'</td></tr>').join('')+'</tbody></table><p>Engagement means at least one weekly review marked complete. Completion means all twelve. These are participation measures, not clinical outcomes.</p>';
 const controls=()=>{root.querySelectorAll('form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();run(()=>submit(f))}));root.querySelectorAll('button[data-action]').forEach(b=>b.addEventListener('click',()=>run(()=>action(b))));};
 let records=[];
 const run=async(fn)=>{status.textContent='Working…';root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){if(e.name!=='AbortError')status.textContent=e.message}finally{root.querySelectorAll('button').forEach(b=>b.disabled=false)}};
 const fields=c=>'<div class="work-grid">'+[['name','Organisation','text',160],['start','Shared start (UTC date)','date'],['end','End date (exclusive; 12 weeks later)','date'],['seats','Pilot seats (1–150)','number']].map(([k,l,t,max])=>'<label>'+l+'<input name="'+k+'" type="'+t+'" '+(max?'maxlength="'+max+'"':'')+' value="'+esc(c[k]??'')+'" required></label>').join('')+'<label>Agreed programme fee (pence; blank if unconfirmed)<input type="number" min="0" name="feePence" value="'+esc(c.feePence??'')+'"></label><label>Proposed testing allowance (pence; does not enable tests)<input type="number" min="0" name="testingAllowancePence" value="'+esc(c.testingAllowancePence??'')+'"></label><label>Employer contact account IDs (comma separated)<input name="reporterIds" value="'+esc((c.reporterIds??[]).join(','))+'"></label></div><label>Programme deliverables<textarea name="scope" maxlength="1600" required>'+esc(c.scope??'')+'</textarea></label><label>Human support limits and response times<textarea name="support" maxlength="600" required>'+esc(c.support??'')+'</textarea></label>';
 const config=f=>{const d=Object.fromEntries(new FormData(f));return {name:d.name,start:d.start,end:d.end,seats:Number(d.seats),feePence:d.feePence===''?null:Number(d.feePence),testingAllowancePence:d.testingAllowancePence===''?null:Number(d.testingAllowancePence),reporterIds:d.reporterIds.trim()?d.reporterIds.split(',').map(Number):[],scope:d.scope,support:d.support}};
 async function load(){if(document.visibilityState==='hidden')return false;generation++;controller.abort();controller=new AbortController();const gen=generation;try{
  if(mode==='hq'){
   const d=await request('/v1/hq/work');if(gen!==generation)return;records=d.employers;
   root.innerHTML='<section class="work-panel"><h2>Create a draft pilot</h2><p>Pricing is private. Testing is disabled. Record actual agreements; a readiness reference does not itself approve a pilot.</p><form data-kind="create">'+fields({seats:50})+'<button>Create draft</button></form></section>'+records.map(s=>'<section class="work-panel" data-org="'+s.id+'"><h2>'+esc(s.config.name)+'</h2>'+show('Status',s.status)+show('Dates',s.config.start+' to '+s.config.end)+show('Seats',s.config.seats)+button('View company memberships (SHIFT staff only)','members',s.id)+'<div data-members="'+s.id+'"></div><details><summary>Employer reporting access</summary><form data-kind="reporters" data-id="'+s.id+'"><label>Existing contact account IDs; clear to revoke all<input name="reporterIds" value="'+esc(s.config.reporterIds.join(','))+'"></label><button>Save reporting access</button></form></details>'+show('Programme fee',s.config.feePence===null?'Unconfirmed':'£'+(s.config.feePence/100).toFixed(2))+show('Deliverables',s.config.scope)+show('Support',s.config.support)+(s.status==='draft'?'<details><summary>Edit draft contract</summary><form data-kind="configure" data-id="'+s.id+'">'+fields(s.config)+'<button>Save draft</button></form></details>':'')+(['draft','paused'].includes(s.status)?'<form data-kind="activate" data-id="'+s.id+'"><label>Reviewed contract, DPIA and commissioning record reference<input name="privacyReference" maxlength="200" required></label><button>Activate only if commissioned</button></form>':'')+(s.status==='active'?button('Pause programme','pause',s.id)+'<form data-kind="invite" data-id="'+s.id+'"><label>Invitation expiry (UTC)<input name="expiry" type="datetime-local" required></label><button>Issue private invitation code</button></form>':'')+'<div>'+s.invites.map(i=>'<p>Invitation '+esc(i.id)+' · expires '+esc(i.expiresAt)+(i.revokedAt?' · revoked':button('Revoke code','revoke',s.id,'data-invite="'+i.id+'"'))+'</p>').join('')+'</div>'+(s.report?'<h3>Released closing report</h3>'+reportHTML(s.report):'<details><summary>Release one closing report</summary><p>Only after the pilot ends and a contextual privacy review. Thresholds alone do not establish anonymity. No later refresh or team/site filters.</p>'+(s.candidateReport?reportHTML(s.candidateReport):'<p>The candidate report becomes available after the pilot ends.</p>')+'<form data-kind="report" data-id="'+s.id+'"><label>Review record reference<input name="reviewReference" required maxlength="200"></label><label class="check"><input type="checkbox" name="safe" required>I have reviewed this cohort, billing and previous disclosures for identification risk.</label><button>Release fixed closing report</button></form></details>')+'</section>').join('');
  }else if(mode==='employer'){
   const d=await request('/v1/employer/work');if(gen!==generation)return;root.innerHTML='<p>These are fixed reports released after privacy review. Named participation, health records and test redemptions are never available here.</p>'+ (d.reports.length?d.reports.map(s=>'<section class="work-panel"><h2>'+esc(s.name)+'</h2>'+show('Pilot',s.start+' to '+s.end)+reportHTML(s.report)+'</section>').join(''):'<p>No employer reporting access has been assigned to this account.</p>');
  }else{
   const d=await request('/v1/work');if(gen!==generation)return;records=d.workplaces;
   root.innerHTML='<section class="work-panel"><h2>Join your workplace programme</h2><p>My Timber is free. Your employer funds the workplace programme. Your employer cannot open your account, view named participation, personal answers or progress. Reports may be withheld for small groups. Joining is optional; declining a blood test does not affect programme access. Testing is not available.</p><p>Authorised SHIFT staff can see which accounts belong to each company to administer access; employers cannot use this view. We store your account link, joining date, notice version and which weekly reviews you mark complete. You can withdraw here and remove that link and review history; your free account remains. Previously released anonymous reports cannot identify and remove a person. Read the <a href="/privacy">SHIFT privacy notice</a>. Do not enter health information in invitation fields.</p><p><a href="/v1/work/export" download>Download my workplace data</a></p><form data-kind="join"><label>Private invitation code<input name="code" autocomplete="off" spellcheck="false" required maxlength="101"></label><label class="check"><input type="checkbox" name="consent" required>I choose to join and have read the workplace information above.</label><button>Join privately</button></form></section>'+records.map(s=>'<section class="work-panel"><h2>'+esc(s.name)+'</h2>'+show('Shared start',s.start)+show('Programme ends',s.end)+show('Current week',s.week)+show('Access',s.active?'Active':'Paused, not started or ended')+show('Deliverables',s.scope)+show('Support limits',s.support)+(s.week===0?'<p>Your place is confirmed. Everyone starts together on '+esc(s.start)+'. Weekly reviews open then.</p>':'')+'<p>Short actions, private self-check-ins and a weekly review you work through yourself.</p><p><a href="/member/journey">My Journey</a> · <a href="/member/grub">SHIFT Grub</a> · <a href="/member/fit">SHIFT Fit</a> · <a href="/member/check-in">My check-in</a></p><ol class="work-weeks">'+Array.from({length:12},(_,i)=>'<li>Week '+(i+1)+' '+(s.completedWeeks.includes(i+1)?'review complete':'')+(s.active&&i<s.week?button(s.completedWeeks.includes(i+1)?'Mark incomplete':'Mark review complete','review',s.employerId,'data-week="'+(i+1)+'" data-done="'+s.completedWeeks.includes(i+1)+'"'):'')+'</li>').join('')+'</ol><p>'+esc(s.testing.message)+'</p><details><summary>Leave this workplace programme</summary><p>This removes your workplace link and review-completion history. Your free My Timber account and its existing tools remain.</p>'+button('Confirm withdrawal','withdraw',s.employerId)+'</details></section>').join('');
  }
  controls();status.textContent='';return true;
 }catch(e){if(e.name!=='AbortError')status.textContent=e.message;return false}}
 async function submit(f){
  const kind=f.dataset.kind,d=Object.fromEntries(new FormData(f));let result;
  if(kind==='join'){await request('/v1/work/join',{code:d.code.trim(),consent:d.consent==='on',noticeVersion:'work-pilot-2026-09-12-v1'});if(await load())status.textContent='Workplace programme joined privately.';return}
  const s=records.find(s=>s.id===f.dataset.id),body={action:kind,...(s?{id:s.id,revision:s.revision}:{})};
  if(['create','configure'].includes(kind))body.config=config(f);
  if(kind==='activate')body.privacyReference=d.privacyReference;
  if(kind==='reporters')body.reporterIds=d.reporterIds.trim()?d.reporterIds.split(',').map(Number):[];
  if(kind==='invite')body.expiresAt=new Date(d.expiry+':00Z').toISOString();
  if(kind==='report'){body.reviewReference=d.reviewReference;body.safeToRelease=d.safe==='on'}
  result=await request('/v1/hq/work',body);if(!await load())return;
  if(result.code){const box=document.createElement('div');box.className='work-panel';const note=document.createElement('p');note.textContent='Copy this private code now and distribute through the agreed general invitation. It is not stored in readable form and will clear when this tab is hidden.';const field=document.createElement('textarea');field.readOnly=true;field.value=result.code;box.append(note,field);root.prepend(box);status.textContent='Invitation created.'}else status.textContent='Saved.';
 }
 async function action(b){
  const id=b.dataset.id,act=b.dataset.action;
  if(mode==='hq'){
   const s=records.find(s=>s.id===id),result=await request('/v1/hq/work',{action:act,id,revision:s.revision,...(act==='revoke'?{inviteId:b.dataset.invite}:{}),...(act.endsWith('-member')?{userId:Number(b.dataset.user)}:{})});
   if(act==='members'){
    if(!await load())return;
    const box=root.querySelector('[data-members="'+id+'"]');if(!box)return;
    box.innerHTML='<p>SHIFT operations only. Account membership for access administration; no health answers or individual engagement.</p>'+result.members.map(m=>'<p>'+esc(m.firstName)+' · account '+esc(m.userId)+' · '+esc(m.status)+'</p><details><summary>'+ (m.status==='revoked'?'Allow this account to join again':'Revoke this workplace entitlement')+'</summary><p>Revocation removes workplace review history and blocks rejoining. The free My Timber account remains. Restoring permission requires a new voluntary code claim.</p>'+button(m.status==='revoked'?'Confirm permission to rejoin':'Confirm workplace revocation',m.status==='revoked'?'restore-member':'revoke-member',id,'data-user="'+m.userId+'"')+'</details>').join('');
    box.querySelectorAll('button[data-action]').forEach(b=>b.addEventListener('click',()=>run(()=>action(b))));status.textContent='Membership access recorded in the HQ audit.';return;
   }
  }
  else if(act==='review')await request('/v1/work/review',{employerId:id,week:Number(b.dataset.week),completed:b.dataset.done!=='true'});
  else if(act==='withdraw')await request('/v1/work/withdraw',{employerId:id,confirm:true});
  if(await load())status.textContent='Saved.';
 }
 const menu=document.querySelector('.menu-trigger'),drawer=document.querySelector('#site-drawer');if(menu&&drawer){menu.addEventListener('click',()=>{drawer.hidden=!drawer.hidden;menu.setAttribute('aria-expanded',String(!drawer.hidden))});drawer.querySelector('.drawer-close')?.addEventListener('click',()=>{drawer.hidden=true;menu.setAttribute('aria-expanded','false')})}
 load();
}
