import {programmeHTML} from '../programme/screen.mjs';
import {workClientSource} from './client.mjs';
export const workCSS=`html:has(body.work-reduce-motion){scroll-behavior:auto!important}.work-reduce-motion *{animation:none!important;transition:none!important;scroll-behavior:auto!important}.work-large-text .work{font-size:20px!important}.work-large-text .work button{font-size:18px!important}main.work h1{font-size:clamp(32px,4vw,48px);max-width:none;margin:0 0 20px}main.work h2{font-size:clamp(24px,3vw,32px)}main.work .work-header-links{display:flex!important;grid-template-columns:none!important;gap:12px 22px!important;margin:0 0 22px!important}main.work .work-header-links a{width:auto!important;min-height:44px;display:inline-flex;align-items:center}main.work .work-panel{padding:22px}main.work table{display:table;table-layout:fixed;width:100%}main.work th,main.work td{overflow-wrap:anywhere}main.work p{max-width:85ch}.work{max-width:1120px;margin:auto;padding:24px;color:#050505;background:#e7e3da;font:16px/1.6 Arial,sans-serif}.work-panel{padding:22px;border:1px solid #707762;margin:20px 0}.work h1,.work h2,.work h3{color:#050505}.work-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.work label{display:block;margin:12px 0;font-weight:700}.work input[type=checkbox]{flex:0 0 20px;width:20px;min-height:20px;height:20px;margin:3px 0}.work input:not([type=checkbox]),.work textarea{box-sizing:border-box;display:block;width:100%;min-height:46px;padding:10px;background:#e7e3da;color:#050505;border:1px solid #050505;font:inherit}.work textarea{min-height:90px}.work .check{display:flex;align-items:flex-start;gap:10px}.work button{min-height:44px;padding:10px 18px;margin:8px 6px 8px 0;color:#e7e3da;background:#050505;border:2px solid #050505;font:700 15px/1.4 Arial;cursor:pointer}.work button:disabled{opacity:.55}.work a{color:#050505;text-decoration:underline}.work table{width:100%;border-collapse:collapse}.work th,.work td{text-align:left;vertical-align:top;border-bottom:1px solid #707762;padding:10px}.work pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px}.work :focus-visible{outline:3px solid #707762;outline-offset:3px}.work-weeks{padding-left:22px}.work details{margin-top:20px}.work summary{cursor:pointer;font-weight:700}.work #work-status{min-height:1.6em}.work-header-links{display:flex;flex-wrap:wrap;gap:18px}@media(max-width:560px){.work{padding:16px}.work-panel{padding:16px}.work-grid{grid-template-columns:1fr}}`;
export const workJS=workClientSource;
export function workHTML(mode){
 const title=mode==='hq'?'SHIFT for Work · HQ':mode==='employer'?'Your employer reports':'Your workplace programme';
 const main=`<main class="work"><h1>${title}</h1><nav class="work-header-links" aria-label="Workplace navigation"><a href="/member/dashboard">My Timber</a><a href="/member/work">My workplace programme</a>${mode==='hq'?'<a href="/hq/catalogue-controls">HQ catalogue</a>':''}${mode==='employer'?'<a href="/employer/work">Employer reports</a>':''}</nav><p id="work-status" role="status" aria-live="polite"></p><div id="work-app" data-mode="${mode}"><p>Opening your private workspace…</p></div></main>`;
 return programmeHTML.replace(/<title>.*?<\/title>/,`<title>${title}</title>`).replace('/assets/programme-v1/programme.css','/assets/work/work.css').replace('/assets/programme-v1/programme.mjs','/assets/work/work.mjs').replace(/<main\b.*?<\/main>/s,main);
}
