import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyLifeBack,applyLifeBackOperation,lifeBackRoutes} from '../life-back-routes.mjs';
import {lifeBackState,summary,dailyTrend,score} from '../life-back/model.mjs';
import {applyGrubOperation,emptyGrub} from '../grub-workspace.mjs';
import {connectedDay} from '../journey-context.mjs';
import {memberExperienceRoutes} from '../entry.mjs';
const ratings={energy:72,sleep:64,confidence:70,movement:66,clothes:60,personal:75};
const add=(s,id='test-operation-123456')=>applyLifeBackOperation(s,{action:'checkin',operationId:id,goalId:s.goalId,ratings,win:'A useful walk'},'2026-09-15T12:00:00Z');
test('new members have no fabricated history or score; all six ratings required',()=>{assert.equal(summary(lifeBackState()).score,null);assert.equal(score({...ratings,energy:null}),null);assert.throws(()=>applyLifeBackOperation(emptyLifeBack(),{action:'checkin',operationId:'test-operation-123456',goalId:'personal-start',ratings:{...ratings,energy:null}}),/six areas/)});
test('every timestamped entry is retained; repeated requests do not duplicate',()=>{const one=add(emptyLifeBack()),two=add(one,'test-operation-987654');assert.equal(two.entries.length,2);assert.deepEqual(add(two),two);assert.equal(summary(lifeBackState(two)).score,68);assert.equal(dailyTrend(two.entries,two.goalId)[0].count,2)});
test('new goal starts an honest baseline; stale goal writes are rejected',()=>{const old=add(emptyLifeBack()),next=applyLifeBackOperation(old,{action:'goal',operationId:'new-goal-operation-1234',revision:old.revision,goal:'Walk the dog'});assert.equal(next.entries.length,1);assert.equal(summary(lifeBackState(next)).score,null);assert.throws(()=>applyLifeBackOperation(next,{action:'checkin',operationId:'test-operation-22222',goalId:old.goalId,ratings}),/goal changed/)});
test('separate daily averages follow UK dates and missing days are absent',()=>{let s=emptyLifeBack();for(const [i,at]of ['2026-09-14T22:30:00Z','2026-09-14T23:30:00Z','2026-09-17T10:00:00Z'].entries())s=applyLifeBackOperation(s,{action:'checkin',operationId:'daily-operation-123'+i,goalId:s.goalId,ratings},at);assert.deepEqual(dailyTrend(s.entries,s.goalId).map(x=>x.day),['2026-09-14','2026-09-15','2026-09-17'])});
test('food preferences and relative plan days do not masquerade as today’s confirmed meal',async()=>{const db={prepare:()=>({bind:()=>({first:async()=>null})})};const prefs={grubV2:{week:[{day:1}],learning:{yay:['r']}}};assert.equal((await connectedDay(db,1,prefs,'2026-09-15')).meal,null);const food=applyGrubOperation(emptyGrub(),{action:'choose-today',operationId:'food-operation-1234',revision:0,recipeId:'r'},[{id:'r',name:'Reviewed meal',minutes:10}],{date:'2026-09-15',at:'2026-09-15T12:00:00Z'});assert.equal((await connectedDay(db,1,{grubV2:food},'2026-09-15')).meal.name,'Reviewed meal');assert.equal((await connectedDay(db,1,{grubV2:food},'2026-09-16')).meal,null)});
test('Today counts actual done/skipped entries without declaring a session complete',async()=>{const db={prepare:()=>({bind:()=>({first:async()=>null})})};const out=await connectedDay(db,1,{fitJourney:{entries:{a:{status:'done',recordedOn:'2026-09-15'},b:{status:'skipped',recordedOn:'2026-09-15'}}}},'2026-09-15');assert.deepEqual(out.movement,{done:1,skipped:1});assert.equal(out.movement.completed,undefined)});
test('Life Back server rejects cross-origin writes and requires authentication',async()=>{const env={MEMBER_EXPERIENCE_V1_ENABLED:'true'};assert.equal((await lifeBackRoutes(new Request('https://stage/v1/life-back'),env)).status,401);assert.equal((await lifeBackRoutes(new Request('https://stage/v1/life-back',{method:'POST',headers:{Origin:'https://foreign'}}),env)).status,403)});
test('approved presentation exposes no sample history and uses the dedicated API',async()=>{const env={MEMBER_EXPERIENCE_V1_ENABLED:'true'},html=await memberExperienceRoutes(new Request('https://stage/member/life-back'),env).text(),client=await memberExperienceRoutes(new Request('https://stage/assets/member-experience/life-back/client.mjs'),env).text();assert.doesNotMatch(html,/92\.4|Walked my son|Sample member/);assert.match(client,/\/v1\/life-back/);assert.doesNotMatch(client,/saveMemberState|localStorage|sessionStorage/)});

test('editing an older Fit entry does not move it into today; bad old dates are ignored',async()=>{const db={prepare:()=>({bind:()=>({first:async()=>null})})};const out=await connectedDay(db,1,{fitJourney:{entries:{a:{status:'done',recordedOn:'2026-09-14',updatedAt:'2026-09-15T12:00:00Z'},b:{status:'done',updatedAt:'invalid'}}}},'2026-09-15');assert.deepEqual(out.movement,{done:0,skipped:0})});
