import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fixture} from '../../health-passport/fixture.mjs';
import {memberDetailsRoute,appendMemberDetailsExport,validateMemberDetails} from '../member-details-routes.mjs';
import {memberExperienceEntry,memberExperienceRoutes} from '../entry.mjs';
import {memberDetailsRuntime,withMemberDetails,memberDetailsStyles} from '../member-details.mjs';
import {searchGpPractices,memberDetailsLookupRoute} from '../member-details-lookups.mjs';
import vm from 'node:vm';
const origin='https://shiftsometimber.co.uk';
const url=origin+'/v1/member/details';
const request=(method='GET',body,id=1,headers={})=>new Request(url,{method,headers:{...(id?{Cookie:'sst_session=test-only-member-'+id}:{}),Origin:origin,'Content-Type':'application/json',...headers},...(body!==undefined?{body:JSON.stringify(body)}:{})});
function setup(t,{schema=true}={}){
 const f=fixture({seed:false});t.after(()=>f.close());
 f.db.exec('ALTER TABLE users ADD COLUMN phone TEXT;ALTER TABLE users ADD COLUMN date_of_birth TEXT;ALTER TABLE users ADD COLUMN postcode TEXT;ALTER TABLE users ADD COLUMN updated_at TEXT;CREATE TABLE member_status(user_id INTEGER PRIMARY KEY,last_activity_at TEXT,updated_at TEXT);INSERT INTO member_status(user_id) VALUES(1),(2);CREATE TABLE orders(id INTEGER PRIMARY KEY,user_id INTEGER,address TEXT);INSERT INTO orders(user_id,address) VALUES(1,\'Old historical order address\');');
 if(schema)f.db.exec(readFileSync(new URL('../member-details.sql',import.meta.url),'utf8'));
 return f;
}
const details=()=>({firstName:'Fictional',lastName:'Reviewer',phone:'07700 900123',dateOfBirth:'1982-01-12',postcode:'SK10 1AA',address1:'1 Fictional Close',address2:'',town:'Macclesfield',county:'Cheshire',gpPractice:'Test practice',gpPostcode:'SK10 1AA',gpCode:''});
const get=async f=>{const r=await memberDetailsRoute(request(),f.env);assert.equal(r.status,200);return r.json();};
const change=async(f,values=details(),revision)=>{const before=revision||((await get(f)).revision),body={details:values,revision:before,operationId:crypto.randomUUID()},response=await memberDetailsRoute(request('PATCH',body),f.env);return{body,response};};
const stored=f=>Object.fromEntries(['users','member_account_details','member_state','consents','orders','audit_log'].map(t=>[t,f.db.prepare('SELECT * FROM '+t).all()]));

test('new Details form is actually mounted in Settings and aliases without replacing any old controls',async()=>{
 const source='<html><head></head><body><nav class="sst-member-tabs"></nav><main><h1>Settings</h1><form id="oldPreferences">OLD</form><section id="oldPrivacy">PRIVACY</section></main></body></html>';
 for(const path of ['/member/settings','/member/settings.html']){const r=await memberExperienceEntry(new Request(origin+path),{MEMBER_EXPERIENCE_V1_ENABLED:'true'},new Response(source,{headers:{'Content-Type':'text/html'}}));const html=await r.text();assert.equal((html.match(/id="memberDetailsPanel"/g)||[]).length,1);assert(html.includes('id="oldPreferences"'));assert(html.includes('id="oldPrivacy"'));assert(html.includes('/member/settings#memberDetailsPanel'));assert(html.includes('memberDetailsFields" disabled'));assert(html.includes('memberDetailsSave" type="submit" disabled'));}
 assert.equal(withMemberDetails(withMemberDetails(source)),withMemberDetails(source));
 new vm.Script(memberDetailsRuntime);assert(!memberDetailsRuntime.includes("'/v1/member-state'"));assert(!memberDetailsStyles.includes('#fff'));assert(!memberDetailsRuntime.includes('localStorage'));
});
test('Details assets use existing private headers and supported HEAD response',async()=>{for(const path of ['member-details.mjs','member-details.css']){for(const method of ['GET','HEAD']){const r=memberExperienceRoutes(new Request(origin+'/assets/member-experience/'+path,{method}),{MEMBER_EXPERIENCE_V1_ENABLED:'true'});assert.equal(r.status,200);assert.match(r.headers.get('Cache-Control'),/no-store/);assert.match(r.headers.get('X-Robots-Tag'),/noindex/);if(method==='HEAD')assert.equal(await r.text(),'');}}});
test('a real change of address, name and phone is atomic, read back, and isolated from orders/preferences/consent',async t=>{
 const f=setup(t),before=stored(f),initial=await get(f);assert.equal(initial.details.firstName,'Alex');assert.equal(initial.details.address1,'');assert.equal(initial.addressLookupConfigured,false);
 const {response}=await change(f);assert.equal(response.status,200);const saved=await response.json();assert.equal(saved.details.address1,'1 Fictional Close');assert.notEqual(saved.revision,initial.revision);assert.equal((await get(f)).details.phone,'07700 900123');
 const after=stored(f);for(const k of ['member_state','consents','orders'])assert.deepEqual(after[k],before[k]);assert.deepEqual(after.users.find(u=>u.id===2),before.users.find(u=>u.id===2));assert.equal(after.audit_log.length,1);assert.equal(after.audit_log[0].metadata,'{}');assert(!JSON.stringify(after.member_state).includes('Fictional Close'));
 const move=details();move.address1='2 Fictional Lane';const x=await change(f,move);assert.equal(x.response.status,200);assert.equal((await get(f)).details.address1,move.address1);assert.equal(f.db.prepare('SELECT address FROM orders').get().address,'Old historical order address');
});
test('clearing optional phone, DOB and address fields really clears them instead of retaining COALESCE values',async t=>{const f=setup(t);assert.equal((await change(f)).response.status,200);const d=details();for(const k of ['phone','dateOfBirth','postcode','address1','address2','town','county','gpPractice','gpPostcode','gpCode'])d[k]='';assert.equal((await change(f,d)).response.status,200);const saved=await get(f);for(const k of ['phone','dateOfBirth','postcode','address1','gpPractice'])assert.equal(saved.details[k],'');});
test('a stale form cannot overwrite newer account details; it receives a conflict',async t=>{const f=setup(t),rev=(await get(f)).revision;assert.equal((await change(f)).response.status,200);const before=stored(f);const d=details();d.address1='Rejected stale address';assert.equal((await change(f,d,rev)).response.status,409);assert.deepEqual(stored(f),before);});
test('profile edited after validation but before batch makes the whole stale save a no-op',async t=>{
 const f=setup(t),batch=f.DB.batch;let intercepted=false;f.DB.batch=async stmts=>{if(!intercepted){intercepted=true;f.db.prepare('UPDATE users SET phone=? WHERE id=1').run('07700 900555');}return batch(stmts);};
 const r=await change(f);assert.equal(r.response.status,409);assert.equal(f.db.prepare('SELECT phone FROM users WHERE id=1').get().phone,'07700 900555');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM member_account_details').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM audit_log').get().n,0);
});
test('failure inside D1 batch rolls back address and profile together; deliberate retry then succeeds',async t=>{
 const f=setup(t);f.db.exec("CREATE TRIGGER fail_contact BEFORE UPDATE ON users BEGIN SELECT RAISE(ABORT,'injected failure');END;");const before=stored(f),{body,response}=await change(f);assert.equal(response.status,503);assert.deepEqual(stored(f),before);f.db.exec('DROP TRIGGER fail_contact');assert.equal((await memberDetailsRoute(request('PATCH',body),f.env)).status,200);
});
test('same operation is idempotent; altered payload with the same identity is refused',async t=>{
 const f=setup(t),{body,response}=await change(f);assert.equal(response.status,200);const before=stored(f);assert.equal((await memberDetailsRoute(request('PATCH',body),f.env)).status,200);assert.deepEqual(stored(f),before);body.details.phone='07700 900999';assert.equal((await memberDetailsRoute(request('PATCH',body),f.env)).status,409);assert.deepEqual(stored(f),before);
});
test('simultaneous identical retry cannot duplicate the audit or alter a winning save',async t=>{
 const f=setup(t),revision=(await get(f)).revision,body={details:details(),revision,operationId:crypto.randomUUID()};const responses=await Promise.all([memberDetailsRoute(request('PATCH',body),f.env),memberDetailsRoute(request('PATCH',body),f.env)]);assert(responses.some(r=>r.status===200));assert(responses.every(r=>[200,409].includes(r.status)));assert.equal(f.db.prepare('SELECT count(*) n FROM audit_log').get().n,1);assert.equal(f.db.prepare('SELECT revision FROM member_account_details').get().revision,1);
});
test('unrelated settings saved concurrently are retained exactly',async t=>{const f=setup(t),batch=f.DB.batch;f.DB.batch=async s=>{f.db.prepare('UPDATE member_state SET preferences=? WHERE user_id=1').run('{"newPreference":"keep","grubV2":{"newMeal":"keep"}}');return batch(s);};assert.equal((await change(f)).response.status,200);assert.equal(f.db.prepare('SELECT preferences FROM member_state WHERE user_id=1').get().preferences,'{"newPreference":"keep","grubV2":{"newMeal":"keep"}}');});
test('anonymous, revoked sessions, foreign origins, malformed and oversized requests fail closed',async t=>{const f=setup(t);assert.equal((await memberDetailsRoute(request('GET',undefined,0),f.env)).status,401);const rev=(await get(f)).revision,body={details:details(),revision:rev,operationId:crypto.randomUUID()};assert.equal((await memberDetailsRoute(request('PATCH',body,1,{Origin:'https://evil.invalid'}),f.env)).status,403);assert.equal((await memberDetailsRoute(request('PATCH',body,1,{'Content-Type':'text/plain'}),f.env)).status,415);assert.equal((await memberDetailsRoute(request('PATCH',{...body,accountId:2}),f.env)).status,400);const big={...body,details:{...details(),address2:'x'.repeat(9000)}};assert.equal((await memberDetailsRoute(request('PATCH',big),f.env)).status,413);f.db.prepare('UPDATE user_sessions SET revoked_at=? WHERE user_id=1').run(new Date().toISOString());assert.equal((await memberDetailsRoute(request(),f.env)).status,401);});
test('server validates real calendar dates, complete addresses, phone and safe text; postcode normalises',()=>{const d=details();d.postcode='sk101aa';assert.equal(validateMemberDetails(d).postcode,'SK10 1AA');for(const [k,v]of [['dateOfBirth','2026-02-30'],['dateOfBirth','2999-01-01'],['phone','not-a-phone'],['postcode','INVALID'],['firstName',''],['address1',''],['gpCode','<script>'],['address2','x'.repeat(121)],['town','A\u0000B']])assert.throws(()=>validateMemberDetails({...details(),[k]:v}));assert.throws(()=>validateMemberDetails({...details(),email:'hijack@example.invalid'}));});
test('another account cannot read or update the first account through identifiers',async t=>{const f=setup(t);assert.equal((await change(f)).response.status,200);const r=await memberDetailsRoute(new Request(url+'?userId=1',{headers:{Cookie:'sst_session=test-only-member-2'}}),f.env);const b=await r.json();assert.equal(b.details.firstName,'Sam');assert.equal(b.details.address1,'');assert.equal((await memberDetailsRoute(request('PATCH',{details:details(),revision:b.revision,operationId:crypto.randomUUID(),userId:1},2),f.env)).status,400);});
test('missing additive schema refuses edits rather than mutating a production schema automatically',async t=>{const f=setup(t,{schema:false});assert.equal((await memberDetailsRoute(request(),f.env)).status,503);assert.equal(f.db.prepare("SELECT name FROM sqlite_master WHERE name='member_account_details'").get(),undefined);});
test('account export includes only this account contact record and preserves existing export; erasure cascade has no orphan contact',async t=>{
 const f=setup(t);assert.equal((await change(f)).response.status,200);const original=()=>Response.json({existing:{keep:true}},{headers:{'Content-Disposition':'attachment; filename="account.json"'}});const response=await appendMemberDetailsExport(new Request(origin+'/v1/privacy/export',{method:'POST',headers:{Cookie:'sst_session=test-only-member-1',Origin:origin}}),f.env,original());const data=await response.json();assert(data.existing.keep);assert.equal(data.memberAccountDetails.address1,'1 Fictional Close');assert.equal(response.headers.get('Content-Disposition'),'attachment; filename="account.json"');const other=await appendMemberDetailsExport(new Request(origin+'/v1/privacy/export',{method:'POST',headers:{Cookie:'sst_session=test-only-member-2',Origin:origin}}),f.env,original());assert.equal((await other.json()).memberAccountDetails,null);f.db.prepare('DELETE FROM users WHERE id=1').run();assert.equal(f.db.prepare('SELECT count(*) n FROM member_account_details').get().n,0);
});
test('NHS search uses exact fixed endpoint and active GP filters, no member identity, bounded results',async()=>{
 let called;const result=await searchGpPractices('Blackdown',async(url,opts)=>{called={url,opts};return Response.json({Organisations:[{Name:'BLACKDOWN PRACTICE',OrgId:'L83044',Status:'Active',PrimaryRoleId:'RO177',PostCode:'EX15 3SF'},{Name:'Retired practice',OrgId:'A12345',Status:'Inactive',PrimaryRoleId:'RO177',PostCode:'SW1A 1AA'}]});});const u=new URL(called.url);assert.equal(u.origin,'https://directory.spineservices.nhs.uk');assert.equal(u.searchParams.get('NonPrimaryRoleId'),'RO76');assert.equal(called.opts.redirect,'manual');assert.equal(result.practices.length,1);assert.equal(result.practices[0].code,'L83044');assert.equal(called.opts.headers.Cookie,undefined);
});
test('GP provider failures and redirects do not fabricate practice suggestions',async()=>{await assert.rejects(searchGpPractices('Blackdown',async()=>new Response(null,{status:302,headers:{Location:'https://evil.invalid'}})));await assert.rejects(searchGpPractices('Blackdown',async()=>Response.json({unexpected:[]})));});
test('public and unrelated routes are untouched by the new API modules',async()=>{const env={};assert.equal(await memberDetailsRoute(new Request(origin+'/'),env),null);assert.equal(await memberDetailsLookupRoute(new Request(origin+'/v1/profile'),env),null);const response=new Response('unchanged');assert.equal(await appendMemberDetailsExport(new Request(origin+'/'),env,response),response);});
