import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {pbkdf2Sync} from 'node:crypto';import vm from 'node:vm';
import {fixture} from '../../health-passport/fixture.mjs';import {memberEmailChangeRoute,verifyEmailChangePassword,renderEmailChangeMessage} from '../member-email-change.mjs';import {emailChangeMarkup,emailChangeRuntime,emailConfirmationRuntime} from '../member-email-client.mjs';import {authenticateMember} from '../../member-state-fast-v1.js';import {handleAuthRecovery} from '../../auth-recovery-v1.js';
const origin='https://shiftsometimber.co.uk',password='Fictional-Password-Only-123!',salt=Buffer.alloc(16,1),stored='pbkdf2$100000$'+salt.toString('base64url')+'$'+pbkdf2Sync(password,salt,100000,32,'sha256').toString('base64url');
function req(path='',method='GET',body,id=1,headers={}){return new Request(origin+'/v1/member/details/email-change'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(id?{Cookie:'sst_session=test-only-member-'+id}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});}
function setup(t){const f=fixture({seed:false});t.after(()=>f.close());f.db.exec("ALTER TABLE users ADD COLUMN updated_at TEXT;CREATE UNIQUE INDEX users_email_unique_ci ON users(lower(email));CREATE TABLE user_auth(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,password_hash TEXT,email_verified INTEGER,email_verified_at TEXT,updated_at TEXT,locked_until TEXT,failed_login_attempts INTEGER DEFAULT 0);CREATE TABLE auth_tokens(id INTEGER PRIMARY KEY,user_id INTEGER,token_type TEXT,token_hash TEXT,expires_at TEXT,used_at TEXT);CREATE TABLE orders(id INTEGER PRIMARY KEY,user_id INTEGER,email TEXT,address TEXT);INSERT INTO orders VALUES(1,1,'fictional-1@example.invalid','Keep this historical address');");f.db.exec(readFileSync(new URL('../member-email-change.sql',import.meta.url),'utf8'));for(const id of [1,2])f.db.prepare('INSERT INTO user_auth(user_id,password_hash) VALUES(?,?)').run(id,stored);f.db.prepare("INSERT INTO auth_tokens(user_id,token_type,token_hash,expires_at) VALUES(1,'password_reset','old-reset-hash','2099-01-01')").run();f.mail=[];f.env.MEMBER_EMAIL_CHANGE_ENABLED='true';f.env.EMAIL={send:async m=>{f.mail.push(m);return {id:'fictional-provider-acceptance-only'};}};return f;}
const change=()=>({currentPassword:password,newEmail:'new-address@example.invalid',confirmEmail:'new-address@example.invalid',operationId:crypto.randomUUID()});
async function start(f,body=change()){const response=await memberEmailChangeRoute(req('','POST',body),f.env);return {response,body,data:await response.json()};}
const tokens=f=>{const links=f.mail.slice(0,2).flatMap(m=>[...m.text.matchAll(/https:\/\/[^\s]+/g)].map(x=>new URL(x[0])));return {old:new URLSearchParams(links[0].hash.slice(1)).get('token'),cancel:new URLSearchParams(links[1].hash.slice(1)).get('token'),new:new URLSearchParams(links[2].hash.slice(1)).get('token')};};
const confirm=(f,token,action='confirm')=>memberEmailChangeRoute(req('/confirm','POST',{token,action},0),f.env);
const email=f=>f.db.prepare('SELECT email FROM users WHERE id=1').get().email;
function protectedRows(f){return Object.fromEntries(['orders','member_state','consents'].map(t=>[t,f.db.prepare('SELECT * FROM '+t).all()]));}
test('explicit feature flag and mail binding required; no disabled-state schema reads',async()=>{for(const env of [{},{MEMBER_EMAIL_CHANGE_ENABLED:'true'},{EMAIL:{send(){}}}]){const r=await memberEmailChangeRoute(req(),env);assert.equal(r.status,503);assert.equal((await r.json()).enabled,false);}});
test('current password verifier uses retained PBKDF2 envelope with bounded iterations',async()=>{assert(await verifyEmailChangePassword(password,stored));assert(!await verifyEmailChangePassword('wrong',stored));assert(!await verifyEmailChangePassword(password,stored.replace('100000','999999999')));assert(!await verifyEmailChangePassword(password,'bad'));});
test('pending email does not modify identity; only hashes stored and no password/token in response',async t=>{const f=setup(t),s=await start(f);assert.equal(s.response.status,202);assert.equal(email(f),'fictional-1@example.invalid');assert.equal(f.mail.length,2);const ts=tokens(f),row=f.db.prepare('SELECT * FROM member_email_changes').get();for(const raw of Object.values(ts)){assert(!JSON.stringify(row).includes(raw));assert(!JSON.stringify(s.data).includes(raw));}assert(!JSON.stringify(row).includes(stored));assert(!JSON.stringify(row).includes(password));assert.equal(s.data.pending,true);assert.equal(row.status,'pending');assert(f.mail.every(m=>m.text.includes('#token=')&&!m.text.includes('?token=')));});
test('both confirmations required in either order; one transaction preserves user ownership and historical data',async t=>{for(const order of [['old','new'],['new','old']]){const f=setup(t),before=protectedRows(f);await start(f);const ts=tokens(f);let r=await confirm(f,ts[order[0]]);assert.equal(r.status,200);assert.equal((await r.json()).completed,false);assert.equal(email(f),'fictional-1@example.invalid');assert(!(await authenticateMember(req(),f.env)).response);r=await confirm(f,ts[order[1]]);assert.equal(r.status,200);assert.equal((await r.json()).completed,true);assert.equal(email(f),'new-address@example.invalid');assert.equal((await authenticateMember(req(),f.env)).response.status,401);assert(!(await authenticateMember(req('', 'GET',undefined,2),f.env)).response);assert.deepEqual(protectedRows(f),before);assert.equal(f.db.prepare('SELECT email_verified FROM user_auth WHERE user_id=1').get().email_verified,1);assert(f.db.prepare('SELECT used_at FROM auth_tokens WHERE user_id=1').get().used_at);assert.equal(f.db.prepare('SELECT old_token_hash FROM member_email_changes').get().old_token_hash,null);assert.equal((await confirm(f,ts[order[0]])).status,400);assert.equal(f.mail.length,4);}});
test('old and new tokens cannot cancel; cancellation link stops request without changing sign-in',async t=>{const f=setup(t);await start(f);const ts=tokens(f);assert.equal((await confirm(f,ts.new,'cancel')).status,400);assert.equal((await confirm(f,ts.cancel)).status,400);assert.equal((await confirm(f,ts.cancel,'cancel')).status,200);assert.equal((await confirm(f,ts.new)).status,400);assert.equal(email(f),'fictional-1@example.invalid');assert(!(await authenticateMember(req(),f.env)).response);});
test('expired, replaced and previously consumed links cannot be used',async t=>{const f=setup(t);await start(f);let ts=tokens(f);assert.equal((await confirm(f,ts.old)).status,200);assert.equal((await confirm(f,ts.old)).status,400);f.db.exec("UPDATE member_email_changes SET expires_at='2000-01-01'");assert.equal((await confirm(f,ts.new)).status,400);await start(f);assert.equal((await confirm(f,ts.new)).status,400);assert.equal(email(f),'fictional-1@example.invalid');});
test('password change/reset while request pending invalidates both outstanding links',async t=>{const f=setup(t);await start(f);const ts=tokens(f);await confirm(f,ts.old);f.db.prepare('UPDATE user_auth SET password_hash=? WHERE user_id=1').run(stored+'changed');assert.equal((await confirm(f,ts.new)).status,409);assert.equal(email(f),'fictional-1@example.invalid');assert.equal((await confirm(f,ts.new)).status,400);});
test('wrong password, locked account, same email, mismatches and unknown inputs never send email',async t=>{const f=setup(t);for(const patch of [{currentPassword:'wrong'},{newEmail:'fictional-1@example.invalid',confirmEmail:'fictional-1@example.invalid'},{confirmEmail:'other@example.invalid'},{userId:2}])assert((await start(f,{...change(),...patch})).response.status>=400);assert.equal(f.mail.length,0);f.db.exec("UPDATE user_auth SET locked_until='2099-01-01' WHERE user_id=1");assert.equal((await start(f)).response.status,401);assert.equal(f.mail.length,0);});
test('request retries are idempotent; changed identity input cannot reuse operation ID',async t=>{const f=setup(t),s=await start(f);assert.equal((await start(f,s.body)).response.status,202);assert.equal(f.mail.length,2);assert.equal((await start(f,{...s.body,newEmail:'different@example.invalid',confirmEmail:'different@example.invalid'})).response.status,409);});
test('own-account rate limit bounds password attempts; no account selector or external origin allowed',async t=>{const f=setup(t);for(let i=0;i<5;i++)assert.equal((await start(f,{...change(),currentPassword:'wrong'})).response.status,401);assert.equal((await start(f)).response.status,429);assert.equal((await memberEmailChangeRoute(req('','POST',change(),1,{Origin:'https://attacker.invalid'}),f.env)).status,403);assert.equal((await memberEmailChangeRoute(req('','POST',change(),0),f.env)).status,401);assert.equal(f.mail.length,0);});
test('mail failure cancels both tokens and retains the old identity without claiming delivery',async t=>{const f=setup(t);f.env.EMAIL.send=async m=>{f.mail.push(m);if(f.mail.length===2)throw Error('provider failure');};const r=await start(f);assert.equal(r.response.status,503);assert.equal(email(f),'fictional-1@example.invalid');assert.equal(f.db.prepare('SELECT status FROM member_email_changes').get().status,'cancelled');assert.equal((await confirm(f,tokens(f).old)).status,400);});
test('a conflicting email before request or at final confirmation never steals an account',async t=>{const f=setup(t);assert.equal((await start(f,{...change(),newEmail:'FICTIONAL-2@EXAMPLE.INVALID',confirmEmail:'fictional-2@example.invalid'})).response.status,409);await start(f);const ts=tokens(f);await confirm(f,ts.old);f.db.exec("UPDATE users SET email='new-address@example.invalid' WHERE id=2");assert.equal((await confirm(f,ts.new)).status,409);assert.equal(email(f),'fictional-1@example.invalid');assert(!(await authenticateMember(req(),f.env)).response);});
test('concurrent duplicate confirmations cannot consume twice or change user ownership',async t=>{const f=setup(t);await start(f);const ts=tokens(f);await confirm(f,ts.old);const results=await Promise.all([confirm(f,ts.new),confirm(f,ts.new)]);assert.equal(results.filter(r=>r.status===200).length,1);assert.equal(email(f),'new-address@example.invalid');assert.equal(f.db.prepare("SELECT count(*) n FROM audit_log WHERE action='member.email.changed'").get().n,1);});
test('late database failure atomically restores token, user, password metadata and sessions',async t=>{const f=setup(t);await start(f);const ts=tokens(f);await confirm(f,ts.old);f.db.exec("CREATE TRIGGER fail_identity_audit BEFORE INSERT ON audit_log BEGIN SELECT RAISE(ABORT,'fixture failure');END;");assert.equal((await confirm(f,ts.new)).status,503);assert.equal(email(f),'fictional-1@example.invalid');assert(!(await authenticateMember(req(),f.env)).response);f.db.exec('DROP TRIGGER fail_identity_audit');assert.equal((await confirm(f,ts.new)).status,200);assert.equal(email(f),'new-address@example.invalid');});
test('final notification failure is reported honestly without undoing a completed identity change',async t=>{const f=setup(t);await start(f);const ts=tokens(f);f.env.EMAIL.send=async()=>{throw Error('final notice unavailable');};await confirm(f,ts.old);const r=await confirm(f,ts.new),b=await r.json();assert.equal(r.status,200);assert.equal(b.completed,true);assert.equal(b.noticesSent,false);assert.equal(email(f),'new-address@example.invalid');});
test('GET confirmation page and browser scripts never activate links automatically or persist secrets',async t=>{const f=setup(t);await start(f);const ts=tokens(f);const before=JSON.stringify(f.db.prepare('SELECT * FROM member_email_changes').get());const r=await memberEmailChangeRoute(new Request(origin+'/member/email-change?token='+ts.old),f.env);assert.equal(r.status,200);assert.equal(JSON.stringify(f.db.prepare('SELECT * FROM member_email_changes').get()),before);assert.match(r.headers.get('Content-Security-Policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('Referrer-Policy'),'no-referrer');assert.equal((await memberEmailChangeRoute(req('/confirm','GET'),f.env)).status,405);new vm.Script(emailChangeRuntime);new vm.Script(emailConfirmationRuntime);assert(emailChangeMarkup.includes('current-password'));for(const s of [emailChangeRuntime,emailConfirmationRuntime]){assert(!s.includes('localStorage'));assert(!s.includes('sessionStorage'));}assert(emailConfirmationRuntime.includes("history.replaceState(null,'',location.pathname)"));});
test('existing password-reset mechanism routes only to new email after completion',async t=>{const f=setup(t);await start(f);const ts=tokens(f);await confirm(f,ts.old);await confirm(f,ts.new);const before=f.mail.length;const reset=e=>handleAuthRecovery(new Request(origin+'/v1/auth/request-password-reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e})}),f.env,{},()=>{throw Error('Unexpected fallback');});await reset('fictional-1@example.invalid');assert.equal(f.mail.length,before);await reset('new-address@example.invalid');assert.equal(f.mail.length,before+1);assert.equal(f.mail.at(-1).to,'new-address@example.invalid');});
test('only the owning account sees pending target; erasing account cascades pending secrets and limiter',async t=>{const f=setup(t);await start(f);const other=await (await memberEmailChangeRoute(req('','GET',undefined,2),f.env)).json();assert.equal(other.pending,false);assert(!JSON.stringify(other).includes('new-address'));f.db.exec('DELETE FROM users WHERE id=1');assert.equal(f.db.prepare('SELECT count(*) n FROM member_email_changes').get().n,0);assert.equal(f.db.prepare('SELECT count(*) n FROM member_email_change_limits').get().n,0);});

test('confirmation emails contain explicit escaped links and no executable user markup',()=>{const url='https://shiftsometimber.co.uk/member/email-change#token='+'a'.repeat(64)+'&action=confirm';const html=renderEmailChangeMessage('Click '+url+' <img src=x onerror=alert(1)>');assert(html.includes('<a href="https://shiftsometimber.co.uk/member/email-change#token='));assert(html.includes('&amp;action=confirm'));assert(!html.includes('<img'));assert(html.includes('&lt;img'));});
test('non-string email inputs produce validation errors, not service failures',async t=>{const f=setup(t);for(const patch of [{newEmail:123},{confirmEmail:123},{newEmail:null},{confirmEmail:{}}])assert.equal((await start(f,{...change(),...patch})).response.status,400);assert.equal(f.mail.length,0);});
