import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
import {fixture} from '../../health-passport/fixture.mjs';import {memberDeliveryRoute,validateDelivery} from '../member-delivery-routes.mjs';import {memberDetailsRoute,appendMemberDetailsExport} from '../member-details-routes.mjs';import {deliveryRuntime,deliveryMarkup} from '../member-delivery-client.mjs';import {withMemberDetails} from '../member-details.mjs';
const origin='https://shiftsometimber.co.uk',path='/v1/member/details/delivery';
const req=(method='GET',body,id=1,extra={})=>new Request(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(id?{Cookie:'sst_session=test-only-member-'+id}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})});
function setup(t){const f=fixture({seed:false});t.after(()=>f.close());f.db.exec("ALTER TABLE users ADD COLUMN phone TEXT;ALTER TABLE users ADD COLUMN date_of_birth TEXT;ALTER TABLE users ADD COLUMN postcode TEXT;ALTER TABLE users ADD COLUMN updated_at TEXT;CREATE TABLE member_status(user_id INTEGER PRIMARY KEY,last_activity_at TEXT,updated_at TEXT);INSERT INTO member_status(user_id) VALUES(1),(2);CREATE TABLE orders(id INTEGER PRIMARY KEY,user_id INTEGER,address TEXT);INSERT INTO orders VALUES(1,1,'Keep historical address');");f.db.exec(readFileSync(new URL('../member-details.sql',import.meta.url),'utf8'));return f;}
const details=()=>({firstName:'Alex',lastName:'Test',phone:'07700 900123',dateOfBirth:'1982-01-12',postcode:'SK10 1AA',address1:'1 Fictional Close',address2:'',town:'Macclesfield',county:'Cheshire',gpPractice:'Test practice',gpPostcode:'SK10 1AA',gpCode:''});
const separate=()=>({useHome:false,recipient:'Fictional Recipient',address1:'2 Fictional Road',address2:'Flat 2',town:'London',county:'',postcode:'SW1A 1AA'});
const homeRequest=(method='GET',body)=>new Request(origin+'/v1/member/details',{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:'sst_session=test-only-member-1'},...(body?{body:JSON.stringify(body)}:{})});
async function setHome(f,d=details()){const b=await (await memberDetailsRoute(homeRequest(),f.env)).json();return memberDetailsRoute(homeRequest('PATCH',{details:d,revision:b.revision,operationId:crypto.randomUUID()}),f.env);}
async function get(f,id=1){const r=await memberDeliveryRoute(req('GET',undefined,id),f.env);assert.equal(r.status,200);return r.json();}
async function put(f,d=separate(),rev){const b={delivery:d,revision:rev||(await get(f)).revision,operationId:crypto.randomUUID()};return {body:b,response:await memberDeliveryRoute(req('PUT',b),f.env)};}
function protectedRows(f){return Object.fromEntries(['users','orders','member_state','consents'].map(t=>[t,f.db.prepare('SELECT * FROM '+t).all()]));}
test('delivery card is mounted without nested forms; its runtime compiles and no order endpoint exists',()=>{const html=withMemberDetails('<html><head></head><body><main><form id="legacy">KEEP</form></main></body></html>');assert(html.includes(deliveryMarkup));assert(html.includes('id="legacy"'));assert(html.indexOf('</form>')<html.indexOf('id="memberDeliveryForm"'));new vm.Script(deliveryRuntime);assert(!deliveryRuntime.includes('localStorage'));assert(!deliveryRuntime.includes('/orders'));});
test('separate delivery saves and reloads without altering home, orders, consents or another member',async t=>{const f=setup(t);assert.equal((await setHome(f)).status,200);const before=protectedRows(f),r=await put(f);assert.equal(r.response.status,200);const b=await get(f);assert.deepEqual(b.delivery,separate());assert.equal(b.home.address1,'1 Fictional Close');assert.equal(b.effectiveAddress.address1,'2 Fictional Road');assert.deepEqual(protectedRows(f),before);assert.equal((await get(f,2)).configured,false);});
test('old account-details client preserves the independently saved delivery object',async t=>{const f=setup(t);await setHome(f);await put(f);const d=details();d.address1='Changed home only';assert.equal((await setHome(f,d)).status,200);assert.equal((await get(f)).delivery.address1,'2 Fictional Road');assert.equal((await get(f)).home.address1,'Changed home only');});
test('same-as-home resolves current saved home but never rewrites historical orders',async t=>{const f=setup(t);await setHome(f);assert.equal((await put(f,{...separate(),useHome:true})).response.status,200);const d=details();d.address1='New home';await setHome(f,d);assert.equal((await get(f)).effectiveAddress.address1,'New home');assert.equal(f.db.prepare('SELECT address FROM orders').get().address,'Keep historical address');});
test('same-as-home cannot be saved until a complete home address exists',async t=>{const f=setup(t);assert.equal((await put(f,{...separate(),useHome:true})).response.status,400);assert.equal((await get(f)).configured,false);});
test('stale delivery edits reject both another delivery save and a changed home address',async t=>{const f=setup(t);await setHome(f);const rev=(await get(f)).revision;await put(f);assert.equal((await put(f,{...separate(),town:'Other town'},rev)).response.status,409);const next=(await get(f)).revision;await setHome(f,{...details(),phone:'07700 900555'});assert.equal((await put(f,separate(),next)).response.status,409);});
test('delivery write failure rolls back; exact retry is idempotent and altered operation refuses',async t=>{const f=setup(t);await setHome(f);f.db.exec("CREATE TRIGGER fail_delivery BEFORE INSERT ON audit_log BEGIN SELECT RAISE(ABORT,'injected failure');END;");const {body,response}=await put(f);assert.equal(response.status,503);assert.equal((await get(f)).configured,false);f.db.exec('DROP TRIGGER fail_delivery');assert.equal((await memberDeliveryRoute(req('PUT',body),f.env)).status,200);const count=f.db.prepare('SELECT count(*) n FROM audit_log').get().n;assert.equal((await memberDeliveryRoute(req('PUT',body),f.env)).status,200);assert.equal(f.db.prepare('SELECT count(*) n FROM audit_log').get().n,count);body.delivery.town='Different';assert.equal((await memberDeliveryRoute(req('PUT',body),f.env)).status,409);});
test('unauthenticated, foreign origin and injected account IDs cannot update delivery',async t=>{const f=setup(t);assert.equal((await memberDeliveryRoute(req('GET',undefined,0),f.env)).status,401);const body={delivery:separate(),revision:(await get(f)).revision,operationId:crypto.randomUUID()};assert.equal((await memberDeliveryRoute(req('PUT',body,1,{Origin:'https://evil.invalid'}),f.env)).status,403);assert.equal((await memberDeliveryRoute(req('PUT',{...body,userId:2}),f.env)).status,400);assert.equal((await memberDeliveryRoute(req('PUT',body,1,{'Content-Type':'text/plain'}),f.env)).status,415);});
test('delivery participates in existing own-account export and FK hard-deletion lifecycle',async t=>{const f=setup(t);await put(f);const r=await appendMemberDetailsExport(new Request(origin+'/v1/privacy/export',{method:'POST',headers:{Cookie:'sst_session=test-only-member-1'}}),f.env,Response.json({existing:true}));const b=await r.json();assert.equal(b.memberAccountDetails.delivery.address1,'2 Fictional Road');assert.equal(b.existing,true);f.db.prepare('DELETE FROM users WHERE id=1').run();assert.equal(f.db.prepare('SELECT count(*) n FROM member_account_details').get().n,0);});
test('real validation rejects incomplete, oversized, invalid or ambiguous delivery data',()=>{assert.equal(validateDelivery({...separate(),postcode:'sw1a1aa'}).postcode,'SW1A 1AA');for(const patch of [{useHome:'false'},{recipient:''},{address1:''},{town:''},{postcode:'NOPE'},{county:'x'.repeat(101)},{recipient:'A\nB'},{extra:'no'}])assert.throws(()=>validateDelivery({...separate(),...patch}));});
test('both retained assessment templates load the shared GP component exactly once',()=>{for(const path of ['../../frontend/member/treatment-assessment.html','../../frontend/medicine-front-door/treatment-assessment.html']){const s=readFileSync(new URL(path,import.meta.url),'utf8');assert.equal((s.match(/src="\/assets\/member-experience\/gp-form\.mjs"/g)||[]).length,1);assert(s.includes('name="gpContactConsent"'));assert(s.includes('name="gpAddress"'));}});
