import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import {treatmentRoutes,validateTreatment} from '../treatment-routes.mjs';
function setup(){const sql=new DatabaseSync(':memory:');sql.exec(`CREATE TABLE users(id INTEGER PRIMARY KEY,email TEXT);CREATE TABLE user_sessions(id TEXT,user_id INTEGER,token_hash TEXT,expires_at TEXT,revoked_at TEXT,last_used_at TEXT);CREATE TABLE consents(id INTEGER PRIMARY KEY,user_id INTEGER,consent_type TEXT,granted INTEGER);INSERT INTO users VALUES(1,'one@example.invalid'),(2,'two@example.invalid');INSERT INTO consents VALUES(1,1,'my_shift_health_tracking',1),(2,2,'my_shift_health_tracking',1);`);sql.exec(readFileSync(new URL('../treatment.sql',import.meta.url),'utf8'));const DB={prepare(query){let values=[];return {bind(...args){values=args;return this;},async first(){return sql.prepare(query).get(...values)||null;},async all(){return{results:sql.prepare(query).all(...values)};},async run(){return{meta:{changes:Number(sql.prepare(query).run(...values).changes)}}}}},async batch(stmts){sql.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};return{sql,DB,MY_TREATMENT_PREVIEW_ENABLED:'true'};}
async function token(env,user){const value='token-'+user,hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))).toString('hex');env.sql.prepare('INSERT INTO user_sessions VALUES(?,?,?,?,NULL,NULL)').run('s'+user,user,hash,'2099-01-01');return value;}
const req=(path,token,body)=>new Request('https://preview.invalid/v1/member/treatment'+path,{method:body?'POST':'GET',headers:{Cookie:'sst_session='+token,Origin:'https://preview.invalid','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
test('separate accounts, source integrity, consent, versions and idempotent history',async()=>{const env=setup(),one=await token(env,1),two=await token(env,2);assert.equal((await treatmentRoutes(req('', '',null),env)).status,401);let r=await treatmentRoutes(req('/records',one,{medicine:'Mounjaro',prescriptionDetails:'Follow prescription',supply:3,nextAt:null}),env);assert.equal(r.status,201);const{id}=await r.json();assert.equal((await (await treatmentRoutes(req('',two),env)).json()).treatments.length,0);const event={treatmentId:id,kind:'dose_taken',note:'Taken',occurredAt:new Date().toISOString(),operationId:crypto.randomUUID()};assert.equal((await treatmentRoutes(req('/events',two,event),env)).status,404);assert.equal((await treatmentRoutes(req('/events',one,event),env)).status,201);assert.equal((await treatmentRoutes(req('/events',one,event),env)).status,200);assert.equal((await (await treatmentRoutes(req('',one),env)).json()).events.length,2);assert.equal((await treatmentRoutes(req('/events',one,{...event,source:'partner'}),env)).status,400);const details={conditions:'Example',allergies:'',otherMedicines:'',pastTreatment:'',familyHistory:'',gp:''};assert.equal((await treatmentRoutes(req('/medical',one,{revision:0,details}),env)).status,201);assert.equal((await treatmentRoutes(req('/medical',one,{revision:0,details}),env)).status,409);assert.equal((await treatmentRoutes(req('/medical',one,{revision:1,details:{...details,conditions:'Updated'}}),env)).status,201);const result=await (await treatmentRoutes(req('',one),env)).json();assert.equal(result.medical.length,2);assert.equal(result.medical[1].details.conditions,'Example');env.sql.exec('UPDATE consents SET granted=0 WHERE user_id=1');assert.equal((await treatmentRoutes(req('/medical',one,{revision:2,details}),env)).status,409);});
test('rejects unsupported compounds and invented schedules',()=>{assert.throws(()=>validateTreatment({medicine:'Research peptide',prescriptionDetails:'X',supply:1,nextAt:null}));assert.throws(()=>validateTreatment({medicine:'Mounjaro',prescriptionDetails:'X',supply:1,nextAt:'bad date'}));});
test('saved dose, status, stock and check-ins are read back together without altering the prescription',async()=>{const env=setup(),one=await token(env,1);const r=await treatmentRoutes(req('/records',one,{medicine:'Wegovy',prescriptionDetails:'Original prescribed instruction',supply:4,nextAt:null}),env);const {id}=await r.json();async function event(kind,details={}){const body={treatmentId:id,kind,note:'QA',operationId:crypto.randomUUID(),occurredAt:new Date().toISOString(),...details};return treatmentRoutes(req('/events',one,body),env);}assert.equal((await event('dose_taken')).status,201);assert.equal((await event('paused')).status,201);assert.equal((await event('checkin',{checkin:{weight:85.5,appetite:'Low',energy:'Usual',sideEffects:'Member report'}})).status,201);assert.equal((await event('checkin',{checkin:{weight:-1,appetite:'Low',energy:'Usual',sideEffects:''}})).status,400);const data=await (await treatmentRoutes(req('',one),env)).json();assert.equal(data.treatments[0].supply,3);assert.equal(data.treatments[0].status,'paused');assert.equal(data.treatments[0].prescription_details,'Original prescribed instruction');assert.equal(data.events.find(e=>e.kind==='checkin').details.checkin.weight,85.5);});
test('PDF download is authenticated, owned and omits disclosures by default',async()=>{const env=setup(),one=await token(env,1),two=await token(env,2);const r=await treatmentRoutes(req('/records',one,{medicine:'Wegovy',prescriptionDetails:'Owned record',supply:4,nextAt:null}),env);const{id}=await r.json();const details={conditions:'PRIVATE_QA_CONDITION',allergies:'',otherMedicines:'',pastTreatment:'',familyHistory:'',gp:''};await treatmentRoutes(req('/medical',one,{revision:0,details}),env);const path='/summary.pdf?treatment='+id+'&period=all';let response=await treatmentRoutes(req(path,one),env);assert.equal(response.headers.get('Content-Type'),'application/pdf');assert.equal(response.status,200);assert(!(await response.text()).includes('PRIVATE_QA_CONDITION'));response=await treatmentRoutes(req(path+'&medical=1',one),env);assert((await response.text()).includes('PRIVATE_QA_CONDITION'));assert.equal((await treatmentRoutes(req(path,two),env)).status,404);assert.equal((await treatmentRoutes(req(path,''),env)).status,401);});
test('treatment reminders deduplicate and suppress logged doses, logout and withdrawal',async()=>{const {runTreatmentReminders}=await import('../treatment-reminders.mjs');const env=setup(),one=await token(env,1);const now=new Date(),due=new Date(now.getTime()-60000).toISOString();let r=await treatmentRoutes(req('/records',one,{medicine:'Wegovy',prescriptionDetails:'QA instruction',supply:4,nextAt:due}),env);const{id}=await r.json();const base={treatmentId:id,note:'QA',operationId:crypto.randomUUID(),occurredAt:now.toISOString()};await treatmentRoutes(req('/events',one,{...base,kind:'reminder_updated',enabled:true}),env);env.sql.prepare('INSERT INTO member_treatment_push_devices VALUES(?,?,?,?,?,?)').run('https://fcm.googleapis.com/qa-device',1,'s1','synthetic','synthetic',now.toISOString());let sends=0;const send=async()=>{sends++;return 'accepted';};assert.equal((await runTreatmentReminders(env,now,send)).accepted,1);await runTreatmentReminders(env,now,send);assert.equal(sends,1);env.sql.exec('DELETE FROM member_treatment_push_deliveries');await treatmentRoutes(req('/events',one,{...base,operationId:crypto.randomUUID(),kind:'dose_taken'}),env);await runTreatmentReminders(env,now,send);assert.equal(sends,1);env.sql.exec("DELETE FROM member_treatment_events WHERE kind='dose_taken';UPDATE user_sessions SET revoked_at='2026-01-01' WHERE user_id=1");await runTreatmentReminders(env,now,send);assert.equal(sends,1);env.sql.exec('UPDATE user_sessions SET revoked_at=NULL;UPDATE consents SET granted=0');await runTreatmentReminders(env,now,send);assert.equal(sends,1);});
test('treatment push uses encrypted generic payloads and rejects untrusted endpoints',async()=>{const {sendTreatmentPush}=await import('../treatment-reminders.mjs');const{createECDH,randomBytes}=await import('node:crypto');const client=createECDH('prime256v1');client.generateKeys();const env=setup(),row={endpoint:'https://fcm.googleapis.com/qa-synthetic',p256dh:client.getPublicKey().toString('base64url'),auth:randomBytes(16).toString('base64url')};let calls=0;const transport=async(url,options)=>{calls++;assert.equal(options.redirect,'manual');assert.equal(new Headers(options.headers).get('Content-Encoding'),'aes128gcm');assert(new Headers(options.headers).get('Authorization').startsWith('vapid t='));assert(!Buffer.from(options.body).toString().includes('My Timber'));return new Response(null,{status:201});};assert.equal(await sendTreatmentPush(env,row,transport),'accepted');assert.equal(calls,1);assert.equal(await sendTreatmentPush(env,{...row,endpoint:'https://127.0.0.1/private'},transport),'rejected');assert.equal(calls,1);});
test('native reminder lease is private, consent-bound and ends at session expiry',async()=>{
 const env=setup(),one=await token(env,1),two=await token(env,2),now=Date.now();
 const due=new Date(now+3600000).toISOString();
 const {id}=await (await treatmentRoutes(req('/records',one,{medicine:'Wegovy',prescriptionDetails:'PRIVATE PRESCRIPTION',supply:4,nextAt:due}),env)).json();
 await treatmentRoutes(req('/events',one,{treatmentId:id,kind:'reminder_updated',enabled:true,note:'PRIVATE NOTE',occurredAt:new Date().toISOString(),operationId:crypto.randomUUID()}),env);
 let response=await treatmentRoutes(req('/native-reminders',one),env),body=await response.json();assert.equal(body.account,'1');assert.deepEqual(body.reminders,[{id,at:Date.parse(due)}]);assert(!JSON.stringify(body).includes('PRIVATE'));assert(!JSON.stringify(body).includes('Wegovy'));
 assert.deepEqual((await (await treatmentRoutes(req('/native-reminders',two),env)).json()).reminders,[]);
 env.sql.prepare('UPDATE user_sessions SET expires_at=? WHERE user_id=1').run(new Date(now+1800000).toISOString());assert.deepEqual((await (await treatmentRoutes(req('/native-reminders',one),env)).json()).reminders,[]);
 env.sql.exec("UPDATE user_sessions SET expires_at='2099-01-01';UPDATE consents SET granted=0 WHERE user_id=1");assert.deepEqual((await (await treatmentRoutes(req('/native-reminders',one),env)).json()).reminders,[]);
 assert.equal((await treatmentRoutes(req('/native-reminders',''),env)).status,401);
});
