import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from '../../health-passport/fixture.mjs';
import {unitSettingsRoute} from '../unit-settings.mjs';
const origin='https://shiftsometimber.co.uk';
const req=(method='GET',body,user=1,source=origin)=>new Request(origin+'/v1/settings/units',{method,headers:{Origin:source,'Content-Type':'application/json',...(user?{Cookie:'sst_session=test-only-member-'+user}:{})},...(body?{body:JSON.stringify(body)}:{})});
test('Settings units persist without health consent or changing measurements and other owned records',async t=>{
 const f=fixture({seed:false});t.after(()=>f.close());
 const before={myJourney:{setup:{units:'stone_lb',heightCm:182},weight:{currentKg:103}},fitJourney:{entries:{old:{status:'done'}}},grubV2:{today:{name:'Saved meal'}},lifeBack:{progress:{revision:5}}};
 f.db.prepare('UPDATE member_state SET preferences=? WHERE user_id=1').run(JSON.stringify(before));
 const response=await unitSettingsRoute(req('PATCH',{weight:'kg',height:'cm'}),f.env);assert.equal(response.status,200);
 assert.deepEqual(await response.json(),{units:{weight:'kg',height:'cm'}});
 assert.deepEqual(await (await unitSettingsRoute(req(),f.env)).json(),{units:{weight:'kg',height:'cm'}});
 const expected=structuredClone(before);expected.myJourney.setup.units='kg';expected.displayUnits={height:'cm'};
 assert.deepEqual(JSON.parse(f.db.prepare('SELECT preferences FROM member_state WHERE user_id=1').get().preferences),expected);
 assert.equal((await unitSettingsRoute(req('PATCH',{weight:'kg',height:'cm'},1,'https://wrong.example'),f.env)).status,403);
 assert.equal((await unitSettingsRoute(req('PATCH',{weight:'invalid',height:'cm'}),f.env)).status,400);
 assert.equal((await unitSettingsRoute(req('GET',undefined,0),f.env)).status,401);
 assert.deepEqual(await (await unitSettingsRoute(req('GET',undefined,2),f.env)).json(),{units:{weight:'stone_lb',height:'ft_in'}});
});
