// Fictional responsive review only. Imported solely by the staging entry.
import {workHTML,workCSS,workJS} from '../screen.mjs';
import fixtures from './layout-fixtures.json' with {type:'json'};
const base="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'";
const css='body{margin:20px;background:#e7e3da;color:#050505;font:16px/1.5 Arial}label{display:inline-block;margin:0 16px 12px 0}select,button{font:inherit;padding:10px;min-height:44px}iframe{display:block;border:1px solid #707762;height:780px;background:#e7e3da}';
const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>SHIFT workplace layout review</title><link rel="stylesheet" href="/staging/layout/check.css"><script type="module" src="/staging/layout/check.mjs"></script></head><body><h1>Workplace layout review</h1><p>Fictional, read-only screens using the current workplace client and styles. Width checks in this browser do not certify Safari or a physical mobile device.</p><label>Screen <select id="screen"><option value="member">Employee</option><option value="hq">SHIFT HQ</option><option value="employer">Employer report</option></select></label><label>Viewport width <select id="width"><option>320</option><option>375</option><option selected>390</option><option>768</option><option>1024</option></select></label><p id="metrics" role="status">Measuring fictional screen…</p><iframe id="layout-frame" title="Fictional workplace screen" src="/staging/layout/member" width="390"></iframe></body></html>';
const controls=String.raw`const frame=document.querySelector('#layout-frame'),metrics=document.querySelector('#metrics');
let observer;
function measure(){const doc=frame.contentDocument;if(!doc)return;const area=doc.documentElement.clientWidth,content=Math.max(doc.documentElement.scrollWidth,doc.body.scrollWidth);metrics.textContent=frame.width+'px frame · '+area+'px content area · '+content+'px content width · '+(content<=area?'No horizontal overflow':'Horizontal overflow detected');}
frame.addEventListener('load',()=>{observer?.disconnect();observer=new MutationObserver(measure);observer.observe(frame.contentDocument.body,{childList:true,subtree:true});measure()});
document.querySelector('#width').addEventListener('change',e=>{frame.width=e.target.value;requestAnimationFrame(measure)});
document.querySelector('#screen').addEventListener('change',e=>{metrics.textContent='Measuring fictional screen…';frame.src='/staging/layout/'+e.target.value});`;

const client='const fictional='+JSON.stringify(fixtures)+';const fetch=async(path,options={})=>new Response(JSON.stringify(options.method===\'POST\'?{error:\'Read-only layout review. Nothing has been saved.\'}:fictional[path]??{error:\'Not connected in layout review.\'}),{status:options.method===\'POST\'?409:fictional[path]?200:404});document.addEventListener(\'click\',e=>{if(e.target.closest(\'a\'))e.preventDefault()});'+workJS;
export function layoutResponse(request){
 const p=new URL(request.url).pathname;if(p!=='/staging/layout-check'&&!p.startsWith('/staging/layout/'))return null;
 const assets={'/staging/layout-check':[html,'text/html'], '/staging/layout/check.css':[css,'text/css'],'/staging/layout/check.mjs':[controls,'text/javascript'],'/staging/layout/work.css':[workCSS,'text/css'],'/staging/layout/work.mjs':[client,'text/javascript']};
 for(const mode of ['member','hq','employer'])assets['/staging/layout/'+mode]=[workHTML(mode).replace('/assets/work/work.css','/staging/layout/work.css').replace('/assets/work/work.mjs','/staging/layout/work.mjs').replace('<main class="work">','<main class="work"><p><strong>Fictional layout review — no accounts or live data.</strong></p>'),'text/html'];
 const a=assets[p];if(!a)return new Response('Unknown layout screen.',{status:404});if(request.method!=='GET')return new Response('Read-only review.',{status:405});
 return new Response(a[0],{headers:{'Content-Type':a[1]+'; charset=utf-8','Content-Security-Policy':base+(p==='/staging/layout-check'?"; frame-src 'self'; frame-ancestors 'none'":"; frame-ancestors 'self'"),'Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'}});
}
