import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { phase3Pages } from '../../seo-authority/phase3-first-pages-r2.mjs';

const out = process.argv[2] || '.evidence-desk-demo-dist';
await mkdir(`${out}/preview`, { recursive: true });
await mkdir(`${out}/rollback`, { recursive: true });
await mkdir(`${out}/phase-3`, { recursive: true });

const copy = 'c219e05c948e2d89bfe42d5b4b13f06b4d92d406d82043fd4fbbb561e6680452';
const baseline = '773b67fed65c5ef4f13be58248118c9abc6f7792acf35b84752a9e7d0da035d7';
const candidate = 'a00ff939edddb532a671562a86cf2b647445e216e13f6a8693f8cfa132be4475';
const css = `<style>:root{color-scheme:dark;--ink:#e9e6dc;--muted:#aaa99f;--bg:#080a08;--card:#121611;--line:#30382c;--lime:#c8f04b;--red:#ff806f;--amber:#ffc960}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:40px 22px}h1{font-size:clamp(2rem,5vw,4.4rem);line-height:1}.eyebrow{color:var(--lime);font-weight:800;text-transform:uppercase;letter-spacing:.1em}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:14px}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:20px}.red{color:var(--red)}.amber{color:var(--amber)}.ok{color:var(--lime)}code{overflow-wrap:anywhere;color:#d9f58d}a{color:var(--lime)}table{border-collapse:collapse;width:100%;font-size:.92rem}th,td{border-bottom:1px solid var(--line);padding:10px;text-align:left;vertical-align:top}.banner{border:2px solid var(--red);border-radius:14px;padding:16px;background:#21110f}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:5px 10px;margin:3px}.copy{border-left:4px solid var(--amber);padding:14px 18px;background:#17140d}.article{max-width:760px}.article .dek{font-size:1.25rem;color:var(--muted)}.tool{padding:18px;border:1px solid var(--lime);border-radius:14px;background:#10150d}.tool label{display:block;margin:10px 0}.tool input{display:block;width:100%;max-width:320px;padding:10px}.tool button{padding:10px 16px;background:var(--lime);color:#101408;border:0;border-radius:8px;font-weight:800}.tool output{display:block;margin-top:14px;font-size:1.2rem}</style>`;
const head = (title) => `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${title}</title>${css}</head><body><main>`;
const foot = `</main></body></html>`;
const escapeHtml = (value) => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');

await writeFile(`${out}/index.html`, `${head('Shift Evidence Desk — sealed staging demo')}
<p class="eyebrow">Shift Evidence Desk · R1.x staging demonstration</p><h1>The machine works.<br><span class="red">Publication does not.</span></h1>
<div class="banner"><strong>Environment: non-production / staging</strong><br>Specialist review: <strong>not obtained</strong> · Publication: <strong>disabled</strong></div>
<h2>NAION decision package</h2><div class="grid">
<section class="card"><h3>1 · Evidence</h3><p class="ok">Source snapshot persisted</p><p>MHRA · 5 February 2026 · semaglutide-specific · very rare NAION safety update.</p></section>
<section class="card"><h3>2 · Mapping</h3><p class="ok">Exact dependency</p><code>claim → /glp1-knowledge-centre.html → section 07</code></section>
<section class="card"><h3>3 · Copy lock</h3><p class="ok">SHA-256 bound</p><code>${copy}</code></section>
<section class="card"><h3>4 · Editorial</h3><p class="ok">Editorial accepted</p><p>Read-only packet and audit retained.</p></section>
<section class="card"><h3>5 · Specialist gates</h3><p class="red">Clinical: not obtained<br>Medicines-comms: not obtained</p></section>
<section class="card"><h3>6 · Preflight</h3><p class="red">FAIL CLOSED</p><p>Also awaiting page baseline/rollback acceptance and publication authority.</p></section>
<section class="card"><h3>7 · Shutdown</h3><p class="ok">Fetch killed · destinations killed</p><p>Web, newsletter, social, model and live polling remain off.</p></section>
<section class="card"><h3>8 · Rollback</h3><p class="ok">Byte-exact</p><code>${baseline}</code></section></div>
<h2>Demonstration surfaces</h2><p><a href="/preview/">Would-publish preview</a> · <a href="/rollback/">Rollback proof</a> · <a href="/phase-3/">Phase 3 map and first pages</a></p>
<p><span class="pill">Production off</span><span class="pill">R2 off</span><span class="pill">Wave 3 off</span><span class="pill">PR off</span></p>${foot}`);

const exact = `<p>The MHRA says semaglutide (Wegovy, Ozempic and Rybelsus) has, in very rare reports, been linked to a serious eye condition called non-arteritic anterior ischaemic optic neuropathy (NAION), which can affect vision. If you are taking semaglutide and notice a change in your eyesight — including sudden blindness or a rapid deterioration — urgently contact a doctor. Call NHS 111, attend eye casualty if one is available in your area, or go to A&amp;E if you cannot reach your GP or GLP-1 prescriber. This warning is specific to semaglutide; the MHRA says it is reviewing evidence about other GLP-1 agonists.</p>`;
await writeFile(`${out}/preview/index.html`, `${head('Would-publish preview — disabled')}<p class="eyebrow">Staging-only candidate · would publish</p><h1>GLP-1 Knowledge Centre</h1><div class="banner">Not live. Not clinically reviewed. Not medicines-communications approved. Publication disabled.</div><section class="copy"><p class="eyebrow">MHRA safety update · 5 February 2026</p><h2>Safety update: changes to eyesight</h2>${exact}<p><a href="https://www.gov.uk/government/publications/glp-1-medicines-for-weight-loss-and-diabetes-what-you-need-to-know/glp-1-medicines-for-weight-loss-and-diabetes-what-you-need-to-know">Read the MHRA guidance</a></p><p><strong>General information, not individual medical advice.</strong></p></section><p>Candidate page SHA-256: <code>${candidate}</code><br>Exact copy SHA-256: <code>${copy}</code></p><p><a href="/">Back to control desk</a></p>${foot}`);
await writeFile(`${out}/rollback/index.html`, `${head('Rollback proof')}<p class="eyebrow">Candidate containment</p><h1>Rollback is byte-exact.</h1><div class="grid"><section class="card"><h2>Baseline</h2><code>${baseline}</code></section><section class="card"><h2>Rollback</h2><code>${baseline}</code></section></div><p class="ok"><strong>PASS:</strong> candidate block absent after rollback; restored bytes equal captured baseline.</p><p>Candidate retained only as a non-production evidence artifact: <code>${candidate}</code>.</p><p><a href="/">Back to control desk</a></p>${foot}`);

let rows='';
for (const page of phase3Pages) {
  const sources = page.sources.map((source) => `<li><a href="${escapeHtml(source.href)}">${escapeHtml(source.label)}</a></li>`).join('');
  const sections = page.sections.map((section) => `<section><h2>${escapeHtml(section.heading)}</h2>${section.paragraphs.map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join('')}</section>`).join('');
  const bmiTool = page.tool === 'bmi' ? `<section><h2>Calculate your BMI</h2><div class="tool"><form id="bmi-form"><label>Height in centimetres<input name="height" min="100" max="250" required type="number" step="0.1"></label><label>Weight in kilograms<input name="weight" min="25" max="400" required type="number" step="0.1"></label><button type="submit">Calculate</button><output id="bmi-result" aria-live="polite"></output></form></div><script>document.querySelector('#bmi-form').addEventListener('submit',function(event){event.preventDefault();const data=new FormData(event.currentTarget);const metres=Number(data.get('height'))/100;const weight=Number(data.get('weight'));const output=document.querySelector('#bmi-result');if(!Number.isFinite(metres)||!Number.isFinite(weight)||metres<1||metres>2.5||weight<25||weight>400){output.textContent='Check the height and weight entered.';return}output.textContent='BMI: '+(weight/(metres*metres)).toFixed(1)+'. Use this as screening information, not a diagnosis.'})</script></section>` : '';
  rows += `<tr><td>${escapeHtml(page.hub)}</td><td><code>${escapeHtml(page.url)}</code></td><td>${escapeHtml(page.intent)}</td><td>${page.sources.map((source) => `<a href="${escapeHtml(source.href)}">${escapeHtml(source.label)}</a>`).join('<br>')}</td><td><a href="/phase-3/${escapeHtml(page.slug)}.html">production-ready candidate</a></td></tr>`;
  await writeFile(`${out}/phase-3/${page.slug}.html`, `${head(page.title)}<article class="article"><p class="eyebrow">${escapeHtml(page.hub)} · production-ready candidate</p><h1>${escapeHtml(page.title)}</h1><p class="dek">${escapeHtml(page.dek)}</p><div class="banner"><strong>Staging / not published.</strong> ${escapeHtml(page.boundary)} No clinical-review badge is claimed.</div><p>This URL owns one intent: <strong>${escapeHtml(page.intent)}</strong>.</p>${bmiTool}${sections}<section><h2>Sources and evidence date</h2><ul>${sources}</ul><p>Sources checked 26 August 2026. Material claims remain governed by the Evidence Desk.</p></section><p>Planned production URL: <code>${escapeHtml(page.url)}</code></p><p><a href="/phase-3/">Back to Phase 3 map</a></p></article>${foot}`);
}
await writeFile(`${out}/phase-3/index.html`, `${head('Phase 3 map and first pages')}<p class="eyebrow">Phase 3 · staging only</p><h1>Seven hubs. One intent per URL.</h1><div class="banner">Complete editorial candidates on staging, not live pages. No page claims clinical review. Production, Wave 3 and public medicines-safety publication remain disabled.</div><table><thead><tr><th>Hub</th><th>Owner URL</th><th>Single intent</th><th>Primary sources</th><th>Candidate</th></tr></thead><tbody>${rows}</tbody></table><p><a href="/">Back to control desk</a></p>${foot}`);

const preview = await readFile('evidence/evidence-desk/r17/glp1-knowledge-centre.r17-candidate.html');
const rollback = await readFile('evidence/evidence-desk/r17/glp1-knowledge-centre.r17-rollback.html');
if (createHash('sha256').update(preview).digest('hex') !== candidate) throw new Error('candidate drift');
if (createHash('sha256').update(rollback).digest('hex') !== baseline) throw new Error('rollback drift');
await copyFile('evidence/evidence-desk/r17/r17-manifest.json', `${out}/r17-manifest.json`);
