import {mkdirSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {sitemapUrls,extractPublicPage} from '../../member-experience/ai-site-knowledge.mjs';
const base='https://shiftsometimber.co.uk',directory='evidence/shift-ai-site-index';mkdirSync(directory,{recursive:true});
const r=await fetch(base+'/sitemap.xml',{signal:AbortSignal.timeout(20000)});assert(r.ok);const urls=sitemapUrls(await r.text());assert(urls.length>50,'Expected a substantial live public information catalogue');
let next=0;const pages=[],skipped=[];
await Promise.all(Array.from({length:6},async()=>{while(next<urls.length){const url=urls[next++];try{const response=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(20000)});if(!response.ok){skipped.push({url,status:response.status});continue}const html=await response.text();const page=extractPublicPage(html,url);if(page)pages.push({...page,sha256:createHash('sha256').update(html).digest('hex')});else skipped.push({url,reason:'not_indexable'});}catch{skipped.push({url,reason:'fetch_failed'});}}}));
pages.sort((a,b)=>a.url.localeCompare(b.url));const report={at:new Date().toISOString(),source:process.env.GITHUB_SHA,discovered:urls.length,indexed:pages.length,chunks:pages.reduce((n,p)=>n+p.chunks.length,0),skipped,pages};writeFileSync(directory+'/index.json',JSON.stringify(report,null,2));
const q=s=>"'"+String(s).replace(/'/g,"''")+"'";let sql='';
for(const p of pages){const key='shift-public:'+p.url;sql+=`INSERT INTO ai_knowledge_documents(title,source_uri,category,trust_tier,status,checksum,updated_at) VALUES(${q(p.title)},${q(p.url)},'shift_public_site',3,'published_site',${q(key)},CURRENT_TIMESTAMP) ON CONFLICT(checksum) DO UPDATE SET title=excluded.title,status='published_site',updated_at=CURRENT_TIMESTAMP;\nDELETE FROM ai_knowledge_chunks WHERE document_id=(SELECT id FROM ai_knowledge_documents WHERE checksum=${q(key)});\n`;p.chunks.forEach((content,i)=>{sql+=`INSERT INTO ai_knowledge_chunks(document_id,chunk_index,content,search_text) VALUES((SELECT id FROM ai_knowledge_documents WHERE checksum=${q(key)}),${i},${q(content)},${q((p.title+' '+content).toLowerCase())});\n`;});}
writeFileSync(directory+'/index.sql',sql);console.log('SHIFT_PUBLIC_INDEX '+JSON.stringify({...report,pages:pages.map(p=>({url:p.url,title:p.title,chunks:p.chunks.length,sha256:p.sha256}))}));assert(pages.length>=50,'Not enough public pages indexed');assert(skipped.filter(x=>x.reason==='fetch_failed'||x.status>=500).length<=Math.ceil(urls.length*0.05),'Public source crawl had excessive errors');
