import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {pillarClient} from './measurement.mjs';
function setup({consent=true,suppressed=false,throwPush=false,referrer='https://shiftsometimber.co.uk/male-obesity',path='/weight-loss-support-for-men',kind='navigate',ready='complete'}={}){let click,load,prevented=0;const events=[];if(throwPush)events.push=()=>{throw Error('unavailable');};const window={SSTConsent:{get:()=>({analytics:consent})},SST_ANALYTICS_SUPPRESSED:suppressed,dataLayer:events,location:{origin:'https://shiftsometimber.co.uk',pathname:path},performance:{getEntriesByType:()=>[{type:kind}]},addEventListener:(_,f)=>load=f};const document={referrer,readyState:ready,querySelector:()=>null,addEventListener:(_,f)=>click=f};vm.runInNewContext(pillarClient,{window,document,URL});return{events,load,click:(href)=>{const a={getAttribute:()=>href};click({target:{closest:()=>a},preventDefault:()=>prevented++});},prevented:()=>prevented};}
test('consented completed public support arrival emits exactly one event with no referrer, destination or answer',()=>{const x=setup();assert.equal(x.events.length,1);assert.equal(x.events[0].event,'shift_pillar_onward_opened');assert.deepEqual(Object.keys(x.events[0]),['event']);});
test('arrival waits for existing bootstrap load without replaying a later consent choice',()=>{const x=setup({ready:'loading'});assert.equal(x.events.length,0);x.load();assert.equal(x.events.length,1);const y=setup({ready:'loading',consent:false});y.load();assert.equal(y.events.length,0);});
test('declined and suppressed arrivals send nothing',()=>{for(const options of [{consent:false},{suppressed:true}])assert.equal(setup(options).events.length,0);});
test('external, direct, malformed and private arrivals cannot be attributed to the public hub',()=>{for(const options of [{referrer:''},{referrer:'https://example.org/male-obesity'},{referrer:'broken'},{referrer:'https://shiftsometimber.co.uk/other'},{path:'/member/dashboard'},{path:'/male-obesity'},{path:'/start-here'}])assert.equal(setup(options).events.length,0);});
test('reload and history return do not count an additional completed onward arrival',()=>{for(const kind of ['reload','back_forward'])assert.equal(setup({kind}).events.length,0);});
test('native onward navigation is never intercepted, even if the collector is absent or throws',()=>{for(const throwPush of [false,true]){const x=setup({path:'/male-obesity',throwPush});x.click('/weight-loss-support-for-men');assert.equal(x.prevented(),0);assert.equal(x.events.length,0);}});
test('first useful action remains a generic consented event',()=>{const x=setup({path:'/male-obesity'});x.click('#first-step');assert.equal(x.events[0].event,'shift_pillar_first_step_opened');assert.deepEqual(Object.keys(x.events[0]),['event']);});
