import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
assert.equal(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.GITHUB_ACTOR_ID,'315011648');
assert.equal(process.env.GITHUB_REF,'refs/heads/codex/full-website-content-20261002');
const account=process.env.CLOUDFLARE_ACCOUNT_ID;
const cf=async(path,method='GET')=>{const r=await fetch('https://api.cloudflare.com/client/v4/accounts/'+account+path,{method,headers:{Authorization:'Bearer '+process.env.CLOUDFLARE_API_TOKEN},signal:AbortSignal.timeout(30000)});const j=await r.json();assert(r.ok&&j.success,'Pages operation failed');return j.result;};
// This release writes Pages bytes only. Guard the exact current Pages identity and
// fingerprint below; unrelated main/Worker commits must not block scoped copy fixes.
const git=await fetch('https://api.github.com/repos/shiftsometimber/shift-core/git/refs/heads/main',{headers:{Authorization:'Bearer '+process.env.GITHUB_TOKEN},signal:AbortSignal.timeout(20000)});assert(git.ok);const observedMain=(await git.json()).object.sha;
const project=await cf('/pages/projects/projectshift');assert.equal(project.name,'projectshift');assert.equal(project.production_branch,'main');
const before=project.canonical_deployment;assert.equal(before.id,'2e63ae40-45cf-435b-9156-e04ce90b699b','Another public release superseded the reviewed baseline');
assert.equal(before.deployment_trigger.metadata.commit_hash,'d2fc4a26fdd7e8da64af4e51ac2982a0d77d92b4');
const control=JSON.parse(readFileSync('faq-release/control.json')),browser=JSON.parse(readFileSync('faq-browser-proof/receipt.json'));assert.equal(browser.sha,process.env.GITHUB_SHA);assert.equal(browser.reports.length,76);
assert.equal(browser.restoredLegacySprite.sha256,'0ae9686743e2b98e6837fbfeab6d1ad06e44e86ebd3d243c341a590c9c3a68bc');
const baselineFp=await fetch(before.url+'/DEPLOYMENT-FINGERPRINT.json');assert(baselineFp.ok);assert.equal((await baselineFp.json()).aggregate_sha256,control.expected_live_fingerprint);
const fp=await fetch(browser.origin+'/DEPLOYMENT-FINGERPRINT.json');assert(fp.ok);assert.equal((await fp.json()).aggregate_sha256,control.source_fingerprint);
mkdirSync('faq-live-proof',{recursive:true});writeFileSync('faq-live-proof/before.json',JSON.stringify({id:before.id,url:before.url,commit:before.deployment_trigger.metadata.commit_hash},null,2));
const root=process.cwd(),commandDir=process.env.RUNNER_TEMP+'/faq-pages-command';mkdirSync(commandDir,{recursive:true});
const output=execFileSync(process.execPath,[root+'/node_modules/wrangler/bin/wrangler.js','pages','deploy',root+'/faq-release/site','--project-name','projectshift','--branch','main','--commit-hash',process.env.GITHUB_SHA],{encoding:'utf8',maxBuffer:2e6,timeout:240000,cwd:commandDir});
writeFileSync('faq-live-proof/deploy.log',output);
let deployed=await cf('/pages/projects/projectshift');const after=deployed.canonical_deployment;
assert.equal(after.deployment_trigger.metadata.commit_hash,process.env.GITHUB_SHA,'Deployment identity did not match this release');
const errors=[],specs=JSON.parse(readFileSync('editorial/content-audit/faq-copy.json')).articles,checks=[];
for(const spec of specs){try{const url='https://shiftsometimber.co.uk/faq/'+spec.slug,r=await fetch(url,{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(20000)});assert(r.ok,'Article not available');const html=await r.text();const plain=html.replaceAll('&amp;','&').replaceAll('&#x27;',"'").replaceAll('&#39;',"'").replaceAll('&quot;','"');assert(plain.includes(spec.intro),'Reviewed intro missing');assert(!html.includes('The fuller answer'));assert(!html.includes('What should you take from this?'));assert(html.includes('2 October 2026'));checks.push({url,status:r.status,reviewedCopyVisible:true});}catch(e){errors.push({slug:spec.slug,error:e.message});}}
for(const spec of JSON.parse(readFileSync('editorial/content-audit/core-guides.json')).articles){try{const url='https://shiftsometimber.co.uk/guides/'+spec.slug,r=await fetch(url,{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(20000)});assert(r.ok);const text=(await r.text()).replaceAll('&amp;','&').replaceAll('&#x27;',"'").replaceAll('&#39;',"'").replaceAll('&quot;','"');assert(text.includes(spec.intro));assert(text.includes('3 October 2026'));assert(!text.includes('Use recognised health guidance as the framework'));checks.push({url,status:r.status,reviewedCopyVisible:true});}catch(e){errors.push({slug:spec.slug,error:e.message});}}
for(const path of ['/health-mot-methodology']){const r=await fetch('https://shiftsometimber.co.uk'+path,{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(20000)});const text=await r.text();if(!r.ok||!text.includes('A shared browser can retain sensitive answers')||!text.includes('separate SHIFT Health home blood-test'))errors.push({path,error:'Reviewed legacy Health MOT methodology missing'});else checks.push({url:'https://shiftsometimber.co.uk'+path,status:r.status,reviewedCopyVisible:true});}
// Keep the main-domain commercial redirect. The legacy form is dormant there.
try{const r=await fetch('https://shiftsometimber.co.uk/health-mot',{redirect:'manual',signal:AbortSignal.timeout(20000)});assert.equal(r.status,301);assert.equal(new URL(r.headers.get('location'),'https://shiftsometimber.co.uk').pathname,'/shift-health/health-mot');const legacy=await fetch(after.url+'/health-mot');assert(legacy.ok);assert((await legacy.text()).includes('Priority signals'));checks.push({url:'https://shiftsometimber.co.uk/health-mot',status:r.status,existingHomeTestRedirectPreserved:true,legacyQuestionnaireEnabledOnMainDomain:false});}catch(e){errors.push({path:'/health-mot',error:e.message});}
const script=await fetch('https://shiftsometimber.co.uk/health-mot.js',{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(20000)});const js=await script.text();if(!script.ok||js.includes('const score=Math.max')||!js.includes('not a validated health score'))errors.push({path:'/health-mot.js',error:'Corrected Health MOT script missing'});
const afterfp=await fetch(after.url+'/DEPLOYMENT-FINGERPRINT.json');assert(afterfp.ok);assert.equal((await afterfp.json()).aggregate_sha256,control.source_fingerprint);
try{const spriteResponse=await fetch('https://shiftsometimber.co.uk/assets/fit/shift-fit-batch2.svg',{headers:{'Cache-Control':'no-cache'},signal:AbortSignal.timeout(20000)});assert(spriteResponse.ok);const sprite=await spriteResponse.text();assert.equal(sprite,readFileSync('assets/fit/shift-fit-batch2.svg','utf8'));checks.push({url:'https://shiftsometimber.co.uk/assets/fit/shift-fit-batch2.svg',status:spriteResponse.status,originalRepositoryAssetRestored:true});}catch(e){errors.push({path:'/assets/fit/shift-fit-batch2.svg',error:e.message});}
if(errors.length){
 // A concurrent later release must never be overwritten by recovery.
 const latest=(await cf('/pages/projects/projectshift')).canonical_deployment;assert.equal(latest.id,after.id,'Newer public release exists; do not roll it back');
 await cf('/pages/projects/projectshift/deployments/'+before.id+'/rollback','POST');writeFileSync('faq-live-proof/errors.json',JSON.stringify(errors,null,2));throw Error('Post-publication copy check failed; previous Pages release restored');
}
writeFileSync('faq-live-proof/receipt.json',JSON.stringify({at:new Date().toISOString(),source:process.env.GITHUB_SHA,observedMain,from:before.id,to:after.id,url:after.url,fingerprint:control.source_fingerprint,checks,preservedOtherFiles:836,legacyQuestionnaireMainDomainEnabled:false,workerDeployed:false,customerDataChanged:false,stockOrPricesChanged:false},null,2));console.log('PASS: 32 reviewed FAQs, four core guides, accurate legacy Health MOT methodology and original missing sprite published; main Health MOT product redirect preserved');
