// Actual ordinary password/token modules; no commissioning identity or auto-verify.
// EMAIL is a recording transport. This proves content and state, not inbox delivery.
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {fastMemberRegister} from '../member-register-fastpath-v2.js';
import {fastMemberLogin} from '../member-login-fastpath-v1.js';
import {handleEmailVerification} from '../auth-email-verification-v1.js';
import {handleAuthRecovery} from '../auth-recovery-v1.js';
import {authenticateMember} from '../member-state-fast-v1.js';
const EMAIL='ordinary-acceptance@example.invalid',PASSWORD='Fictional-Passphrase-19!';
function fixture(t,{delivery='ok'}={}){
 const db=new DatabaseSync(':memory:');t.after(()=>db.close());
 db.exec(`CREATE TABLE users(id INTEGER PRIMARY KEY,email TEXT UNIQUE,first_name TEXT,last_name TEXT,phone TEXT,date_of_birth TEXT,postcode TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT);CREATE TABLE user_auth(user_id INTEGER PRIMARY KEY,password_hash TEXT,email_verified INTEGER DEFAULT 0,email_verified_at TEXT,failed_login_attempts INTEGER DEFAULT 0,locked_until TEXT,last_login_at TEXT,updated_at TEXT);CREATE TABLE member_status(user_id INTEGER PRIMARY KEY,lifecycle_stage TEXT,membership_status TEXT,source TEXT,last_activity_at TEXT,updated_at TEXT);CREATE TABLE member_state(user_id INTEGER PRIMARY KEY);CREATE TABLE user_sessions(id INTEGER PRIMARY KEY,user_id INTEGER,token_hash TEXT,expires_at TEXT,last_used_at TEXT,created_at TEXT,revoked_at TEXT);CREATE TABLE audit_log(id INTEGER PRIMARY KEY,user_id INTEGER,action TEXT,entity_type TEXT,entity_id TEXT,metadata TEXT,ip_address TEXT,created_at TEXT);CREATE TABLE auth_tokens(id INTEGER PRIMARY KEY,user_id INTEGER,token_hash TEXT,token_type TEXT,expires_at TEXT,used_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
 const DB={async exec(sql){db.exec(sql)},prepare(sql){let args=[];return{bind(...a){args=a;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return{results:db.prepare(sql).all(...args)}},_run(){const r=db.prepare(sql).run(...args);return{meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}},async run(){return this._run()}}},async batch(xs){db.exec('BEGIN');try{const r=xs.map(x=>x._run());db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}};
 const messages=[],env={DB,AUTO_VERIFY_EMAIL:'false',PUBLIC_SITE_URL:'https://shiftsometimber.co.uk',...(delivery==='missing'?{}:{EMAIL:{async send(m){if(delivery==='failed')throw Error('test_delivery_failure');messages.push(m);return{id:'fictional-delivery-'+messages.length}}}})};
 const req=(path,body,headers={})=>new Request('https://shiftsometimber.co.uk/v1/auth/'+path,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
 const register=()=>handleEmailVerification(req('register',{email:EMAIL,password:PASSWORD,firstName:'Alex'}),env,{},fastMemberRegister);
 const login=(password=PASSWORD)=>fastMemberLogin(req('login',{email:EMAIL,password}),env);
 const link=()=>messages.at(-1).text.match(/https:\/\/[^\s]+/)[0];
 const verify=()=>handleEmailVerification(new Request(link()),env,{},fastMemberLogin);
 return{db,DB,env,messages,req,register,login,link,verify};
}
test('ordinary registration requires email verification and revokes its provisional session',async t=>{const f=fixture(t),r=await f.register(),b=await r.json();assert.equal(r.status,201);assert.equal(b.emailVerified,false);assert.equal(b.verificationRequired,true);assert.equal(b.verificationDelivery,'sent');assert.equal(f.messages.length,1);assert.match(f.link(),/\/v1\/auth\/verify-email\?token=/);assert.equal(f.db.prepare('SELECT count(*) n FROM user_sessions WHERE revoked_at IS NULL').get().n,0);assert.equal((await f.login()).status,403);assert.match(r.headers.get('set-cookie'),/Max-Age=0/)});
test('a valid email link enables a real password session with the actual session verifier',async t=>{const f=fixture(t);await f.register();const verified=await f.verify();assert.equal(verified.status,302);assert.match(verified.headers.get('location'),/verified=1/);const login=await f.login();assert.equal(login.status,200);const cookies=login.headers.getSetCookie(),cookie=cookies.find(s=>/^sst_session=.+; Path=\//.test(s)&&!s.includes('Max-Age=0'));assert.ok(cookie);const auth=await authenticateMember(new Request('https://shiftsometimber.co.uk/v1/me',{headers:{Cookie:cookie.split(';')[0]}}),f.env);assert.equal(auth.userId,1)});
test('resending expires the old link and creates an actionable replacement',async t=>{const f=fixture(t);await f.register();const old=f.link();await handleEmailVerification(f.req('resend-verification',{email:EMAIL}),f.env,{},fastMemberLogin);const fresh=f.link();assert.notEqual(old,fresh);const rejected=await handleEmailVerification(new Request(old),f.env,{},fastMemberLogin);assert.match(rejected.headers.get('location'),/verification_expired/);assert.equal(f.db.prepare('SELECT email_verified FROM user_auth').get().email_verified,0);assert.match((await f.verify()).headers.get('location'),/verified=1/)});
test('expired and replayed links cannot verify again or send another welcome',async t=>{const f=fixture(t);await f.register();const old=f.link();f.db.exec("UPDATE auth_tokens SET expires_at='2000-01-01'");assert.match((await f.verify()).headers.get('location'),/verification_expired/);await handleEmailVerification(f.req('resend-verification',{email:EMAIL}),f.env,{},fastMemberLogin);const fresh=f.link();await f.verify();const before=f.messages.length;assert.match((await handleEmailVerification(new Request(fresh),f.env,{},fastMemberLogin)).headers.get('location'),/verification_expired/);assert.equal(f.messages.length,before);assert.notEqual(fresh,old)});
test('unknown-email reset and resend return generic responses without email delivery',async t=>{const f=fixture(t);const a=await handleEmailVerification(f.req('resend-verification',{email:'unknown@example.invalid'}),f.env,{},fastMemberLogin);const b=await handleAuthRecovery(f.req('request-password-reset',{email:'unknown@example.invalid'}),f.env,{},fastMemberLogin);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(f.messages.length,0)});
test('ordinary reset uses its emailed token, changes password and revokes old sessions',async t=>{const f=fixture(t);await f.register();await f.verify();const login=await f.login(),cookie=login.headers.getSetCookie().find(s=>!s.includes('Max-Age=0')).split(';')[0];const r=await handleAuthRecovery(f.req('request-password-reset',{email:EMAIL}),f.env,{},fastMemberLogin);assert.equal(r.status,200);const token=new URL(f.link()).searchParams.get('token');assert.ok(token);const next='Different-Fictional-Passphrase!';const reset=await handleAuthRecovery(f.req('reset-password',{token,password:next}),f.env,{},fastMemberLogin);assert.equal(reset.status,200);assert.equal((await f.login()).status,401);assert.equal((await f.login(next)).status,200);const auth=await authenticateMember(new Request('https://shiftsometimber.co.uk/v1/me',{headers:{Cookie:cookie}}),f.env);assert.equal(auth.response.status,401);assert.equal((await handleAuthRecovery(f.req('reset-password',{token,password:next}),f.env,{},fastMemberLogin)).status,400)});
test('expired reset does not change credentials',async t=>{const f=fixture(t);await f.register();await f.verify();await handleAuthRecovery(f.req('request-password-reset',{email:EMAIL}),f.env,{},fastMemberLogin);const token=new URL(f.link()).searchParams.get('token');f.db.exec("UPDATE auth_tokens SET expires_at='2000-01-01' WHERE token_type='password_reset'");assert.equal((await handleAuthRecovery(f.req('reset-password',{token,password:'Different-Fictional-Password!'}),f.env,{},fastMemberLogin)).status,400);assert.equal((await f.login()).status,200)});
for(const delivery of ['failed','missing'])test('unavailable '+delivery+' email is not presented as a sent verification',async t=>{const f=fixture(t,{delivery});const r=await f.register(),body=await r.json();assert.equal(r.status,201);assert.equal(body.verificationRequired,true);assert.notEqual(body.verificationDelivery,'sent');assert.match(body.message,/could not send/i);assert.equal((await f.login()).status,403);assert.equal(f.messages.length,0)});
test('duplicate registration does not create a second account',async t=>{const f=fixture(t);await f.register();const r=await f.register();assert.equal(r.status,409);assert.equal(f.db.prepare('SELECT count(*) n FROM users').get().n,1);assert.equal(f.messages.length,1)});
